In [1]:
import pandas as pd
import numpy as np

DATA_FOLDER = "./"
df = pd.read_pickle(DATA_FOLDER + "df_fe_for_ensamble_best_customers_0c.pickle")
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
product_ids = pd.read_csv(DATA_FOLDER + "product_id_apredecir201912.txt", sep="\t")[
    "product_id"
].tolist()
#df = df[df["product_id"].isin(product_ids)]
df = df.sort_values(by=["date_id", "product_id"])
df["customer_id"] = 0
df["target"] = df.groupby(["product_id", "customer_id"])["tn"].shift(-2)

In [2]:
df.describe()

,product_id,cust_request_qty,cust_request_tn,tn,stock_final,sku_size,year,mes,quarter,date_id,...,prod_tn_lag_1_x_tn_lag_11,prod_tn_lag_1_x_tn_lag_8,prod_tn_lag_3_x_tn_lag_2,prod_tn_lag_3_x_tn_lag_11,prod_tn_lag_3_x_tn_lag_8,prod_tn_lag_2_x_tn_lag_11,prod_tn_lag_2_x_tn_lag_8,prod_tn_lag_11_x_tn_lag_8,customer_id,target
count,31522.000000,31522.000000,31522.000000,31522.000000,13691.000000,31229.000000,31522.000000,31522.000000,31522.000000,31522.000000,...,1.920900e+04,2.224000e+04,2.787000e+04,1.920900e+04,2.224000e+04,1.920900e+04,2.224000e+04,1.920900e+04,31522.0,29076.000000
mean,20535.827073,200.806865,42.924751,42.033772,19.478148,476.827881,2018.037688,6.575471,2.524840,18.027727,...,1.405697e+04,1.394960e+04,1.369290e+04,1.435157e+04,1.411351e+04,1.426182e+04,1.402111e+04,1.518359e+04,0.0,42.737881
std,347.109552,124.339898,113.127739,109.374512,55.627438,883.449097,0.816015,3.452354,1.118599,10.355680,...,1.006608e+05,1.006127e+05,1.004995e+05,9.949145e+04,9.961061e+04,1.020440e+05,9.971995e+04,1.012742e+05,0.0,111.549156
min,20001.000000,0.000000,0.000000,0.000000,-27.311359,1.000000,2017.000000,1.000000,1.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000
25%,20239.000000,106.000000,2.221153,2.211540,1.160960,90.000000,2017.000000,4.000000,2.000000,9.000000,...,6.883162e+00,6.546921e+00,6.283891e+00,7.520869e+00,7.176875e+00,7.182292e+00,6.957675e+00,8.685013e+00,0.0,2.222740
50%,20495.000000,185.000000,9.652330,9.598450,5.419600,250.000000,2018.000000,7.000000,3.000000,18.000000,...,1.160452e+02,1.088569e+02,1.063643e+02,1.199704e+02,1.132123e+02,1.201063e+02,1.119023e+02,1.358740e+02,0.0,9.635365
75%,20812.000000,281.000000,29.836285,29.572310,17.584541,475.000000,2019.000000,10.000000,4.000000,27.000000,...,1.034533e+03,9.596051e+02,9.119448e+02,1.041381e+03,9.797971e+02,1.059134e+03,9.570754e+02,1.129115e+03,0.0,29.966728
max,21299.000000,756.000000,2423.708740,2295.198242,1562.024536,10000.000000,2019.000000,12.000000,4.000000,35.000000,...,3.009615e+06,4.261805e+06,4.161229e+06,3.366470e+06,3.375448e+06,3.853622e+06,3.781657e+06,3.374882e+06,0.0,2295.198242

In [3]:
df[["fecha", "date_id"]]

         fecha  date_id
0      2017-01        0
1      2017-01        0
2      2017-01        0
3      2017-01        0
4      2017-01        0
...        ...      ...
31517  2019-12       35
31518  2019-12       35
31519  2019-12       35
31520  2019-12       35
31521  2019-12       35

[31522 rows x 2 columns]

In [4]:
# transformacion comun de datos para todos los modelos:
# remuevo periodo_min_producto, periodo_max_producto, periodo_min_customer, periodo_max_customer
df = df.drop(columns=["periodo_min_producto", "periodo_max_producto",
                   "periodo_min_customer", "periodo_max_customer"], errors='ignore')

# transformo columnas object a categorical
for col in df.select_dtypes(include=["object"]).columns:
    df[col] = df[col].astype("category")

# transformo plan precios cuidados a categorical
#df["plan_precios_cuidados"] = df["plan_precios_cuidados"].astype("category")

In [5]:

# dropeo columns donde tenga mas sea todo nan hasta date_id 28
print(f"Df shape before dropping columns: {df.shape}")
subset = df[df["date_id"] <= 28]
cols_to_drop = subset.columns[subset.isna().all()]
df = df.drop(columns=cols_to_drop, errors='ignore')
print(f"Df shape after dropping columns: {df.shape}")

Df shape before dropping columns: (31522, 312)
Df shape after dropping columns: (31522, 312)

In [6]:

from sklearn.model_selection import BaseCrossValidator
import numpy as np

class CustomTimeSeriesSplit(BaseCrossValidator):
    def __init__(self, n_splits=3, gap=1):
        self.n_splits = n_splits
        self.gap = gap

    def get_n_splits(self, X=None, y=None, groups=None):
        return self.n_splits

    def split(self, X, y=None, groups=None):
        # Asegurar que X es DataFrame
        
        unique_dates = sorted(X["date_id"].unique(), reverse=True)
        
        for i in range(self.n_splits):
                
            test_date_id = unique_dates[i]
            train_date_id = test_date_id - self.gap - 1
            
            # Usar np.where para obtener posiciones enteras
            train_mask = X["date_id"] <= train_date_id
            test_mask = X["date_id"] == test_date_id
            
            train_idx = np.where(train_mask)[0]
            test_idx = np.where(test_mask)[0]
            
            yield train_idx, test_idx

In [7]:

class LinearRegressionModel:
    def __init__(self, product_ids="magicos", features_to_use=None, especialidad="all"):
        self.model = None
        self.product_ids = product_ids if product_ids is not None else []
        self.features_to_use = features_to_use or ["lags"]
        self.features = []
        self.especialidad = especialidad

    @property
    def name(self):
        return f"LinearRegression-{self.product_ids}-{self.features_to_use}-{self.especialidad}"

    def _get_product_ids(self, df):
        if self.product_ids == "magicos":
            return [20002, 20003, 20006, 20010, 20011, 20018, 20019, 20021,
                    20026, 20028, 20035, 20039, 20042, 20044, 20045, 20046,
                    20049, 20051, 20052, 20053, 20055, 20008, 20001, 20017,
                    20086, 20180, 20193, 20320, 20532, 20612, 20637, 20807,
                    20838]
        elif self.product_ids == "HC":
            hc_products = df[df["cat1"] == "HC"]["product_id"].unique().tolist()
            return hc_products
        elif self.product_ids == "FOODS":
            foods_products = df[df["cat1"] == "FOODS"]["product_id"].unique().tolist()
            return foods_products
        elif self.product_ids == "PC":
            pc_products = df[df["cat1"] == "PC"]["product_id"].unique().tolist()
            return pc_products
        elif self.product_ids == "all":
            return df["product_id"].unique().tolist()
    
    def prepare_dataset(self, df):
        df = df.copy()
        df = df.groupby(["product_id", "date_id"], as_index=False).agg({"tn": "sum", "target": "sum", "cat1": "first"}).sort_values(["product_id", "date_id"])
        self.features.append("tn")
        if "lags" in self.features_to_use:
            for lag in range(1, 12):
                df[f"tn_{lag}"] = df.groupby("product_id")["tn"].shift(lag)
                self.features.append(f"tn_{lag}")
        if "mean" in self.features_to_use: 
            for window in range(1, 12):
                df[f"tn_mean_{window}"] = df.groupby("product_id")["tn"].transform(lambda x: x.rolling(window=window, min_periods=1).mean())
                self.features.append(f"tn_mean_{window}")
        if "std" in self.features_to_use:
            for window in range(1, 12):
                df[f"tn_std_{window}"] = df.groupby("product_id")["tn"].transform(lambda x: x.rolling(window=window, min_periods=1).std())
                self.features.append(f"tn_std_{window}")
    
        
        return df
    
    def fit_and_predict(self, train_df, pred_df, *args, **kwargs):
        from sklearn.linear_model import LinearRegression
        # si quiero  201912, entreno con 201812 (por estacionalidad)
        # lo busco dinamicamente con pred_df
        date_id_pred = pred_df["date_id"].unique()[0]
        train_df = train_df[train_df["date_id"] == (date_id_pred-12)]
        product_ids_magicos = self._get_product_ids(train_df)

        train_df = train_df[train_df["product_id"].isin(product_ids_magicos)]
        if self.especialidad != "all":
            train_df = train_df[train_df["cat1"] == self.especialidad]

        # elimino registros incompletos
        target = "target"
        train_df = train_df.dropna(subset=self.features + [target])
        print(f"Registros de entrenamiento: {len(train_df)}")
        X = train_df[self.features]
        y = train_df[target]
        model = LinearRegression()
        model.fit(X, y)
        self.model = model

        # hago la prediccion
        pred_df = pred_df.copy()
        
        # solo hace la prediccion para los productos que tienen todas las features
        pred_df = pred_df.dropna(subset=self.features)
        if self.especialidad != "all":
            pred_df = pred_df[pred_df["cat1"] == self.especialidad]
        X_pred = pred_df[self.features]
        pred_df["prediction"] = model.predict(X_pred).clip(min=0)  # Aseguro que la prediccion no sea negativa
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [8]:
class LinearRegressionByProductModel:
    def __init__(self,):
        self.model = None
        self.features = []
    
    @property
    def name(self):
        return "LinearRegressionByProduct"

    
    def prepare_dataset(self, df):
        df = df.copy()
        df = df.groupby(["product_id", "date_id"], as_index=False).agg({"tn": "sum", "target": "sum", "cat1": "first"}).sort_values(["product_id", "date_id"])
        self.features.append("tn")
        for lag in range(1, 24):
            df[f"tn_{lag}"] = df.groupby("product_id")["tn"].shift(lag)
            self.features.append(f"tn_{lag}") 
        return df
    
    def fit_and_predict(self, train_df, pred_df, *args, **kwargs):
        from sklearn.linear_model import LinearRegression
        # si quiero  201912, entreno con 201812 (por estacionalidad)
        # lo busco dinamicamente con pred_df
        date_id_pred = pred_df["date_id"].unique()[0]
        train_df = train_df[train_df["date_id"] == (date_id_pred-12)]

        models = {}
        for product_id in product_ids:
            product_id_train_df = train_df[train_df["product_id"] == product_id]
            target = "target"
            product_id_train_df = product_id_train_df.dropna(subset=[target])
            # hago fillna de features con el promedio del resto de las features en esa row en particular NO CON LA MEDIA DE TODO EL DATASET
            product_id_train_df[self.features] = product_id_train_df[self.features].fillna(
                product_id_train_df[self.features].mean(axis=0)
            ).fillna(0)
            if len(product_id_train_df) == 0:
                continue
            X = train_df[self.features]
            y = train_df[target]
            model = LinearRegression()
            model.fit(X, y)
            self.model = model
            models[product_id] = model        # hago la prediccion
        pred_df = pred_df.copy()
        
        pred_df["prediction"] = np.nan  # Inicializo la columna de predicciones
        for product_id in product_ids:
            model = models.get(product_id)
            if model is None:
                continue
            
            product_id_pred_df = pred_df[pred_df["product_id"] == product_id]
            
            # solo hace la prediccion para los productos que tienen todas las features
            #hago el fillna de features con el promedio del resto de las features en esa row en particular NO CON LA MEDIA DE TODO EL DATASET
            product_id_pred_df[self.features] = product_id_pred_df[self.features].fillna(
                product_id_pred_df[self.features].mean(axis=0)
            )
            X_pred = product_id_pred_df[self.features]
            y_pred = model.predict(X_pred).clip(min=0)
            pred_df.loc[pred_df["product_id"] == product_id, "prediction"] = y_pred
        
        # drop nan predictions
        pred_df = pred_df.dropna(subset=["prediction"])
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [9]:
class SimpleMovingAveragePredictor:
    ''' Usa una media movil simple para predecir tn'''
    def __init__(self, window_size=12):
        self.model = None
        self.window_size = window_size

    @property
    def name(self):
        return f"SMA-{self.window_size}"
    
    def prepare_dataset(self, df):
        df = df.copy()
        df = df.groupby(["product_id", "date_id"], as_index=False).agg({"tn": "sum", "target": "sum"}).sort_values(["product_id", "date_id"])
        # hago una columna que es la media movil simple agrupada por producto
        df["tn_sma"] = df.groupby("product_id")["tn"].transform(
            lambda x: x.rolling(window=self.window_size, min_periods=1).mean()
        )
        return df
    
    def fit_and_predict(self, train_df, pred_df, *args, **kwargs):

        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["tn_sma"],
        })

In [10]:
class ExponentialMovingAveragePredictor:
    ''' Usa una media movil exponencial para predecir tn'''
    def __init__(self, window_size=12):
        self.model = None
        self.window_size = window_size

    @property
    def name(self):
        return f"EMA-{self.window_size}"
    def prepare_dataset(self, df):
        df = df.copy()
        df = df.groupby(["product_id", "date_id"], as_index=False).agg({"tn": "sum", "target": "sum"}).sort_values(["product_id", "date_id"])
        # hago una columna que es la media movil exponencial agrupada por producto
        df["tn_ema"] = df.groupby("product_id")["tn"].transform(
            lambda x: x.ewm(span=self.window_size, adjust=False).mean()
        )
        return df
    
    def fit_and_predict(self, train_df, pred_df, *args, **kwargs):
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["tn_ema"],
        })

In [11]:
class AutoGluonPredictor:
    def __init__(self, presets="best_quality", estimator=None):
        self.model = None
        self.presets = presets
        self.estimator = estimator

    @property
    def name(self):
        if self.estimator:
            return f"AutoGluon-{self.estimator}"
        return f"AutoGluon-{self.presets}"
    
    def prepare_dataset(self, df):

        df = df.copy()
        df["fecha"] = df["fecha"].apply(lambda x: x.to_timestamp("M"))
        df = df.rename(columns={"fecha": "timestamp"})
        df["product_id"] = df["product_id"].astype(int)
        df["serie_id"] = df["product_id"].astype(str) + "-" + df["customer_id"].astype(str)
        df["cat1"] = df["cat1"].astype("category")
        df["cat2"] = df["cat2"].astype("category")
        df["cat3"] = df["cat3"].astype("category")
        df["brand"] = df["brand"].astype("category")
        df["sku_size"] = df["sku_size"].astype("category")

        self.static_features_df = pd.DataFrame({
            "cat1": df.groupby("serie_id")["cat1"].first(),
            "cat2": df.groupby("serie_id")["cat2"].first(),
            "cat3": df.groupby("serie_id")["cat3"].first(),
            "brand": df.groupby("serie_id")["brand"].first(),
            "sku_size": df.groupby("serie_id")["sku_size"].first(),
            "customer_id": df.groupby("serie_id")["customer_id"].first(),
            "product_id": df.groupby("serie_id")["product_id"].first(),
        }).reset_index()
        

        min_periods = 12  # Mínimo 6 meses de datos
        product_counts = df.groupby(["product_id"]).size()
        valid_products = product_counts[product_counts >= min_periods].index
        df = df[df["product_id"].isin(valid_products)]        
        df = df.dropna(subset=["tn"])
        return df
    
    def fit_and_predict(self, train_df, pred_df, df_model):
        from autogluon.timeseries import TimeSeriesPredictor, TimeSeriesDataFrame
        # el autogluon lo entreno con todas las fechas hasta pred_df
        train_df = df_model[df_model["date_id"] <= pred_df["date_id"].unique()[0]]
        train_df = train_df[train_df["product_id"].isin(product_ids)]
        ts_data = TimeSeriesDataFrame.from_data_frame(
            train_df.drop(columns=["target"]), 
            id_column="serie_id", 
            timestamp_column="timestamp", 
            static_features_df=self.static_features_df
        )
        ts_data = ts_data.sort_index()
        ts_data = ts_data.fill_missing_values()

        predictor = TimeSeriesPredictor(
            prediction_length=2,
            target="tn",
            freq="MS",
        )
        if self.estimator:
            predictor.fit(ts_data, hyperparameters={self.estimator: {}})
        else:
            predictor.fit(ts_data, presets=self.presets)
        forecast = predictor.predict(ts_data)
        forecast_mean = forecast["mean"].reset_index()
        forecast_mean = forecast_mean[forecast_mean["timestamp"] == forecast_mean["timestamp"].max()]
        forecast_mean[["product_id", "customer_id"]] = forecast_mean["item_id"].str.split("-", expand=True)
        forecast_mean["product_id"] = forecast_mean["product_id"].astype(int)
        forecast_mean = forecast_mean.groupby("product_id").agg({
            "mean": "sum",
        }).reset_index()

        # rename item_id to product_id
        pred_df = pred_df.copy()
        pred_df["product_id"] = pred_df["product_id"].astype(int)
        # separo serie_id en product_id y customer_id
        pred_df = pred_df.groupby(["product_id"]).agg({
            "target": "sum",
            "date_id": "first"
        }).reset_index()
        pred_df = pred_df.merge(forecast_mean, on=["product_id"], how="left")
        pred_df = pred_df.rename(columns={"mean": "prediction"})
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [12]:


class BaseTabularPredictor:
    
    def _scaling_df(self, df, train=True):
        df = df.copy()
        import re
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        transformations = {
            "tn": [
                r"tn$",
                r"cust_request_qty_per_tn$",
                r"tn_lag_*",
                r"tn_rolling_mean_*",
                r"tn_rolling_max_*",
                r"tn_rolling_min_*",
                r"tn_.*_vendidas$",
                r"tn_agg*",
                r"tn_wavelet_*",
            ]
            + [r"stock_final$"]
            + [r"cust_request_tn_minus_tn$"]
            + [r"tn_diff_*"],
            "cust_request_qty": [
                r"cust_request_qty$",
                r"cust_request_qty_lag_*",
                r"cust_request_qty_rolling_mean_*",
                r"cust_request_qty_rolling_max_*",
                r"cust_request_qty_rolling_min_*",
                r"cust_request_qty_.*_vendidas$",
                r"cust_request_qty_agg*",
                r"cust_request_qty_wavelet_*",
            ]
            + [r"cust_request_qty_diff_*"],
        }

        # busco todas las columnas que empiezan con prod_ y agrego key y valor en transformation
        for col in numeric_cols:
            if col.startswith("prod_"):
                transformations[col] = [r"{}$".format(col)]

        from pandas.errors import PerformanceWarning
        import warnings
        warnings.simplefilter(action="ignore", category=PerformanceWarning)
        df = df.set_index(['serie_id', "date_id"])
        if train:
            prod_stats = df.groupby(["serie_id"])[
                list(transformations.keys())
            ].agg(["std"])
            prod_stats.columns = [
                f"{col[0]}_{col[1]}" for col in prod_stats.columns
            ]  # renombro las columnas para que no tengan tupla

            prod_stats = prod_stats.reset_index()
            self.prod_stats = prod_stats
            prod_stats = prod_stats.set_index(['serie_id'])
            # supress performance warnings
            self.prod_stats = prod_stats

            print("Scaling")
        else:
            if self.prod_stats is None:
                raise ValueError("prod_stats is not set. Call prepare_dataset first.")
            prod_stats = self.prod_stats
        for trainer, regex_cols in transformations.items():
            for col in regex_cols:
                matching_cols = [c for c in numeric_cols if re.match(col, c)]
                if not matching_cols:
                    continue
                for col in matching_cols:
                    std_col = prod_stats[trainer + "_std"]
                    df[f"{col}_scaled"] = (df[col] / std_col).replace([np.inf, -np.inf], np.nan)

        # scalo el target con tn_std
        df["target_scaled"] = df["target"] / prod_stats["tn_std"]
        df["target_scaled"] = df["target_scaled"].replace([np.inf, -np.inf], np.nan).fillna(0)

        df = df.reset_index()
        return df

    def prepare_dataset(self, df):
        df = df.copy()
        df["serie_id"] = df["product_id"].astype(str) + "-" + df["customer_id"].astype(str)
        return df


class AutoMLPredictor(BaseTabularPredictor):
    
    def __init__(self, estimator="lgbm", time_budget=60):
        self.model = None
        self.prod_stats = None
        self.estimator = estimator
        self.time_budget = time_budget

    @property
    def name(self):
        return f"AutoML-{self.estimator}-{self.time_budget}s"
    
    def custom_metric(self, X_val, y_val, estimator, labels, X_train, y_train, *args, **kwargs):
        y_pred = estimator.predict(X_val)
    
        temp_df = pd.DataFrame({
            "product_id": X_val["product_id"].values,
            "customer_id": X_val["customer_id"].values,
            "y_true": y_val,
            "y_pred": y_pred
        })
        temp_df["product_id"] = temp_df["product_id"].astype(int)
        temp_df["customer_id"] = temp_df["customer_id"].astype(int)
        prod_stats = self.prod_stats.copy().reset_index()
        prod_stats[["product_id", "customer_id"]] = prod_stats["serie_id"].str.split("-", expand=True)
        prod_stats["product_id"] = prod_stats["product_id"].astype(int)
        prod_stats["customer_id"] = prod_stats["customer_id"].astype(int)
        temp_df = temp_df.merge(prod_stats[["product_id", "customer_id", "tn_std"]], on=["product_id", "customer_id"], how="left")
        # desescale the predictions
        temp_df["y_pred"] = temp_df["y_pred"] * temp_df["tn_std"]
        temp_df["y_true"] = temp_df["y_true"] * temp_df["tn_std"]
    
        grouped = temp_df.groupby("product_id")[["y_true", "y_pred"]].sum()
        total_true = grouped["y_true"].sum()
    
        if total_true == 0:
            return 0.0, {"total_error": 0.0}
    
        total_error = np.abs(grouped["y_pred"] - grouped["y_true"]).sum() / total_true
        return total_error, {"total_error": total_error}

    def fit_and_predict(self, train_df, pred_df, df_model):
        from flaml import AutoML
        train_df = self._scaling_df(train_df, train=True)
        pred_df = self._scaling_df(pred_df, train=False)
        tscv = CustomTimeSeriesSplit(2, gap=1)
        automl_settings = {
            "time_budget": self.time_budget,
            "task": "regression",
            "metric": self.custom_metric,
            "estimator_list": [self.estimator],
            "n_jobs": -1,
            "eval_method": "cv",
            "split_type": tscv,
            "verbose": 3,
            "retrain_full": True
        }
        X_train = train_df.drop(columns=["target", "target_scaled", "fecha"])
        y_train = train_df["target_scaled"]
        automl = AutoML()
        automl.fit(X_train, y_train, **automl_settings)
        # hago la prediccion
        y_pred = automl.predict(pred_df.drop(columns=["target", "target_scaled", "fecha"]))
        pred_df = pred_df.copy()
        pred_df["prediction"] = y_pred
        pred_df["serie_id"] = pred_df["product_id"].astype(str) + "-" + pred_df["customer_id"].astype(str)
        pred_df.set_index("serie_id", inplace=True)
        pred_df["prediction"] = pred_df["prediction"] * self.prod_stats["tn_std"]
        pred_df = pred_df.reset_index().groupby("product_id").agg({
            "target": "sum",
            "date_id": "first",
            "prediction": "sum"
        }).reset_index()
 
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [13]:
class AutoGluonTabularPredictor(BaseTabularPredictor):
    
    def __init__(self, presets="medium_quality", exclude_model_types=None, time_budget=None, subsample=1):
        self.model = None
        self.prod_stats = None
        self.presets = presets
        self.exclude_model_types = exclude_model_types or []
        self.time_budget = time_budget
        self.subsample = subsample

    @property
    def name(self):
        return f"AutoGluonTabular-{self.presets}-budget-{self.time_budget}s-subsample-{self.subsample}"
    
    def fit_and_predict(self, train_df, pred_df, df_model):
        from autogluon.tabular import TabularPredictor, TabularDataset
        train_df = self._scaling_df(train_df, train=True)
        pred_df = self._scaling_df(pred_df, train=False)

        # uso el date_id mas alto de train_df como tunning_data
        train_df = train_df.sample(frac=self.subsample, random_state=42)
        train = TabularDataset(train_df.drop(columns=["fecha", "serie_id"], errors='ignore'))
        pred = TabularDataset(pred_df.drop(columns=["fecha", "serie_id"], errors='ignore'))

        predictor = TabularPredictor(
            label="target_scaled",
            eval_metric="mean_absolute_error",
        )
        predictor.fit(
            train.drop(columns=["target"]),
            presets=self.presets,
            excluded_model_types=["RF", "XT"] + self.exclude_model_types,
            time_limit=self.time_budget,
        )

        y_pred = predictor.predict(pred.drop(columns=["target", "target_scaled"]))
        pred_df = pred_df.copy()
        pred_df["prediction"] = y_pred
        pred_df["serie_id"] = pred_df["product_id"].astype(str) + "-" + pred_df["customer_id"].astype(str)
        pred_df.set_index("serie_id", inplace=True)
        pred_df["prediction"] = pred_df["prediction"] * self.prod_stats["tn_std"]
        pred_df = pred_df.reset_index().groupby("product_id").agg({
            "target": "sum",
            "date_id": "first",
            "prediction": "sum"
        }).reset_index()
 
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [14]:
class BasicXGBoostPredictor(BaseTabularPredictor):
    
    def __init__(self):
        self.model = None
        self.prod_stats = None

    @property
    def name(self):
        return f"BasicXGBoost"
    
    def fit_and_predict(self, train_df, pred_df, df_model):
        import xgboost as xgb
        train_df = self._scaling_df(train_df, train=True)
        pred_df = self._scaling_df(pred_df, train=False)

        X_train = train_df.drop(columns=["target", "target_scaled", "fecha", "serie_id"])
        y_train = train_df["target_scaled"]

        X_test = pred_df.drop(columns=["target", "target_scaled", "fecha", "serie_id"])
        y_test = pred_df["target_scaled"]
        
        # I use the tn_std as weight
        train_df = train_df.merge(self.prod_stats.reset_index()[["serie_id", "tn_std"]], on="serie_id", how="left")
        w_train = train_df["tn_std"].fillna(0)
        dtrain = xgb.DMatrix(X_train, label=y_train, weight=w_train, enable_categorical=True)
        dtest = xgb.DMatrix(X_test, label=y_test, enable_categorical=True)
        
        model = xgb.train(
            params={
                "objective": "reg:tweedie",
                "device": "cuda",
                "tree_method": "hist",
                "sampling_method": "uniform",
                "max_depth": 0,
                "learning_rate": 0.03,
                "num_leaves": 31,
                "subsample": 0.8,
                "colsample_bytree": 0.6,
            },
            dtrain=dtrain,
            evals=[(dtest, "test")],
            num_boost_round=1000,
            #num_boost_round=20
        )

        y_pred = model.predict(dtest)
        pred_df = pred_df.copy()
        pred_df["prediction"] = y_pred
        pred_df["serie_id"] = pred_df["product_id"].astype(str) + "-" + pred_df["customer_id"].astype(str)
        pred_df.set_index("serie_id", inplace=True)
        pred_df["prediction"] = pred_df["prediction"] * self.prod_stats["tn_std"]
        pred_df = pred_df.reset_index().groupby("product_id").agg({
            "target": "sum",
            "date_id": "first",
            "prediction": "sum"
        }).reset_index()
 
        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [15]:
class BasicLGBMPredictor(BaseTabularPredictor):
    def __init__(self, with_scaling=True, extra_trees=False, n_trials=0, boosting_type="gbdt", use_weight=True, target="t+2"):
        self.model = None
        self.prod_stats = None
        self.with_scaling = with_scaling
        self.extra_trees = extra_trees
        self.n_trials = n_trials
        self.boosting_type = boosting_type
        self.base_params = {
            "objective": "tweedie",
            "device": "cpu",
            "max_bin": 512,
            "extra_trees": self.extra_trees,
            "boosting_type": self.boosting_type,
            "metric": "None",
        }
        self.use_weight = use_weight
        self.target = target # opciones: t+2, delta
        if self.target == "delta":
            self.base_params["objective"] = "regression"


    @property
    def name(self):
        return f"LGBM-extra_trees-{self.extra_trees}-trials-{self.n_trials}-scaling-{self.with_scaling}-boosting-{self.boosting_type}-weight-{self.use_weight}-target-{self.target}"


    def optimize_params(self,train_df):
        class LGBCustomMetric:
            def __init__(self, eval_df, prod_stats):
                self.eval_df = eval_df.copy()
                self.eval_df["serie_id"] = self.eval_df["product_id"].astype(str) + "-" + self.eval_df["customer_id"].astype(str)
                self.prod_stats = prod_stats

            def __call__(self, preds, train_data):
                eval_df = self.eval_df.copy()
                eval_df["prediction"] = preds

                eval_df = eval_df[eval_df["product_id"].isin(product_ids)]
                eval_df.set_index("serie_id", inplace=True)
                eval_df["prediction"] = eval_df["prediction"] * self.prod_stats["tn_std"]
                eval_df = eval_df.groupby("product_id").agg({
                    "target": "sum",
                    "prediction": "sum",
                }).reset_index()
                total_error = np.sum(np.abs(eval_df["prediction"] - eval_df["target"])) / np.sum(eval_df["target"])
                return "total_error", total_error, False  # False indicates that lower is better

        #uso la maxima fecha como eval_df
        eval_df = train_df[train_df["date_id"] == train_df["date_id"].max()].copy()
        train_df = train_df[train_df["date_id"] < eval_df["date_id"].max()].copy()
        from optuna import create_study
        from optuna.samplers import TPESampler
        import lightgbm as lgb
        def objective(trial):
            nonlocal train_df
            nonlocal eval_df
            train_df_trial = train_df.copy()
            eval_df_trial = eval_df.copy()
            if self.n_trials <= 1:
                print("Skipping hyperparameter optimization, using default parameters.")
                params = {
                    **self.base_params,
                    "num_leaves": 31,
                    "learning_rate": 0.03,
                    "feature_fraction": 0.8,
                    "bagging_fraction": 0.8,
                    "bagging_freq": 5,
                    "min_data_in_leaf": 30,
                }
            else:
                print("Optimizing hyperparameters with Optuna.")        
                params = {
                    **self.base_params,
                    "tweedie_variance_power": trial.suggest_float("tweedie_variance_power", 1.1, 1.9),
                    "num_leaves": trial.suggest_int("num_leaves", 16, 512),
                    "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.075),
                    "feature_fraction": trial.suggest_float("feature_fraction", 0.3, 1.0),
                    "bagging_fraction": trial.suggest_float("bagging_fraction", 0.3, 1.0),
                    "bagging_freq": trial.suggest_int("bagging_freq", 1, 20),
                    "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 1, 40),
                }
                if self.target == "delta":
                    # en este caso saco tweedie_variance_power porque no es necesario
                    params.pop("tweedie_variance_power", None)
            # TODO: optimizar custom metric porque relentiza mucho, mientras uso mae
            params["metric"] = "mae"
            # TODO: en la optimizacion NO Uso max bin por performance, pero en el entrenamiento si
            params["max_bin"] = 255
            # agrego los weights a train_df (y luego hago drop de la columna)
            train_df_trial = train_df_trial.merge(self.prod_stats.reset_index()[["serie_id", "tn_std"]], on="serie_id", how="left")
            w_train = train_df_trial["tn_std"].fillna(0)
            train_df_trial.drop(columns=["tn_std"], inplace=True)
            # si use_weight es False pongo w_train a 1.0
            if not self.use_weight:
                w_train = np.ones_like(w_train)

            dtrain = lgb.Dataset(train_df_trial.drop(columns=["target", "target_scaled", "fecha", "serie_id"]), label=train_df_trial["target_scaled"], weight=w_train)
            dval = lgb.Dataset(eval_df_trial.drop(columns=["target", "target_scaled", "fecha", "serie_id"]), label=eval_df_trial["target_scaled"])
            eval_result = {}
            if self.boosting_type == "gbdt":
                callbacks = [
                    lgb.log_evaluation(500),
                    lgb.early_stopping(int(400 + 4 / params["learning_rate"]), first_metric_only=True),
                    lgb.record_evaluation(eval_result),
                ]
            else:
                # dart no tiene early stopping
                callbacks = [
                    lgb.log_evaluation(500),
                    lgb.record_evaluation(eval_result),
                ]
            model = lgb.train(
                params, 
                dtrain, 
                num_boost_round=9999, 
                valid_sets=[dval], 
                valid_names=["eval"],
                #feval=LGBCustomMetric(eval_df, self.prod_stats),
                callbacks=callbacks
            )
            scores = eval_result["eval"]["l1"]
            best_iteration = min(enumerate(scores, 1), key=lambda x: x[1])[0]  # Encuentra la mejor iteración
            print(f"Best iteration: {best_iteration}, Score: {scores[best_iteration-1]}")
            # me guardo la mejor iteracion como attr del trial
            trial.set_user_attr("best_iteration", best_iteration)
            y_pred = model.predict(eval_df_trial.drop(columns=["target","target_scaled", "fecha", "serie_id"]), num_iteration=best_iteration)
            eval_df_trial["prediction"] = y_pred
            eval_df_trial.set_index("serie_id", inplace=True)
            eval_df_trial["prediction"] = eval_df_trial["prediction"] * self.prod_stats["tn_std"]
            if self.target == "delta":
                eval_df_trial["prediction"] = eval_df_trial["prediction"] + eval_df_trial["tn"]
                eval_df_trial["target"] = eval_df_trial["target"] + eval_df_trial["tn"]
            eval_df_trial = eval_df_trial.reset_index().groupby("product_id").agg({
                "target": "sum",
                "prediction": "sum",
            }).reset_index()
            total_error = np.sum(np.abs(eval_df_trial["prediction"] - eval_df_trial["target"])) / np.sum(eval_df_trial["target"])
            return total_error

        study = create_study(direction="minimize", sampler=TPESampler(seed=42))
        if self.n_trials == 0:
            self.n_trials = 1 # hago uno para optimizar al menos el n_estimator
        study.optimize(objective, n_trials=self.n_trials, show_progress_bar=True)
        best_trial = study.best_trial
        best_parameters = best_trial.params
        num_iteration = best_trial.user_attrs.get("best_iteration")
        if self.n_trials <= 1:
            return {
                "num_leaves": 31,
                "learning_rate": 0.03,
                "feature_fraction": 0.8,
                "bagging_fraction": 0.8,
                "bagging_freq": 5,
                "min_data_in_leaf": 30,
            }, num_iteration
        return best_parameters, num_iteration

    def fit_and_predict(self, train_df, pred_df, df_model):
        import lightgbm as lgb
        # si target es delta hago la diff entre target y tn
        if self.target == "delta":
            train_df["target"] = train_df["target"] - train_df["tn"]
            pred_df["target"] = pred_df["target"] - pred_df["tn"]
        if self.with_scaling:
            # Nota: puedo escalar con los datos de pred porque en el instante T tengo esos datos, lo que no tengo es el target
            train_scaling_df = df_model[df_model["date_id"] <= pred_df["date_id"].max()]
            train_scaling_df = self._scaling_df(train_scaling_df, train=True)
            train_df = self._scaling_df(train_df, train=False)
            pred_df = self._scaling_df(pred_df, train=False)
        else:
            # ignore SettingWithCopyWarning
            import warnings
            warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)
            self.prod_stats = pd.DataFrame({
                "serie_id": train_df["serie_id"].unique(),
                "tn_std": 1.0
            }).set_index("serie_id")
            train_df["target_scaled"] = train_df["target"]
            pred_df["target_scaled"] = pred_df["target"]

        best_params, num_iteration = self.optimize_params(train_df)
        X_train = train_df.drop(columns=["target", "target_scaled", "fecha", "serie_id"])
        y_train = train_df["target_scaled"]

        X_test = pred_df.drop(columns=["target", "target_scaled", "fecha", "serie_id"])
        y_test = pred_df["target_scaled"]
        
        # I use the tn_std as weight
        train_df = train_df.merge(self.prod_stats.reset_index()[["serie_id", "tn_std"]], on="serie_id", how="left")
        w_train = train_df["tn_std"].fillna(0)
        # si use_weight es False pongo w_train a 1.0
        if not self.use_weight:
            w_train = np.ones_like(w_train)
        
        dtrain = lgb.Dataset(X_train, label=y_train, weight=w_train)
        dtest = lgb.Dataset(X_test, label=y_test)

        params = {
            **self.base_params,
            **best_params,
            "verbose": 0,
        }
        print(f"Training LGBM with parameters: {params}, and {num_iteration} iterations")
        model = lgb.train(
            params,
            dtrain,
            #num_boost_round=1000,
            num_boost_round=num_iteration,
            valid_sets=[dtest],
            callbacks=[lgb.log_evaluation(1000)]
        )

        y_pred = model.predict(X_test)
        pred_df = pred_df.copy()
        pred_df["prediction"] = y_pred
        pred_df["serie_id"] = pred_df["product_id"].astype(str) + "-" + pred_df["customer_id"].astype(str)
        pred_df.set_index("serie_id", inplace=True)
        pred_df["prediction"] = pred_df["prediction"] * self.prod_stats["tn_std"]
        if self.target == "delta":
            # si target es delta, deshago la diff
            pred_df["prediction"] = pred_df["prediction"] + pred_df["tn"]
            pred_df["target"] = pred_df["target"] + pred_df["tn"]
        pred_df = pred_df.reset_index().groupby("product_id").agg({
            "target": "sum",
            "date_id": "first",
            "prediction": "sum"
        }).reset_index()

        return pd.DataFrame({
            "product_id": pred_df["product_id"],
            "date_id": pred_df["date_id"],
            "target": pred_df["target"],
            "prediction": pred_df["prediction"]
        })

In [16]:
#autogluon_tabular_predictor = AutoGluonTabularPredictor(presets="medium")
#df_autogluon_tabular = autogluon_tabular_predictor.prepare_dataset(df)
#test_df = df_autogluon_tabular[df_autogluon_tabular["date_id"] == 33]
#train_df = df_autogluon_tabular[df_autogluon_tabular["date_id"] < 32]
#results = autogluon_tabular_predictor.fit_and_predict(train_df, test_df, df_autogluon_tabular)

In [17]:

# import deep copy
from copy import deepcopy
class EnsambleTrainer:
    def __init__(self, models):
        self.models = models
        self.model_weights = None
        self.train_results = None

    def _combina_results(self, results):
        from collections import defaultdict
        # Diccionario para almacenar resultados intermedios
        combined_results = defaultdict(dict)

        for split, models in results.items():
            for model_info in models:
                model_name = model_info["model"].name
                pred_df = model_info["pred_df"]

                for _, row in pred_df.iterrows():
                    key = (row["product_id"], row["date_id"])
                    combined_results[key]["product_id"] = row["product_id"]
                    combined_results[key]["date_id"] = row["date_id"]
                    combined_results[key]["target"] = row["target"]
                    combined_results[key][f"prediction_{model_name}"] = row["prediction"]

        # Convertir a DataFrame
        results_df = pd.DataFrame(combined_results.values())

        # Opcional: ordenar columnas
        cols = ["product_id", "date_id", "target"] + sorted([col for col in results_df.columns if col not in {"product_id", "date_id", "target"}])
        results_df = results_df[cols]

        def fill_row_na_with_row_mean(row, prediction_cols):
            preds = row[prediction_cols]
            row[prediction_cols] = preds.fillna(preds.mean(skipna=True))
            return row

        prediction_cols = [col for col in results_df.columns if col.startswith("prediction_")]

        results_df = results_df.apply(fill_row_na_with_row_mean, axis=1, prediction_cols=prediction_cols)   
        self.train_results = results_df
        return results_df
        
    def _optimize_weights(self, results_df, max_models=1):
        import numpy as np
        import pandas as pd
    
        prediction_cols = [col for col in results_df.columns if col.startswith("prediction_")]
    
        model_weights_by_max = {}
    
        product_weights = {}
        predictions_list = []
    
        for _, row in results_df.iterrows():
            product_id = row["product_id"]
            target = row["target"]
    
            preds = np.array([row[col] for col in prediction_cols])
            diffs = preds - target
    
            if max_models == 1:
                # comportamiento original: one-hot del modelo más cercano
                errors = diffs ** 2
                best_idx = np.argmin(errors)
                weights = np.zeros(len(prediction_cols))
                weights[best_idx] = 1
            else:
                above = np.where(diffs >= 0)[0]
                below = np.where(diffs < 0)[0]
    
                if len(above) > 0 and len(below) > 0:
                    i_above = above[np.argmin(diffs[above])]
                    i_below = below[np.argmax(diffs[below])]
                    p1, p2 = preds[i_below], preds[i_above]
    
                    # resolver w en target = w*p1 + (1-w)*p2 => w = (target - p2)/(p1 - p2)
                    denom = p1 - p2
                    if denom != 0:
                        w = (target - p2) / denom
                        w = np.clip(w, 0, 1)
                    else:
                        w = 0.5  # predicciones iguales => promedio
    
                    weights = np.zeros(len(prediction_cols))
                    weights[i_below] = w
                    weights[i_above] = 1 - w
                else:
                    # todos arriba o todos abajo: fallback a comportamiento original
                    errors = diffs ** 2
                    best_idx = np.argmin(errors)
                    weights = np.zeros(len(prediction_cols))
                    weights[best_idx] = 1
    
            if product_id not in product_weights:
                product_weights[product_id] = []
            product_weights[product_id].append(weights)
    
        weights_list = []
        predictions_list = []
        product_ids = list(product_weights.keys())
    
        for product_id in product_ids:
            weight_arr = np.mean(product_weights[product_id], axis=0)
            weights_dict = dict(zip(prediction_cols, weight_arr))
            weights_list.append(weights_dict)
    
            product_rows = results_df[results_df["product_id"] == product_id]
            preds_matrix = product_rows[prediction_cols].values
            weighted_preds = preds_matrix @ weight_arr
            mean_prediction = np.mean(weighted_preds)
            predictions_list.append(mean_prediction)
    
        agg_df = pd.DataFrame({
            "product_id": product_ids,
            "weights": weights_list,
            "predictions": predictions_list
        })
    
        if not hasattr(self, "model_weights") or self.model_weights is None:
            self.model_weights = {}
    
        self.model_weights[max_models] = agg_df[["product_id", "weights"]].set_index("product_id")


    def _compute_metrics_simple(self, y_true, y_pred):
        """Calcula el error absoluto medio entre y_true e y_pred"""
        return np.sum(np.abs(y_true - y_pred)) / np.sum(y_true) if np.sum(y_true) > 0 else 0

    def _compute_metrics(self, results_df, max_models=1):
        prediction_cols = [col for col in results_df.columns if col.startswith("prediction_")]
        agg_df = results_df.groupby("product_id")[["target"] + prediction_cols].sum().reset_index()
        agg_df = agg_df.set_index("product_id")
        agg_df["weights"] = self.model_weights[max_models]["weights"]
        agg_df["prediction_ensamble"] = agg_df.apply(
            lambda row: sum(row[col] * row["weights"][col] for col in prediction_cols), 
            axis=1
        )
        self.agg_df = agg_df
        # calculo metricas
        metrics = {}
        def total_error(y_true, y_pred):
            return np.sum(np.abs(y_true - y_pred)) / np.sum(y_true)

        prediction_cols = [col for col in agg_df.columns if col.startswith("prediction_")]
        for col in prediction_cols:
            metrics[col] = total_error(agg_df["target"], agg_df[col])
        return pd.DataFrame(metrics, index=[0]).T.rename(columns={0: "error"})
    
    def fit(self, df, splitter):
        """Entrena todos los modelos en cada split del splitter"""
        df = df.dropna(subset=["target"])
        number_of_splits = splitter.get_n_splits(df)
        results = {f"split_{i}": [] for i in range(number_of_splits)}
        for i, (train_idx, test_idx) in enumerate(splitter.split(df)):
            # Obtener las fechas de los splits originales
            train_dates = df.iloc[train_idx]["date_id"].unique()
            test_dates = df.iloc[test_idx]["date_id"].unique()
            
            for m in self.models:
                model = deepcopy(m)
                df_model = model.prepare_dataset(df)
                
                # Recalcular train/test usando las fechas, no los índices
                train_df = df_model[df_model["date_id"].isin(train_dates)]
                test_df = df_model[df_model["date_id"].isin(test_dates)]
                test_df = test_df[test_df["product_id"].isin(product_ids)]
                
                pred_df = model.fit_and_predict(train_df, test_df, df_model)
                results[f"split_{i}"].append({
                    "model": model,
                    "target": test_df[["target", "product_id", "date_id"]],
                    "pred_df": pred_df
                })
                print(f"Modelo {model.name} entrenado en split {i+1}/{number_of_splits}:")
                print(self._compute_metrics_simple(pred_df["target"], pred_df["prediction"]))
        
        results_df = self._combina_results(results)
        # VALIDACION
        biggest_date = results_df["date_id"].max()
        val_weights_df = results_df[results_df["date_id"] != biggest_date]
        test_df = results_df[results_df["date_id"] == biggest_date]
        self._optimize_weights(val_weights_df)
        print("VALIDACIÓN 1 MODEL MAX (primer fold con pesos del resto):")
        print(self._compute_metrics(test_df))

        self._optimize_weights(val_weights_df, max_models=2)
        print("VALIDACIÓN 2 MODEL MAX (primer fold con pesos del resto):")
        print(self._compute_metrics(test_df, max_models=2))

        
        self._optimize_weights(results_df)
        print(self._compute_metrics(results_df))
        self._optimize_weights(results_df, max_models=2)
        print(self._compute_metrics(results_df, max_models=2))

    def final_pred(self, df, kaggle_date_id):
        """Vuelve a entrenar todos los modelos con el dataset completo"""
        results = {"split_final": []}
        for m in self.models:
            model = deepcopy(m)
            df_model = model.prepare_dataset(df)
            # Recalcular train/test usando las fechas, no los índices
            train_df = df_model[df_model["date_id"] < kaggle_date_id]
            train_df = train_df.dropna(subset=["target"])
            pred_df = df_model[df_model["date_id"] == kaggle_date_id]
            pred_df = pred_df[pred_df["product_id"].isin(product_ids)]

            pred_df = model.fit_and_predict(train_df, pred_df, df_model)
            results["split_final"].append({
                "model": model,
                "target": pred_df[["target", "product_id", "date_id"]],
                "pred_df": pred_df
            })
        results_df = self._combina_results(results)  
        prediction_cols = [col for col in results_df.columns if col.startswith("prediction_")]
        agg_df = results_df.groupby("product_id")[["target"] + prediction_cols].sum().reset_index()
        agg_df = agg_df.set_index("product_id", drop=False)
        agg_df["weights"] = self.model_weights[1]["weights"]
        agg_df["prediction_ensamble"] = agg_df.apply(
            lambda row: sum(row[col] * row["weights"][col] for col in prediction_cols), 
            axis=1
        )
        agg_df["weights"] = self.model_weights[2]["weights"]
        agg_df["prediction_ensamble_2"] = agg_df.apply(
            lambda row: sum(row[col] * row["weights"][col] for col in prediction_cols), 
            axis=1
        )
        return agg_df.rename(columns={"prediction_ensamble": "tn", "prediction_ensamble_2": "tn_2"})

In [18]:
# TODO: entrenar el lightgbm con todos los product_ids? (la validacion solo con los 780)
import sys
from contextlib import redirect_stdout

#trainer = EnsambleTrainer([
#    #AutoGluonTabularPredictor(exclude_model_types=["KNN"]),
#    #BasicLGBMPredictor(n_trials=35, with_scaling=True, extra_trees=False, boosting_type="gbdt"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="gbdt"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="gbdt"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="dart"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="dart"),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=False),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt", use_weight=False),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt", use_weight=False),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart", use_weight=False),
#    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=False),
#    #BasicXGBoostPredictor(),
#    LinearRegressionModel(),
#    #AutoGluonTabularPredictor(presets="best", time_budget=3600, exclude_model_types=["KNN"]),
#    AutoGluonPredictor(presets="best_quality"),
#    #AutoGluonPredictor(presets="fast_training"),
#    SimpleMovingAveragePredictor(window_size=12)
#])

# only linear regressions + moving average
trainer = EnsambleTrainer([
    LinearRegressionModel(),
    LinearRegressionModel(especialidad="HC"),
    LinearRegressionModel(especialidad="FOODS"),
    LinearRegressionModel(especialidad="PC"),
    LinearRegressionModel(product_ids="all"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="gbdt", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="gbdt", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="dart", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="dart", use_weight=True, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="gbdt", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="gbdt", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="dart", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart", use_weight=False, target="delta"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="dart", use_weight=False, target="delta"),


    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="gbdt", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="gbdt", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="dart", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="dart", use_weight=True, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="gbdt", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="gbdt", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="gbdt", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="gbdt", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=True, boosting_type="dart", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=True, boosting_type="dart", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=True, extra_trees=False, boosting_type="dart", use_weight=False, target="t+2"),
    BasicLGBMPredictor(n_trials=0, with_scaling=False, extra_trees=False, boosting_type="dart", use_weight=False, target="t+2"),
    AutoGluonPredictor(presets="best_quality"),
    AutoGluonPredictor(presets="fast_training"), # only stadistical models
    ##LinearRegressionByProductModel(),
    SimpleMovingAveragePredictor(window_size=12),
])
splitter = CustomTimeSeriesSplit(n_splits=3, gap=1)
trainer.fit(df, splitter)

Registros de entrenamiento: 33
Modelo LinearRegression-magicos-['lags']-all entrenado en split 1/3:
0.33242905
Registros de entrenamiento: 20
Modelo LinearRegression-magicos-['lags']-HC entrenado en split 1/3:
0.4803329
Registros de entrenamiento: 5
Modelo LinearRegression-magicos-['lags']-FOODS entrenado en split 1/3:
0.3568
Registros de entrenamiento: 8
Modelo LinearRegression-magicos-['lags']-PC entrenado en split 1/3:
0.3492257
Registros de entrenamiento: 786
Modelo LinearRegression-all-['lags']-all entrenado en split 1/3:
0.27242267

/tmp/ipykernel_63886/1139988248.py:163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df["target"] = train_df["target"] - train_df["tn"]

Scaling

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2025-07-19 14:46:30,900] A new study created in memory with name: no-name-3afe1fbe-c0bb-412e-9fa7-b7e2ac2cbea4
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.050934 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 141489
[LightGBM] [Info] Number of data points in the train set: 26342, number of used features: 575
[LightGBM] [Info] Start training from score -0.047139
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.761126
[1000]	eval's l1: 0.749115
[1500]	eval's l1: 0.743917
[2000]	eval's l1: 0.736729
[2500]	eval's l1: 0.73078
[3000]	eval's l1: 0.727
[3500]	eval's l1: 0.722417
[4000]	eval's l1: 0.720989
[4500]	eval's l1: 0.719199

Best trial: 0. Best value: 0.260409: 100%|██████████| 1/1 [01:26<00:00, 86.45s/it]

Early stopping, best iteration is:
[4367]	eval's l1: 0.718773
Evaluated only: l1
Best iteration: 4367, Score: 0.7187726765114414
[I 2025-07-19 14:47:57,348] Trial 0 finished with value: 0.2604091690780577 and parameters: {}. Best is trial 0 with value: 0.2604091690780577.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4367 iterations

/tmp/ipykernel_63886/1139988248.py:163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df["target"] = train_df["target"] - train_df["tn"]
[I 2025-07-19 14:50:13,775] A new study created in memory with name: no-name-4eea4543-819e-418c-b652-30ab73d29250

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 1/3:
0.24297321054238982

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.5112
[1000]	eval's l1: 11.3926
[1500]	eval's l1: 11.3111
[2000]	eval's l1: 11.2316
[2500]	eval's l1: 11.1971
[3000]	eval's l1: 11.1588
[3500]	eval's l1: 11.1293
[4000]	eval's l1: 11.1072

Best trial: 0. Best value: 0.275692: 100%|██████████| 1/1 [00:28<00:00, 28.60s/it]

Early stopping, best iteration is:
[3932]	eval's l1: 11.0991
Evaluated only: l1
Best iteration: 3932, Score: 11.099137880250353
[I 2025-07-19 14:50:42,372] Trial 0 finished with value: 0.27569229434554665 and parameters: {}. Best is trial 0 with value: 0.27569229434554665.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3932 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 1/3:
0.26657903394341365
Scaling

[I 2025-07-19 14:51:15,204] A new study created in memory with name: no-name-d90c3ab1-5e06-4d29-8133-4aea567551e6
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.743799
[1000]	eval's l1: 0.71935
[1500]	eval's l1: 0.711299
[2000]	eval's l1: 0.704759
[2500]	eval's l1: 0.701658
[3000]	eval's l1: 0.700172
[3500]	eval's l1: 0.699498
[4000]	eval's l1: 0.699837

Best trial: 0. Best value: 0.243775: 100%|██████████| 1/1 [01:10<00:00, 70.28s/it]

Early stopping, best iteration is:
[3682]	eval's l1: 0.698259
Evaluated only: l1
Best iteration: 3682, Score: 0.6982592998581241
[I 2025-07-19 14:52:25,484] Trial 0 finished with value: 0.24377485009794225 and parameters: {}. Best is trial 0 with value: 0.24377485009794225.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3682 iterations

[I 2025-07-19 14:54:07,297] A new study created in memory with name: no-name-b415dae9-d6b2-4fca-89bf-6cc7d0a5ba1c

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 1/3:
0.25580630031383744

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.5091
[1000]	eval's l1: 11.2668
[1500]	eval's l1: 11.1257
[2000]	eval's l1: 11.0627
[2500]	eval's l1: 11.0811

Best trial: 0. Best value: 0.274709: 100%|██████████| 1/1 [00:19<00:00, 19.30s/it]

Early stopping, best iteration is:
[2008]	eval's l1: 11.0596
Evaluated only: l1
Best iteration: 2008, Score: 11.059563423818807
[I 2025-07-19 14:54:26,594] Trial 0 finished with value: 0.27470930154626383 and parameters: {}. Best is trial 0 with value: 0.27470930154626383.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2008 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 1/3:
0.29788485952059873
Scaling

[I 2025-07-19 14:54:48,321] A new study created in memory with name: no-name-8ad38382-b744-4b4b-b6c9-c460449cb4fe
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.79121
[1000]	eval's l1: 0.780248
[1500]	eval's l1: 0.771179
[2000]	eval's l1: 0.757693
[2500]	eval's l1: 0.748377
[3000]	eval's l1: 0.746612
[3500]	eval's l1: 0.747891
[4000]	eval's l1: 0.742964
[4500]	eval's l1: 0.742592
[5000]	eval's l1: 0.738502
[5500]	eval's l1: 0.735076
[6000]	eval's l1: 0.733213
[6500]	eval's l1: 0.729256
[7000]	eval's l1: 0.728102
[7500]	eval's l1: 0.728077
[8000]	eval's l1: 0.726135
[8500]	eval's l1: 0.725329
[9000]	eval's l1: 0.724429
[9500]	eval's l1: 0.722858

Best trial: 0. Best value: 0.263027: 100%|██████████| 1/1 [04:12<00:00, 252.67s/it]

Best iteration: 9886, Score: 0.7208701725110448
[I 2025-07-19 14:59:00,993] Trial 0 finished with value: 0.26302725125517135 and parameters: {}. Best is trial 0 with value: 0.26302725125517135.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9886 iterations

[I 2025-07-19 15:05:26,314] A new study created in memory with name: no-name-8f596d20-eb50-49b6-b323-c28a323d014e

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 1/3:
0.24410780906274146

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 12.0603
[1000]	eval's l1: 11.9357
[1500]	eval's l1: 11.8075
[2000]	eval's l1: 11.7652
[2500]	eval's l1: 11.7527
[3000]	eval's l1: 11.7088
[3500]	eval's l1: 11.6843
[4000]	eval's l1: 11.6779
[4500]	eval's l1: 11.6471
[5000]	eval's l1: 11.6135
[5500]	eval's l1: 11.5859
[6000]	eval's l1: 11.5513
[6500]	eval's l1: 11.5364
[7000]	eval's l1: 11.4916
[7500]	eval's l1: 11.446
[8000]	eval's l1: 11.4556
[8500]	eval's l1: 11.4642
[9000]	eval's l1: 11.4619
[9500]	eval's l1: 11.4389

Best trial: 0. Best value: 0.282829: 100%|██████████| 1/1 [02:08<00:00, 128.09s/it]

Best iteration: 9987, Score: 11.386043280721738
[I 2025-07-19 15:07:34,408] Trial 0 finished with value: 0.2828287045621978 and parameters: {}. Best is trial 0 with value: 0.2828287045621978.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9987 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 1/3:
0.26594741227766167
Scaling

[I 2025-07-19 15:10:05,800] A new study created in memory with name: no-name-a78be739-98fb-441c-a3de-71b4edc1b066
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.780284
[1000]	eval's l1: 0.769909
[1500]	eval's l1: 0.75908
[2000]	eval's l1: 0.749999
[2500]	eval's l1: 0.742478
[3000]	eval's l1: 0.737819
[3500]	eval's l1: 0.734658
[4000]	eval's l1: 0.730969
[4500]	eval's l1: 0.726098
[5000]	eval's l1: 0.723375
[5500]	eval's l1: 0.72221
[6000]	eval's l1: 0.724113
[6500]	eval's l1: 0.72101
[7000]	eval's l1: 0.719607
[7500]	eval's l1: 0.720071
[8000]	eval's l1: 0.717337
[8500]	eval's l1: 0.715589
[9000]	eval's l1: 0.714643
[9500]	eval's l1: 0.712664

Best trial: 0. Best value: 0.256014: 100%|██████████| 1/1 [04:37<00:00, 277.96s/it]

Best iteration: 9728, Score: 0.7095715697576308
[I 2025-07-19 15:14:43,757] Trial 0 finished with value: 0.2560142662794348 and parameters: {}. Best is trial 0 with value: 0.2560142662794348.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9728 iterations

[I 2025-07-19 15:21:31,254] A new study created in memory with name: no-name-2bf91195-8c0e-42d7-8d91-0cae6e14d59c

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 1/3:
0.2478499575125817

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 12.004
[1000]	eval's l1: 11.761
[1500]	eval's l1: 11.5911
[2000]	eval's l1: 11.5563
[2500]	eval's l1: 11.4528
[3000]	eval's l1: 11.3925
[3500]	eval's l1: 11.3361
[4000]	eval's l1: 11.2771
[4500]	eval's l1: 11.3087
[5000]	eval's l1: 11.2909
[5500]	eval's l1: 11.2179
[6000]	eval's l1: 11.1773
[6500]	eval's l1: 11.1775
[7000]	eval's l1: 11.2071
[7500]	eval's l1: 11.2333
[8000]	eval's l1: 11.2307
[8500]	eval's l1: 11.2367
[9000]	eval's l1: 11.2233
[9500]	eval's l1: 11.2441

Best trial: 0. Best value: 0.293967: 100%|██████████| 1/1 [02:57<00:00, 177.75s/it]

Best iteration: 6127, Score: 11.15435255707809
[I 2025-07-19 15:24:29,005] Trial 0 finished with value: 0.29396735838843496 and parameters: {}. Best is trial 0 with value: 0.29396735838843496.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6127 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 1/3:
0.290677549666018
Scaling

[I 2025-07-19 15:26:42,164] A new study created in memory with name: no-name-5a2298e8-a6a4-45f7-8e40-ec6da2633706
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.729925
[1000]	eval's l1: 0.718095
[1500]	eval's l1: 0.713073
[2000]	eval's l1: 0.706772
[2500]	eval's l1: 0.703948

Best trial: 0. Best value: 0.251275: 100%|██████████| 1/1 [00:44<00:00, 44.62s/it]

Early stopping, best iteration is:
[2456]	eval's l1: 0.70374
Evaluated only: l1
Best iteration: 2456, Score: 0.7037398283507122
[I 2025-07-19 15:27:26,780] Trial 0 finished with value: 0.2512746774661316 and parameters: {}. Best is trial 0 with value: 0.2512746774661316.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2456 iterations

[I 2025-07-19 15:28:23,988] A new study created in memory with name: no-name-639b23f5-e4b7-4033-90f8-590c11339196

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 1/3:
0.25227763022383315

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.5112
[1000]	eval's l1: 11.3926
[1500]	eval's l1: 11.3111
[2000]	eval's l1: 11.2316
[2500]	eval's l1: 11.1971
[3000]	eval's l1: 11.1588
[3500]	eval's l1: 11.1293
[4000]	eval's l1: 11.1072

Best trial: 0. Best value: 0.275692: 100%|██████████| 1/1 [00:24<00:00, 24.60s/it]

Early stopping, best iteration is:
[3932]	eval's l1: 11.0991
Evaluated only: l1
Best iteration: 3932, Score: 11.099137880250355
[I 2025-07-19 15:28:48,582] Trial 0 finished with value: 0.27569229434554665 and parameters: {}. Best is trial 0 with value: 0.27569229434554665.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3932 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 1/3:
0.26657903394341365
Scaling

[I 2025-07-19 15:29:20,461] A new study created in memory with name: no-name-283ba3bb-c5b7-4bc2-8651-a33a0ea1a1f9
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.696261
[1000]	eval's l1: 0.682714
[1500]	eval's l1: 0.676734
[2000]	eval's l1: 0.671835
[2500]	eval's l1: 0.671625
[3000]	eval's l1: 0.670255
[3500]	eval's l1: 0.66856
[4000]	eval's l1: 0.668397
[4500]	eval's l1: 0.667914
[5000]	eval's l1: 0.667537
[5500]	eval's l1: 0.667325

Best trial: 0. Best value: 0.239978: 100%|██████████| 1/1 [01:23<00:00, 83.45s/it]

Early stopping, best iteration is:
[5387]	eval's l1: 0.666971
Evaluated only: l1
Best iteration: 5387, Score: 0.6669708325338422
[I 2025-07-19 15:30:43,906] Trial 0 finished with value: 0.23997752606787867 and parameters: {}. Best is trial 0 with value: 0.23997752606787867.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5387 iterations

[I 2025-07-19 15:33:14,529] A new study created in memory with name: no-name-6414f38f-dc98-4b1a-8172-52c0dd6c36c6

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 1/3:
0.272085859057247

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.5091
[1000]	eval's l1: 11.2668
[1500]	eval's l1: 11.1257
[2000]	eval's l1: 11.0627
[2500]	eval's l1: 11.0811

Best trial: 0. Best value: 0.274709: 100%|██████████| 1/1 [00:44<00:00, 44.79s/it]

Early stopping, best iteration is:
[2008]	eval's l1: 11.0596
Evaluated only: l1
Best iteration: 2008, Score: 11.059563423818805
[I 2025-07-19 15:33:59,318] Trial 0 finished with value: 0.27470930154626383 and parameters: {}. Best is trial 0 with value: 0.27470930154626383.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2008 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 1/3:
0.29788485952059873
Scaling

[I 2025-07-19 15:34:22,407] A new study created in memory with name: no-name-34a25848-0834-43e5-b611-290f931f75ec
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.766886
[1000]	eval's l1: 0.748777
[1500]	eval's l1: 0.747658
[2000]	eval's l1: 0.740773
[2500]	eval's l1: 0.734826
[3000]	eval's l1: 0.729612
[3500]	eval's l1: 0.728665
[4000]	eval's l1: 0.727073
[4500]	eval's l1: 0.72513
[5000]	eval's l1: 0.726325
[5500]	eval's l1: 0.724751
[6000]	eval's l1: 0.723336
[6500]	eval's l1: 0.721145
[7000]	eval's l1: 0.720891
[7500]	eval's l1: 0.720147
[8000]	eval's l1: 0.72065
[8500]	eval's l1: 0.721383
[9000]	eval's l1: 0.721057
[9500]	eval's l1: 0.72185

Best trial: 0. Best value: 0.272894: 100%|██████████| 1/1 [04:08<00:00, 248.45s/it]

Best iteration: 7344, Score: 0.7188737478137159
[I 2025-07-19 15:38:30,857] Trial 0 finished with value: 0.2728940006092082 and parameters: {}. Best is trial 0 with value: 0.2728940006092082.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 7344 iterations

[I 2025-07-19 15:43:20,849] A new study created in memory with name: no-name-3b24190b-5177-4b80-961f-83b9d1a07b6f

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 1/3:
0.24368464631753645

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 12.0603
[1000]	eval's l1: 11.9357
[1500]	eval's l1: 11.8075
[2000]	eval's l1: 11.7652
[2500]	eval's l1: 11.7527
[3000]	eval's l1: 11.7088
[3500]	eval's l1: 11.6843
[4000]	eval's l1: 11.6779
[4500]	eval's l1: 11.6471
[5000]	eval's l1: 11.6135
[5500]	eval's l1: 11.5859
[6000]	eval's l1: 11.5513
[6500]	eval's l1: 11.5364
[7000]	eval's l1: 11.4916
[7500]	eval's l1: 11.446
[8000]	eval's l1: 11.4556
[8500]	eval's l1: 11.4642
[9000]	eval's l1: 11.4619
[9500]	eval's l1: 11.4389

Best trial: 0. Best value: 0.282829: 100%|██████████| 1/1 [02:51<00:00, 171.92s/it]

Best iteration: 9987, Score: 11.386043280721779
[I 2025-07-19 15:46:12,765] Trial 0 finished with value: 0.2828287045621989 and parameters: {}. Best is trial 0 with value: 0.2828287045621989.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9987 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 1/3:
0.2659474122776628
Scaling

[I 2025-07-19 15:49:02,687] A new study created in memory with name: no-name-3afff57d-25f8-4774-a7e6-96ee3c0125cb
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.74061
[1000]	eval's l1: 0.732538
[1500]	eval's l1: 0.72359
[2000]	eval's l1: 0.722037
[2500]	eval's l1: 0.717258
[3000]	eval's l1: 0.7154
[3500]	eval's l1: 0.709418
[4000]	eval's l1: 0.705332
[4500]	eval's l1: 0.702325
[5000]	eval's l1: 0.700233
[5500]	eval's l1: 0.699703
[6000]	eval's l1: 0.697413
[6500]	eval's l1: 0.695153
[7000]	eval's l1: 0.69344
[7500]	eval's l1: 0.692627
[8000]	eval's l1: 0.69308
[8500]	eval's l1: 0.692166
[9000]	eval's l1: 0.691141
[9500]	eval's l1: 0.689344

Best trial: 0. Best value: 0.25213: 100%|██████████| 1/1 [04:34<00:00, 274.99s/it]

Best iteration: 9735, Score: 0.6878231641424268
[I 2025-07-19 15:53:37,672] Trial 0 finished with value: 0.2521301518724395 and parameters: {}. Best is trial 0 with value: 0.2521301518724395.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9735 iterations

[I 2025-07-19 16:00:14,266] A new study created in memory with name: no-name-102a2578-4c37-449b-8472-ecc8f602ed1e

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 1/3:
0.26184909824334146

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 12.004
[1000]	eval's l1: 11.761
[1500]	eval's l1: 11.5911
[2000]	eval's l1: 11.5563
[2500]	eval's l1: 11.4528
[3000]	eval's l1: 11.3925
[3500]	eval's l1: 11.3361
[4000]	eval's l1: 11.2771
[4500]	eval's l1: 11.3087
[5000]	eval's l1: 11.2909
[5500]	eval's l1: 11.2179
[6000]	eval's l1: 11.1773
[6500]	eval's l1: 11.1775
[7000]	eval's l1: 11.2071
[7500]	eval's l1: 11.2333
[8000]	eval's l1: 11.2307
[8500]	eval's l1: 11.2367
[9000]	eval's l1: 11.2233
[9500]	eval's l1: 11.2441

Best trial: 0. Best value: 0.293967: 100%|██████████| 1/1 [02:56<00:00, 176.11s/it]

Best iteration: 6127, Score: 11.154352557078086
[I 2025-07-19 16:03:10,371] Trial 0 finished with value: 0.29396735838843496 and parameters: {}. Best is trial 0 with value: 0.29396735838843496.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6127 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 1/3:
0.290677549666018
Scaling

[I 2025-07-19 16:05:27,419] A new study created in memory with name: no-name-a691d28c-94fc-4a4d-80b0-d527b7aa9183
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.7861
[1000]	eval's l1: 0.782873
[1500]	eval's l1: 0.776842
[2000]	eval's l1: 0.770381
[2500]	eval's l1: 0.772125
Early stopping, best iteration is:
[1978]	eval's l1: 0.76996
Evaluated only: l1
Best iteration: 1978, Score: 0.7699603858561881

Best trial: 0. Best value: 0.276531: 100%|██████████| 1/1 [00:40<00:00, 40.35s/it]

[I 2025-07-19 16:06:07,764] Trial 0 finished with value: 0.276530683148525 and parameters: {}. Best is trial 0 with value: 0.276530683148525.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1978 iterations

[I 2025-07-19 16:06:55,938] A new study created in memory with name: no-name-76db4d1a-5a1f-40d1-afcf-4da8916f6366

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 1/3:
0.24493885916965258

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.4353
[1000]	eval's l1: 10.3594
[1500]	eval's l1: 10.2369
[2000]	eval's l1: 10.3151
Early stopping, best iteration is:
[1493]	eval's l1: 10.23
Evaluated only: l1

Best trial: 0. Best value: 0.254104: 100%|██████████| 1/1 [00:15<00:00, 15.20s/it]

Best iteration: 1493, Score: 10.230002088979061
[I 2025-07-19 16:07:11,138] Trial 0 finished with value: 0.25410376532923934 and parameters: {}. Best is trial 0 with value: 0.25410376532923934.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1493 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 1/3:
0.243450707793204
Scaling

[I 2025-07-19 16:07:33,036] A new study created in memory with name: no-name-2578251f-0249-4ccb-b067-93a85767ce0a
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.729962
[1000]	eval's l1: 0.724704
[1500]	eval's l1: 0.723534
[2000]	eval's l1: 0.724572

Best trial: 0. Best value: 0.257512: 100%|██████████| 1/1 [00:46<00:00, 46.33s/it]

Early stopping, best iteration is:
[1735]	eval's l1: 0.722473
Evaluated only: l1
Best iteration: 1735, Score: 0.7224732860778301
[I 2025-07-19 16:08:19,360] Trial 0 finished with value: 0.2575122245969064 and parameters: {}. Best is trial 0 with value: 0.2575122245969064.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1735 iterations

[I 2025-07-19 16:09:15,959] A new study created in memory with name: no-name-e7ef9d04-f6cc-4074-952b-805078e7cc58

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 1/3:
0.2501929524465555

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.61901
[1000]	eval's l1: 9.77803

Best trial: 0. Best value: 0.236833: 100%|██████████| 1/1 [00:09<00:00,  9.01s/it]

Early stopping, best iteration is:
[520]	eval's l1: 9.53471
Evaluated only: l1
Best iteration: 520, Score: 9.534708013976111
[I 2025-07-19 16:09:24,972] Trial 0 finished with value: 0.23683330527139673 and parameters: {}. Best is trial 0 with value: 0.23683330527139673.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 520 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 1/3:
0.2536914824879212
Scaling

[I 2025-07-19 16:09:33,296] A new study created in memory with name: no-name-274a744e-2683-470c-9a44-f3e93abb85f5
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.86356
[1000]	eval's l1: 0.836763
[1500]	eval's l1: 0.817917
[2000]	eval's l1: 0.798005
[2500]	eval's l1: 0.790591
[3000]	eval's l1: 0.782563
[3500]	eval's l1: 0.783964
[4000]	eval's l1: 0.781531
[4500]	eval's l1: 0.779034
[5000]	eval's l1: 0.772015
[5500]	eval's l1: 0.77597
[6000]	eval's l1: 0.778158
[6500]	eval's l1: 0.773886
[7000]	eval's l1: 0.772906
[7500]	eval's l1: 0.771547
[8000]	eval's l1: 0.774108
[8500]	eval's l1: 0.777165
[9000]	eval's l1: 0.773887
[9500]	eval's l1: 0.774518

Best trial: 0. Best value: 0.413166: 100%|██████████| 1/1 [03:49<00:00, 229.16s/it]

Best iteration: 6842, Score: 0.7707651058061481
[I 2025-07-19 16:13:22,452] Trial 0 finished with value: 0.41316610401596066 and parameters: {}. Best is trial 0 with value: 0.41316610401596066.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6842 iterations

[I 2025-07-19 16:17:10,892] A new study created in memory with name: no-name-4142e9d8-bf84-4ab0-be12-1270a456ef84

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 1/3:
0.2426753339306945

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 17.2006
[1000]	eval's l1: 15.3441
[1500]	eval's l1: 14.3956
[2000]	eval's l1: 12.9678
[2500]	eval's l1: 12.5922
[3000]	eval's l1: 12.0036
[3500]	eval's l1: 12.0541
[4000]	eval's l1: 11.7791
[4500]	eval's l1: 11.8255
[5000]	eval's l1: 11.45
[5500]	eval's l1: 11.3464
[6000]	eval's l1: 11.4507
[6500]	eval's l1: 11.2279
[7000]	eval's l1: 11.2093
[7500]	eval's l1: 11.0627
[8000]	eval's l1: 11.1416
[8500]	eval's l1: 11.2793
[9000]	eval's l1: 11.0181
[9500]	eval's l1: 11.0513

Best trial: 0. Best value: 0.311043: 100%|██████████| 1/1 [02:21<00:00, 141.63s/it]

Best iteration: 9715, Score: 10.942894426788351
[I 2025-07-19 16:19:32,521] Trial 0 finished with value: 0.3110434649479364 and parameters: {}. Best is trial 0 with value: 0.3110434649479364.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9715 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 1/3:
0.25432503108157617
Scaling

[I 2025-07-19 16:22:17,029] A new study created in memory with name: no-name-a2c54f62-eb15-4851-b126-c743ddbad939
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.847569
[1000]	eval's l1: 0.807125
[1500]	eval's l1: 0.790105
[2000]	eval's l1: 0.766224
[2500]	eval's l1: 0.762559
[3000]	eval's l1: 0.753864
[3500]	eval's l1: 0.75181
[4000]	eval's l1: 0.749377
[4500]	eval's l1: 0.752941
[5000]	eval's l1: 0.752592
[5500]	eval's l1: 0.750351
[6000]	eval's l1: 0.752395
[6500]	eval's l1: 0.748672
[7000]	eval's l1: 0.749986
[7500]	eval's l1: 0.745614
[8000]	eval's l1: 0.748391
[8500]	eval's l1: 0.753023
[9000]	eval's l1: 0.749252
[9500]	eval's l1: 0.750621

Best trial: 0. Best value: 0.566001: 100%|██████████| 1/1 [04:19<00:00, 259.69s/it]

Best iteration: 3956, Score: 0.7445944133257988
[I 2025-07-19 16:26:36,717] Trial 0 finished with value: 0.5660013933243903 and parameters: {}. Best is trial 0 with value: 0.5660013933243903.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3956 iterations

[I 2025-07-19 16:31:13,125] A new study created in memory with name: no-name-cbea95fb-3053-477d-a20f-0373dd3db8a3

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 1/3:
0.24147569575002717

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 16.8412
[1000]	eval's l1: 14.8329
[1500]	eval's l1: 13.8734
[2000]	eval's l1: 12.5638
[2500]	eval's l1: 12.1121
[3000]	eval's l1: 11.6359
[3500]	eval's l1: 11.6432
[4000]	eval's l1: 11.4096
[4500]	eval's l1: 11.4437
[5000]	eval's l1: 11.1641
[5500]	eval's l1: 11.08
[6000]	eval's l1: 11.1937
[6500]	eval's l1: 11.0325
[7000]	eval's l1: 11.0523
[7500]	eval's l1: 10.9255
[8000]	eval's l1: 10.9774
[8500]	eval's l1: 11.073
[9000]	eval's l1: 10.818
[9500]	eval's l1: 10.8663

Best trial: 0. Best value: 0.30145: 100%|██████████| 1/1 [04:00<00:00, 240.81s/it]

Best iteration: 9715, Score: 10.77605145868696
[I 2025-07-19 16:35:13,932] Trial 0 finished with value: 0.3014503411278507 and parameters: {}. Best is trial 0 with value: 0.3014503411278507.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9715 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 1/3:
0.25572859457483876
Scaling

[I 2025-07-19 16:39:09,110] A new study created in memory with name: no-name-f9eaa20d-d2a6-4f8c-aefc-00fbd69f7278
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.758965
[1000]	eval's l1: 0.749189

Best trial: 0. Best value: 0.262566: 100%|██████████| 1/1 [00:21<00:00, 21.74s/it]

Early stopping, best iteration is:
[902]	eval's l1: 0.748261
Evaluated only: l1
Best iteration: 902, Score: 0.7482606707507257
[I 2025-07-19 16:39:30,849] Trial 0 finished with value: 0.2625657018767194 and parameters: {}. Best is trial 0 with value: 0.2625657018767194.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 902 iterations

[I 2025-07-19 16:39:53,806] A new study created in memory with name: no-name-a3d9dfed-0fe6-45c5-9c4e-e4e0b1f8ea8b

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 1/3:
0.23202178053079467

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.4353
[1000]	eval's l1: 10.3594
[1500]	eval's l1: 10.2369
[2000]	eval's l1: 10.3151

Best trial: 0. Best value: 0.254104: 100%|██████████| 1/1 [00:14<00:00, 14.51s/it]

Early stopping, best iteration is:
[1493]	eval's l1: 10.23
Evaluated only: l1
Best iteration: 1493, Score: 10.230002088979061
[I 2025-07-19 16:40:08,317] Trial 0 finished with value: 0.25410376532923934 and parameters: {}. Best is trial 0 with value: 0.25410376532923934.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1493 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 1/3:
0.243450707793204
Scaling

[I 2025-07-19 16:40:24,291] A new study created in memory with name: no-name-6c9efb86-299e-4131-b5e2-20f81c9dbd76
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.718708
[1000]	eval's l1: 0.719381

Best trial: 0. Best value: 0.248523: 100%|██████████| 1/1 [00:36<00:00, 36.50s/it]

Early stopping, best iteration is:
[679]	eval's l1: 0.715052
Evaluated only: l1
Best iteration: 679, Score: 0.7150521867950311
[I 2025-07-19 16:41:00,785] Trial 0 finished with value: 0.24852300952419407 and parameters: {}. Best is trial 0 with value: 0.24852300952419407.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 679 iterations

[I 2025-07-19 16:41:35,405] A new study created in memory with name: no-name-23797a95-ceff-4d7a-bdec-1918e3571852

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 1/3:
0.24425635515705588

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.61901
[1000]	eval's l1: 9.77803

Best trial: 0. Best value: 0.236833: 100%|██████████| 1/1 [00:32<00:00, 32.45s/it]

Early stopping, best iteration is:
[520]	eval's l1: 9.53471
Evaluated only: l1
Best iteration: 520, Score: 9.534708013976113
[I 2025-07-19 16:42:07,855] Trial 0 finished with value: 0.23683330527139673 and parameters: {}. Best is trial 0 with value: 0.23683330527139673.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 520 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 1/3:
0.2536914824879212
Scaling

[I 2025-07-19 16:42:16,286] A new study created in memory with name: no-name-e33ad1e9-1083-462c-a9f5-c9954076df60
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.839086
[1000]	eval's l1: 0.809684
[1500]	eval's l1: 0.796653
[2000]	eval's l1: 0.777265
[2500]	eval's l1: 0.7708
[3000]	eval's l1: 0.760174
[3500]	eval's l1: 0.762535
[4000]	eval's l1: 0.758326
[4500]	eval's l1: 0.759031
[5000]	eval's l1: 0.75532
[5500]	eval's l1: 0.754997
[6000]	eval's l1: 0.757477
[6500]	eval's l1: 0.757116
[7000]	eval's l1: 0.758881
[7500]	eval's l1: 0.758089
[8000]	eval's l1: 0.758681
[8500]	eval's l1: 0.763265
[9000]	eval's l1: 0.760185
[9500]	eval's l1: 0.760222

Best trial: 0. Best value: 0.460718: 100%|██████████| 1/1 [04:24<00:00, 264.80s/it]

Best iteration: 5602, Score: 0.7519734458318642
[I 2025-07-19 16:46:41,087] Trial 0 finished with value: 0.46071790114036826 and parameters: {}. Best is trial 0 with value: 0.46071790114036826.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5602 iterations

[I 2025-07-19 16:50:31,659] A new study created in memory with name: no-name-f02ea640-2ce5-4565-a9cf-95c93bb172bd

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 1/3:
0.22886363168696933

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 17.2006
[1000]	eval's l1: 15.3441
[1500]	eval's l1: 14.3956
[2000]	eval's l1: 12.9678
[2500]	eval's l1: 12.5922
[3000]	eval's l1: 12.0036
[3500]	eval's l1: 12.0541
[4000]	eval's l1: 11.7791
[4500]	eval's l1: 11.8255
[5000]	eval's l1: 11.45
[5500]	eval's l1: 11.3464
[6000]	eval's l1: 11.4174
[6500]	eval's l1: 11.246
[7000]	eval's l1: 11.2522
[7500]	eval's l1: 11.1475
[8000]	eval's l1: 11.1815
[8500]	eval's l1: 11.3726
[9000]	eval's l1: 11.1561
[9500]	eval's l1: 11.1843

Best trial: 0. Best value: 0.636727: 100%|██████████| 1/1 [02:45<00:00, 165.62s/it]

Best iteration: 7802, Score: 11.00547006498132
[I 2025-07-19 16:53:17,282] Trial 0 finished with value: 0.636726596209928 and parameters: {}. Best is trial 0 with value: 0.636726596209928.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 7802 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 1/3:
0.2519082730613018
Scaling

[I 2025-07-19 16:56:08,612] A new study created in memory with name: no-name-948b6dbc-f517-43bd-9191-2bfb09e3cf12
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.819973
[1000]	eval's l1: 0.784069
[1500]	eval's l1: 0.768215
[2000]	eval's l1: 0.750467
[2500]	eval's l1: 0.74118
[3000]	eval's l1: 0.734135
[3500]	eval's l1: 0.736522
[4000]	eval's l1: 0.733247
[4500]	eval's l1: 0.735638
[5000]	eval's l1: 0.73339
[5500]	eval's l1: 0.731263
[6000]	eval's l1: 0.733499
[6500]	eval's l1: 0.732221
[7000]	eval's l1: 0.733791
[7500]	eval's l1: 0.734632
[8000]	eval's l1: 0.737792
[8500]	eval's l1: 0.743274
[9000]	eval's l1: 0.740558
[9500]	eval's l1: 0.745263

Best trial: 0. Best value: 0.466867: 100%|██████████| 1/1 [05:15<00:00, 315.60s/it]

Best iteration: 5460, Score: 0.7290707183903626
[I 2025-07-19 17:01:24,210] Trial 0 finished with value: 0.4668670141172916 and parameters: {}. Best is trial 0 with value: 0.4668670141172916.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5460 iterations

[I 2025-07-19 17:05:16,276] A new study created in memory with name: no-name-bfde744e-2f70-4391-b826-ea56a4181761

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 1/3:
0.24346681518889304

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 16.8412
[1000]	eval's l1: 14.8329
[1500]	eval's l1: 13.8734
[2000]	eval's l1: 12.5638
[2500]	eval's l1: 12.1121
[3000]	eval's l1: 11.6359
[3500]	eval's l1: 11.6432
[4000]	eval's l1: 11.4096
[4500]	eval's l1: 11.449
[5000]	eval's l1: 11.1708
[5500]	eval's l1: 11.155
[6000]	eval's l1: 11.2281
[6500]	eval's l1: 11.0831
[7000]	eval's l1: 11.1093
[7500]	eval's l1: 10.997
[8000]	eval's l1: 11.0436
[8500]	eval's l1: 11.1423
[9000]	eval's l1: 10.8949
[9500]	eval's l1: 10.923

Best trial: 0. Best value: 0.279287: 100%|██████████| 1/1 [02:17<00:00, 137.24s/it]

Best iteration: 9924, Score: 10.820190905741157
[I 2025-07-19 17:07:33,510] Trial 0 finished with value: 0.2792874443504728 and parameters: {}. Best is trial 0 with value: 0.2792874443504728.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9924 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 1/3:
0.2535209857716711

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250719_201021'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       20.13 GB / 31.23 GB (64.5%)
Disk Space Avail:   726.15 GB / 914.78 GB (79.4%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': [],
 'num_val_windows': 2,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 20140 rows, 656 time series. Median time series length is 34 (min=12, max=34).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 17:10:32
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE']
Training timeseries model SeasonalNaive.
	-0.2661       = Validation score (-WQL)
	1.72    s     = Training runtime
	0.33    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2236       = Validation score (-WQL)
	1.29    s     = Training runtime
	0.05    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2259       = Validation score (-WQL)
	6.51    s     = Training runtime
	0.11    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3237       = Validation score (-WQL)
	0.39    s     = Training runtime
	0.23    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta.
	-0.2121       = Validation score (-WQL)
	1.04    s     = Training runtime
	0.42    s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	-0.2166       = Validation score (-WQL)
	1.33    s     = Training runtime
	1.17    s     = Validation (prediction) runtime
Training timeseries model ChronosZeroShot[bolt_base].
	-0.2126       = Validation score (-WQL)
	3.22    s     = Training runtime
	1.35    s     = Validation (prediction) runtime
Training timeseries model ChronosFineTuned[bolt_small].
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250719_201021/models/ChronosFineTuned[bolt_small]/W0/fine-tuned-ckpt
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250719_201021/models/ChronosFineTuned[bolt_small]/W1/fine-tuned-ckpt
	-0.2035       = Validation score (-WQL)
	88.64   s     = Training runtime
	0.08    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.1918       = Validation score (-WQL)
	105.63  s     = Training runtime
	0.64    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.1938       = Validation score (-WQL)
	53.26   s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.1826       = Validation score (-WQL)
	54.49   s     = Training runtime
	0.25    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.2151       = Validation score (-WQL)
	162.07  s     = Training runtime
	0.46    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoETS': 0.09, 'DeepAR': 0.14, 'NPTS': 0.01, 'PatchTST': 0.58, 'TemporalFusionTransformer': 0.18}
	-0.1794       = Validation score (-WQL)
	1.52    s     = Training runtime
	2.52    s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WeightedEnsemble']
Total runtime: 486.91 s
Best model: WeightedEnsemble
Best model score: -0.1794
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-best_quality entrenado en split 1/3:
0.28818021708197405

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250719_201850'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       17.04 GB / 31.23 GB (54.5%)
Disk Space Avail:   725.75 GB / 914.78 GB (79.3%)
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 20140 rows, 656 time series. Median time series length is 34 (min=12, max=34).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 17:19:01
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive.
	-0.2651       = Validation score (-WQL)
	0.06    s     = Training runtime
	1.56    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.2202       = Validation score (-WQL)
	0.06    s     = Training runtime
	0.44    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2105       = Validation score (-WQL)
	0.66    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2303       = Validation score (-WQL)
	3.98    s     = Training runtime
	0.13    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.1947       = Validation score (-WQL)
	0.07    s     = Training runtime
	1.77    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.1924       = Validation score (-WQL)
	0.07    s     = Training runtime
	0.25    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'ETS': 0.53, 'RecursiveTabular': 0.1, 'SeasonalNaive': 0.37, 'Theta': 0.01}
	-0.1720       = Validation score (-WQL)
	0.41    s     = Training runtime
	2.52    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 9.65 s
Best model: WeightedEnsemble
Best model score: -0.1720
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-fast_training entrenado en split 1/3:
0.26141285643339135
Modelo SMA-12 entrenado en split 1/3:
0.2922211499143638
Registros de entrenamiento: 33
Modelo LinearRegression-magicos-['lags']-all entrenado en split 2/3:
0.37338707
Registros de entrenamiento: 20
Modelo LinearRegression-magicos-['lags']-HC entrenado en split 2/3:
0.62181586
Registros de entrenamiento: 5
Modelo LinearRegression-magicos-['lags']-FOODS entrenado en split 2/3:
0.67709666
Registros de entrenamiento: 8
Modelo LinearRegression-magicos-['lags']-PC entrenado en split 2/3:
0.3157205
Registros de entrenamiento: 772
Modelo LinearRegression-all-['lags']-all entrenado en split 2/3:
0.3286661
Scaling

[I 2025-07-19 17:19:23,568] A new study created in memory with name: no-name-58228c05-19a9-4d3b-b6e2-465ae8a5f7f2
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.67711

Best trial: 0. Best value: 0.240086: 100%|██████████| 1/1 [00:11<00:00, 11.56s/it]

Early stopping, best iteration is:
[252]	eval's l1: 0.671642
Evaluated only: l1
Best iteration: 252, Score: 0.6716421102941157
[I 2025-07-19 17:19:35,130] Trial 0 finished with value: 0.24008570438078466 and parameters: {}. Best is trial 0 with value: 0.24008570438078466.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 252 iterations

[I 2025-07-19 17:19:43,555] A new study created in memory with name: no-name-57e078f5-b38a-40fc-bc61-b73536e47e26

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 2/3:
0.2572043566050097

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.63936

Best trial: 0. Best value: 0.229024: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]

Early stopping, best iteration is:
[77]	eval's l1: 8.76386
Evaluated only: l1
Best iteration: 77, Score: 8.763863580405731
[I 2025-07-19 17:19:46,972] Trial 0 finished with value: 0.22902376728863677 and parameters: {}. Best is trial 0 with value: 0.22902376728863677.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 77 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 2/3:
0.25741917201073733
Scaling

[I 2025-07-19 17:19:49,056] A new study created in memory with name: no-name-0bb30f57-9180-424d-bbed-0db3375474d2
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.680017
[1000]	eval's l1: 0.67066
[1500]	eval's l1: 0.665891
[2000]	eval's l1: 0.66266
[2500]	eval's l1: 0.660633
[3000]	eval's l1: 0.659458
[3500]	eval's l1: 0.659462

Best trial: 0. Best value: 0.262344: 100%|██████████| 1/1 [00:50<00:00, 50.34s/it]

Early stopping, best iteration is:
[3028]	eval's l1: 0.658812
Evaluated only: l1
Best iteration: 3028, Score: 0.6588117222156518
[I 2025-07-19 17:20:39,398] Trial 0 finished with value: 0.26234444588602424 and parameters: {}. Best is trial 0 with value: 0.26234444588602424.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3028 iterations

[I 2025-07-19 17:22:01,207] A new study created in memory with name: no-name-dbcbf927-bac4-444a-baa5-a9d61e91cd7c

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 2/3:
0.25296115101901173

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.17791

Best trial: 0. Best value: 0.224948: 100%|██████████| 1/1 [00:04<00:00,  4.35s/it]

Early stopping, best iteration is:
[119]	eval's l1: 8.6079
Evaluated only: l1
Best iteration: 119, Score: 8.607895798339925
[I 2025-07-19 17:22:05,559] Trial 0 finished with value: 0.22494790180539984 and parameters: {}. Best is trial 0 with value: 0.22494790180539984.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 119 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 2/3:
0.2527852635487611
Scaling

[I 2025-07-19 17:22:08,289] A new study created in memory with name: no-name-be04c759-d1ed-4529-b5c4-b137a09cffb0
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.67539
[1000]	eval's l1: 0.671217
[1500]	eval's l1: 0.664475
[2000]	eval's l1: 0.660797
[2500]	eval's l1: 0.657102
[3000]	eval's l1: 0.657894
[3500]	eval's l1: 0.65549
[4000]	eval's l1: 0.651064
[4500]	eval's l1: 0.646888
[5000]	eval's l1: 0.650035
[5500]	eval's l1: 0.651064
[6000]	eval's l1: 0.650114
[6500]	eval's l1: 0.652913
[7000]	eval's l1: 0.653187
[7500]	eval's l1: 0.653964
[8000]	eval's l1: 0.652935
[8500]	eval's l1: 0.653858
[9000]	eval's l1: 0.653466
[9500]	eval's l1: 0.652306

Best trial: 0. Best value: 0.22725: 100%|██████████| 1/1 [03:41<00:00, 221.21s/it]

Best iteration: 4605, Score: 0.6463919433316284
[I 2025-07-19 17:25:49,499] Trial 0 finished with value: 0.22724975077393422 and parameters: {}. Best is trial 0 with value: 0.22724975077393422.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4605 iterations

[I 2025-07-19 17:28:42,376] A new study created in memory with name: no-name-98376546-c276-4b2a-8fad-e865a103f4b9

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 2/3:
0.2555574026218222

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.12537
[1000]	eval's l1: 9.27293
[1500]	eval's l1: 9.426
[2000]	eval's l1: 9.65129
[2500]	eval's l1: 9.80332
[3000]	eval's l1: 9.91312
[3500]	eval's l1: 9.95212
[4000]	eval's l1: 9.95038
[4500]	eval's l1: 10.0031
[5000]	eval's l1: 10.0869
[5500]	eval's l1: 10.0978
[6000]	eval's l1: 10.0841
[6500]	eval's l1: 10.1101
[7000]	eval's l1: 10.1115
[7500]	eval's l1: 10.1108
[8000]	eval's l1: 10.1268
[8500]	eval's l1: 10.1069
[9000]	eval's l1: 10.1477
[9500]	eval's l1: 10.1573

Best trial: 0. Best value: 0.260506: 100%|██████████| 1/1 [01:55<00:00, 115.57s/it]

Best iteration: 212, Score: 8.857624550426959
[I 2025-07-19 17:30:37,944] Trial 0 finished with value: 0.2605056519950373 and parameters: {}. Best is trial 0 with value: 0.2605056519950373.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 212 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 2/3:
0.2533429886997859
Scaling

[I 2025-07-19 17:30:41,687] A new study created in memory with name: no-name-e6baa205-deb9-4560-b977-e20f4b3f8dc7
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.683916
[1000]	eval's l1: 0.677682
[1500]	eval's l1: 0.665676
[2000]	eval's l1: 0.664263
[2500]	eval's l1: 0.664074
[3000]	eval's l1: 0.665609
[3500]	eval's l1: 0.664994
[4000]	eval's l1: 0.666232
[4500]	eval's l1: 0.66705
[5000]	eval's l1: 0.669212
[5500]	eval's l1: 0.667762
[6000]	eval's l1: 0.667986
[6500]	eval's l1: 0.666817
[7000]	eval's l1: 0.663727
[7500]	eval's l1: 0.66298
[8000]	eval's l1: 0.660932
[8500]	eval's l1: 0.661845
[9000]	eval's l1: 0.662317
[9500]	eval's l1: 0.660953

Best trial: 0. Best value: 0.253066: 100%|██████████| 1/1 [04:06<00:00, 246.62s/it]

Best iteration: 9887, Score: 0.6593722519225188
[I 2025-07-19 17:34:48,305] Trial 0 finished with value: 0.25306616510162844 and parameters: {}. Best is trial 0 with value: 0.25306616510162844.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9887 iterations

[I 2025-07-19 17:41:34,913] A new study created in memory with name: no-name-fd4e11ee-3e16-4e98-89dc-0d520f29f281

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 2/3:
0.25077887588007297

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.96583
[1000]	eval's l1: 9.10938
[1500]	eval's l1: 9.07902
[2000]	eval's l1: 9.23918
[2500]	eval's l1: 9.29119
[3000]	eval's l1: 9.3198
[3500]	eval's l1: 9.37727
[4000]	eval's l1: 9.42861
[4500]	eval's l1: 9.43647
[5000]	eval's l1: 9.557
[5500]	eval's l1: 9.5907
[6000]	eval's l1: 9.60859
[6500]	eval's l1: 9.63179
[7000]	eval's l1: 9.6864
[7500]	eval's l1: 9.74722
[8000]	eval's l1: 9.75134
[8500]	eval's l1: 9.74407
[9000]	eval's l1: 9.77169
[9500]	eval's l1: 9.79839

Best trial: 0. Best value: 0.257945: 100%|██████████| 1/1 [02:44<00:00, 164.30s/it]

Best iteration: 322, Score: 8.763500199172833
[I 2025-07-19 17:44:19,211] Trial 0 finished with value: 0.25794488509905344 and parameters: {}. Best is trial 0 with value: 0.25794488509905344.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 322 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 2/3:
0.2514723803196376
Scaling

[I 2025-07-19 17:44:25,581] A new study created in memory with name: no-name-91cae34f-87e6-4607-8fd1-aa014e47736d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.645262
[1000]	eval's l1: 0.643004

Best trial: 0. Best value: 0.235488: 100%|██████████| 1/1 [00:17<00:00, 17.04s/it]

Early stopping, best iteration is:
[663]	eval's l1: 0.642041
Evaluated only: l1
Best iteration: 663, Score: 0.6420414761232708
[I 2025-07-19 17:44:42,619] Trial 0 finished with value: 0.2354879776525953 and parameters: {}. Best is trial 0 with value: 0.2354879776525953.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 663 iterations

[I 2025-07-19 17:45:02,506] A new study created in memory with name: no-name-c7b702c5-c27e-456c-9894-2117eb0b81cd

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 2/3:
0.2553383066329842

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.63936

Best trial: 0. Best value: 0.229024: 100%|██████████| 1/1 [00:09<00:00,  9.81s/it]

Early stopping, best iteration is:
[77]	eval's l1: 8.76386
Evaluated only: l1
Best iteration: 77, Score: 8.763863580405733
[I 2025-07-19 17:45:12,316] Trial 0 finished with value: 0.22902376728863677 and parameters: {}. Best is trial 0 with value: 0.22902376728863677.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 77 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 2/3:
0.25741917201073733
Scaling

[I 2025-07-19 17:45:14,396] A new study created in memory with name: no-name-ffd243ed-1b3e-494d-88bd-f760f3d62259
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.657739
Early stopping, best iteration is:
[184]	eval's l1: 0.653521
Evaluated only: l1
Best iteration: 184, Score: 0.6535206534225738

Best trial: 0. Best value: 0.23722: 100%|██████████| 1/1 [00:12<00:00, 12.32s/it]

[I 2025-07-19 17:45:26,711] Trial 0 finished with value: 0.2372201423344148 and parameters: {}. Best is trial 0 with value: 0.2372201423344148.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 184 iterations

[I 2025-07-19 17:45:34,316] A new study created in memory with name: no-name-5de4a29a-9b80-4c84-b8fc-33923be88dc6

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 2/3:
0.25351945898651557

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 9.17791

Best trial: 0. Best value: 0.224948: 100%|██████████| 1/1 [00:04<00:00,  4.38s/it]

Early stopping, best iteration is:
[119]	eval's l1: 8.6079
Evaluated only: l1
Best iteration: 119, Score: 8.607895798339925
[I 2025-07-19 17:45:38,692] Trial 0 finished with value: 0.22494790180539984 and parameters: {}. Best is trial 0 with value: 0.22494790180539984.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 119 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 2/3:
0.2527852635487611
Scaling

[I 2025-07-19 17:45:41,541] A new study created in memory with name: no-name-2f55aabb-e1d6-4730-be48-e4419cd6a84e
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.650172
[1000]	eval's l1: 0.639468
[1500]	eval's l1: 0.63803
[2000]	eval's l1: 0.628732
[2500]	eval's l1: 0.627587
[3000]	eval's l1: 0.624477
[3500]	eval's l1: 0.621246
[4000]	eval's l1: 0.622818
[4500]	eval's l1: 0.623706
[5000]	eval's l1: 0.624077
[5500]	eval's l1: 0.62058
[6000]	eval's l1: 0.618705
[6500]	eval's l1: 0.61911
[7000]	eval's l1: 0.620269
[7500]	eval's l1: 0.621715
[8000]	eval's l1: 0.623885
[8500]	eval's l1: 0.623544
[9000]	eval's l1: 0.625217
[9500]	eval's l1: 0.626322

Best trial: 0. Best value: 0.219899: 100%|██████████| 1/1 [03:38<00:00, 218.27s/it]

Best iteration: 6386, Score: 0.617426685613778
[I 2025-07-19 17:49:19,806] Trial 0 finished with value: 0.2198992722157692 and parameters: {}. Best is trial 0 with value: 0.2198992722157692.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6386 iterations

[I 2025-07-19 17:54:08,881] A new study created in memory with name: no-name-b61dcdae-f47b-461e-a988-19c1b0cbebee

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 2/3:
0.2503475355728646

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.12537
[1000]	eval's l1: 9.27293
[1500]	eval's l1: 9.426
[2000]	eval's l1: 9.65129
[2500]	eval's l1: 9.80332
[3000]	eval's l1: 9.91312
[3500]	eval's l1: 9.95212
[4000]	eval's l1: 9.95038
[4500]	eval's l1: 10.0031
[5000]	eval's l1: 10.0869
[5500]	eval's l1: 10.0978
[6000]	eval's l1: 10.0841
[6500]	eval's l1: 10.1101
[7000]	eval's l1: 10.1115
[7500]	eval's l1: 10.1108
[8000]	eval's l1: 10.1268
[8500]	eval's l1: 10.1069
[9000]	eval's l1: 10.1477
[9500]	eval's l1: 10.1573

Best trial: 0. Best value: 0.260506: 100%|██████████| 1/1 [02:21<00:00, 141.97s/it]

Best iteration: 212, Score: 8.857624550426959
[I 2025-07-19 17:56:30,852] Trial 0 finished with value: 0.2605056519950373 and parameters: {}. Best is trial 0 with value: 0.2605056519950373.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 212 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 2/3:
0.2533429886997859
Scaling

[I 2025-07-19 17:56:40,870] A new study created in memory with name: no-name-07d842ae-ab5b-407e-b277-254d685668e3
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.647218
[1000]	eval's l1: 0.647567
[1500]	eval's l1: 0.641268
[2000]	eval's l1: 0.640796
[2500]	eval's l1: 0.640091
[3000]	eval's l1: 0.636223
[3500]	eval's l1: 0.633985
[4000]	eval's l1: 0.631467
[4500]	eval's l1: 0.630395
[5000]	eval's l1: 0.630287
[5500]	eval's l1: 0.627569
[6000]	eval's l1: 0.625691
[6500]	eval's l1: 0.625182
[7000]	eval's l1: 0.626597
[7500]	eval's l1: 0.626937
[8000]	eval's l1: 0.627462
[8500]	eval's l1: 0.627881
[9000]	eval's l1: 0.629493
[9500]	eval's l1: 0.632096

Best trial: 0. Best value: 0.2263: 100%|██████████| 1/1 [04:35<00:00, 275.13s/it]

Best iteration: 6160, Score: 0.6246097569188683
[I 2025-07-19 18:01:16,003] Trial 0 finished with value: 0.22630047895490382 and parameters: {}. Best is trial 0 with value: 0.22630047895490382.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6160 iterations

[I 2025-07-19 18:06:19,417] A new study created in memory with name: no-name-2be6bdd2-9292-4f85-b9bd-87300b031c24

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 2/3:
0.25182788231938097

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.96583
[1000]	eval's l1: 9.10938
[1500]	eval's l1: 9.07902
[2000]	eval's l1: 9.23918
[2500]	eval's l1: 9.29119
[3000]	eval's l1: 9.3198
[3500]	eval's l1: 9.37727
[4000]	eval's l1: 9.42861
[4500]	eval's l1: 9.43647
[5000]	eval's l1: 9.557
[5500]	eval's l1: 9.5907
[6000]	eval's l1: 9.60859
[6500]	eval's l1: 9.63179
[7000]	eval's l1: 9.6864
[7500]	eval's l1: 9.74722
[8000]	eval's l1: 9.75134
[8500]	eval's l1: 9.74407
[9000]	eval's l1: 9.77169
[9500]	eval's l1: 9.79839

Best trial: 0. Best value: 0.257945: 100%|██████████| 1/1 [05:25<00:00, 325.04s/it]

Best iteration: 322, Score: 8.763500199172833
[I 2025-07-19 18:11:44,460] Trial 0 finished with value: 0.25794488509905344 and parameters: {}. Best is trial 0 with value: 0.25794488509905344.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 322 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 2/3:
0.2514723803196376
Scaling

[I 2025-07-19 18:11:51,497] A new study created in memory with name: no-name-58ea8043-8b00-429e-9aac-e4c7d98ba1d0
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.742789

Best trial: 0. Best value: 0.244108: 100%|██████████| 1/1 [00:11<00:00, 11.86s/it]

Early stopping, best iteration is:
[115]	eval's l1: 0.732005
Evaluated only: l1
Best iteration: 115, Score: 0.7320045209348951
[I 2025-07-19 18:12:03,352] Trial 0 finished with value: 0.24410778963892896 and parameters: {}. Best is trial 0 with value: 0.24410778963892896.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 115 iterations

[I 2025-07-19 18:12:08,883] A new study created in memory with name: no-name-530a6fae-2a62-486d-8a1d-ce832da5f52e

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 2/3:
0.2549420095739359

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.463

Best trial: 0. Best value: 0.243772: 100%|██████████| 1/1 [00:06<00:00,  6.36s/it]

Early stopping, best iteration is:
[149]	eval's l1: 9.32823
Evaluated only: l1
Best iteration: 149, Score: 9.328229111692771
[I 2025-07-19 18:12:15,241] Trial 0 finished with value: 0.2437721851814027 and parameters: {}. Best is trial 0 with value: 0.2437721851814027.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 149 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 2/3:
0.26204928653133286
Scaling

[I 2025-07-19 18:12:26,649] A new study created in memory with name: no-name-bb39ac13-34bd-4d99-b7e0-c1332da29f3c
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.77236

Best trial: 0. Best value: 0.242897: 100%|██████████| 1/1 [00:12<00:00, 12.40s/it]

Early stopping, best iteration is:
[73]	eval's l1: 0.742009
Evaluated only: l1
Best iteration: 73, Score: 0.7420089892513079
[I 2025-07-19 18:12:39,044] Trial 0 finished with value: 0.24289743752116527 and parameters: {}. Best is trial 0 with value: 0.24289743752116527.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 73 iterations

[I 2025-07-19 18:12:43,313] A new study created in memory with name: no-name-16fcfdb3-8ee2-4585-afb1-6bafcf82f870

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 2/3:
0.2580401266507539

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.3879

Best trial: 0. Best value: 0.256477: 100%|██████████| 1/1 [00:19<00:00, 19.16s/it]

Early stopping, best iteration is:
[110]	eval's l1: 9.8144
Evaluated only: l1
Best iteration: 110, Score: 9.814397477109873
[I 2025-07-19 18:13:02,470] Trial 0 finished with value: 0.25647709662651735 and parameters: {}. Best is trial 0 with value: 0.25647709662651735.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 110 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 2/3:
0.2711474097398247
Scaling

[I 2025-07-19 18:13:06,233] A new study created in memory with name: no-name-5cb8b922-d310-4020-9c2e-19b97e2eb89d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.776854
[1000]	eval's l1: 0.762092
[1500]	eval's l1: 0.75429
[2000]	eval's l1: 0.748774
[2500]	eval's l1: 0.739738
[3000]	eval's l1: 0.732655
[3500]	eval's l1: 0.733021
[4000]	eval's l1: 0.729292
[4500]	eval's l1: 0.727909
[5000]	eval's l1: 0.726154
[5500]	eval's l1: 0.72927
[6000]	eval's l1: 0.729385
[6500]	eval's l1: 0.728538
[7000]	eval's l1: 0.728673
[7500]	eval's l1: 0.728414
[8000]	eval's l1: 0.730944
[8500]	eval's l1: 0.732358
[9000]	eval's l1: 0.729562
[9500]	eval's l1: 0.731516

Best trial: 0. Best value: 0.511853: 100%|██████████| 1/1 [04:28<00:00, 268.57s/it]

Best iteration: 4737, Score: 0.7235802163852278
[I 2025-07-19 18:17:34,800] Trial 0 finished with value: 0.5118525774239423 and parameters: {}. Best is trial 0 with value: 0.5118525774239423.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4737 iterations

[I 2025-07-19 18:21:09,092] A new study created in memory with name: no-name-79148c4a-6995-4712-a5cc-149e56958cc2

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 2/3:
0.2799360846465888

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 14.8692
[1000]	eval's l1: 13.4882
[1500]	eval's l1: 13.2034
[2000]	eval's l1: 12.0107
[2500]	eval's l1: 11.6605
[3000]	eval's l1: 11.2212
[3500]	eval's l1: 11.3504
[4000]	eval's l1: 11.2158
[4500]	eval's l1: 11.3682
[5000]	eval's l1: 11.0842
[5500]	eval's l1: 11.0681
[6000]	eval's l1: 11.3172
[6500]	eval's l1: 11.0721
[7000]	eval's l1: 11.2001
[7500]	eval's l1: 11.1444
[8000]	eval's l1: 11.2513
[8500]	eval's l1: 11.4293
[9000]	eval's l1: 11.0883
[9500]	eval's l1: 11.0985

Best trial: 0. Best value: 0.953623: 100%|██████████| 1/1 [06:09<00:00, 369.33s/it]

Best iteration: 3382, Score: 10.637910282777707
[I 2025-07-19 18:27:18,418] Trial 0 finished with value: 0.9536226390661954 and parameters: {}. Best is trial 0 with value: 0.9536226390661954.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3382 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 2/3:
0.28598158263705264
Scaling

[I 2025-07-19 18:28:34,923] A new study created in memory with name: no-name-6721ec30-c879-4d6e-969d-b029e65771fd
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.795199
[1000]	eval's l1: 0.789673
[1500]	eval's l1: 0.782615
[2000]	eval's l1: 0.769523
[2500]	eval's l1: 0.762864
[3000]	eval's l1: 0.758706
[3500]	eval's l1: 0.758781
[4000]	eval's l1: 0.754342
[4500]	eval's l1: 0.755803
[5000]	eval's l1: 0.75769
[5500]	eval's l1: 0.755042
[6000]	eval's l1: 0.756928
[6500]	eval's l1: 0.75573
[7000]	eval's l1: 0.754925
[7500]	eval's l1: 0.75569
[8000]	eval's l1: 0.755632
[8500]	eval's l1: 0.756892
[9000]	eval's l1: 0.755411
[9500]	eval's l1: 0.756126

Best trial: 0. Best value: 0.565157: 100%|██████████| 1/1 [04:43<00:00, 283.22s/it]

Best iteration: 3819, Score: 0.749425265837069
[I 2025-07-19 18:33:18,138] Trial 0 finished with value: 0.5651570207052861 and parameters: {}. Best is trial 0 with value: 0.5651570207052861.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3819 iterations

[I 2025-07-19 18:36:20,800] A new study created in memory with name: no-name-d60837c2-9fd2-49fa-8d6b-152b315c39b4

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 2/3:
0.2747330998936634

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 14.988
[1000]	eval's l1: 13.9983
[1500]	eval's l1: 13.6889
[2000]	eval's l1: 12.8227
[2500]	eval's l1: 12.6314
[3000]	eval's l1: 12.2071
[3500]	eval's l1: 12.3648
[4000]	eval's l1: 12.3337
[4500]	eval's l1: 12.3062
[5000]	eval's l1: 12.0123
[5500]	eval's l1: 11.991
[6000]	eval's l1: 12.0743
[6500]	eval's l1: 11.882
[7000]	eval's l1: 11.9955
[7500]	eval's l1: 11.8664
[8000]	eval's l1: 11.9333
[8500]	eval's l1: 12.1504
[9000]	eval's l1: 11.7552
[9500]	eval's l1: 11.8044

Best trial: 0. Best value: 0.355316: 100%|██████████| 1/1 [02:44<00:00, 164.18s/it]

Best iteration: 9715, Score: 11.641012317301442
[I 2025-07-19 18:39:04,976] Trial 0 finished with value: 0.35531633427436116 and parameters: {}. Best is trial 0 with value: 0.35531633427436116.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9715 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 2/3:
0.259669295297359
Scaling

[I 2025-07-19 18:49:08,671] A new study created in memory with name: no-name-ca71a9d5-b822-46c3-8e25-ca2d7a54586e
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.69276

Best trial: 0. Best value: 0.236039: 100%|██████████| 1/1 [00:12<00:00, 12.46s/it]

Early stopping, best iteration is:
[154]	eval's l1: 0.688337
Evaluated only: l1
Best iteration: 154, Score: 0.6883365356121929
[I 2025-07-19 18:49:21,132] Trial 0 finished with value: 0.23603897945205488 and parameters: {}. Best is trial 0 with value: 0.23603897945205488.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 154 iterations

[I 2025-07-19 18:49:27,669] A new study created in memory with name: no-name-8617d768-9208-45b9-aee9-396f3a01c1a8

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 2/3:
0.253067541064763

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.463

Best trial: 0. Best value: 0.243772: 100%|██████████| 1/1 [00:20<00:00, 20.29s/it]

Early stopping, best iteration is:
[149]	eval's l1: 9.32823
Evaluated only: l1
Best iteration: 149, Score: 9.328229111692774
[I 2025-07-19 18:49:47,958] Trial 0 finished with value: 0.2437721851814027 and parameters: {}. Best is trial 0 with value: 0.2437721851814027.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 149 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 2/3:
0.26204928653133286
Scaling

[I 2025-07-19 18:49:51,938] A new study created in memory with name: no-name-4eaab8c6-b924-4d3c-941a-51af51e6dbb4
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.700357

Best trial: 0. Best value: 0.241399: 100%|██████████| 1/1 [00:13<00:00, 13.90s/it]

Early stopping, best iteration is:
[147]	eval's l1: 0.685753
Evaluated only: l1
Best iteration: 147, Score: 0.6857530155602146
[I 2025-07-19 18:50:05,842] Trial 0 finished with value: 0.24139942119984986 and parameters: {}. Best is trial 0 with value: 0.24139942119984986.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 147 iterations

[I 2025-07-19 18:50:12,813] A new study created in memory with name: no-name-eb47eec9-9adc-42d4-a18c-6cd4310ea0b4

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 2/3:
0.2519325689184382

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 11.3879

Best trial: 0. Best value: 0.256477: 100%|██████████| 1/1 [00:06<00:00,  6.70s/it]

Early stopping, best iteration is:
[110]	eval's l1: 9.8144
Evaluated only: l1
Best iteration: 110, Score: 9.814397477109873
[I 2025-07-19 18:50:19,511] Trial 0 finished with value: 0.25647709662651735 and parameters: {}. Best is trial 0 with value: 0.25647709662651735.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 110 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 2/3:
0.2711474097398247
Scaling

[I 2025-07-19 18:50:23,701] A new study created in memory with name: no-name-3c96f24e-e55d-416c-9043-ef6bf308b209
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.733388
[1000]	eval's l1: 0.713816
[1500]	eval's l1: 0.708361
[2000]	eval's l1: 0.700269
[2500]	eval's l1: 0.699596
[3000]	eval's l1: 0.697472
[3500]	eval's l1: 0.697009
[4000]	eval's l1: 0.697028
[4500]	eval's l1: 0.699194
[5000]	eval's l1: 0.697107
[5500]	eval's l1: 0.696227
[6000]	eval's l1: 0.697832
[6500]	eval's l1: 0.696255
[7000]	eval's l1: 0.697824
[7500]	eval's l1: 0.699535
[8000]	eval's l1: 0.701749
[8500]	eval's l1: 0.704139
[9000]	eval's l1: 0.702345
[9500]	eval's l1: 0.702579

Best trial: 0. Best value: 0.545145: 100%|██████████| 1/1 [04:35<00:00, 275.21s/it]

Best iteration: 3956, Score: 0.6916475671896165
[I 2025-07-19 18:54:58,906] Trial 0 finished with value: 0.5451453942553036 and parameters: {}. Best is trial 0 with value: 0.5451453942553036.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3956 iterations

[I 2025-07-19 18:58:00,420] A new study created in memory with name: no-name-b76bbc37-ff21-4d81-837a-33f663fdca03

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 2/3:
0.263638563453362

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 14.8692
[1000]	eval's l1: 13.4882
[1500]	eval's l1: 13.2034
[2000]	eval's l1: 12.0107
[2500]	eval's l1: 11.6605
[3000]	eval's l1: 11.2212
[3500]	eval's l1: 11.3504
[4000]	eval's l1: 11.2158
[4500]	eval's l1: 11.3682
[5000]	eval's l1: 11.0842
[5500]	eval's l1: 11.0681
[6000]	eval's l1: 11.3172
[6500]	eval's l1: 11.0721
[7000]	eval's l1: 11.2001
[7500]	eval's l1: 11.1444
[8000]	eval's l1: 11.2513
[8500]	eval's l1: 11.4293
[9000]	eval's l1: 11.0883
[9500]	eval's l1: 11.0985

Best trial: 0. Best value: 0.953623: 100%|██████████| 1/1 [02:35<00:00, 155.69s/it]

Best iteration: 3382, Score: 10.63791028277771
[I 2025-07-19 19:00:36,113] Trial 0 finished with value: 0.9536226390661954 and parameters: {}. Best is trial 0 with value: 0.9536226390661954.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3382 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 2/3:
0.2859815826370528
Scaling

[I 2025-07-19 19:01:42,717] A new study created in memory with name: no-name-6026f034-ca93-490b-99cd-af175b5ebe2d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.731477
[1000]	eval's l1: 0.73422
[1500]	eval's l1: 0.723198
[2000]	eval's l1: 0.713261
[2500]	eval's l1: 0.713966
[3000]	eval's l1: 0.711202
[3500]	eval's l1: 0.724468
[4000]	eval's l1: 0.722482
[4500]	eval's l1: 0.722709
[5000]	eval's l1: 0.724288
[5500]	eval's l1: 0.723669
[6000]	eval's l1: 0.72688
[6500]	eval's l1: 0.727296
[7000]	eval's l1: 0.727822
[7500]	eval's l1: 0.730478
[8000]	eval's l1: 0.732704
[8500]	eval's l1: 0.735487
[9000]	eval's l1: 0.733351
[9500]	eval's l1: 0.734862

Best trial: 0. Best value: 0.61327: 100%|██████████| 1/1 [04:29<00:00, 269.56s/it]

Best iteration: 2264, Score: 0.7059403488084596
[I 2025-07-19 19:06:12,271] Trial 0 finished with value: 0.6132699854762065 and parameters: {}. Best is trial 0 with value: 0.6132699854762065.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2264 iterations

[I 2025-07-19 19:08:16,579] A new study created in memory with name: no-name-0dbed112-02ca-4056-a5af-8559d7ed1e2d

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 2/3:
0.25912781803778884

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 14.988
[1000]	eval's l1: 13.9983
[1500]	eval's l1: 13.689
[2000]	eval's l1: 12.8227
[2500]	eval's l1: 12.6314
[3000]	eval's l1: 12.2071
[3500]	eval's l1: 12.3649
[4000]	eval's l1: 12.3337
[4500]	eval's l1: 12.3106
[5000]	eval's l1: 11.9875
[5500]	eval's l1: 11.9876
[6000]	eval's l1: 12.142
[6500]	eval's l1: 11.8587
[7000]	eval's l1: 12.0001
[7500]	eval's l1: 11.9338
[8000]	eval's l1: 12.0548
[8500]	eval's l1: 12.2333
[9000]	eval's l1: 11.8055
[9500]	eval's l1: 11.8816

Best trial: 0. Best value: 0.953717: 100%|██████████| 1/1 [03:15<00:00, 195.69s/it]

Best iteration: 3382, Score: 11.726652777542139
[I 2025-07-19 19:11:32,271] Trial 0 finished with value: 0.9537174540968609 and parameters: {}. Best is trial 0 with value: 0.9537174540968609.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3382 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 2/3:
0.2674718542771695

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250719_221314'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       17.83 GB / 31.23 GB (57.1%)
Disk Space Avail:   725.69 GB / 914.78 GB (79.3%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': [],
 'num_val_windows': 2,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 19484 rows, 656 time series. Median time series length is 33 (min=11, max=33).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 19:13:24
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE']
Training timeseries model SeasonalNaive.
	-0.2724       = Validation score (-WQL)
	1.84    s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2168       = Validation score (-WQL)
	1.47    s     = Training runtime
	0.07    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2017       = Validation score (-WQL)
	12.38   s     = Training runtime
	0.10    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3258       = Validation score (-WQL)
	0.39    s     = Training runtime
	0.25    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta.
	-0.2033       = Validation score (-WQL)
	1.10    s     = Training runtime
	0.31    s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	-0.2035       = Validation score (-WQL)
	1.36    s     = Training runtime
	1.30    s     = Validation (prediction) runtime
Training timeseries model ChronosZeroShot[bolt_base].
	-0.1971       = Validation score (-WQL)
	1.83    s     = Training runtime
	1.31    s     = Validation (prediction) runtime
Training timeseries model ChronosFineTuned[bolt_small].
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250719_221314/models/ChronosFineTuned[bolt_small]/W0/fine-tuned-ckpt
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250719_221314/models/ChronosFineTuned[bolt_small]/W1/fine-tuned-ckpt
	-0.1907       = Validation score (-WQL)
	99.07   s     = Training runtime
	0.08    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.1763       = Validation score (-WQL)
	163.93  s     = Training runtime
	0.63    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.1918       = Validation score (-WQL)
	97.01   s     = Training runtime
	0.23    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.1749       = Validation score (-WQL)
	87.94   s     = Training runtime
	0.25    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.1869       = Validation score (-WQL)
	147.32  s     = Training runtime
	0.47    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoETS': 0.06, 'PatchTST': 0.31, 'RecursiveTabular': 0.01, 'TemporalFusionTransformer': 0.45, 'TiDE': 0.17}
	-0.1687       = Validation score (-WQL)
	1.53    s     = Training runtime
	2.74    s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WeightedEnsemble']
Total runtime: 622.65 s
Best model: WeightedEnsemble
Best model score: -0.1687
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-best_quality entrenado en split 2/3:
0.23305520755531847

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250719_222359'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       15.78 GB / 31.23 GB (50.5%)
Disk Space Avail:   725.26 GB / 914.78 GB (79.3%)
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 19484 rows, 656 time series. Median time series length is 33 (min=11, max=33).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 19:24:09
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive.
	-0.2580       = Validation score (-WQL)
	0.06    s     = Training runtime
	1.58    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.3100       = Validation score (-WQL)
	0.06    s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2344       = Validation score (-WQL)
	0.63    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2146       = Validation score (-WQL)
	2.82    s     = Training runtime
	0.09    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.2199       = Validation score (-WQL)
	0.07    s     = Training runtime
	1.84    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.2213       = Validation score (-WQL)
	0.07    s     = Training runtime
	0.26    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'DirectTabular': 0.53, 'ETS': 0.33, 'RecursiveTabular': 0.13}
	-0.2017       = Validation score (-WQL)
	0.42    s     = Training runtime
	2.00    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 8.31 s
Best model: WeightedEnsemble
Best model score: -0.2017
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-fast_training entrenado en split 2/3:
0.21802489131320393
Modelo SMA-12 entrenado en split 2/3:
0.2579996583872914
Registros de entrenamiento: 33
Modelo LinearRegression-magicos-['lags']-all entrenado en split 3/3:
0.43769825
Registros de entrenamiento: 20
Modelo LinearRegression-magicos-['lags']-HC entrenado en split 3/3:
0.48148686
Registros de entrenamiento: 5
Modelo LinearRegression-magicos-['lags']-FOODS entrenado en split 3/3:
0.38890284
Registros de entrenamiento: 8
Modelo LinearRegression-magicos-['lags']-PC entrenado en split 3/3:
0.7852721
Registros de entrenamiento: 754
Modelo LinearRegression-all-['lags']-all entrenado en split 3/3:
0.3155724
Scaling

[I 2025-07-19 19:24:30,627] A new study created in memory with name: no-name-3808bd3c-92c4-4d2a-ab29-8392528be09d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.646923
[1000]	eval's l1: 0.639057

Best trial: 0. Best value: 0.383278: 100%|██████████| 1/1 [00:26<00:00, 26.00s/it]

Early stopping, best iteration is:
[909]	eval's l1: 0.637374
Evaluated only: l1
Best iteration: 909, Score: 0.6373740855145078
[I 2025-07-19 19:24:56,630] Trial 0 finished with value: 0.3832782330325614 and parameters: {}. Best is trial 0 with value: 0.3832782330325614.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 909 iterations

[I 2025-07-19 19:25:31,981] A new study created in memory with name: no-name-66e8ca5c-7f30-425d-8b72-a85ffe9c1c6d

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 3/3:
0.3033478803308595

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.2291
[1000]	eval's l1: 10.0015
[1500]	eval's l1: 9.94185

Best trial: 0. Best value: 0.352797: 100%|██████████| 1/1 [00:13<00:00, 13.83s/it]

Early stopping, best iteration is:
[1426]	eval's l1: 9.90917
Evaluated only: l1
Best iteration: 1426, Score: 9.909172174080814
[I 2025-07-19 19:25:45,810] Trial 0 finished with value: 0.3527971076237677 and parameters: {}. Best is trial 0 with value: 0.3527971076237677.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1426 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 3/3:
0.31426066934380825
Scaling

[I 2025-07-19 19:26:51,253] A new study created in memory with name: no-name-9005943d-00f0-4bf9-a314-822675d67538
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.641854
[1000]	eval's l1: 0.633937
[1500]	eval's l1: 0.629485
[2000]	eval's l1: 0.62456
[2500]	eval's l1: 0.624042
[3000]	eval's l1: 0.620792
[3500]	eval's l1: 0.620503

Best trial: 0. Best value: 0.381087: 100%|██████████| 1/1 [01:38<00:00, 98.98s/it]

Early stopping, best iteration is:
[3302]	eval's l1: 0.61868
Evaluated only: l1
Best iteration: 3302, Score: 0.6186803464039217
[I 2025-07-19 19:28:30,232] Trial 0 finished with value: 0.38108705741912463 and parameters: {}. Best is trial 0 with value: 0.38108705741912463.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3302 iterations

[I 2025-07-19 19:31:36,778] A new study created in memory with name: no-name-ae380316-f686-4183-ba48-8e90c0398097

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta entrenado en split 3/3:
0.3177024654980912

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.8932
[1000]	eval's l1: 10.786
[1500]	eval's l1: 10.7337

Best trial: 0. Best value: 0.380178: 100%|██████████| 1/1 [00:25<00:00, 25.54s/it]

Early stopping, best iteration is:
[1360]	eval's l1: 10.6782
Evaluated only: l1
Best iteration: 1360, Score: 10.678234901224242
[I 2025-07-19 19:32:02,321] Trial 0 finished with value: 0.3801781140393822 and parameters: {}. Best is trial 0 with value: 0.3801781140393822.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1360 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta entrenado en split 3/3:
0.3018912766007646
Scaling

[I 2025-07-19 19:32:29,615] A new study created in memory with name: no-name-d50fe05e-8989-4e78-8f3f-47a2e43cfae2
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.676317
[1000]	eval's l1: 0.672834
[1500]	eval's l1: 0.664484
[2000]	eval's l1: 0.651842
[2500]	eval's l1: 0.642166
[3000]	eval's l1: 0.64109
[3500]	eval's l1: 0.640201
[4000]	eval's l1: 0.634948
[4500]	eval's l1: 0.631794
[5000]	eval's l1: 0.629503
[5500]	eval's l1: 0.624505
[6000]	eval's l1: 0.623853
[6500]	eval's l1: 0.622921
[7000]	eval's l1: 0.621983
[7500]	eval's l1: 0.619599
[8000]	eval's l1: 0.618092
[8500]	eval's l1: 0.617676
[9000]	eval's l1: 0.615922
[9500]	eval's l1: 0.615137

Best trial: 0. Best value: 0.378024: 100%|██████████| 1/1 [07:15<00:00, 435.28s/it]

Best iteration: 9754, Score: 0.6147873895527387
[I 2025-07-19 19:39:44,894] Trial 0 finished with value: 0.37802446648469784 and parameters: {}. Best is trial 0 with value: 0.37802446648469784.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9754 iterations

[I 2025-07-19 19:49:05,164] A new study created in memory with name: no-name-26b6abc3-bafc-4db2-83b0-865e3dec6592

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 3/3:
0.3002844237294729

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 10.8974
[1000]	eval's l1: 10.6717
[1500]	eval's l1: 10.6172
[2000]	eval's l1: 10.6479
[2500]	eval's l1: 10.4241
[3000]	eval's l1: 10.3804
[3500]	eval's l1: 10.3142
[4000]	eval's l1: 10.2509
[4500]	eval's l1: 10.2917
[5000]	eval's l1: 10.2021
[5500]	eval's l1: 10.1565
[6000]	eval's l1: 10.1954
[6500]	eval's l1: 10.1764
[7000]	eval's l1: 10.2485
[7500]	eval's l1: 10.2467
[8000]	eval's l1: 10.2774
[8500]	eval's l1: 10.2701
[9000]	eval's l1: 10.2771
[9500]	eval's l1: 10.2386

Best trial: 0. Best value: 0.387152: 100%|██████████| 1/1 [02:29<00:00, 149.46s/it]

Best iteration: 5478, Score: 10.143575683564015
[I 2025-07-19 19:51:34,620] Trial 0 finished with value: 0.3871515512825614 and parameters: {}. Best is trial 0 with value: 0.3871515512825614.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5478 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 3/3:
0.3096574046227542
Scaling

[I 2025-07-19 19:53:19,147] A new study created in memory with name: no-name-4bdf8486-b477-4fa9-a700-75e79f051363
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.664153
[1000]	eval's l1: 0.656598
[1500]	eval's l1: 0.652563
[2000]	eval's l1: 0.64222
[2500]	eval's l1: 0.63994
[3000]	eval's l1: 0.634561
[3500]	eval's l1: 0.630943
[4000]	eval's l1: 0.629971
[4500]	eval's l1: 0.632711
[5000]	eval's l1: 0.630222
[5500]	eval's l1: 0.627199
[6000]	eval's l1: 0.628717
[6500]	eval's l1: 0.63037
[7000]	eval's l1: 0.627832
[7500]	eval's l1: 0.626887
[8000]	eval's l1: 0.626555
[8500]	eval's l1: 0.627307
[9000]	eval's l1: 0.626523
[9500]	eval's l1: 0.625753

Best trial: 0. Best value: 0.380249: 100%|██████████| 1/1 [04:39<00:00, 279.79s/it]

Best iteration: 9984, Score: 0.6248374734456738
[I 2025-07-19 19:57:58,935] Trial 0 finished with value: 0.38024892423320383 and parameters: {}. Best is trial 0 with value: 0.38024892423320383.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9984 iterations

[I 2025-07-19 20:08:02,862] A new study created in memory with name: no-name-24ecd6fd-6a27-4662-84a3-31af3058ee3b

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-delta entrenado en split 3/3:
0.31347644098259086

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 11.1371
[1000]	eval's l1: 10.8422
[1500]	eval's l1: 10.8596
[2000]	eval's l1: 10.879
[2500]	eval's l1: 10.7501
[3000]	eval's l1: 10.6057
[3500]	eval's l1: 10.6092
[4000]	eval's l1: 10.5845
[4500]	eval's l1: 10.4716
[5000]	eval's l1: 10.4149
[5500]	eval's l1: 10.4264
[6000]	eval's l1: 10.4283
[6500]	eval's l1: 10.4033
[7000]	eval's l1: 10.414
[7500]	eval's l1: 10.4211
[8000]	eval's l1: 10.4081
[8500]	eval's l1: 10.429
[9000]	eval's l1: 10.4238
[9500]	eval's l1: 10.4203

Best trial: 0. Best value: 0.369878: 100%|██████████| 1/1 [06:10<00:00, 370.25s/it]

Best iteration: 9974, Score: 10.386624191072455
[I 2025-07-19 20:14:13,107] Trial 0 finished with value: 0.36987829686390344 and parameters: {}. Best is trial 0 with value: 0.36987829686390344.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9974 iterations
Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-delta entrenado en split 3/3:
0.29197040806900015
Scaling

[I 2025-07-19 20:19:18,763] A new study created in memory with name: no-name-c633ab4b-4df8-4be3-861d-360c7b6c9174
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.606369
[1000]	eval's l1: 0.600295
[1500]	eval's l1: 0.603345

Best trial: 0. Best value: 0.360692: 100%|██████████| 1/1 [00:28<00:00, 28.70s/it]

Early stopping, best iteration is:
[1000]	eval's l1: 0.600295
Evaluated only: l1
Best iteration: 1000, Score: 0.6002946686723829
[I 2025-07-19 20:19:47,465] Trial 0 finished with value: 0.3606915307688375 and parameters: {}. Best is trial 0 with value: 0.3606915307688375.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1000 iterations

[I 2025-07-19 20:20:21,897] A new study created in memory with name: no-name-871f8d6b-729c-441f-8bda-1b694c33c903

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 3/3:
0.29938221178309743

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.2291
[1000]	eval's l1: 10.0015
[1500]	eval's l1: 9.94185

Best trial: 0. Best value: 0.352797: 100%|██████████| 1/1 [00:14<00:00, 14.55s/it]

Early stopping, best iteration is:
[1426]	eval's l1: 9.90917
Evaluated only: l1
Best iteration: 1426, Score: 9.90917217408081
[I 2025-07-19 20:20:36,444] Trial 0 finished with value: 0.3527971076237677 and parameters: {}. Best is trial 0 with value: 0.3527971076237677.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1426 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 3/3:
0.31426066934380825
Scaling

[I 2025-07-19 20:20:56,563] A new study created in memory with name: no-name-5e7c84c7-43b7-4f35-91e5-242bef4f5dbe
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.605215

Best trial: 0. Best value: 0.354789: 100%|██████████| 1/1 [00:22<00:00, 22.49s/it]

Early stopping, best iteration is:
[339]	eval's l1: 0.601968
Evaluated only: l1
Best iteration: 339, Score: 0.6019680751134782
[I 2025-07-19 20:21:19,056] Trial 0 finished with value: 0.3547894185296415 and parameters: {}. Best is trial 0 with value: 0.3547894185296415.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 339 iterations

[I 2025-07-19 20:21:40,795] A new study created in memory with name: no-name-9229dadb-217d-49f9-b201-a52387a988da

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-delta entrenado en split 3/3:
0.30602755209062316

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.8932
[1000]	eval's l1: 10.786
[1500]	eval's l1: 10.7337

Best trial: 0. Best value: 0.380178: 100%|██████████| 1/1 [00:18<00:00, 18.21s/it]

Early stopping, best iteration is:
[1360]	eval's l1: 10.6782
Evaluated only: l1
Best iteration: 1360, Score: 10.678234901224242
[I 2025-07-19 20:21:59,007] Trial 0 finished with value: 0.3801781140393822 and parameters: {}. Best is trial 0 with value: 0.3801781140393822.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1360 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta entrenado en split 3/3:
0.3018912766007646
Scaling

[I 2025-07-19 20:22:16,983] A new study created in memory with name: no-name-6593f788-8d17-4d96-b7c0-0d0069fb4b0e
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.630634
[1000]	eval's l1: 0.627241
[1500]	eval's l1: 0.615136
[2000]	eval's l1: 0.608637
[2500]	eval's l1: 0.605366
[3000]	eval's l1: 0.607545
[3500]	eval's l1: 0.612492
[4000]	eval's l1: 0.610871
[4500]	eval's l1: 0.612866
[5000]	eval's l1: 0.611574
[5500]	eval's l1: 0.612728
[6000]	eval's l1: 0.61467
[6500]	eval's l1: 0.614659
[7000]	eval's l1: 0.613893
[7500]	eval's l1: 0.613258
[8000]	eval's l1: 0.6138
[8500]	eval's l1: 0.615632
[9000]	eval's l1: 0.614797
[9500]	eval's l1: 0.614257

Best trial: 0. Best value: 0.437647: 100%|██████████| 1/1 [07:50<00:00, 470.73s/it]

Best iteration: 2381, Score: 0.6032412116719391
[I 2025-07-19 20:30:07,711] Trial 0 finished with value: 0.4376474158445938 and parameters: {}. Best is trial 0 with value: 0.4376474158445938.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2381 iterations

[I 2025-07-19 20:35:17,570] A new study created in memory with name: no-name-6149fb72-c95c-41ea-8fda-c7f9ae471226

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 3/3:
0.30634659402580117

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 10.8974
[1000]	eval's l1: 10.6717
[1500]	eval's l1: 10.6172
[2000]	eval's l1: 10.6479
[2500]	eval's l1: 10.4241
[3000]	eval's l1: 10.3804
[3500]	eval's l1: 10.3142
[4000]	eval's l1: 10.2509
[4500]	eval's l1: 10.2917
[5000]	eval's l1: 10.2021
[5500]	eval's l1: 10.1565
[6000]	eval's l1: 10.1954
[6500]	eval's l1: 10.1764
[7000]	eval's l1: 10.2485
[7500]	eval's l1: 10.2467
[8000]	eval's l1: 10.2774
[8500]	eval's l1: 10.2701
[9000]	eval's l1: 10.2771
[9500]	eval's l1: 10.2386

Best trial: 0. Best value: 0.387152: 100%|██████████| 1/1 [05:09<00:00, 309.84s/it]

Best iteration: 5478, Score: 10.143575683564018
[I 2025-07-19 20:40:27,409] Trial 0 finished with value: 0.3871515512825614 and parameters: {}. Best is trial 0 with value: 0.3871515512825614.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5478 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 3/3:
0.3096574046227542
Scaling

[I 2025-07-19 20:42:18,411] A new study created in memory with name: no-name-e15f6df8-b1d8-4f07-9d13-d4424dffe368
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.623859
[1000]	eval's l1: 0.615354
[1500]	eval's l1: 0.614546
[2000]	eval's l1: 0.603305
[2500]	eval's l1: 0.601966
[3000]	eval's l1: 0.599544
[3500]	eval's l1: 0.599322
[4000]	eval's l1: 0.60173
[4500]	eval's l1: 0.604139
[5000]	eval's l1: 0.602786
[5500]	eval's l1: 0.604394
[6000]	eval's l1: 0.604799
[6500]	eval's l1: 0.604234
[7000]	eval's l1: 0.604592
[7500]	eval's l1: 0.604643
[8000]	eval's l1: 0.606281
[8500]	eval's l1: 0.607234
[9000]	eval's l1: 0.605729
[9500]	eval's l1: 0.605895

Best trial: 0. Best value: 0.424965: 100%|██████████| 1/1 [04:41<00:00, 281.97s/it]

Best iteration: 3332, Score: 0.5970925637343997
[I 2025-07-19 20:47:00,376] Trial 0 finished with value: 0.4249653762242275 and parameters: {}. Best is trial 0 with value: 0.4249653762242275.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3332 iterations

[I 2025-07-19 20:49:43,887] A new study created in memory with name: no-name-043ef455-d4b5-43ac-9382-7e6c7fd41d25

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-delta entrenado en split 3/3:
0.3148203587868866

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 11.1371
[1000]	eval's l1: 10.8422
[1500]	eval's l1: 10.8596
[2000]	eval's l1: 10.879
[2500]	eval's l1: 10.7501
[3000]	eval's l1: 10.6057
[3500]	eval's l1: 10.6092
[4000]	eval's l1: 10.5913
[4500]	eval's l1: 10.5167
[5000]	eval's l1: 10.5032
[5500]	eval's l1: 10.5608
[6000]	eval's l1: 10.5647
[6500]	eval's l1: 10.577
[7000]	eval's l1: 10.5623
[7500]	eval's l1: 10.6032
[8000]	eval's l1: 10.5979
[8500]	eval's l1: 10.6039
[9000]	eval's l1: 10.5921
[9500]	eval's l1: 10.5708

Best trial: 0. Best value: 0.402307: 100%|██████████| 1/1 [03:10<00:00, 190.16s/it]

Best iteration: 4985, Score: 10.501956233384126
[I 2025-07-19 20:52:54,045] Trial 0 finished with value: 0.4023067277716133 and parameters: {}. Best is trial 0 with value: 0.4023067277716133.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4985 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-delta entrenado en split 3/3:
0.2921773702767573
Scaling

[I 2025-07-19 20:56:26,871] A new study created in memory with name: no-name-b6a0e69a-93e6-4bb2-b2a7-9923cff7374b
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.641886
[1000]	eval's l1: 0.632494
[1500]	eval's l1: 0.623522
[2000]	eval's l1: 0.618012
[2500]	eval's l1: 0.612149
[3000]	eval's l1: 0.608449
[3500]	eval's l1: 0.605358
[4000]	eval's l1: 0.601527
[4500]	eval's l1: 0.599554
[5000]	eval's l1: 0.598924
[5500]	eval's l1: 0.598076
[6000]	eval's l1: 0.597371
[6500]	eval's l1: 0.597426
[7000]	eval's l1: 0.596687
[7500]	eval's l1: 0.595976
[8000]	eval's l1: 0.594877
[8500]	eval's l1: 0.593746
[9000]	eval's l1: 0.592503
[9500]	eval's l1: 0.592526
Early stopping, best iteration is:
[9234]	eval's l1: 0.591602
Evaluated only: l1

Best trial: 0. Best value: 0.337113: 100%|██████████| 1/1 [02:18<00:00, 138.81s/it]

Best iteration: 9234, Score: 0.5916021667923237
[I 2025-07-19 20:58:45,681] Trial 0 finished with value: 0.3371128368197521 and parameters: {}. Best is trial 0 with value: 0.3371128368197521.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9234 iterations

[I 2025-07-19 21:02:24,948] A new study created in memory with name: no-name-e5f196a7-c340-4431-b753-dd4f8e892562

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 3/3:
0.33699853445405087

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.495

Best trial: 0. Best value: 0.3412: 100%|██████████| 1/1 [00:04<00:00,  4.76s/it]

Early stopping, best iteration is:
[91]	eval's l1: 9.58345
Evaluated only: l1
Best iteration: 91, Score: 9.583452128341344
[I 2025-07-19 21:02:29,707] Trial 0 finished with value: 0.34120046909138274 and parameters: {}. Best is trial 0 with value: 0.34120046909138274.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 91 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 3/3:
0.348840051056301
Scaling

[I 2025-07-19 21:02:32,676] A new study created in memory with name: no-name-343cc86b-c96e-4149-99ec-f5da03ef5c34
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.658927
[1000]	eval's l1: 0.642822
[1500]	eval's l1: 0.629443
[2000]	eval's l1: 0.621965
[2500]	eval's l1: 0.61507
[3000]	eval's l1: 0.611947
[3500]	eval's l1: 0.609662
[4000]	eval's l1: 0.606884
[4500]	eval's l1: 0.604576
[5000]	eval's l1: 0.604336
[5500]	eval's l1: 0.603535
[6000]	eval's l1: 0.602913

Best trial: 0. Best value: 0.356756: 100%|██████████| 1/1 [01:36<00:00, 96.41s/it]

Early stopping, best iteration is:
[5831]	eval's l1: 0.602247
Evaluated only: l1
Best iteration: 5831, Score: 0.6022467089346819
[I 2025-07-19 21:04:09,081] Trial 0 finished with value: 0.3567564936966598 and parameters: {}. Best is trial 0 with value: 0.3567564936966598.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5831 iterations

[I 2025-07-19 21:06:52,023] A new study created in memory with name: no-name-aefc6dc7-b2a2-4498-91fb-4b51ea9396e7

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2 entrenado en split 3/3:
0.354941975841771

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.7641

Best trial: 0. Best value: 0.335293: 100%|██████████| 1/1 [00:05<00:00,  5.44s/it]

Early stopping, best iteration is:
[83]	eval's l1: 9.41752
Evaluated only: l1
Best iteration: 83, Score: 9.41751993911632
[I 2025-07-19 21:06:57,465] Trial 0 finished with value: 0.33529277110920086 and parameters: {}. Best is trial 0 with value: 0.33529277110920086.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 83 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-t+2 entrenado en split 3/3:
0.3550121642375934
Scaling

[I 2025-07-19 21:07:00,452] A new study created in memory with name: no-name-d45944cf-7043-422e-8729-92aa7991895b
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.64193
[1000]	eval's l1: 0.639636
[1500]	eval's l1: 0.635286
[2000]	eval's l1: 0.635279
[2500]	eval's l1: 0.633406
[3000]	eval's l1: 0.632653
[3500]	eval's l1: 0.632169
[4000]	eval's l1: 0.630316
[4500]	eval's l1: 0.627563
[5000]	eval's l1: 0.626618
[5500]	eval's l1: 0.623731
[6000]	eval's l1: 0.620729
[6500]	eval's l1: 0.618725
[7000]	eval's l1: 0.61475
[7500]	eval's l1: 0.614214
[8000]	eval's l1: 0.610174
[8500]	eval's l1: 0.60707
[9000]	eval's l1: 0.608931
[9500]	eval's l1: 0.606368

Best trial: 0. Best value: 0.337508: 100%|██████████| 1/1 [03:49<00:00, 229.20s/it]

Best iteration: 9965, Score: 0.6042828258081705
[I 2025-07-19 21:10:49,648] Trial 0 finished with value: 0.3375081676972898 and parameters: {}. Best is trial 0 with value: 0.3375081676972898.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9965 iterations

[I 2025-07-19 21:17:23,625] A new study created in memory with name: no-name-c43f955d-c726-4b83-b9f2-8c84c7b4e0a1

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 3/3:
0.3338262040190762

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 7.92704
[1000]	eval's l1: 7.72351
[1500]	eval's l1: 7.81623
[2000]	eval's l1: 8.33203
[2500]	eval's l1: 8.68375
[3000]	eval's l1: 9.02326
[3500]	eval's l1: 8.91328
[4000]	eval's l1: 9.17794
[4500]	eval's l1: 9.05845
[5000]	eval's l1: 9.40498
[5500]	eval's l1: 9.4133
[6000]	eval's l1: 9.26088
[6500]	eval's l1: 9.45463
[7000]	eval's l1: 9.27331
[7500]	eval's l1: 9.37606
[8000]	eval's l1: 9.31129
[8500]	eval's l1: 9.16679
[9000]	eval's l1: 9.55662
[9500]	eval's l1: 9.51952

Best trial: 0. Best value: 0.958855: 100%|██████████| 1/1 [02:36<00:00, 156.89s/it]

Best iteration: 1193, Score: 7.528048232841156
[I 2025-07-19 21:20:00,510] Trial 0 finished with value: 0.9588545515285396 and parameters: {}. Best is trial 0 with value: 0.9588545515285396.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1193 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 3/3:
0.42457188876506136
Scaling

[I 2025-07-19 21:20:30,726] A new study created in memory with name: no-name-601598ee-1380-4257-8586-647f917c4bfb
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.62731
[1000]	eval's l1: 0.628299
[1500]	eval's l1: 0.630555
[2000]	eval's l1: 0.635702
[2500]	eval's l1: 0.628489
[3000]	eval's l1: 0.628116
[3500]	eval's l1: 0.622489
[4000]	eval's l1: 0.618215
[4500]	eval's l1: 0.614061
[5000]	eval's l1: 0.616043
[5500]	eval's l1: 0.612675
[6000]	eval's l1: 0.611152
[6500]	eval's l1: 0.608734
[7000]	eval's l1: 0.604089
[7500]	eval's l1: 0.605004
[8000]	eval's l1: 0.602831
[8500]	eval's l1: 0.599581
[9000]	eval's l1: 0.599813
[9500]	eval's l1: 0.59969

Best trial: 0. Best value: 0.30858: 100%|██████████| 1/1 [04:42<00:00, 282.30s/it]

Best iteration: 9133, Score: 0.5967139153860265
[I 2025-07-19 21:25:13,020] Trial 0 finished with value: 0.30857994415524687 and parameters: {}. Best is trial 0 with value: 0.30857994415524687.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9133 iterations

[I 2025-07-19 21:31:53,158] A new study created in memory with name: no-name-d6b4dfe1-1e0a-4aa8-a227-b3fc3481f990

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-True-target-t+2 entrenado en split 3/3:
0.36323784895285055

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 7.5213
[1000]	eval's l1: 7.66003
[1500]	eval's l1: 7.94842
[2000]	eval's l1: 8.54111
[2500]	eval's l1: 8.86475
[3000]	eval's l1: 9.20433
[3500]	eval's l1: 9.08984
[4000]	eval's l1: 9.28011
[4500]	eval's l1: 9.26707
[5000]	eval's l1: 9.61875
[5500]	eval's l1: 9.65228
[6000]	eval's l1: 9.4963
[6500]	eval's l1: 9.79732
[7000]	eval's l1: 9.66649
[7500]	eval's l1: 9.86547
[8000]	eval's l1: 9.80205
[8500]	eval's l1: 9.65881
[9000]	eval's l1: 10.0516
[9500]	eval's l1: 9.97872

Best trial: 0. Best value: 0.961232: 100%|██████████| 1/1 [02:27<00:00, 147.12s/it]

Best iteration: 803, Score: 7.345876860457744
[I 2025-07-19 21:34:20,280] Trial 0 finished with value: 0.9612319732763446 and parameters: {}. Best is trial 0 with value: 0.9612319732763446.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 803 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-t+2 entrenado en split 3/3:
0.445731616765319
Scaling

[I 2025-07-19 21:34:40,236] A new study created in memory with name: no-name-d8f770bf-dcf7-447f-a246-25a0356e664f
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.612573
[1000]	eval's l1: 0.595958
[1500]	eval's l1: 0.59404
[2000]	eval's l1: 0.592551
[2500]	eval's l1: 0.591054
[3000]	eval's l1: 0.590533
[3500]	eval's l1: 0.589339
[4000]	eval's l1: 0.587869

Best trial: 0. Best value: 0.345455: 100%|██████████| 1/1 [00:59<00:00, 59.70s/it]

Early stopping, best iteration is:
[3849]	eval's l1: 0.587321
Evaluated only: l1
Best iteration: 3849, Score: 0.5873205511973862
[I 2025-07-19 21:35:39,936] Trial 0 finished with value: 0.3454550263848673 and parameters: {}. Best is trial 0 with value: 0.3454550263848673.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3849 iterations

[I 2025-07-19 21:37:13,917] A new study created in memory with name: no-name-a48026bd-9456-4ec5-97c3-7e36b6a07caa

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 3/3:
0.319241992325072

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.495

Best trial: 0. Best value: 0.3412: 100%|██████████| 1/1 [00:04<00:00,  4.64s/it]

Early stopping, best iteration is:
[91]	eval's l1: 9.58345
Evaluated only: l1
Best iteration: 91, Score: 9.583452128341344
[I 2025-07-19 21:37:18,554] Trial 0 finished with value: 0.34120046909138274 and parameters: {}. Best is trial 0 with value: 0.34120046909138274.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 91 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 3/3:
0.348840051056301
Scaling

[I 2025-07-19 21:37:21,409] A new study created in memory with name: no-name-e69d28f9-fa54-44c5-9e48-4c2f0b098df2
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.595626
[1000]	eval's l1: 0.587185
[1500]	eval's l1: 0.581529
[2000]	eval's l1: 0.581579
[2500]	eval's l1: 0.580963

Best trial: 0. Best value: 0.344797: 100%|██████████| 1/1 [00:42<00:00, 42.35s/it]

Early stopping, best iteration is:
[2260]	eval's l1: 0.579514
Evaluated only: l1
Best iteration: 2260, Score: 0.5795140658261088
[I 2025-07-19 21:38:03,757] Trial 0 finished with value: 0.34479664699253576 and parameters: {}. Best is trial 0 with value: 0.34479664699253576.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2260 iterations

[I 2025-07-19 21:39:08,550] A new study created in memory with name: no-name-652af8d3-7029-441f-aa70-29a5892ef2d1

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-gbdt-weight-False-target-t+2 entrenado en split 3/3:
0.33455416877468924

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 10.7641

Best trial: 0. Best value: 0.335293: 100%|██████████| 1/1 [00:05<00:00,  5.14s/it]

Early stopping, best iteration is:
[83]	eval's l1: 9.41752
Evaluated only: l1
Best iteration: 83, Score: 9.41751993911632
[I 2025-07-19 21:39:13,692] Trial 0 finished with value: 0.33529277110920086 and parameters: {}. Best is trial 0 with value: 0.33529277110920086.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 83 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2 entrenado en split 3/3:
0.3550121642375934
Scaling

[I 2025-07-19 21:39:16,443] A new study created in memory with name: no-name-6ed00b08-7ae5-4638-bc6d-1fd106704e0f
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.607797
[1000]	eval's l1: 0.607887
[1500]	eval's l1: 0.605612
[2000]	eval's l1: 0.603704
[2500]	eval's l1: 0.597916
[3000]	eval's l1: 0.595075
[3500]	eval's l1: 0.590469
[4000]	eval's l1: 0.588728
[4500]	eval's l1: 0.586022
[5000]	eval's l1: 0.585568
[5500]	eval's l1: 0.584153
[6000]	eval's l1: 0.582967
[6500]	eval's l1: 0.583594
[7000]	eval's l1: 0.582581
[7500]	eval's l1: 0.582531
[8000]	eval's l1: 0.580234
[8500]	eval's l1: 0.580391
[9000]	eval's l1: 0.584384
[9500]	eval's l1: 0.58437

Best trial: 0. Best value: 0.279716: 100%|██████████| 1/1 [03:50<00:00, 230.49s/it]

Best iteration: 8140, Score: 0.5785216601077977
[I 2025-07-19 21:43:06,931] Trial 0 finished with value: 0.27971604266798505 and parameters: {}. Best is trial 0 with value: 0.27971604266798505.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 8140 iterations

[I 2025-07-19 21:48:03,643] A new study created in memory with name: no-name-e1af070c-80a0-4906-b103-fc26a7ad11ce

Modelo LGBM-extra_trees-True-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 3/3:
0.3104818913432673

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 7.92704
[1000]	eval's l1: 7.72351
[1500]	eval's l1: 7.81623
[2000]	eval's l1: 8.33203
[2500]	eval's l1: 8.68375
[3000]	eval's l1: 9.02326
[3500]	eval's l1: 8.91328
[4000]	eval's l1: 9.17794
[4500]	eval's l1: 9.05845
[5000]	eval's l1: 9.40498
[5500]	eval's l1: 9.4133
[6000]	eval's l1: 9.26088
[6500]	eval's l1: 9.45463
[7000]	eval's l1: 9.27331
[7500]	eval's l1: 9.37606
[8000]	eval's l1: 9.31129
[8500]	eval's l1: 9.16679
[9000]	eval's l1: 9.55662
[9500]	eval's l1: 9.51952

Best trial: 0. Best value: 0.958855: 100%|██████████| 1/1 [02:08<00:00, 128.52s/it]

Best iteration: 1193, Score: 7.528048232841172
[I 2025-07-19 21:50:12,160] Trial 0 finished with value: 0.9588545515285396 and parameters: {}. Best is trial 0 with value: 0.9588545515285396.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1193 iterations

Modelo LGBM-extra_trees-True-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 3/3:
0.4245718887650614
Scaling

[I 2025-07-19 21:50:36,721] A new study created in memory with name: no-name-35fb5b00-f3d9-4fc4-8ec9-46f6e1824770
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.594257
[1000]	eval's l1: 0.586691
[1500]	eval's l1: 0.580198
[2000]	eval's l1: 0.586784
[2500]	eval's l1: 0.586215
[3000]	eval's l1: 0.586077
[3500]	eval's l1: 0.586856
[4000]	eval's l1: 0.584852
[4500]	eval's l1: 0.585931
[5000]	eval's l1: 0.58566
[5500]	eval's l1: 0.5858
[6000]	eval's l1: 0.585354
[6500]	eval's l1: 0.584021
[7000]	eval's l1: 0.581444
[7500]	eval's l1: 0.580218
[8000]	eval's l1: 0.579389
[8500]	eval's l1: 0.578487
[9000]	eval's l1: 0.581252
[9500]	eval's l1: 0.582504

Best trial: 0. Best value: 0.50498: 100%|██████████| 1/1 [03:58<00:00, 238.12s/it]

Best iteration: 1519, Score: 0.5769164255930728
[I 2025-07-19 21:54:34,844] Trial 0 finished with value: 0.5049795791261895 and parameters: {}. Best is trial 0 with value: 0.5049795791261895.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1519 iterations

[I 2025-07-19 21:55:42,280] A new study created in memory with name: no-name-660a5c79-ae03-49eb-9551-865a123167b2

Modelo LGBM-extra_trees-False-trials-1-scaling-True-boosting-dart-weight-False-target-t+2 entrenado en split 3/3:
0.3444015275551708

  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 7.5213
[1000]	eval's l1: 7.66003
[1500]	eval's l1: 7.94954
[2000]	eval's l1: 8.54223
[2500]	eval's l1: 8.7937
[3000]	eval's l1: 9.09324
[3500]	eval's l1: 8.98752
[4000]	eval's l1: 9.10495
[4500]	eval's l1: 9.11619
[5000]	eval's l1: 9.5507
[5500]	eval's l1: 9.61999
[6000]	eval's l1: 9.44143
[6500]	eval's l1: 9.7071
[7000]	eval's l1: 9.61918
[7500]	eval's l1: 9.78359
[8000]	eval's l1: 9.71908
[8500]	eval's l1: 9.56524
[9000]	eval's l1: 9.96595
[9500]	eval's l1: 9.88335

Best trial: 0. Best value: 0.961232: 100%|██████████| 1/1 [02:50<00:00, 170.20s/it]

Best iteration: 803, Score: 7.345876860457913
[I 2025-07-19 21:58:32,482] Trial 0 finished with value: 0.9612319732763447 and parameters: {}. Best is trial 0 with value: 0.9612319732763447.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 803 iterations

Modelo LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-t+2 entrenado en split 3/3:
0.4457316167653073

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250720_005852'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       17.00 GB / 31.23 GB (54.4%)
Disk Space Avail:   725.41 GB / 914.78 GB (79.3%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': [],
 'num_val_windows': 2,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 18828 rows, 656 time series. Median time series length is 32 (min=10, max=32).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 21:59:02
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE']
Training timeseries model SeasonalNaive.
	-0.2949       = Validation score (-WQL)
	1.79    s     = Training runtime
	0.45    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2239       = Validation score (-WQL)
	1.43    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2092       = Validation score (-WQL)
	8.90    s     = Training runtime
	0.11    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.3524       = Validation score (-WQL)
	0.40    s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta.
	-0.2087       = Validation score (-WQL)
	1.05    s     = Training runtime
	0.32    s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	Warning: AutoETS/W0 failed for 10 time series (1.5%). Fallback model SeasonalNaive was used for these time series.
	-0.2190       = Validation score (-WQL)
	1.28    s     = Training runtime
	1.17    s     = Validation (prediction) runtime
Training timeseries model ChronosZeroShot[bolt_base].
	-0.2198       = Validation score (-WQL)
	1.61    s     = Training runtime
	1.31    s     = Validation (prediction) runtime
Training timeseries model ChronosFineTuned[bolt_small].
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250720_005852/models/ChronosFineTuned[bolt_small]/W0/fine-tuned-ckpt
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250720_005852/models/ChronosFineTuned[bolt_small]/W1/fine-tuned-ckpt
	-0.2131       = Validation score (-WQL)
	95.70   s     = Training runtime
	0.08    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.1987       = Validation score (-WQL)
	106.82  s     = Training runtime
	0.61    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.1985       = Validation score (-WQL)
	90.62   s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.1904       = Validation score (-WQL)
	66.13   s     = Training runtime
	0.27    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.2001       = Validation score (-WQL)
	176.20  s     = Training runtime
	0.48    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoETS': 0.09, 'DeepAR': 0.14, 'DynamicOptimizedTheta': 0.02, 'PatchTST': 0.39, 'TemporalFusionTransformer': 0.18, 'TiDE': 0.19}
	-0.1851       = Validation score (-WQL)
	1.54    s     = Training runtime
	3.08    s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WeightedEnsemble']
Total runtime: 559.03 s
Best model: WeightedEnsemble
Best model score: -0.1851
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-best_quality entrenado en split 3/3:
0.32437684220687396

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250720_010834'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       15.56 GB / 31.23 GB (49.8%)
Disk Space Avail:   725.01 GB / 914.78 GB (79.3%)
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 18828 rows, 656 time series. Median time series length is 32 (min=10, max=32).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-19 22:08:44
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive.
	-0.2731       = Validation score (-WQL)
	0.06    s     = Training runtime
	1.63    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.3120       = Validation score (-WQL)
	0.06    s     = Training runtime
	0.46    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2367       = Validation score (-WQL)
	0.68    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2151       = Validation score (-WQL)
	3.57    s     = Training runtime
	0.15    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.2386       = Validation score (-WQL)
	0.07    s     = Training runtime
	1.78    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.2246       = Validation score (-WQL)
	0.07    s     = Training runtime
	0.23    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'DirectTabular': 0.56, 'RecursiveTabular': 0.14, 'Theta': 0.3}
	-0.2045       = Validation score (-WQL)
	0.41    s     = Training runtime
	0.44    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 9.35 s
Best model: WeightedEnsemble
Best model score: -0.2045
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Modelo AutoGluon-fast_training entrenado en split 3/3:
0.2807924484712074
Modelo SMA-12 entrenado en split 3/3:
0.251847995358391
VALIDACIÓN 1 MODEL MAX (primer fold con pesos del resto):
                                                       error
prediction_AutoGluon-best_quality                   0.285887
prediction_AutoGluon-fast_training                  0.260927
prediction_LGBM-extra_trees-False-trials-1-scal...  0.290678
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253521
prediction_LGBM-extra_trees-False-trials-1-scal...  0.290678
prediction_LGBM-extra_trees-False-trials-1-scal...  0.255729
prediction_LGBM-extra_trees-False-trials-1-scal...  0.297885
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253691
prediction_LGBM-extra_trees-False-trials-1-scal...  0.297885
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253691
prediction_LGBM-extra_trees-False-trials-1-scal...  0.261849
prediction_LGBM-extra_trees-False-trials-1-scal...  0.243467
prediction_LGBM-extra_trees-False-trials-1-scal...  0.247850
prediction_LGBM-extra_trees-False-trials-1-scal...  0.241476
prediction_LGBM-extra_trees-False-trials-1-scal...  0.272086
prediction_LGBM-extra_trees-False-trials-1-scal...  0.244256
prediction_LGBM-extra_trees-False-trials-1-scal...  0.255806
prediction_LGBM-extra_trees-False-trials-1-scal...  0.250193
prediction_LGBM-extra_trees-True-trials-1-scali...  0.265947
prediction_LGBM-extra_trees-True-trials-1-scali...  0.251908
prediction_LGBM-extra_trees-True-trials-1-scali...  0.265947
prediction_LGBM-extra_trees-True-trials-1-scali...  0.254325
prediction_LGBM-extra_trees-True-trials-1-scali...  0.266579
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243451
prediction_LGBM-extra_trees-True-trials-1-scali...  0.266579
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243451
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243685
prediction_LGBM-extra_trees-True-trials-1-scali...  0.228864
prediction_LGBM-extra_trees-True-trials-1-scali...  0.244108
prediction_LGBM-extra_trees-True-trials-1-scali...  0.242675
prediction_LGBM-extra_trees-True-trials-1-scali...  0.252278
prediction_LGBM-extra_trees-True-trials-1-scali...  0.232022
prediction_LGBM-extra_trees-True-trials-1-scali...  0.242973
prediction_LGBM-extra_trees-True-trials-1-scali...  0.244939
prediction_LinearRegression-all-['lags']-all        0.271193
prediction_LinearRegression-magicos-['lags']-FOODS  0.249859
prediction_LinearRegression-magicos-['lags']-HC     0.393891
prediction_LinearRegression-magicos-['lags']-PC     0.244255
prediction_LinearRegression-magicos-['lags']-all    0.327149
prediction_SMA-12                                   0.292221
prediction_ensamble                                 0.256026
VALIDACIÓN 2 MODEL MAX (primer fold con pesos del resto):
                                                       error
prediction_AutoGluon-best_quality                   0.285887
prediction_AutoGluon-fast_training                  0.260927
prediction_LGBM-extra_trees-False-trials-1-scal...  0.290678
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253521
prediction_LGBM-extra_trees-False-trials-1-scal...  0.290678
prediction_LGBM-extra_trees-False-trials-1-scal...  0.255729
prediction_LGBM-extra_trees-False-trials-1-scal...  0.297885
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253691
prediction_LGBM-extra_trees-False-trials-1-scal...  0.297885
prediction_LGBM-extra_trees-False-trials-1-scal...  0.253691
prediction_LGBM-extra_trees-False-trials-1-scal...  0.261849
prediction_LGBM-extra_trees-False-trials-1-scal...  0.243467
prediction_LGBM-extra_trees-False-trials-1-scal...  0.247850
prediction_LGBM-extra_trees-False-trials-1-scal...  0.241476
prediction_LGBM-extra_trees-False-trials-1-scal...  0.272086
prediction_LGBM-extra_trees-False-trials-1-scal...  0.244256
prediction_LGBM-extra_trees-False-trials-1-scal...  0.255806
prediction_LGBM-extra_trees-False-trials-1-scal...  0.250193
prediction_LGBM-extra_trees-True-trials-1-scali...  0.265947
prediction_LGBM-extra_trees-True-trials-1-scali...  0.251908
prediction_LGBM-extra_trees-True-trials-1-scali...  0.265947
prediction_LGBM-extra_trees-True-trials-1-scali...  0.254325
prediction_LGBM-extra_trees-True-trials-1-scali...  0.266579
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243451
prediction_LGBM-extra_trees-True-trials-1-scali...  0.266579
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243451
prediction_LGBM-extra_trees-True-trials-1-scali...  0.243685
prediction_LGBM-extra_trees-True-trials-1-scali...  0.228864
prediction_LGBM-extra_trees-True-trials-1-scali...  0.244108
prediction_LGBM-extra_trees-True-trials-1-scali...  0.242675
prediction_LGBM-extra_trees-True-trials-1-scali...  0.252278
prediction_LGBM-extra_trees-True-trials-1-scali...  0.232022
prediction_LGBM-extra_trees-True-trials-1-scali...  0.242973
prediction_LGBM-extra_trees-True-trials-1-scali...  0.244939
prediction_LinearRegression-all-['lags']-all        0.271193
prediction_LinearRegression-magicos-['lags']-FOODS  0.249859
prediction_LinearRegression-magicos-['lags']-HC     0.393891
prediction_LinearRegression-magicos-['lags']-PC     0.244255
prediction_LinearRegression-magicos-['lags']-all    0.327149
prediction_SMA-12                                   0.292221
prediction_ensamble                                 0.253621
                                                       error
prediction_AutoGluon-best_quality                   0.158927
prediction_AutoGluon-fast_training                  0.147683
prediction_LGBM-extra_trees-False-trials-1-scal...  0.145159
prediction_LGBM-extra_trees-False-trials-1-scal...  0.248488
prediction_LGBM-extra_trees-False-trials-1-scal...  0.144192
prediction_LGBM-extra_trees-False-trials-1-scal...  0.242862
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165309
prediction_LGBM-extra_trees-False-trials-1-scal...  0.190753
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165708
prediction_LGBM-extra_trees-False-trials-1-scal...  0.216800
prediction_LGBM-extra_trees-False-trials-1-scal...  0.160666
prediction_LGBM-extra_trees-False-trials-1-scal...  0.176299
prediction_LGBM-extra_trees-False-trials-1-scal...  0.166843
prediction_LGBM-extra_trees-False-trials-1-scal...  0.200758
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.258172
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.260901
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164890
prediction_LGBM-extra_trees-True-trials-1-scali...  0.189450
prediction_LGBM-extra_trees-True-trials-1-scali...  0.166197
prediction_LGBM-extra_trees-True-trials-1-scali...  0.217226
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164060
prediction_LGBM-extra_trees-True-trials-1-scali...  0.173025
prediction_LGBM-extra_trees-True-trials-1-scali...  0.172950
prediction_LGBM-extra_trees-True-trials-1-scali...  0.199721
prediction_LinearRegression-all-['lags']-all        0.192178
prediction_LinearRegression-magicos-['lags']-FOODS  0.184474
prediction_LinearRegression-magicos-['lags']-HC     0.194353
prediction_LinearRegression-magicos-['lags']-PC     0.199981
prediction_LinearRegression-magicos-['lags']-all    0.240638
prediction_SMA-12                                   0.175209
prediction_ensamble                                 0.117894
                                                       error
prediction_AutoGluon-best_quality                   0.158927
prediction_AutoGluon-fast_training                  0.147683
prediction_LGBM-extra_trees-False-trials-1-scal...  0.145159
prediction_LGBM-extra_trees-False-trials-1-scal...  0.248488
prediction_LGBM-extra_trees-False-trials-1-scal...  0.144192
prediction_LGBM-extra_trees-False-trials-1-scal...  0.242862
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165309
prediction_LGBM-extra_trees-False-trials-1-scal...  0.190753
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165708
prediction_LGBM-extra_trees-False-trials-1-scal...  0.216800
prediction_LGBM-extra_trees-False-trials-1-scal...  0.160666
prediction_LGBM-extra_trees-False-trials-1-scal...  0.176299
prediction_LGBM-extra_trees-False-trials-1-scal...  0.166843
prediction_LGBM-extra_trees-False-trials-1-scal...  0.200758
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.258172
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.260901
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164890
prediction_LGBM-extra_trees-True-trials-1-scali...  0.189450
prediction_LGBM-extra_trees-True-trials-1-scali...  0.166197
prediction_LGBM-extra_trees-True-trials-1-scali...  0.217226
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164060
prediction_LGBM-extra_trees-True-trials-1-scali...  0.173025
prediction_LGBM-extra_trees-True-trials-1-scali...  0.172950
prediction_LGBM-extra_trees-True-trials-1-scali...  0.199721
prediction_LinearRegression-all-['lags']-all        0.192178
prediction_LinearRegression-magicos-['lags']-FOODS  0.184474
prediction_LinearRegression-magicos-['lags']-HC     0.194353
prediction_LinearRegression-magicos-['lags']-PC     0.199981
prediction_LinearRegression-magicos-['lags']-all    0.240638
prediction_SMA-12                                   0.175209
prediction_ensamble                                 0.114003

In [19]:
trainer.model_weights[1]

                                                      weights
product_id
20001.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
20002.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
20003.0     {'prediction_AutoGluon-best_quality': 0.333333...
20004.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
20005.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
...                                                       ...
21252.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
21265.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
21266.0     {'prediction_AutoGluon-best_quality': 0.333333...
21267.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...
21276.0     {'prediction_AutoGluon-best_quality': 0.0, 'pr...

[780 rows x 1 columns]

In [20]:
trainer._compute_metrics(trainer.train_results)

                                                       error
prediction_AutoGluon-best_quality                   0.158927
prediction_AutoGluon-fast_training                  0.147683
prediction_LGBM-extra_trees-False-trials-1-scal...  0.145159
prediction_LGBM-extra_trees-False-trials-1-scal...  0.248488
prediction_LGBM-extra_trees-False-trials-1-scal...  0.144192
prediction_LGBM-extra_trees-False-trials-1-scal...  0.242862
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.153596
prediction_LGBM-extra_trees-False-trials-1-scal...  0.203961
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165309
prediction_LGBM-extra_trees-False-trials-1-scal...  0.190753
prediction_LGBM-extra_trees-False-trials-1-scal...  0.165708
prediction_LGBM-extra_trees-False-trials-1-scal...  0.216800
prediction_LGBM-extra_trees-False-trials-1-scal...  0.160666
prediction_LGBM-extra_trees-False-trials-1-scal...  0.176299
prediction_LGBM-extra_trees-False-trials-1-scal...  0.166843
prediction_LGBM-extra_trees-False-trials-1-scal...  0.200758
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.258172
prediction_LGBM-extra_trees-True-trials-1-scali...  0.155153
prediction_LGBM-extra_trees-True-trials-1-scali...  0.260901
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.168886
prediction_LGBM-extra_trees-True-trials-1-scali...  0.210205
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164890
prediction_LGBM-extra_trees-True-trials-1-scali...  0.189450
prediction_LGBM-extra_trees-True-trials-1-scali...  0.166197
prediction_LGBM-extra_trees-True-trials-1-scali...  0.217226
prediction_LGBM-extra_trees-True-trials-1-scali...  0.164060
prediction_LGBM-extra_trees-True-trials-1-scali...  0.173025
prediction_LGBM-extra_trees-True-trials-1-scali...  0.172950
prediction_LGBM-extra_trees-True-trials-1-scali...  0.199721
prediction_LinearRegression-all-['lags']-all        0.192178
prediction_LinearRegression-magicos-['lags']-FOODS  0.184474
prediction_LinearRegression-magicos-['lags']-HC     0.194353
prediction_LinearRegression-magicos-['lags']-PC     0.199981
prediction_LinearRegression-magicos-['lags']-all    0.240638
prediction_SMA-12                                   0.175209
prediction_ensamble                                 0.117894

In [21]:

models_used = [model.name for model in trainer.models]
models_used = " ".join(models_used)
# hago un hash en base de models_used para el nombre del archivo
import hashlib
hash_object = hashlib.md5(models_used.encode())
hash_hex = hash_object.hexdigest()

trainer.train_results.to_csv(f"train_results_{hash_hex}.csv", index=False)

In [22]:
trainer.agg_df

,target,prediction_AutoGluon-best_quality,prediction_AutoGluon-fast_training,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-t+2,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-t+2,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-True-target-delta,...,prediction_LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-delta,prediction_LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2,prediction_LinearRegression-all-['lags']-all,prediction_LinearRegression-magicos-['lags']-FOODS,prediction_LinearRegression-magicos-['lags']-HC,prediction_LinearRegression-magicos-['lags']-PC,prediction_LinearRegression-magicos-['lags']-all,prediction_SMA-12,weights,prediction_ensamble
product_id,,,,,,,,,,,,,,,,,,,,,
20001.0,4463.566406,4192.395459,4372.735319,4422.990425,3378.876181,4396.318820,3405.254866,4323.707452,3221.895933,4323.707452,...,4171.962970,4103.809705,4702.397339,4043.273878,4340.302307,4043.273878,4933.541870,4567.446299,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",4284.419268
20002.0,4490.422363,3117.013740,3132.103425,3775.911540,3068.031680,3758.201114,3075.186824,3670.705772,3133.139903,3670.705772,...,3168.781488,3182.906228,4227.423950,3314.785060,4087.703308,3314.785060,4550.385742,3481.152552,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",4008.257663
20003.0,2922.161682,2693.429281,2570.598216,2212.192339,2043.189654,2239.980674,2016.316762,2096.693808,2130.119467,2096.693808,...,2375.259509,2316.656912,3170.063721,2680.570129,2366.516722,2366.516722,3459.910645,2422.960470,{'prediction_AutoGluon-best_quality': 0.333333...,2790.503471
20004.0,2426.538391,1933.518164,2141.002004,1758.915773,1470.870708,1780.698198,1480.297685,1721.726093,1587.317701,1721.726093,...,1833.624492,1766.360850,1775.895447,1797.609314,1762.877578,1762.877578,2037.894104,1859.216726,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",1992.168474
20005.0,2196.938965,1812.241342,1992.391091,1874.755538,1276.263161,1870.320513,1280.920390,1727.971250,1369.488550,1727.971250,...,1790.897510,1602.736698,1653.824432,1472.110077,1654.632991,1654.632991,2059.518066,1888.259326,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",1692.873893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21263.0,0.060690,0.163030,0.058352,0.604628,0.058426,0.579401,0.053004,0.284404,0.754035,0.284404,...,0.061787,0.115338,0.150209,0.180201,0.180201,0.238204,0.150209,0.285505,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.285586
21265.0,0.225280,0.325172,0.325172,0.372250,0.176697,0.399770,0.156400,0.537846,0.846566,0.537846,...,0.194472,0.190116,0.325172,0.325172,0.325172,0.325172,0.325172,0.301994,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.218462
21266.0,0.236650,0.336069,0.336069,0.383420,0.173076,0.407427,0.155701,0.381304,0.843787,0.381304,...,0.223481,0.188721,0.336069,0.336069,0.336069,0.336069,0.336069,0.318535,{'prediction_AutoGluon-best_quality': 0.333333...,0.264897
21267.0,0.152970,0.419577,0.419577,0.743717,0.191970,0.803147,0.170935,1.350264,0.840867,1.350264,...,0.191202,0.139648,0.419577,0.419577,0.419577,0.419577,0.419577,0.345966,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.154671
21276.0,0.063120,0.373987,0.373987,0.857237,0.165135,0.914499,0.143502,1.510725,0.809004,1.510725,...,0.051533,0.054064,0.373987,0.373987,0.373987,0.373987,0.373987,0.169556,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.047513

In [23]:
final_df = trainer.final_pred(df, 35)

Registros de entrenamiento: 33
Registros de entrenamiento: 20
Registros de entrenamiento: 5
Registros de entrenamiento: 8
Registros de entrenamiento: 791
Scaling

[I 2025-07-19 22:09:10,228] A new study created in memory with name: no-name-bf9737ba-59b4-4459-8cee-765b4b956f62
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.631529
[1000]	eval's l1: 0.619581
[1500]	eval's l1: 0.615812
[2000]	eval's l1: 0.611223
[2500]	eval's l1: 0.611427
[3000]	eval's l1: 0.609331
[3500]	eval's l1: 0.608662
[4000]	eval's l1: 0.607108
[4500]	eval's l1: 0.607433

Best trial: 0. Best value: 0.273904: 100%|██████████| 1/1 [01:52<00:00, 112.34s/it]

Early stopping, best iteration is:
[4091]	eval's l1: 0.606633
Evaluated only: l1
Best iteration: 4091, Score: 0.6066331333290785
[I 2025-07-19 22:11:02,571] Trial 0 finished with value: 0.27390361560799503 and parameters: {}. Best is trial 0 with value: 0.27390361560799503.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4091 iterations

[I 2025-07-19 22:13:07,198] A new study created in memory with name: no-name-683ff972-8eb8-460a-a539-eb6e44c732ae
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 8.30766

Best trial: 0. Best value: 0.292027: 100%|██████████| 1/1 [00:05<00:00,  5.81s/it]

Early stopping, best iteration is:
[441]	eval's l1: 8.28679
Evaluated only: l1
Best iteration: 441, Score: 8.286788551208184
[I 2025-07-19 22:13:13,009] Trial 0 finished with value: 0.2920268131253573 and parameters: {}. Best is trial 0 with value: 0.2920268131253573.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 441 iterations

Scaling

[I 2025-07-19 22:13:17,777] A new study created in memory with name: no-name-2edc5cc8-7d95-427a-b9d1-669e2e84b4e4
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.651231
[1000]	eval's l1: 0.63111
[1500]	eval's l1: 0.628283
[2000]	eval's l1: 0.625479
[2500]	eval's l1: 0.631083

Best trial: 0. Best value: 0.27741: 100%|██████████| 1/1 [00:39<00:00, 39.74s/it]

Early stopping, best iteration is:
[1999]	eval's l1: 0.625407
Evaluated only: l1
Best iteration: 1999, Score: 0.6254068844637569
[I 2025-07-19 22:13:57,511] Trial 0 finished with value: 0.27741045934872394 and parameters: {}. Best is trial 0 with value: 0.27741045934872394.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1999 iterations

[I 2025-07-19 22:14:59,391] A new study created in memory with name: no-name-d65f9553-3721-487a-b57c-93b395bf3ef7
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 8.42305

Best trial: 0. Best value: 0.294557: 100%|██████████| 1/1 [00:04<00:00,  4.75s/it]

Early stopping, best iteration is:
[194]	eval's l1: 8.35858
Evaluated only: l1
Best iteration: 194, Score: 8.358578312003822
[I 2025-07-19 22:15:04,145] Trial 0 finished with value: 0.294556687628304 and parameters: {}. Best is trial 0 with value: 0.294556687628304.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 194 iterations

Scaling

[I 2025-07-19 22:15:07,810] A new study created in memory with name: no-name-f105ec83-a996-4372-ba8b-fcb7b8118a29
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.681471
[1000]	eval's l1: 0.657088
[1500]	eval's l1: 0.644959
[2000]	eval's l1: 0.636776
[2500]	eval's l1: 0.630558
[3000]	eval's l1: 0.627039
[3500]	eval's l1: 0.630119
[4000]	eval's l1: 0.628226
[4500]	eval's l1: 0.628043
[5000]	eval's l1: 0.622507
[5500]	eval's l1: 0.619301
[6000]	eval's l1: 0.619845
[6500]	eval's l1: 0.618579
[7000]	eval's l1: 0.618536
[7500]	eval's l1: 0.618698
[8000]	eval's l1: 0.618401
[8500]	eval's l1: 0.617716
[9000]	eval's l1: 0.617734
[9500]	eval's l1: 0.616513

Best trial: 0. Best value: 0.274887: 100%|██████████| 1/1 [03:48<00:00, 229.00s/it]

Best iteration: 9999, Score: 0.6143460549803438
[I 2025-07-19 22:18:56,806] Trial 0 finished with value: 0.2748866923766647 and parameters: {}. Best is trial 0 with value: 0.2748866923766647.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9999 iterations

[I 2025-07-19 22:24:42,780] A new study created in memory with name: no-name-d2f21b68-aeb8-4854-a476-e535a5a24429
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.64048
[1000]	eval's l1: 8.65406
[1500]	eval's l1: 8.45743
[2000]	eval's l1: 8.29078
[2500]	eval's l1: 8.29471
[3000]	eval's l1: 8.24806
[3500]	eval's l1: 8.34642
[4000]	eval's l1: 8.2653
[4500]	eval's l1: 8.24434
[5000]	eval's l1: 8.26237
[5500]	eval's l1: 8.30761
[6000]	eval's l1: 8.30197
[6500]	eval's l1: 8.26716
[7000]	eval's l1: 8.24705
[7500]	eval's l1: 8.26325
[8000]	eval's l1: 8.23398
[8500]	eval's l1: 8.29208
[9000]	eval's l1: 8.32835
[9500]	eval's l1: 8.32844

Best trial: 0. Best value: 0.364672: 100%|██████████| 1/1 [01:54<00:00, 114.12s/it]

Best iteration: 4758, Score: 8.204953366553141
[I 2025-07-19 22:26:36,894] Trial 0 finished with value: 0.36467184444028083 and parameters: {}. Best is trial 0 with value: 0.36467184444028083.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4758 iterations

Scaling

[I 2025-07-19 22:27:50,264] A new study created in memory with name: no-name-5b00c77f-51a5-45dc-ac9c-e0ec0a6e001c
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.669345
[1000]	eval's l1: 0.654728
[1500]	eval's l1: 0.647094
[2000]	eval's l1: 0.635381
[2500]	eval's l1: 0.626451
[3000]	eval's l1: 0.622661
[3500]	eval's l1: 0.62069
[4000]	eval's l1: 0.618237
[4500]	eval's l1: 0.618507
[5000]	eval's l1: 0.616239
[5500]	eval's l1: 0.614055
[6000]	eval's l1: 0.615025
[6500]	eval's l1: 0.614483
[7000]	eval's l1: 0.614729
[7500]	eval's l1: 0.612792
[8000]	eval's l1: 0.611093
[8500]	eval's l1: 0.612122
[9000]	eval's l1: 0.612593
[9500]	eval's l1: 0.609596

Best trial: 0. Best value: 0.277975: 100%|██████████| 1/1 [03:58<00:00, 238.07s/it]

Best iteration: 9489, Score: 0.6094552434873824
[I 2025-07-19 22:31:48,334] Trial 0 finished with value: 0.27797499040619006 and parameters: {}. Best is trial 0 with value: 0.27797499040619006.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9489 iterations

[I 2025-07-19 22:38:11,604] A new study created in memory with name: no-name-8eed645d-4e44-41d8-a0d3-98ad2269b7da
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.68558
[1000]	eval's l1: 8.66597
[1500]	eval's l1: 8.70651
[2000]	eval's l1: 8.61839
[2500]	eval's l1: 8.60373
[3000]	eval's l1: 8.60405
[3500]	eval's l1: 8.67726
[4000]	eval's l1: 8.72429
[4500]	eval's l1: 8.73543
[5000]	eval's l1: 8.7726
[5500]	eval's l1: 8.82805
[6000]	eval's l1: 8.85895
[6500]	eval's l1: 8.86832
[7000]	eval's l1: 8.83823
[7500]	eval's l1: 8.85302
[8000]	eval's l1: 8.85432
[8500]	eval's l1: 8.84984
[9000]	eval's l1: 8.8561
[9500]	eval's l1: 8.87529

Best trial: 0. Best value: 0.449704: 100%|██████████| 1/1 [02:42<00:00, 162.25s/it]

Best iteration: 2231, Score: 8.557613986033672
[I 2025-07-19 22:40:53,851] Trial 0 finished with value: 0.4497041970459353 and parameters: {}. Best is trial 0 with value: 0.4497041970459353.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2231 iterations

Scaling

[I 2025-07-19 22:41:41,629] A new study created in memory with name: no-name-db28c37a-47cd-4cf5-90ec-4ef2d0ddd184
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.651895
[1000]	eval's l1: 0.645421
[1500]	eval's l1: 0.640368
[2000]	eval's l1: 0.639306

Best trial: 0. Best value: 0.282917: 100%|██████████| 1/1 [00:30<00:00, 30.68s/it]

Early stopping, best iteration is:
[1960]	eval's l1: 0.638619
Evaluated only: l1
Best iteration: 1960, Score: 0.6386186116225606
[I 2025-07-19 22:42:12,312] Trial 0 finished with value: 0.28291717922175086 and parameters: {}. Best is trial 0 with value: 0.28291717922175086.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 1960 iterations

[I 2025-07-19 22:42:59,366] A new study created in memory with name: no-name-81c8a7e8-8065-4b19-9f6e-7cf46d57300f
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 8.30766

Best trial: 0. Best value: 0.292027: 100%|██████████| 1/1 [00:04<00:00,  4.75s/it]

Early stopping, best iteration is:
[441]	eval's l1: 8.28679
Evaluated only: l1
Best iteration: 441, Score: 8.286788551208183
[I 2025-07-19 22:43:04,115] Trial 0 finished with value: 0.2920268131253573 and parameters: {}. Best is trial 0 with value: 0.2920268131253573.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 441 iterations

Scaling

[I 2025-07-19 22:43:09,256] A new study created in memory with name: no-name-3fd4bc20-844c-40ba-8938-d8f3c8d4e0c0
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.660477
[1000]	eval's l1: 0.655175
[1500]	eval's l1: 0.648467
[2000]	eval's l1: 0.643961
[2500]	eval's l1: 0.644322

Best trial: 0. Best value: 0.302541: 100%|██████████| 1/1 [00:35<00:00, 35.82s/it]

Early stopping, best iteration is:
[2087]	eval's l1: 0.643132
Evaluated only: l1
Best iteration: 2087, Score: 0.6431316632499514
[I 2025-07-19 22:43:45,076] Trial 0 finished with value: 0.3025408339693795 and parameters: {}. Best is trial 0 with value: 0.3025408339693795.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2087 iterations

[I 2025-07-19 22:44:40,336] A new study created in memory with name: no-name-cfa3fb78-dd26-440e-9db4-6189c258f544
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 8.42305

Best trial: 0. Best value: 0.294557: 100%|██████████| 1/1 [00:04<00:00,  4.40s/it]

Early stopping, best iteration is:
[194]	eval's l1: 8.35858
Evaluated only: l1
Best iteration: 194, Score: 8.358578312003822
[I 2025-07-19 22:44:44,732] Trial 0 finished with value: 0.294556687628304 and parameters: {}. Best is trial 0 with value: 0.294556687628304.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 194 iterations

Scaling

[I 2025-07-19 22:44:48,374] A new study created in memory with name: no-name-863e0848-675e-4999-b2a3-b18464e78a5c
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.669834
[1000]	eval's l1: 0.657549
[1500]	eval's l1: 0.652012
[2000]	eval's l1: 0.645061
[2500]	eval's l1: 0.64004
[3000]	eval's l1: 0.637245
[3500]	eval's l1: 0.636661
[4000]	eval's l1: 0.634663
[4500]	eval's l1: 0.62669
[5000]	eval's l1: 0.62678
[5500]	eval's l1: 0.625907
[6000]	eval's l1: 0.627272
[6500]	eval's l1: 0.623583
[7000]	eval's l1: 0.620448
[7500]	eval's l1: 0.617033
[8000]	eval's l1: 0.613171
[8500]	eval's l1: 0.61416
[9000]	eval's l1: 0.612897
[9500]	eval's l1: 0.610404

Best trial: 0. Best value: 0.274288: 100%|██████████| 1/1 [03:30<00:00, 210.36s/it]

Best iteration: 9915, Score: 0.6067225723183802
[I 2025-07-19 22:48:18,735] Trial 0 finished with value: 0.27428799995264774 and parameters: {}. Best is trial 0 with value: 0.27428799995264774.

Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9915 iterations

[I 2025-07-19 22:55:12,924] A new study created in memory with name: no-name-0c4891b9-818e-4c2d-9465-0b68af827ada
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.64048
[1000]	eval's l1: 8.65406
[1500]	eval's l1: 8.45743
[2000]	eval's l1: 8.29078
[2500]	eval's l1: 8.29471
[3000]	eval's l1: 8.24806
[3500]	eval's l1: 8.34642
[4000]	eval's l1: 8.2653
[4500]	eval's l1: 8.24434
[5000]	eval's l1: 8.26237
[5500]	eval's l1: 8.30761
[6000]	eval's l1: 8.30197
[6500]	eval's l1: 8.26716
[7000]	eval's l1: 8.24705
[7500]	eval's l1: 8.26325
[8000]	eval's l1: 8.23398
[8500]	eval's l1: 8.29208
[9000]	eval's l1: 8.32835
[9500]	eval's l1: 8.32844

Best trial: 0. Best value: 0.364672: 100%|██████████| 1/1 [02:01<00:00, 121.79s/it]

Best iteration: 4758, Score: 8.204953366553132
[I 2025-07-19 22:57:14,713] Trial 0 finished with value: 0.3646718444402803 and parameters: {}. Best is trial 0 with value: 0.3646718444402803.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 4758 iterations

Scaling

[I 2025-07-19 22:58:45,850] A new study created in memory with name: no-name-ad73a6a7-ecd5-4fef-9c57-27ba145cff15
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.687872
[1000]	eval's l1: 0.66081
[1500]	eval's l1: 0.638341
[2000]	eval's l1: 0.626093
[2500]	eval's l1: 0.622143
[3000]	eval's l1: 0.618512
[3500]	eval's l1: 0.614056
[4000]	eval's l1: 0.608105
[4500]	eval's l1: 0.606342
[5000]	eval's l1: 0.604774
[5500]	eval's l1: 0.603467
[6000]	eval's l1: 0.604694
[6500]	eval's l1: 0.603537
[7000]	eval's l1: 0.604515
[7500]	eval's l1: 0.606208
[8000]	eval's l1: 0.60542
[8500]	eval's l1: 0.606388
[9000]	eval's l1: 0.606923
[9500]	eval's l1: 0.606246

Best trial: 0. Best value: 0.31797: 100%|██████████| 1/1 [03:32<00:00, 212.31s/it]

Best iteration: 6731, Score: 0.602415084814036
[I 2025-07-19 23:02:18,162] Trial 0 finished with value: 0.31796950948427355 and parameters: {}. Best is trial 0 with value: 0.31796950948427355.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6731 iterations

[I 2025-07-19 23:06:12,263] A new study created in memory with name: no-name-91ff7014-7bff-450f-9724-6771c4512e5d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 8.68558
[1000]	eval's l1: 8.66597
[1500]	eval's l1: 8.70651
[2000]	eval's l1: 8.61839
[2500]	eval's l1: 8.60373
[3000]	eval's l1: 8.60405
[3500]	eval's l1: 8.67726
[4000]	eval's l1: 8.72429
[4500]	eval's l1: 8.73543
[5000]	eval's l1: 8.7726
[5500]	eval's l1: 8.82805
[6000]	eval's l1: 8.85895
[6500]	eval's l1: 8.86832
[7000]	eval's l1: 8.83823
[7500]	eval's l1: 8.85302
[8000]	eval's l1: 8.85432
[8500]	eval's l1: 8.84984
[9000]	eval's l1: 8.8561
[9500]	eval's l1: 8.87529

Best trial: 0. Best value: 0.449704: 100%|██████████| 1/1 [02:26<00:00, 146.41s/it]

Best iteration: 2231, Score: 8.557613986033672
[I 2025-07-19 23:08:38,672] Trial 0 finished with value: 0.4497041970459353 and parameters: {}. Best is trial 0 with value: 0.4497041970459353.
Training LGBM with parameters: {'objective': 'regression', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2231 iterations

Scaling

[I 2025-07-19 23:09:19,741] A new study created in memory with name: no-name-68a57c98-7d69-4d13-8ba1-964539cd126f
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.637383
[1000]	eval's l1: 0.62027
[1500]	eval's l1: 0.610267
[2000]	eval's l1: 0.602322
[2500]	eval's l1: 0.596585
[3000]	eval's l1: 0.593603
[3500]	eval's l1: 0.589185
[4000]	eval's l1: 0.587946
[4500]	eval's l1: 0.584509
[5000]	eval's l1: 0.583005
[5500]	eval's l1: 0.580871
[6000]	eval's l1: 0.578697
[6500]	eval's l1: 0.577821
[7000]	eval's l1: 0.57667
[7500]	eval's l1: 0.57742
Early stopping, best iteration is:
[7188]	eval's l1: 0.576034
Evaluated only: l1
Best iteration: 7188, Score: 0.576034346760027

Best trial: 0. Best value: 0.252398: 100%|██████████| 1/1 [01:13<00:00, 73.52s/it]

[I 2025-07-19 23:10:33,264] Trial 0 finished with value: 0.25239756204675867 and parameters: {}. Best is trial 0 with value: 0.25239756204675867.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 7188 iterations

[I 2025-07-19 23:12:42,714] A new study created in memory with name: no-name-0bfa3335-5aae-4cf5-af0f-87fe53f7c2a9
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 7.43474
[1000]	eval's l1: 7.2847

Best trial: 0. Best value: 0.256467: 100%|██████████| 1/1 [00:08<00:00,  8.44s/it]

[1500]	eval's l1: 7.34178
Early stopping, best iteration is:
[996]	eval's l1: 7.27772
Evaluated only: l1
Best iteration: 996, Score: 7.277716610301728
[I 2025-07-19 23:12:51,154] Trial 0 finished with value: 0.25646707116702894 and parameters: {}. Best is trial 0 with value: 0.25646707116702894.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 996 iterations
Scaling

[I 2025-07-19 23:13:01,825] A new study created in memory with name: no-name-d7028fc1-bf4c-48ea-913c-e8ee356f9394
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.640143
[1000]	eval's l1: 0.620582
[1500]	eval's l1: 0.610703
[2000]	eval's l1: 0.607725
[2500]	eval's l1: 0.605711
[3000]	eval's l1: 0.600541
[3500]	eval's l1: 0.596475
[4000]	eval's l1: 0.590351
[4500]	eval's l1: 0.587056
[5000]	eval's l1: 0.585982
[5500]	eval's l1: 0.583107
[6000]	eval's l1: 0.582751

Best trial: 0. Best value: 0.254346: 100%|██████████| 1/1 [01:09<00:00, 69.95s/it]

Early stopping, best iteration is:
[5600]	eval's l1: 0.582173
Evaluated only: l1
Best iteration: 5600, Score: 0.5821734604637653
[I 2025-07-19 23:14:11,777] Trial 0 finished with value: 0.25434649890492517 and parameters: {}. Best is trial 0 with value: 0.25434649890492517.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 5600 iterations

[I 2025-07-19 23:16:12,457] A new study created in memory with name: no-name-b231c40a-d6e9-4dc8-9573-b7a99692ac52
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 7.50413
[1000]	eval's l1: 7.37526

Best trial: 0. Best value: 0.258761: 100%|██████████| 1/1 [00:08<00:00,  8.13s/it]

Early stopping, best iteration is:
[731]	eval's l1: 7.34282
Evaluated only: l1
Best iteration: 731, Score: 7.342816349146977
[I 2025-07-19 23:16:20,584] Trial 0 finished with value: 0.2587611889857616 and parameters: {}. Best is trial 0 with value: 0.2587611889857616.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 731 iterations

Scaling

[I 2025-07-19 23:16:30,322] A new study created in memory with name: no-name-dafa43d3-7bc9-46bd-b80c-caff5fd8cf88
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.645499
[1000]	eval's l1: 0.637759
[1500]	eval's l1: 0.634413
[2000]	eval's l1: 0.629576
[2500]	eval's l1: 0.624394
[3000]	eval's l1: 0.619477
[3500]	eval's l1: 0.610753
[4000]	eval's l1: 0.60903
[4500]	eval's l1: 0.605733
[5000]	eval's l1: 0.60476
[5500]	eval's l1: 0.602757
[6000]	eval's l1: 0.599504
[6500]	eval's l1: 0.597756
[7000]	eval's l1: 0.595158
[7500]	eval's l1: 0.59443
[8000]	eval's l1: 0.591182
[8500]	eval's l1: 0.589922
[9000]	eval's l1: 0.591527
[9500]	eval's l1: 0.590318

Best trial: 0. Best value: 0.255129: 100%|██████████| 1/1 [03:55<00:00, 235.52s/it]

Best iteration: 9982, Score: 0.5884047658359186
[I 2025-07-19 23:20:25,837] Trial 0 finished with value: 0.25512887891380526 and parameters: {}. Best is trial 0 with value: 0.25512887891380526.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9982 iterations

[I 2025-07-19 23:26:26,161] A new study created in memory with name: no-name-7b30f5d8-6535-4276-a6f9-a0a4be013c0a
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.0169
[1000]	eval's l1: 8.17479
[1500]	eval's l1: 7.97392
[2000]	eval's l1: 7.56905
[2500]	eval's l1: 7.48094
[3000]	eval's l1: 7.35684
[3500]	eval's l1: 7.38941
[4000]	eval's l1: 7.38727
[4500]	eval's l1: 7.39792
[5000]	eval's l1: 7.41325
[5500]	eval's l1: 7.4368
[6000]	eval's l1: 7.43514
[6500]	eval's l1: 7.4343
[7000]	eval's l1: 7.46488
[7500]	eval's l1: 7.47947
[8000]	eval's l1: 7.48446
[8500]	eval's l1: 7.46442
[9000]	eval's l1: 7.47624
[9500]	eval's l1: 7.49065

Best trial: 0. Best value: 0.951269: 100%|██████████| 1/1 [02:14<00:00, 134.04s/it]

Best iteration: 2974, Score: 7.339811325549654
[I 2025-07-19 23:28:40,204] Trial 0 finished with value: 0.9512686774426078 and parameters: {}. Best is trial 0 with value: 0.9512686774426078.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2974 iterations

Scaling

[I 2025-07-19 23:29:45,881] A new study created in memory with name: no-name-8fc2c019-124e-472d-aeac-ef749de1eb7e
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.640358
[1000]	eval's l1: 0.632572
[1500]	eval's l1: 0.627438
[2000]	eval's l1: 0.620132
[2500]	eval's l1: 0.61276
[3000]	eval's l1: 0.608288
[3500]	eval's l1: 0.603454
[4000]	eval's l1: 0.599398
[4500]	eval's l1: 0.596716
[5000]	eval's l1: 0.597065
[5500]	eval's l1: 0.594683
[6000]	eval's l1: 0.593262
[6500]	eval's l1: 0.59007
[7000]	eval's l1: 0.587651
[7500]	eval's l1: 0.585778
[8000]	eval's l1: 0.584387
[8500]	eval's l1: 0.583008
[9000]	eval's l1: 0.585547
[9500]	eval's l1: 0.583535

Best trial: 0. Best value: 0.260283: 100%|██████████| 1/1 [04:29<00:00, 269.27s/it]

Best iteration: 9965, Score: 0.5821915249296641
[I 2025-07-19 23:34:15,150] Trial 0 finished with value: 0.2602833055417781 and parameters: {}. Best is trial 0 with value: 0.2602833055417781.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9965 iterations

[I 2025-07-19 23:40:57,740] A new study created in memory with name: no-name-8d018d57-eae9-4985-866f-afea50dd6874
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.06898
[1000]	eval's l1: 8.47198
[1500]	eval's l1: 8.23612
[2000]	eval's l1: 7.67264
[2500]	eval's l1: 7.54379
[3000]	eval's l1: 7.4882
[3500]	eval's l1: 7.43753
[4000]	eval's l1: 7.42397
[4500]	eval's l1: 7.42425
[5000]	eval's l1: 7.39936
[5500]	eval's l1: 7.38268
[6000]	eval's l1: 7.38209
[6500]	eval's l1: 7.36488
[7000]	eval's l1: 7.40038
[7500]	eval's l1: 7.43188
[8000]	eval's l1: 7.48569
[8500]	eval's l1: 7.493
[9000]	eval's l1: 7.42706
[9500]	eval's l1: 7.42312

Best trial: 0. Best value: 0.764963: 100%|██████████| 1/1 [02:26<00:00, 146.19s/it]

Best iteration: 6099, Score: 7.338958982860977
[I 2025-07-19 23:43:23,925] Trial 0 finished with value: 0.7649630248274905 and parameters: {}. Best is trial 0 with value: 0.7649630248274905.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6099 iterations

Scaling

[I 2025-07-19 23:45:26,244] A new study created in memory with name: no-name-6b6b6313-1bce-43fd-89b5-35bac97fa9a4
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.653246
[1000]	eval's l1: 0.630098
[1500]	eval's l1: 0.617299
[2000]	eval's l1: 0.608817
[2500]	eval's l1: 0.605529
[3000]	eval's l1: 0.600087
[3500]	eval's l1: 0.597642
[4000]	eval's l1: 0.594268
[4500]	eval's l1: 0.592143
[5000]	eval's l1: 0.589174
[5500]	eval's l1: 0.587658
[6000]	eval's l1: 0.585726
[6500]	eval's l1: 0.58417
[7000]	eval's l1: 0.584273
Early stopping, best iteration is:
[6508]	eval's l1: 0.584071
Evaluated only: l1
Best iteration: 6508, Score: 0.584070709096083

Best trial: 0. Best value: 0.253181: 100%|██████████| 1/1 [01:21<00:00, 81.01s/it]

[I 2025-07-19 23:46:47,249] Trial 0 finished with value: 0.2531805086125886 and parameters: {}. Best is trial 0 with value: 0.2531805086125886.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 6508 iterations

[I 2025-07-19 23:49:10,088] A new study created in memory with name: no-name-8fb61309-9b35-4932-9192-ce51f3792c8d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 7.43474
[1000]	eval's l1: 7.2847
[1500]	eval's l1: 7.34178
Early stopping, best iteration is:
[996]	eval's l1: 7.27772
Evaluated only: l1
Best iteration: 996, Score: 7.277716610301728

Best trial: 0. Best value: 0.256467: 100%|██████████| 1/1 [00:10<00:00, 10.54s/it]

[I 2025-07-19 23:49:20,626] Trial 0 finished with value: 0.25646707116702894 and parameters: {}. Best is trial 0 with value: 0.25646707116702894.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 996 iterations
Scaling

[I 2025-07-19 23:49:33,703] A new study created in memory with name: no-name-05cd2249-5bd1-470c-9e47-660792829bc3
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 0.63418
[1000]	eval's l1: 0.611431
[1500]	eval's l1: 0.599631
[2000]	eval's l1: 0.594486
[2500]	eval's l1: 0.591492
[3000]	eval's l1: 0.586724
[3500]	eval's l1: 0.584071
[4000]	eval's l1: 0.581706
[4500]	eval's l1: 0.581715
[5000]	eval's l1: 0.579644
[5500]	eval's l1: 0.578905
[6000]	eval's l1: 0.578005
[6500]	eval's l1: 0.576824
[7000]	eval's l1: 0.576471
[7500]	eval's l1: 0.57622
[8000]	eval's l1: 0.575923
[8500]	eval's l1: 0.575695
[9000]	eval's l1: 0.575116
[9500]	eval's l1: 0.574884
Did not meet early stopping. Best iteration is:
[9959]	eval's l1: 0.5744
Evaluated only: l1

Best trial: 0. Best value: 0.261903: 100%|██████████| 1/1 [02:11<00:00, 131.27s/it]

Best iteration: 9959, Score: 0.5743997154215922
[I 2025-07-19 23:51:44,973] Trial 0 finished with value: 0.261903253467888 and parameters: {}. Best is trial 0 with value: 0.261903253467888.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9959 iterations

[I 2025-07-19 23:55:44,859] A new study created in memory with name: no-name-b861f424-0895-46a5-a266-d116dfc7420d
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
Training until validation scores don't improve for 533 rounds
[500]	eval's l1: 7.50413
[1000]	eval's l1: 7.37526

Best trial: 0. Best value: 0.258761: 100%|██████████| 1/1 [00:09<00:00,  9.96s/it]

Early stopping, best iteration is:
[731]	eval's l1: 7.34282
Evaluated only: l1
Best iteration: 731, Score: 7.342816349146976
[I 2025-07-19 23:55:54,817] Trial 0 finished with value: 0.2587611889857616 and parameters: {}. Best is trial 0 with value: 0.2587611889857616.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'gbdt', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 731 iterations

Scaling

[I 2025-07-19 23:56:06,384] A new study created in memory with name: no-name-b762ba5d-4cf4-47c5-86ed-089cc8877e4b
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.645018
[1000]	eval's l1: 0.63824
[1500]	eval's l1: 0.628555
[2000]	eval's l1: 0.616165
[2500]	eval's l1: 0.608886
[3000]	eval's l1: 0.610988
[3500]	eval's l1: 0.604859
[4000]	eval's l1: 0.601618
[4500]	eval's l1: 0.600524
[5000]	eval's l1: 0.597291
[5500]	eval's l1: 0.592387
[6000]	eval's l1: 0.588905
[6500]	eval's l1: 0.587109
[7000]	eval's l1: 0.583702
[7500]	eval's l1: 0.583802
[8000]	eval's l1: 0.579957
[8500]	eval's l1: 0.577613
[9000]	eval's l1: 0.576377
[9500]	eval's l1: 0.575848

Best trial: 0. Best value: 0.249896: 100%|██████████| 1/1 [03:24<00:00, 204.63s/it]

Best iteration: 9982, Score: 0.5733361111123975
[I 2025-07-19 23:59:31,009] Trial 0 finished with value: 0.24989628111753298 and parameters: {}. Best is trial 0 with value: 0.24989628111753298.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9982 iterations

[I 2025-07-20 00:05:07,823] A new study created in memory with name: no-name-e4967ec5-ab4e-4cdd-97b7-b22f1910befa
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.0169
[1000]	eval's l1: 8.17479
[1500]	eval's l1: 7.97392
[2000]	eval's l1: 7.56905
[2500]	eval's l1: 7.48094
[3000]	eval's l1: 7.35684
[3500]	eval's l1: 7.38941
[4000]	eval's l1: 7.38727
[4500]	eval's l1: 7.39792
[5000]	eval's l1: 7.41325
[5500]	eval's l1: 7.4368
[6000]	eval's l1: 7.43514
[6500]	eval's l1: 7.4343
[7000]	eval's l1: 7.45364
[7500]	eval's l1: 7.47148
[8000]	eval's l1: 7.45273
[8500]	eval's l1: 7.45276
[9000]	eval's l1: 7.52772
[9500]	eval's l1: 7.53846

Best trial: 0. Best value: 0.951269: 100%|██████████| 1/1 [03:06<00:00, 186.67s/it]

Best iteration: 2974, Score: 7.339811325549353
[I 2025-07-20 00:08:14,487] Trial 0 finished with value: 0.951268677442605 and parameters: {}. Best is trial 0 with value: 0.951268677442605.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': True, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 2974 iterations

Scaling

[I 2025-07-20 00:09:19,837] A new study created in memory with name: no-name-a208b76a-9c6d-4d35-9cbc-2fc3403e7641
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 0.641776
[1000]	eval's l1: 0.62677
[1500]	eval's l1: 0.615115
[2000]	eval's l1: 0.609655
[2500]	eval's l1: 0.603214
[3000]	eval's l1: 0.601395
[3500]	eval's l1: 0.596585
[4000]	eval's l1: 0.592933
[4500]	eval's l1: 0.588888
[5000]	eval's l1: 0.587901
[5500]	eval's l1: 0.588112
[6000]	eval's l1: 0.58656
[6500]	eval's l1: 0.58496
[7000]	eval's l1: 0.583068
[7500]	eval's l1: 0.581358
[8000]	eval's l1: 0.579924
[8500]	eval's l1: 0.577643
[9000]	eval's l1: 0.578181
[9500]	eval's l1: 0.575832

Best trial: 0. Best value: 0.246272: 100%|██████████| 1/1 [04:34<00:00, 274.78s/it]

Best iteration: 9453, Score: 0.5752217474247431
[I 2025-07-20 00:13:54,620] Trial 0 finished with value: 0.24627235336026027 and parameters: {}. Best is trial 0 with value: 0.24627235336026027.

Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 9453 iterations

[I 2025-07-20 00:21:09,588] A new study created in memory with name: no-name-421159dd-1590-4dcd-8c96-7507935e2ba6
  0%|          | 0/1 [00:00<?, ?it/s]

Skipping hyperparameter optimization, using default parameters.
[500]	eval's l1: 9.06898
[1000]	eval's l1: 8.47198
[1500]	eval's l1: 8.23612
[2000]	eval's l1: 7.67264
[2500]	eval's l1: 7.54379
[3000]	eval's l1: 7.4882
[3500]	eval's l1: 7.43753
[4000]	eval's l1: 7.42397
[4500]	eval's l1: 7.45165
[5000]	eval's l1: 7.46178
[5500]	eval's l1: 7.47442
[6000]	eval's l1: 7.47142
[6500]	eval's l1: 7.4593
[7000]	eval's l1: 7.48594
[7500]	eval's l1: 7.49713
[8000]	eval's l1: 7.54331
[8500]	eval's l1: 7.52573
[9000]	eval's l1: 7.49906
[9500]	eval's l1: 7.47868

Best trial: 0. Best value: 0.931817: 100%|██████████| 1/1 [03:08<00:00, 188.81s/it]

Best iteration: 3629, Score: 7.356593310958047
[I 2025-07-20 00:24:18,402] Trial 0 finished with value: 0.9318166813807647 and parameters: {}. Best is trial 0 with value: 0.9318166813807647.
Training LGBM with parameters: {'objective': 'tweedie', 'device': 'cpu', 'max_bin': 512, 'extra_trees': False, 'boosting_type': 'dart', 'metric': 'None', 'num_leaves': 31, 'learning_rate': 0.03, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 5, 'min_data_in_leaf': 30, 'verbose': 0}, and 3629 iterations

Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250720_032605'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       16.80 GB / 31.23 GB (53.8%)
Disk Space Avail:   724.94 GB / 914.78 GB (79.2%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': [],
 'num_val_windows': 2,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 21452 rows, 656 time series. Median time series length is 36 (min=14, max=36).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-20 00:26:15
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE']
Training timeseries model SeasonalNaive.
	-0.2316       = Validation score (-WQL)
	1.82    s     = Training runtime
	0.21    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2115       = Validation score (-WQL)
	1.64    s     = Training runtime
	0.07    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2245       = Validation score (-WQL)
	15.42   s     = Training runtime
	0.29    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-0.2784       = Validation score (-WQL)
	0.41    s     = Training runtime
	0.24    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta.
	-0.2033       = Validation score (-WQL)
	1.11    s     = Training runtime
	0.29    s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	-0.2014       = Validation score (-WQL)
	1.45    s     = Training runtime
	1.33    s     = Validation (prediction) runtime
Training timeseries model ChronosZeroShot[bolt_base].
	-0.1905       = Validation score (-WQL)
	1.67    s     = Training runtime
	2.12    s     = Validation (prediction) runtime
Training timeseries model ChronosFineTuned[bolt_small].
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250720_032605/models/ChronosFineTuned[bolt_small]/W0/fine-tuned-ckpt
	Saving fine-tuned model to /home/fede/programacion/labo3/AutogluonModels/ag-20250720_032605/models/ChronosFineTuned[bolt_small]/W1/fine-tuned-ckpt
	-0.1792       = Validation score (-WQL)
	98.94   s     = Training runtime
	0.09    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer.
	-0.1806       = Validation score (-WQL)
	134.98  s     = Training runtime
	0.69    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-0.1910       = Validation score (-WQL)
	75.14   s     = Training runtime
	0.23    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.1938       = Validation score (-WQL)
	53.97   s     = Training runtime
	0.27    s     = Validation (prediction) runtime
Training timeseries model TiDE.
	-0.2343       = Validation score (-WQL)
	157.15  s     = Training runtime
	0.50    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoETS': 0.15, 'ChronosFineTuned[bolt_small]': 0.31, 'NPTS': 0.09, 'SeasonalNaive': 0.04, 'TemporalFusionTransformer': 0.41}
	-0.1710       = Validation score (-WQL)
	1.59    s     = Training runtime
	2.57    s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'ChronosZeroShot[bolt_base]', 'ChronosFineTuned[bolt_small]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'TiDE', 'WeightedEnsemble']
Total runtime: 551.89 s
Best model: WeightedEnsemble
Best model score: -0.1710
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
Beginning AutoGluon training...
AutoGluon will save models to '/home/fede/programacion/labo3/AutogluonModels/ag-20250720_033541'
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.3
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2
CPU Count:          16
GPU Count:          1
Memory Avail:       15.39 GB / 31.23 GB (49.3%)
Disk Space Avail:   724.51 GB / 914.78 GB (79.2%)
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'freq': 'MS',
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 2,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'tn',
 'verbosity': 2}

train_data with frequency 'ME' has been resampled to frequency 'MS'.
Provided train_data has 21452 rows, 656 time series. Median time series length is 36 (min=14, max=36).

Provided data contains following columns:
	target: 'tn'
	past_covariates:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['product_id', 'cust_request_qty', 'cust_request_tn', 'stock_final', 'year', 'mes', ...]
	static_features:
		categorical:        ['cat1', 'cat2', 'cat3', 'brand', 'sku_size']
		continuous (float): ['customer_id', 'product_id']

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored covariates:      ['prod_cust_request_tn_x_tn', 'prod_tn_product_weight_x_tn', 'prod_tn_rolling_max_12_x_tn', 'prod_tn_rolling_mean_12_x_tn', 'prod_tn_rolling_mean_24_x_tn', 'prod_tn_rolling_mean_6_x_tn', 'prod_tn_rolling_min_12_x_tn', 'prod_tn_rolling_min_24_x_tn', 'prod_tn_rolling_min_6_x_tn', 'prod_tn_x_tn_lag_1', 'prod_tn_x_tn_lag_10', 'prod_tn_x_tn_lag_11', 'prod_tn_x_tn_lag_2', 'prod_tn_x_tn_lag_3', 'prod_tn_x_tn_lag_8', 'prod_tn_x_tn_lag_9', 'prod_tn_x_tn_rolling_max_24', 'prod_tn_x_tn_rolling_max_6']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2025-07-20 00:35:52
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive.
	-0.3036       = Validation score (-WQL)
	0.07    s     = Training runtime
	1.76    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-0.2429       = Validation score (-WQL)
	0.07    s     = Training runtime
	0.24    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-0.2124       = Validation score (-WQL)
	0.86    s     = Training runtime
	0.07    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.2162       = Validation score (-WQL)
	7.97    s     = Training runtime
	0.19    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.2082       = Validation score (-WQL)
	0.08    s     = Training runtime
	2.11    s     = Validation (prediction) runtime
Training timeseries model Theta.
	-0.2089       = Validation score (-WQL)
	0.08    s     = Training runtime
	0.28    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'DirectTabular': 0.31, 'ETS': 0.23, 'RecursiveTabular': 0.34, 'SeasonalNaive': 0.11}
	-0.1897       = Validation score (-WQL)
	0.42    s     = Training runtime
	2.60    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 14.32 s
Best model: WeightedEnsemble
Best model score: -0.1897
data with frequency 'ME' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

In [28]:
final_df

,product_id,target,prediction_AutoGluon-best_quality,prediction_AutoGluon-fast_training,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-False-target-t+2,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-dart-weight-True-target-t+2,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-delta,prediction_LGBM-extra_trees-False-trials-1-scaling-False-boosting-gbdt-weight-False-target-t+2,...,prediction_LGBM-extra_trees-True-trials-1-scaling-True-boosting-gbdt-weight-True-target-t+2,prediction_LinearRegression-all-['lags']-all,prediction_LinearRegression-magicos-['lags']-FOODS,prediction_LinearRegression-magicos-['lags']-HC,prediction_LinearRegression-magicos-['lags']-PC,prediction_LinearRegression-magicos-['lags']-all,prediction_SMA-12,weights,tn,tn_2
product_id,,,,,,,,,,,,,,,,,,,,,
20001.0,20001.0,0.0,1315.988068,1414.626422,1625.705279,1181.747647,1625.705279,1198.199425,1590.005865,1367.074970,...,1271.386618,1277.502197,1364.332970,1199.431152,1364.332970,1162.707520,1454.732737,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",1393.236927,1381.724773
20002.0,20002.0,0.0,1096.504174,1118.941426,1166.179259,1167.432187,1166.179259,1194.259037,1198.439143,1346.510526,...,1345.176336,1222.369629,1239.921424,1294.223633,1239.921424,1183.640625,1175.437134,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",1203.750208,1208.116727
20003.0,20003.0,0.0,693.700877,746.214679,610.529758,658.460728,610.529758,628.172522,621.712087,632.810920,...,768.385407,765.707947,643.368164,743.975282,743.975282,684.763855,784.976405,{'prediction_AutoGluon-best_quality': 0.199020...,755.089894,748.838745
20004.0,20004.0,0.0,521.957952,565.213435,629.887948,557.094131,629.887948,542.904335,548.114435,544.855566,...,594.886968,604.437927,501.384521,581.107301,581.107301,580.485046,627.215322,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",549.027668,556.595002
20005.0,20005.0,0.0,486.702169,555.912126,661.317679,547.798851,661.317679,562.972249,567.994537,548.287994,...,581.862732,568.349304,441.741516,576.480911,576.480911,563.560852,668.270111,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",612.534548,614.142580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21263.0,21263.0,0.0,-0.000782,0.006956,1.229206,0.018691,1.229206,0.023327,1.404239,0.016714,...,0.015996,1.899233,0.331520,0.331520,0.619479,0.467764,0.029993,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.012265,0.013266
21265.0,21265.0,0.0,0.274838,0.274838,0.857413,0.043563,0.857413,0.041426,1.131591,0.044660,...,0.063152,0.274838,0.274838,0.274838,0.274838,0.274838,0.089541,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.058889,0.063042
21266.0,21266.0,0.0,0.285134,0.285134,0.944235,0.045977,0.944235,0.043808,1.132731,0.044603,...,0.061001,0.285134,0.285134,0.285134,0.285134,0.285134,0.094659,{'prediction_AutoGluon-best_quality': 0.192409...,0.138368,0.109723
21267.0,21267.0,0.0,0.331438,0.331438,1.261484,0.038742,1.261484,0.038423,1.465153,0.039554,...,0.052874,0.331438,0.331438,0.331438,0.331438,0.331438,0.092835,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.044595,0.177618
21276.0,21276.0,0.0,0.312821,0.312821,1.254714,0.035899,1.254714,0.035518,1.458383,0.035614,...,0.023098,0.312821,0.312821,0.312821,0.312821,0.312821,0.045447,"{'prediction_AutoGluon-best_quality': 0.0, 'pr...",0.022144,0.020103

In [29]:

models_used = [model.name for model in trainer.models]
models_used = " ".join(models_used)
# hago un hash en base de models_used para el nombre del archivo
import hashlib
hash_object = hashlib.md5(models_used.encode())
hash_hex = hash_object.hexdigest()
description = f"Ensamble de modelos: {models_used}"
# save txt with name hash_hex.txt and the description
with open(f"description_{hash_hex}.txt", "w") as f:
    f.write(description)
submission = final_df[["product_id", "tn"]].reset_index(drop=True)
submission.to_csv(f"submission_weighted_ensamble_{hash_hex}.csv", index=False)
submission

     product_id           tn
0       20001.0  1393.236927
1       20002.0  1203.750208
2       20003.0   755.089894
3       20004.0   549.027668
4       20005.0   612.534548
..          ...          ...
775     21263.0     0.012265
776     21265.0     0.058889
777     21266.0     0.138368
778     21267.0     0.044595
779     21276.0     0.022144

[780 rows x 2 columns]

In [34]:
final_df.to_csv(f"final_df_{hash_hex}.csv", index=False)
hash_hex

'08f7f3fe2145910b0357d179691f8c60'

In [30]:
submission_2_models = final_df[["product_id", "tn_2"]].reset_index(drop=True)
submission_2_models.rename(columns={"tn_2": "tn"}, inplace=True)
submission_2_models.to_csv(f"submission_2_models_weighted_ensamble_{hash_hex}.csv", index=False)
submission_2_models

     product_id           tn
0       20001.0  1381.724773
1       20002.0  1208.116727
2       20003.0   748.838745
3       20004.0   556.595002
4       20005.0   614.142580
..          ...          ...
775     21263.0     0.013266
776     21265.0     0.063042
777     21266.0     0.109723
778     21267.0     0.177618
779     21276.0     0.020103

[780 rows x 2 columns]

In [31]:
print(description)

Ensamble de modelos: LinearRegression-magicos-['lags']-all LinearRegression-magicos-['lags']-HC LinearRegression-magicos-['lags']-FOODS LinearRegression-magicos-['lags']-PC LinearRegression-all-['lags']-all LGBM-extra_trees-True-trials-0-scaling-True-boosting-gbdt-weight-True-target-delta LGBM-extra_trees-True-trials-0-scaling-False-boosting-gbdt-weight-True-target-delta LGBM-extra_trees-False-trials-0-scaling-True-boosting-gbdt-weight-True-target-delta LGBM-extra_trees-False-trials-0-scaling-False-boosting-gbdt-weight-True-target-delta LGBM-extra_trees-True-trials-0-scaling-True-boosting-dart-weight-True-target-delta LGBM-extra_trees-True-trials-0-scaling-False-boosting-dart-weight-True-target-delta LGBM-extra_trees-False-trials-0-scaling-True-boosting-dart-weight-True-target-delta LGBM-extra_trees-False-trials-0-scaling-False-boosting-dart-weight-True-target-delta LGBM-extra_trees-True-trials-0-scaling-True-boosting-gbdt-weight-False-target-delta LGBM-extra_trees-True-trials-0-scaling-False-boosting-gbdt-weight-False-target-delta LGBM-extra_trees-False-trials-0-scaling-True-boosting-gbdt-weight-False-target-delta LGBM-extra_trees-False-trials-0-scaling-False-boosting-gbdt-weight-False-target-delta LGBM-extra_trees-True-trials-0-scaling-True-boosting-dart-weight-False-target-delta LGBM-extra_trees-True-trials-0-scaling-False-boosting-dart-weight-False-target-delta LGBM-extra_trees-False-trials-0-scaling-True-boosting-dart-weight-False-target-delta LGBM-extra_trees-False-trials-0-scaling-False-boosting-dart-weight-False-target-delta LGBM-extra_trees-True-trials-0-scaling-True-boosting-gbdt-weight-True-target-t+2 LGBM-extra_trees-True-trials-0-scaling-False-boosting-gbdt-weight-True-target-t+2 LGBM-extra_trees-False-trials-0-scaling-True-boosting-gbdt-weight-True-target-t+2 LGBM-extra_trees-False-trials-0-scaling-False-boosting-gbdt-weight-True-target-t+2 LGBM-extra_trees-True-trials-0-scaling-True-boosting-dart-weight-True-target-t+2 LGBM-extra_trees-True-trials-0-scaling-False-boosting-dart-weight-True-target-t+2 LGBM-extra_trees-False-trials-0-scaling-True-boosting-dart-weight-True-target-t+2 LGBM-extra_trees-False-trials-0-scaling-False-boosting-dart-weight-True-target-t+2 LGBM-extra_trees-True-trials-0-scaling-True-boosting-gbdt-weight-False-target-t+2 LGBM-extra_trees-True-trials-0-scaling-False-boosting-gbdt-weight-False-target-t+2 LGBM-extra_trees-False-trials-0-scaling-True-boosting-gbdt-weight-False-target-t+2 LGBM-extra_trees-False-trials-0-scaling-False-boosting-gbdt-weight-False-target-t+2 LGBM-extra_trees-True-trials-0-scaling-True-boosting-dart-weight-False-target-t+2 LGBM-extra_trees-True-trials-0-scaling-False-boosting-dart-weight-False-target-t+2 LGBM-extra_trees-False-trials-0-scaling-True-boosting-dart-weight-False-target-t+2 LGBM-extra_trees-False-trials-0-scaling-False-boosting-dart-weight-False-target-t+2 AutoGluon-best_quality AutoGluon-fast_training SMA-12

In [32]:
submission_3 = final_df_3[["product_id", "pred_weights"]].rename(columns={"pred_weights": "tn"}).reset_index(drop=True)
submission_3.to_csv(f"submission_weights_ensamble_per_product_{hash_hex}.csv", index=False)
submission_3

NameError: name 'final_df_3' is not defined