In [1]:
import pandas as pd
import numpy as np
import re
import os
import warnings
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl
from pytorch_lightning import (LightningDataModule, LightningModule, Trainer)
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint, Timer
from pytorch_lightning.loggers import WandbLogger
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error 
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
DATA_FOLDER = "./"
from sklearn.preprocessing import StandardScaler, RobustScaler

df = pd.read_pickle(DATA_FOLDER + "df_fe_epic_big_best_customers_5c.pickle")
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
product_ids = pd.read_csv(DATA_FOLDER + "product_id_apredecir201912.txt", sep="\t")[
    "product_id"
].tolist()
df = df[df["product_id"].isin(product_ids)]
# sort df by date
df = df.sort_values(by=["date_id"])
target = df.groupby(["product_id", "customer_id"])["tn"].shift(-2)
target_scaler = RobustScaler(with_centering=False).fit(target.dropna().values.reshape(-1, 1))
df["target"] = target

# entreno en todos los df donde target no es NaN
train = df[df["target"].notna()]
train["target"] = target_scaler.transform(train["target"].values.reshape(-1, 1)).flatten()
train["weights"] = np.log1p(train["tn"]).clip(1, 10)
# valido en date_id == 33
val = train[train["date_id"] == 33]

scaler = RobustScaler(with_centering=False)
train[numeric_cols] = scaler.fit_transform(train[numeric_cols].fillna(0))
val[numeric_cols] = scaler.transform(val[numeric_cols].fillna(0))


X_kaggle = df[df["date_id"] == 35][numeric_cols].fillna(0)

# scalo X_train, X_kaggle y X_val con estandar scaler
X_kaggle[numeric_cols] = scaler.transform(X_kaggle[numeric_cols])

target_col = "target"
weight_name = "weights"

/tmp/ipykernel_725501/284001704.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["target"] = target
/tmp/ipykernel_725501/284001704.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train["target"] = target_scaler.transform(train["target"].values.reshape(-1, 1)).flatten()
/tmp/ipykernel_725501/284001704.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train["weights"] = np.log1p(train["tn"]).clip(1, 10)
/tmp/ipykernel_725501/284001704.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train["weights"] = np.log1p(train["tn"]).clip(1, 10)
/tmp/ipykernel_725501/284001704.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[numeric_cols] = scaler.fit_transform(train[numeric_cols].fillna(0))
/tmp/ipykernel_725501/284001704.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val[numeric_cols] = scaler.transform(val[numeric_cols].fillna(0))

In [3]:
class custom_args():
    def __init__(self):
        self.usegpu = True
        self.gpuid = 0
        self.seed = 42
        self.model = "nn"
        self.loader_workers = 0
        self.bs = 8192
        self.lr = 1e-3
        self.weight_decay = 5e-4
        self.droputs = [0.1, 0.1]
        self.n_hidden = [512, 512, 256]
        self.patience = 100
        #self.max_epochs = 20
        self.max_epochs = 8000
        self.N_fold = 15

my_args = custom_args()

In [4]:
#Pytorch Data Module Definition
from pytorch_lightning.utilities.types import EVAL_DATALOADERS


class CustomDataset(Dataset):
    def __init__(self, df, accelerator):
        self.features = torch.FloatTensor(df[numeric_cols].values).to(accelerator)
        self.labels = torch.FloatTensor(df[target_col].values).to(accelerator)
        self.weights = torch.FloatTensor(df[weight_name].values).to(accelerator)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        x = self.features[idx]
        y = self.labels[idx]
        w = self.weights[idx]
        return x, y, w
    
class DataModule(LightningDataModule):
    def __init__(self, train_df, batch_size, valid_df=None, accelerator="cpu"):
        super().__init__()
        self.df = train_df
        self.batch_size = batch_size
        self.dates = self.df["date_id"].unique()
        self.accelerator = accelerator
        self.train_dataset = None
        self.valid_df = None
        if valid_df is not None:
            self.valid_df = valid_df
        self.val_dataset = None

    def setup(self, fold=0, N_fold=5, stage=None):
        selected_dates = [date for ii, date in enumerate(self.dates) if ii % N_fold != fold]
        df_train = self.df.loc[self.df["date_id"].isin(selected_dates)]
        self.train_dataset = CustomDataset(df_train, self.accelerator)
        if self.valid_df is not None:
            df_valid = self.valid_df
            self.val_dataset = CustomDataset(df_valid, self.accelerator)

    def train_dataloader(self, n_workers=0):
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=n_workers,
        )
    
    def val_dataloader(self, n_workers=0):
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=n_workers,
        )
    
class NN(LightningModule):
    def __init__(self, input_dim, hidden_dims, droputs, lr, weight_decay):
        super().__init__()
        self.save_hyperparameters()
        layers = []
        in_dim = input_dim
        for i, hidden_dim in enumerate(hidden_dims):
            layers.append(nn.BatchNorm1d(in_dim))
            if i > 0:
                layers.append(nn.SiLU())
            if i < len(droputs):
                layers.append(nn.Dropout(droputs[i]))
            layers.append(nn.Linear(in_dim, hidden_dim))
            in_dim = hidden_dim
        layers.append(nn.Linear(in_dim, 1))
        layers.append(nn.ReLU())
        self.model = nn.Sequential(*layers)
        self.lr = lr
        self.weight_decay = weight_decay
        self.validation_step_outputs = []

    def forward(self, x):
        return self.model(x).squeeze(-1)
    
    def training_step(self, batch):
        x, y, w = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y, reduction='none')
        loss = (loss * w).mean()
        self.log("train_loss", loss, on_step=False, on_epoch=True, batch_size=x.size(0))
        return loss
    
    def validation_step(self, batch):
        x, y, w = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y, reduction='none')
        loss = (loss * w).mean()
        self.validation_step_outputs.append((y_hat, y, w))
        self.log("val_loss", loss, on_step=False, on_epoch=True, batch_size=x.size(0))
        return loss
    
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr, weight_decay=self.weight_decay)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='min', factor=0.5, patience=5
        )
        return {
            'optimizer': optimizer,
            'lr_scheduler': {
                'scheduler': scheduler,
                'monitor': 'val_loss',
            }
        }
    
    def on_train_epoch_end(self):
        if self.trainer.sanity_checking:
            return
        epoch = self.trainer.current_epoch
        metrics = {k: v.item() if isinstance(v, torch.Tensor) else v for k, v in self.trainer.logged_metrics.items()}
        formatted_metrics = {k: f"{v:.5f}" for k, v in metrics.items()}
        print(f"Epoch {epoch}: {formatted_metrics}")

In [5]:
# crete pytorch data module
args = my_args
device = torch.device("cuda" if args.usegpu and torch.cuda.is_available() else "cpu")
accelerator = "cuda" if args.usegpu and torch.cuda.is_available() else "cpu"
loader_device = "cpu"

data_module = DataModule(
    train_df=train,
    batch_size=args.bs,
    valid_df=val,
    accelerator=accelerator
)

In [6]:
import gc
import os

os.environ['CUDA_LAUNCH_BLOCKING']="1"
os.environ['TORCH_USE_CUDA_DSA'] = "1"
del df
gc.collect()
pl.seed_everything(args.seed)
models = []
for fold in range(args.N_fold):
    data_module.setup(fold=fold, N_fold=args.N_fold)
    input_dim = data_module.train_dataset.features.shape[1]
    model = NN(
        input_dim=input_dim,
        hidden_dims=args.n_hidden,
        droputs=args.droputs,
        lr=args.lr,
        weight_decay=args.weight_decay
    )
    early_stopping = EarlyStopping(
        monitor="val_loss",
        patience=args.patience,
        mode="min",
        verbose=False,
    )
    checkpoint_callback = ModelCheckpoint(
        monitor="val_loss",
        mode="min",
        save_top_k=1,
        verbose=False,
        dirpath="./models",           # Carpeta donde querés guardar los checkpoints
        filename=f"./nn_{fold}.model"
    )
    timer = Timer()
    trainer = Trainer(
        max_epochs=args.max_epochs,
        accelerator=accelerator,
        devices=[args.gpuid] if args.usegpu else None,
        callbacks=[early_stopping, checkpoint_callback, timer],
        enable_progress_bar=True,
    )
    trainer.fit(model, data_module.train_dataloader(args.loader_workers), data_module.val_dataloader(args.loader_workers))
    print(f'Fold-{fold} Training completed in {timer.time_elapsed("train"):.2f}s')
    models.append(model)

Seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (14) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=57]Epoch 0: {'val_loss': '4620.86523', 'train_loss': '349.46161'}
Epoch 1: 100%|██████████| 14/14 [00:01<00:00,  9.35it/s, v_num=57]Epoch 1: {'val_loss': '609.35034', 'train_loss': '151.21185'}
Epoch 2: 100%|██████████| 14/14 [00:01<00:00, 10.51it/s, v_num=57]Epoch 2: {'val_loss': '188.30568', 'train_loss': '127.17375'}
Epoch 3: 100%|██████████| 14/14 [00:01<00:00, 10.38it/s, v_num=57]Epoch 3: {'val_loss': '52.10709', 'train_loss': '119.12083'}
Epoch 4: 100%|██████████| 14/14 [00:01<00:00, 10.39it/s, v_num=57]Epoch 4: {'val_loss': '51.13974', 'train_loss': '110.27779'}
Epoch 5: 100%|██████████| 14/14 [00:01<00:00, 10.43it/s, v_num=57]Epoch 5: {'val_loss': '37.50797', 'train_loss': '110.31298'}
Epoch 6: 100%|██████████| 14/14 [00:01<00:00,  9.28it/s, v_num=57]Epoch 6: {'val_loss': '44.98460', 'train_loss': '102.45656'}
Epoch 7: 100%|██████████| 14/14 [00:01<00:00, 10.46it/s, v_num=57]Epoch 7: {'val_loss': '40.06538', 'train_loss': '97.98562'}
Epoch 8: 100%|██████████| 14/14 [00:01<00:00, 10.37it/s, v_num=57]Epoch 8: {'val_loss': '59.19733', 'train_loss': '100.79658'}
Epoch 9: 100%|██████████| 14/14 [00:01<00:00, 10.48it/s, v_num=57]Epoch 9: {'val_loss': '45.55104', 'train_loss': '108.37624'}
Epoch 10: 100%|██████████| 14/14 [00:01<00:00,  9.40it/s, v_num=57]Epoch 10: {'val_loss': '49.65887', 'train_loss': '95.65375'}
Epoch 11: 100%|██████████| 14/14 [00:01<00:00, 10.58it/s, v_num=57]Epoch 11: {'val_loss': '48.16695', 'train_loss': '104.23300'}
Epoch 12: 100%|██████████| 14/14 [00:01<00:00, 10.25it/s, v_num=57]Epoch 12: {'val_loss': '57.59040', 'train_loss': '98.21867'}
Epoch 13: 100%|██████████| 14/14 [00:01<00:00, 10.48it/s, v_num=57]Epoch 13: {'val_loss': '36.87042', 'train_loss': '95.08389'}
Epoch 14: 100%|██████████| 14/14 [00:01<00:00, 10.38it/s, v_num=57]Epoch 14: {'val_loss': '44.56770', 'train_loss': '98.73271'}
Epoch 15: 100%|██████████| 14/14 [00:01<00:00,  9.27it/s, v_num=57]Epoch 15: {'val_loss': '37.36330', 'train_loss': '98.59229'}
Epoch 16: 100%|██████████| 14/14 [00:01<00:00, 10.41it/s, v_num=57]Epoch 16: {'val_loss': '43.51181', 'train_loss': '95.13424'}
Epoch 17: 100%|██████████| 14/14 [00:01<00:00, 10.43it/s, v_num=57]Epoch 17: {'val_loss': '43.03675', 'train_loss': '92.50930'}
Epoch 18: 100%|██████████| 14/14 [00:01<00:00, 10.44it/s, v_num=57]Epoch 18: {'val_loss': '37.67624', 'train_loss': '88.60611'}
Epoch 19: 100%|██████████| 14/14 [00:01<00:00,  9.14it/s, v_num=57]Epoch 19: {'val_loss': '34.61317', 'train_loss': '89.60910'}
Epoch 20: 100%|██████████| 14/14 [00:01<00:00, 10.38it/s, v_num=57]Epoch 20: {'val_loss': '40.39645', 'train_loss': '89.29281'}
Epoch 21: 100%|██████████| 14/14 [00:01<00:00, 10.46it/s, v_num=57]Epoch 21: {'val_loss': '34.92757', 'train_loss': '85.15720'}
Epoch 22: 100%|██████████| 14/14 [00:01<00:00, 10.42it/s, v_num=57]Epoch 22: {'val_loss': '52.45921', 'train_loss': '92.21380'}
Epoch 23: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 23: {'val_loss': '49.98912', 'train_loss': '92.81533'}
Epoch 24: 100%|██████████| 14/14 [00:01<00:00, 10.48it/s, v_num=57]Epoch 24: {'val_loss': '33.65932', 'train_loss': '84.17716'}
Epoch 25: 100%|██████████| 14/14 [00:01<00:00,  9.17it/s, v_num=57]Epoch 25: {'val_loss': '38.66192', 'train_loss': '95.01271'}
Epoch 26: 100%|██████████| 14/14 [00:01<00:00, 10.38it/s, v_num=57]Epoch 26: {'val_loss': '44.33163', 'train_loss': '93.05473'}
Epoch 27: 100%|██████████| 14/14 [00:01<00:00, 10.40it/s, v_num=57]Epoch 27: {'val_loss': '34.83731', 'train_loss': '84.40505'}
Epoch 28: 100%|██████████| 14/14 [00:01<00:00, 10.42it/s, v_num=57]Epoch 28: {'val_loss': '38.19143', 'train_loss': '84.08159'}
Epoch 29: 100%|██████████| 14/14 [00:01<00:00, 10.48it/s, v_num=57]Epoch 29: {'val_loss': '35.61891', 'train_loss': '87.02052'}
Epoch 30: 100%|██████████| 14/14 [00:01<00:00,  9.27it/s, v_num=57]Epoch 30: {'val_loss': '36.37809', 'train_loss': '92.60003'}
Epoch 31: 100%|██████████| 14/14 [00:01<00:00, 10.32it/s, v_num=57]Epoch 31: {'val_loss': '31.44228', 'train_loss': '82.93255'}
Epoch 32: 100%|██████████| 14/14 [00:01<00:00, 10.42it/s, v_num=57]Epoch 32: {'val_loss': '31.63540', 'train_loss': '76.45636'}
Epoch 33: 100%|██████████| 14/14 [00:01<00:00, 10.27it/s, v_num=57]Epoch 33: {'val_loss': '31.32825', 'train_loss': '76.55680'}
Epoch 34: 100%|██████████| 14/14 [00:01<00:00, 10.26it/s, v_num=57]Epoch 34: {'val_loss': '53.56123', 'train_loss': '78.78702'}
Epoch 35: 100%|██████████| 14/14 [00:01<00:00,  9.20it/s, v_num=57]Epoch 35: {'val_loss': '46.21004', 'train_loss': '78.21881'}
Epoch 36: 100%|██████████| 14/14 [00:01<00:00, 10.35it/s, v_num=57]Epoch 36: {'val_loss': '33.77223', 'train_loss': '83.79691'}
Epoch 37: 100%|██████████| 14/14 [00:01<00:00, 10.27it/s, v_num=57]Epoch 37: {'val_loss': '31.10959', 'train_loss': '86.93839'}
Epoch 38: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 38: {'val_loss': '31.87239', 'train_loss': '84.50681'}
Epoch 39: 100%|██████████| 14/14 [00:01<00:00,  9.28it/s, v_num=57]Epoch 39: {'val_loss': '40.72479', 'train_loss': '83.66527'}
Epoch 40: 100%|██████████| 14/14 [00:01<00:00, 10.45it/s, v_num=57]Epoch 40: {'val_loss': '41.28574', 'train_loss': '90.28201'}
Epoch 41: 100%|██████████| 14/14 [00:01<00:00, 10.36it/s, v_num=57]Epoch 41: {'val_loss': '33.65253', 'train_loss': '84.10223'}
Epoch 42: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=57]Epoch 42: {'val_loss': '30.77030', 'train_loss': '81.14796'}
Epoch 43: 100%|██████████| 14/14 [00:01<00:00, 10.35it/s, v_num=57]Epoch 43: {'val_loss': '31.23331', 'train_loss': '82.25511'}
Epoch 44: 100%|██████████| 14/14 [00:01<00:00,  9.16it/s, v_num=57]Epoch 44: {'val_loss': '32.92056', 'train_loss': '83.45190'}
Epoch 45: 100%|██████████| 14/14 [00:01<00:00, 10.35it/s, v_num=57]Epoch 45: {'val_loss': '46.60193', 'train_loss': '79.95689'}
Epoch 46: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 46: {'val_loss': '37.56973', 'train_loss': '78.15410'}
Epoch 47: 100%|██████████| 14/14 [00:01<00:00, 10.32it/s, v_num=57]Epoch 47: {'val_loss': '32.06300', 'train_loss': '76.05302'}
Epoch 48: 100%|██████████| 14/14 [00:01<00:00,  9.24it/s, v_num=57]Epoch 48: {'val_loss': '45.35074', 'train_loss': '80.52955'}
Epoch 49: 100%|██████████| 14/14 [00:01<00:00, 10.36it/s, v_num=57]Epoch 49: {'val_loss': '31.40014', 'train_loss': '72.88319'}
Epoch 50: 100%|██████████| 14/14 [00:01<00:00, 10.34it/s, v_num=57]Epoch 50: {'val_loss': '36.39777', 'train_loss': '78.20634'}
Epoch 51: 100%|██████████| 14/14 [00:01<00:00, 10.36it/s, v_num=57]Epoch 51: {'val_loss': '32.08267', 'train_loss': '75.90504'}
Epoch 52: 100%|██████████| 14/14 [00:01<00:00, 10.31it/s, v_num=57]Epoch 52: {'val_loss': '30.82519', 'train_loss': '72.21389'}
Epoch 53: 100%|██████████| 14/14 [00:01<00:00,  9.15it/s, v_num=57]Epoch 53: {'val_loss': '34.27592', 'train_loss': '73.05798'}
Epoch 54: 100%|██████████| 14/14 [00:01<00:00, 10.33it/s, v_num=57]Epoch 54: {'val_loss': '32.08775', 'train_loss': '73.60007'}
Epoch 55: 100%|██████████| 14/14 [00:01<00:00, 10.34it/s, v_num=57]Epoch 55: {'val_loss': '31.61904', 'train_loss': '71.82521'}
Epoch 56: 100%|██████████| 14/14 [00:01<00:00, 10.31it/s, v_num=57]Epoch 56: {'val_loss': '31.46015', 'train_loss': '68.36668'}
Epoch 57: 100%|██████████| 14/14 [00:01<00:00, 10.25it/s, v_num=57]Epoch 57: {'val_loss': '31.50046', 'train_loss': '76.75168'}
Epoch 58: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=57]Epoch 58: {'val_loss': '34.54455', 'train_loss': '73.14754'}
Epoch 59: 100%|██████████| 14/14 [00:01<00:00, 10.36it/s, v_num=57]Epoch 59: {'val_loss': '32.15495', 'train_loss': '70.12141'}
Epoch 60: 100%|██████████| 14/14 [00:01<00:00, 10.33it/s, v_num=57]Epoch 60: {'val_loss': '30.46583', 'train_loss': '74.60770'}
Epoch 61: 100%|██████████| 14/14 [00:01<00:00, 10.32it/s, v_num=57]Epoch 61: {'val_loss': '36.41619', 'train_loss': '69.95881'}
Epoch 62: 100%|██████████| 14/14 [00:01<00:00, 10.31it/s, v_num=57]Epoch 62: {'val_loss': '33.96119', 'train_loss': '78.34258'}
Epoch 63: 100%|██████████| 14/14 [00:01<00:00,  9.22it/s, v_num=57]Epoch 63: {'val_loss': '30.24587', 'train_loss': '68.41489'}
Epoch 64: 100%|██████████| 14/14 [00:01<00:00, 10.35it/s, v_num=57]Epoch 64: {'val_loss': '30.04571', 'train_loss': '76.59449'}
Epoch 65: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=57]Epoch 65: {'val_loss': '31.62764', 'train_loss': '70.48229'}
Epoch 66: 100%|██████████| 14/14 [00:01<00:00, 10.25it/s, v_num=57]Epoch 66: {'val_loss': '31.57445', 'train_loss': '68.11973'}
Epoch 67: 100%|██████████| 14/14 [00:01<00:00,  9.25it/s, v_num=57]Epoch 67: {'val_loss': '29.19870', 'train_loss': '70.41489'}
Epoch 68: 100%|██████████| 14/14 [00:01<00:00, 10.30it/s, v_num=57]Epoch 68: {'val_loss': '33.64514', 'train_loss': '68.04732'}
Epoch 69: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 69: {'val_loss': '29.67403', 'train_loss': '70.37194'}
Epoch 70: 100%|██████████| 14/14 [00:01<00:00, 10.37it/s, v_num=57]Epoch 70: {'val_loss': '30.24152', 'train_loss': '68.86510'}
Epoch 71: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=57]Epoch 71: {'val_loss': '29.54021', 'train_loss': '67.29088'}
Epoch 72: 100%|██████████| 14/14 [00:01<00:00,  8.78it/s, v_num=57]Epoch 72: {'val_loss': '31.06949', 'train_loss': '69.79566'}
Epoch 73: 100%|██████████| 14/14 [00:01<00:00,  9.83it/s, v_num=57]Epoch 73: {'val_loss': '28.53200', 'train_loss': '72.04407'}
Epoch 74: 100%|██████████| 14/14 [00:01<00:00, 10.35it/s, v_num=57]Epoch 74: {'val_loss': '29.51579', 'train_loss': '72.11969'}
Epoch 75: 100%|██████████| 14/14 [00:01<00:00, 10.28it/s, v_num=57]Epoch 75: {'val_loss': '28.53654', 'train_loss': '68.41970'}
Epoch 76: 100%|██████████| 14/14 [00:01<00:00, 10.33it/s, v_num=57]Epoch 76: {'val_loss': '29.62471', 'train_loss': '66.96675'}
Epoch 77: 100%|██████████| 14/14 [00:01<00:00,  9.18it/s, v_num=57]Epoch 77: {'val_loss': '32.53694', 'train_loss': '68.00204'}
Epoch 78: 100%|██████████| 14/14 [00:01<00:00, 10.32it/s, v_num=57]Epoch 78: {'val_loss': '29.24777', 'train_loss': '66.25647'}
Epoch 79: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 79: {'val_loss': '29.95617', 'train_loss': '66.57422'}
Epoch 80: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=57]Epoch 80: {'val_loss': '31.25793', 'train_loss': '67.84517'}
Epoch 81: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=57]Epoch 81: {'val_loss': '31.61016', 'train_loss': '68.03156'}
Epoch 82: 100%|██████████| 14/14 [00:01<00:00,  9.16it/s, v_num=57]Epoch 82: {'val_loss': '27.23992', 'train_loss': '68.84177'}
Epoch 83: 100%|██████████| 14/14 [00:01<00:00, 10.26it/s, v_num=57]Epoch 83: {'val_loss': '27.58205', 'train_loss': '68.17483'}
Epoch 84: 100%|██████████| 14/14 [00:01<00:00, 10.23it/s, v_num=57]Epoch 84: {'val_loss': '28.11297', 'train_loss': '71.14233'}
Epoch 85: 100%|██████████| 14/14 [00:01<00:00, 10.25it/s, v_num=57]Epoch 85: {'val_loss': '29.43740', 'train_loss': '69.41695'}
Epoch 86: 100%|██████████| 14/14 [00:01<00:00, 10.28it/s, v_num=57]Epoch 86: {'val_loss': '30.33367', 'train_loss': '68.97827'}
Epoch 87: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=57]Epoch 87: {'val_loss': '29.31621', 'train_loss': '63.90301'}
Epoch 88: 100%|██████████| 14/14 [00:01<00:00,  9.05it/s, v_num=57]Epoch 88: {'val_loss': '28.31551', 'train_loss': '68.29008'}
Epoch 89: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=57]Epoch 89: {'val_loss': '28.31699', 'train_loss': '65.71945'}
Epoch 90: 100%|██████████| 14/14 [00:01<00:00, 10.36it/s, v_num=57]Epoch 90: {'val_loss': '30.11443', 'train_loss': '72.56566'}
Epoch 91: 100%|██████████| 14/14 [00:01<00:00, 10.26it/s, v_num=57]Epoch 91: {'val_loss': '29.12468', 'train_loss': '65.78918'}
Epoch 92: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 92: {'val_loss': '27.47469', 'train_loss': '64.47198'}
Epoch 93: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=57]Epoch 93: {'val_loss': '27.57004', 'train_loss': '65.24070'}
Epoch 94: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=57]Epoch 94: {'val_loss': '28.30224', 'train_loss': '65.62695'}
Epoch 95: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=57]Epoch 95: {'val_loss': '27.76100', 'train_loss': '65.33922'}
Epoch 96: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 96: {'val_loss': '27.61066', 'train_loss': '67.38412'}
Epoch 97: 100%|██████████| 14/14 [00:01<00:00,  9.11it/s, v_num=57]Epoch 97: {'val_loss': '28.08641', 'train_loss': '65.21311'}
Epoch 98: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 98: {'val_loss': '27.76418', 'train_loss': '62.36259'}
Epoch 99: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=57]Epoch 99: {'val_loss': '27.77835', 'train_loss': '66.20309'}
Epoch 100: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=57]Epoch 100: {'val_loss': '27.16046', 'train_loss': '64.41499'}
Epoch 101: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 101: {'val_loss': '27.13166', 'train_loss': '66.18763'}
Epoch 102: 100%|██████████| 14/14 [00:01<00:00,  9.05it/s, v_num=57]Epoch 102: {'val_loss': '26.77605', 'train_loss': '66.31319'}
Epoch 103: 100%|██████████| 14/14 [00:01<00:00, 10.24it/s, v_num=57]Epoch 103: {'val_loss': '26.91846', 'train_loss': '67.27254'}
Epoch 104: 100%|██████████| 14/14 [00:01<00:00, 10.27it/s, v_num=57]Epoch 104: {'val_loss': '27.43259', 'train_loss': '67.79307'}
Epoch 105: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=57]Epoch 105: {'val_loss': '28.84295', 'train_loss': '67.09818'}
Epoch 106: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=57]Epoch 106: {'val_loss': '27.42390', 'train_loss': '67.78893'}
Epoch 107: 100%|██████████| 14/14 [00:01<00:00,  9.17it/s, v_num=57]Epoch 107: {'val_loss': '26.74588', 'train_loss': '68.69452'}
Epoch 108: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=57]Epoch 108: {'val_loss': '27.51947', 'train_loss': '64.71314'}
Epoch 109: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=57]Epoch 109: {'val_loss': '26.94527', 'train_loss': '63.22044'}
Epoch 110: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=57]Epoch 110: {'val_loss': '26.86791', 'train_loss': '61.22466'}
Epoch 111: 100%|██████████| 14/14 [00:01<00:00,  8.96it/s, v_num=57]Epoch 111: {'val_loss': '27.33037', 'train_loss': '60.76755'}
Epoch 112: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 112: {'val_loss': '27.25004', 'train_loss': '65.39796'}
Epoch 113: 100%|██████████| 14/14 [00:01<00:00, 10.29it/s, v_num=57]Epoch 113: {'val_loss': '26.98438', 'train_loss': '66.54579'}
Epoch 114: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=57]Epoch 114: {'val_loss': '27.08628', 'train_loss': '66.92358'}
Epoch 115: 100%|██████████| 14/14 [00:01<00:00,  9.11it/s, v_num=57]Epoch 115: {'val_loss': '27.55113', 'train_loss': '63.90577'}
Epoch 116: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 116: {'val_loss': '27.01959', 'train_loss': '63.64832'}
Epoch 117: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=57]Epoch 117: {'val_loss': '26.72658', 'train_loss': '64.91605'}
Epoch 118: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=57]Epoch 118: {'val_loss': '26.79632', 'train_loss': '69.51034'}
Epoch 119: 100%|██████████| 14/14 [00:01<00:00, 10.23it/s, v_num=57]Epoch 119: {'val_loss': '26.71158', 'train_loss': '67.86514'}
Epoch 120: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=57]Epoch 120: {'val_loss': '27.85557', 'train_loss': '63.42400'}
Epoch 121: 100%|██████████| 14/14 [00:01<00:00,  9.04it/s, v_num=57]Epoch 121: {'val_loss': '28.04553', 'train_loss': '65.13216'}
Epoch 122: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=57]Epoch 122: {'val_loss': '28.85010', 'train_loss': '65.32319'}
Epoch 123: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=57]Epoch 123: {'val_loss': '28.40117', 'train_loss': '65.13808'}
Epoch 124: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=57]Epoch 124: {'val_loss': '28.12783', 'train_loss': '61.41383'}
Epoch 125: 100%|██████████| 14/14 [00:01<00:00,  9.09it/s, v_num=57]Epoch 125: {'val_loss': '28.85651', 'train_loss': '66.75961'}
Epoch 126: 100%|██████████| 14/14 [00:01<00:00, 10.24it/s, v_num=57]Epoch 126: {'val_loss': '29.15815', 'train_loss': '66.25242'}
Epoch 127: 100%|██████████| 14/14 [00:01<00:00, 10.24it/s, v_num=57]Epoch 127: {'val_loss': '28.35915', 'train_loss': '67.16564'}
Epoch 128: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=57]Epoch 128: {'val_loss': '27.65538', 'train_loss': '64.06983'}
Epoch 129: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=57]Epoch 129: {'val_loss': '27.41572', 'train_loss': '64.38125'}
Epoch 130: 100%|██████████| 14/14 [00:01<00:00,  9.02it/s, v_num=57]Epoch 130: {'val_loss': '27.84090', 'train_loss': '64.64984'}
Epoch 131: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=57]Epoch 131: {'val_loss': '27.81603', 'train_loss': '65.30859'}
Epoch 132: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=57]Epoch 132: {'val_loss': '27.51328', 'train_loss': '64.13773'}
Epoch 133: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=57]Epoch 133: {'val_loss': '27.58871', 'train_loss': '67.17973'}
Epoch 134: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=57]Epoch 134: {'val_loss': '27.58241', 'train_loss': '65.65716'}
Epoch 135: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=57]Epoch 135: {'val_loss': '27.62045', 'train_loss': '64.06895'}
Epoch 136: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=57]Epoch 136: {'val_loss': '27.06711', 'train_loss': '56.87384'}
Epoch 137: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=57]Epoch 137: {'val_loss': '27.53396', 'train_loss': '68.05953'}
Epoch 138: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=57]Epoch 138: {'val_loss': '28.01320', 'train_loss': '71.36144'}
Epoch 139: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=57]Epoch 139: {'val_loss': '27.52936', 'train_loss': '63.78895'}
Epoch 140: 100%|██████████| 14/14 [00:01<00:00,  9.04it/s, v_num=57]Epoch 140: {'val_loss': '27.87624', 'train_loss': '64.94374'}
Epoch 141: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=57]Epoch 141: {'val_loss': '27.41034', 'train_loss': '68.63902'}
Epoch 142: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=57]Epoch 142: {'val_loss': '27.17928', 'train_loss': '59.06187'}
Epoch 143: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=57]Epoch 143: {'val_loss': '27.54093', 'train_loss': '68.93397'}
Epoch 144: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=57]Epoch 144: {'val_loss': '27.35178', 'train_loss': '64.65952'}
Epoch 145: 100%|██████████| 14/14 [00:01<00:00,  9.01it/s, v_num=57]Epoch 145: {'val_loss': '27.37538', 'train_loss': '60.75130'}
Epoch 146: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=57]Epoch 146: {'val_loss': '26.92934', 'train_loss': '62.29918'}
Epoch 147: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=57]Epoch 147: {'val_loss': '27.22025', 'train_loss': '63.92125'}
Epoch 148: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=57]Epoch 148: {'val_loss': '28.12185', 'train_loss': '63.83680'}
Epoch 149: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=57]Epoch 149: {'val_loss': '27.20126', 'train_loss': '64.43536'}
Epoch 150: 100%|██████████| 14/14 [00:01<00:00,  9.16it/s, v_num=57]Epoch 150: {'val_loss': '27.63305', 'train_loss': '68.33420'}
Epoch 151: 100%|██████████| 14/14 [00:01<00:00, 10.25it/s, v_num=57]Epoch 151: {'val_loss': '27.58339', 'train_loss': '59.00162'}
Epoch 152: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=57]Epoch 152: {'val_loss': '27.50307', 'train_loss': '69.63114'}
Epoch 153: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=57]Epoch 153: {'val_loss': '27.71290', 'train_loss': '66.31990'}
Epoch 154: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=57]Epoch 154: {'val_loss': '27.46642', 'train_loss': '70.27926'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (14) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=58]Epoch 0: {'val_loss': '2519.18604', 'train_loss': '378.58197'}
Epoch 1: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 1: {'val_loss': '276.72614', 'train_loss': '155.60144'}
Epoch 2: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=58]Epoch 2: {'val_loss': '61.81316', 'train_loss': '123.70403'}
Epoch 3: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=58]Epoch 3: {'val_loss': '44.37792', 'train_loss': '121.65049'}
Epoch 4: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 4: {'val_loss': '49.57779', 'train_loss': '106.90753'}
Epoch 5: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 5: {'val_loss': '58.59566', 'train_loss': '113.92281'}
Epoch 6: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=58]Epoch 6: {'val_loss': '61.47719', 'train_loss': '112.79993'}
Epoch 7: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=58]Epoch 7: {'val_loss': '66.98676', 'train_loss': '116.41766'}
Epoch 8: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=58]Epoch 8: {'val_loss': '49.44812', 'train_loss': '109.43414'}
Epoch 9: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=58]Epoch 9: {'val_loss': '39.01001', 'train_loss': '106.98414'}
Epoch 10: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 10: {'val_loss': '39.06642', 'train_loss': '102.08160'}
Epoch 11: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 11: {'val_loss': '60.02137', 'train_loss': '103.79939'}
Epoch 12: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=58]Epoch 12: {'val_loss': '38.23285', 'train_loss': '95.57235'}
Epoch 13: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 13: {'val_loss': '43.61714', 'train_loss': '98.92694'}
Epoch 14: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=58]Epoch 14: {'val_loss': '46.63395', 'train_loss': '96.65295'}
Epoch 15: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=58]Epoch 15: {'val_loss': '40.45094', 'train_loss': '119.45472'}
Epoch 16: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 16: {'val_loss': '37.63823', 'train_loss': '112.87791'}
Epoch 17: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=58]Epoch 17: {'val_loss': '62.08576', 'train_loss': '97.80870'}
Epoch 18: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 18: {'val_loss': '46.90086', 'train_loss': '95.56837'}
Epoch 19: 100%|██████████| 14/14 [00:01<00:00,  8.96it/s, v_num=58]Epoch 19: {'val_loss': '50.37736', 'train_loss': '93.65496'}
Epoch 20: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=58]Epoch 20: {'val_loss': '34.04181', 'train_loss': '102.75094'}
Epoch 21: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 21: {'val_loss': '37.58809', 'train_loss': '96.56170'}
Epoch 22: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 22: {'val_loss': '38.31811', 'train_loss': '109.68285'}
Epoch 23: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=58]Epoch 23: {'val_loss': '38.93450', 'train_loss': '106.04423'}
Epoch 24: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 24: {'val_loss': '34.47712', 'train_loss': '93.69755'}
Epoch 25: 100%|██████████| 14/14 [00:01<00:00,  9.81it/s, v_num=58]Epoch 25: {'val_loss': '41.73130', 'train_loss': '94.62080'}
Epoch 26: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=58]Epoch 26: {'val_loss': '55.32113', 'train_loss': '97.86196'}
Epoch 27: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=58]Epoch 27: {'val_loss': '37.73623', 'train_loss': '101.65880'}
Epoch 28: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=58]Epoch 28: {'val_loss': '48.98493', 'train_loss': '92.01646'}
Epoch 29: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=58]Epoch 29: {'val_loss': '34.99044', 'train_loss': '90.49593'}
Epoch 30: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=58]Epoch 30: {'val_loss': '34.33718', 'train_loss': '87.42313'}
Epoch 31: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=58]Epoch 31: {'val_loss': '37.01465', 'train_loss': '88.26940'}
Epoch 32: 100%|██████████| 14/14 [00:01<00:00,  9.03it/s, v_num=58]Epoch 32: {'val_loss': '46.24442', 'train_loss': '93.65969'}
Epoch 33: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 33: {'val_loss': '33.94917', 'train_loss': '79.75835'}
Epoch 34: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 34: {'val_loss': '35.63521', 'train_loss': '76.12065'}
Epoch 35: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 35: {'val_loss': '35.19118', 'train_loss': '83.66165'}
Epoch 36: 100%|██████████| 14/14 [00:01<00:00,  8.87it/s, v_num=58]Epoch 36: {'val_loss': '35.56460', 'train_loss': '87.43134'}
Epoch 37: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=58]Epoch 37: {'val_loss': '34.07641', 'train_loss': '79.27582'}
Epoch 38: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 38: {'val_loss': '34.10943', 'train_loss': '79.52747'}
Epoch 39: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=58]Epoch 39: {'val_loss': '33.44347', 'train_loss': '78.44414'}
Epoch 40: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 40: {'val_loss': '38.05729', 'train_loss': '74.77953'}
Epoch 41: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=58]Epoch 41: {'val_loss': '38.33889', 'train_loss': '77.93684'}
Epoch 42: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=58]Epoch 42: {'val_loss': '33.38103', 'train_loss': '80.20721'}
Epoch 43: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=58]Epoch 43: {'val_loss': '35.55666', 'train_loss': '81.87341'}
Epoch 44: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 44: {'val_loss': '35.94644', 'train_loss': '73.83031'}
Epoch 45: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=58]Epoch 45: {'val_loss': '37.73469', 'train_loss': '81.27117'}
Epoch 46: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=58]Epoch 46: {'val_loss': '31.30878', 'train_loss': '78.50661'}
Epoch 47: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=58]Epoch 47: {'val_loss': '32.80764', 'train_loss': '71.30432'}
Epoch 48: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=58]Epoch 48: {'val_loss': '35.09130', 'train_loss': '78.41720'}
Epoch 49: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=58]Epoch 49: {'val_loss': '31.60522', 'train_loss': '75.01555'}
Epoch 50: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=58]Epoch 50: {'val_loss': '41.37776', 'train_loss': '80.69968'}
Epoch 51: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 51: {'val_loss': '31.72828', 'train_loss': '85.95572'}
Epoch 52: 100%|██████████| 14/14 [00:01<00:00,  8.96it/s, v_num=58]Epoch 52: {'val_loss': '32.74498', 'train_loss': '72.24480'}
Epoch 53: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=58]Epoch 53: {'val_loss': '32.62829', 'train_loss': '72.32020'}
Epoch 54: 100%|██████████| 14/14 [00:01<00:00,  9.78it/s, v_num=58]Epoch 54: {'val_loss': '32.68091', 'train_loss': '70.50328'}
Epoch 55: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 55: {'val_loss': '31.51661', 'train_loss': '73.06120'}
Epoch 56: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=58]Epoch 56: {'val_loss': '32.37132', 'train_loss': '74.46404'}
Epoch 57: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=58]Epoch 57: {'val_loss': '34.32108', 'train_loss': '75.81577'}
Epoch 58: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 58: {'val_loss': '35.22630', 'train_loss': '71.48550'}
Epoch 59: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=58]Epoch 59: {'val_loss': '32.86468', 'train_loss': '72.51973'}
Epoch 60: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=58]Epoch 60: {'val_loss': '35.63674', 'train_loss': '70.11047'}
Epoch 61: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=58]Epoch 61: {'val_loss': '31.32215', 'train_loss': '68.60168'}
Epoch 62: 100%|██████████| 14/14 [00:01<00:00,  9.86it/s, v_num=58]Epoch 62: {'val_loss': '31.20785', 'train_loss': '70.90697'}
Epoch 63: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 63: {'val_loss': '31.40222', 'train_loss': '66.58826'}
Epoch 64: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=58]Epoch 64: {'val_loss': '31.16493', 'train_loss': '64.65032'}
Epoch 65: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 65: {'val_loss': '31.69556', 'train_loss': '70.94060'}
Epoch 66: 100%|██████████| 14/14 [00:01<00:00,  8.91it/s, v_num=58]Epoch 66: {'val_loss': '35.72385', 'train_loss': '75.56461'}
Epoch 67: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=58]Epoch 67: {'val_loss': '31.04544', 'train_loss': '75.03969'}
Epoch 68: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=58]Epoch 68: {'val_loss': '33.58520', 'train_loss': '74.89425'}
Epoch 69: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 69: {'val_loss': '28.73214', 'train_loss': '73.23451'}
Epoch 70: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=58]Epoch 70: {'val_loss': '29.86269', 'train_loss': '67.04691'}
Epoch 71: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=58]Epoch 71: {'val_loss': '30.95814', 'train_loss': '71.36043'}
Epoch 72: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=58]Epoch 72: {'val_loss': '30.07043', 'train_loss': '69.57224'}
Epoch 73: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=58]Epoch 73: {'val_loss': '29.19908', 'train_loss': '75.80548'}
Epoch 74: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=58]Epoch 74: {'val_loss': '29.01138', 'train_loss': '71.10497'}
Epoch 75: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 75: {'val_loss': '30.01837', 'train_loss': '69.49712'}
Epoch 76: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=58]Epoch 76: {'val_loss': '31.27381', 'train_loss': '67.76031'}
Epoch 77: 100%|██████████| 14/14 [00:01<00:00,  8.87it/s, v_num=58]Epoch 77: {'val_loss': '29.85295', 'train_loss': '66.04875'}
Epoch 78: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=58]Epoch 78: {'val_loss': '28.68060', 'train_loss': '67.12264'}
Epoch 79: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 79: {'val_loss': '28.21516', 'train_loss': '68.93076'}
Epoch 80: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=58]Epoch 80: {'val_loss': '29.88665', 'train_loss': '67.61510'}
Epoch 81: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=58]Epoch 81: {'val_loss': '29.93908', 'train_loss': '64.00843'}
Epoch 82: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=58]Epoch 82: {'val_loss': '28.86860', 'train_loss': '69.12149'}
Epoch 83: 100%|██████████| 14/14 [00:01<00:00,  8.95it/s, v_num=58]Epoch 83: {'val_loss': '29.20840', 'train_loss': '63.70673'}
Epoch 84: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 84: {'val_loss': '29.34836', 'train_loss': '75.30544'}
Epoch 85: 100%|██████████| 14/14 [00:01<00:00, 10.24it/s, v_num=58]Epoch 85: {'val_loss': '28.55492', 'train_loss': '67.59787'}
Epoch 86: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=58]Epoch 86: {'val_loss': '29.59171', 'train_loss': '69.24733'}
Epoch 87: 100%|██████████| 14/14 [00:01<00:00,  9.14it/s, v_num=58]Epoch 87: {'val_loss': '28.43702', 'train_loss': '68.24293'}
Epoch 88: 100%|██████████| 14/14 [00:01<00:00, 10.27it/s, v_num=58]Epoch 88: {'val_loss': '28.44985', 'train_loss': '64.49053'}
Epoch 89: 100%|██████████| 14/14 [00:01<00:00, 10.22it/s, v_num=58]Epoch 89: {'val_loss': '27.94199', 'train_loss': '66.64521'}
Epoch 90: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=58]Epoch 90: {'val_loss': '28.23572', 'train_loss': '67.80072'}
Epoch 91: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=58]Epoch 91: {'val_loss': '28.64465', 'train_loss': '68.86992'}
Epoch 92: 100%|██████████| 14/14 [00:01<00:00,  9.08it/s, v_num=58]Epoch 92: {'val_loss': '28.32640', 'train_loss': '61.63162'}
Epoch 93: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=58]Epoch 93: {'val_loss': '28.25473', 'train_loss': '66.48971'}
Epoch 94: 100%|██████████| 14/14 [00:01<00:00, 10.23it/s, v_num=58]Epoch 94: {'val_loss': '28.49395', 'train_loss': '72.72360'}
Epoch 95: 100%|██████████| 14/14 [00:01<00:00, 10.27it/s, v_num=58]Epoch 95: {'val_loss': '28.45521', 'train_loss': '77.46236'}
Epoch 96: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 96: {'val_loss': '29.12432', 'train_loss': '65.75053'}
Epoch 97: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=58]Epoch 97: {'val_loss': '29.15163', 'train_loss': '71.51339'}
Epoch 98: 100%|██████████| 14/14 [00:01<00:00,  9.04it/s, v_num=58]Epoch 98: {'val_loss': '27.99466', 'train_loss': '60.41509'}
Epoch 99: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=58]Epoch 99: {'val_loss': '27.74860', 'train_loss': '81.20812'}
Epoch 100: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=58]Epoch 100: {'val_loss': '28.07184', 'train_loss': '63.57911'}
Epoch 101: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=58]Epoch 101: {'val_loss': '28.30806', 'train_loss': '66.63000'}
Epoch 102: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 102: {'val_loss': '28.60732', 'train_loss': '63.98351'}
Epoch 103: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=58]Epoch 103: {'val_loss': '28.39043', 'train_loss': '61.09876'}
Epoch 104: 100%|██████████| 14/14 [00:01<00:00,  9.07it/s, v_num=58]Epoch 104: {'val_loss': '28.61811', 'train_loss': '65.30135'}
Epoch 105: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=58]Epoch 105: {'val_loss': '28.89742', 'train_loss': '64.15513'}
Epoch 106: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 106: {'val_loss': '28.05070', 'train_loss': '63.80989'}
Epoch 107: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=58]Epoch 107: {'val_loss': '27.99628', 'train_loss': '65.30527'}
Epoch 108: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 108: {'val_loss': '27.93243', 'train_loss': '66.87547'}
Epoch 109: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 109: {'val_loss': '27.74472', 'train_loss': '67.05532'}
Epoch 110: 100%|██████████| 14/14 [00:01<00:00,  9.09it/s, v_num=58]Epoch 110: {'val_loss': '28.25165', 'train_loss': '67.31551'}
Epoch 111: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=58]Epoch 111: {'val_loss': '27.94347', 'train_loss': '62.01569'}
Epoch 112: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 112: {'val_loss': '28.23240', 'train_loss': '66.69950'}
Epoch 113: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 113: {'val_loss': '27.77288', 'train_loss': '70.97182'}
Epoch 114: 100%|██████████| 14/14 [00:01<00:00,  9.17it/s, v_num=58]Epoch 114: {'val_loss': '28.07584', 'train_loss': '63.70088'}
Epoch 115: 100%|██████████| 14/14 [00:01<00:00, 10.23it/s, v_num=58]Epoch 115: {'val_loss': '28.08475', 'train_loss': '71.81197'}
Epoch 116: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=58]Epoch 116: {'val_loss': '27.87399', 'train_loss': '64.89108'}
Epoch 117: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=58]Epoch 117: {'val_loss': '27.64986', 'train_loss': '67.94637'}
Epoch 118: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=58]Epoch 118: {'val_loss': '27.76359', 'train_loss': '64.42702'}
Epoch 119: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=58]Epoch 119: {'val_loss': '27.77632', 'train_loss': '69.47541'}
Epoch 120: 100%|██████████| 14/14 [00:01<00:00,  9.09it/s, v_num=58]Epoch 120: {'val_loss': '28.72674', 'train_loss': '63.94526'}
Epoch 121: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=58]Epoch 121: {'val_loss': '27.94168', 'train_loss': '64.76486'}
Epoch 122: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=58]Epoch 122: {'val_loss': '27.78651', 'train_loss': '68.18439'}
Epoch 123: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=58]Epoch 123: {'val_loss': '27.89996', 'train_loss': '73.81145'}
Epoch 124: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 124: {'val_loss': '27.73308', 'train_loss': '65.86656'}
Epoch 125: 100%|██████████| 14/14 [00:01<00:00, 10.24it/s, v_num=58]Epoch 125: {'val_loss': '27.90961', 'train_loss': '63.56004'}
Epoch 126: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=58]Epoch 126: {'val_loss': '28.97602', 'train_loss': '65.90797'}
Epoch 127: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 127: {'val_loss': '28.73176', 'train_loss': '69.18870'}
Epoch 128: 100%|██████████| 14/14 [00:01<00:00,  9.13it/s, v_num=58]Epoch 128: {'val_loss': '28.22963', 'train_loss': '62.53973'}
Epoch 129: 100%|██████████| 14/14 [00:01<00:00, 10.21it/s, v_num=58]Epoch 129: {'val_loss': '28.54176', 'train_loss': '71.77805'}
Epoch 130: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=58]Epoch 130: {'val_loss': '28.32664', 'train_loss': '62.47974'}
Epoch 131: 100%|██████████| 14/14 [00:01<00:00, 10.20it/s, v_num=58]Epoch 131: {'val_loss': '28.36417', 'train_loss': '65.32619'}
Epoch 132: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 132: {'val_loss': '27.95641', 'train_loss': '62.61955'}
Epoch 133: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=58]Epoch 133: {'val_loss': '27.86476', 'train_loss': '66.02551'}
Epoch 134: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=58]Epoch 134: {'val_loss': '28.68612', 'train_loss': '65.93787'}
Epoch 135: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=58]Epoch 135: {'val_loss': '29.04195', 'train_loss': '64.54410'}
Epoch 136: 100%|██████████| 14/14 [00:01<00:00,  9.09it/s, v_num=58]Epoch 136: {'val_loss': '28.20176', 'train_loss': '62.26540'}
Epoch 137: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=58]Epoch 137: {'val_loss': '28.49621', 'train_loss': '66.37460'}
Epoch 138: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=58]Epoch 138: {'val_loss': '28.10958', 'train_loss': '66.06277'}
Epoch 139: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 139: {'val_loss': '28.12188', 'train_loss': '64.88440'}
Epoch 140: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=58]Epoch 140: {'val_loss': '28.57252', 'train_loss': '70.36511'}
Epoch 141: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=58]Epoch 141: {'val_loss': '28.92810', 'train_loss': '63.84065'}
Epoch 142: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 142: {'val_loss': '28.55514', 'train_loss': '70.14833'}
Epoch 143: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=58]Epoch 143: {'val_loss': '28.18003', 'train_loss': '65.89284'}
Epoch 144: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=58]Epoch 144: {'val_loss': '28.21901', 'train_loss': '65.54860'}
Epoch 145: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=58]Epoch 145: {'val_loss': '27.98005', 'train_loss': '61.47440'}
Epoch 146: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=58]Epoch 146: {'val_loss': '28.10417', 'train_loss': '63.95116'}
Epoch 147: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=58]Epoch 147: {'val_loss': '28.41354', 'train_loss': '60.62339'}
Epoch 148: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=58]Epoch 148: {'val_loss': '28.22926', 'train_loss': '67.60985'}
Epoch 149: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=58]Epoch 149: {'val_loss': '27.91107', 'train_loss': '70.46252'}
Epoch 150: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=58]Epoch 150: {'val_loss': '28.77600', 'train_loss': '64.37205'}
Epoch 151: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=58]Epoch 151: {'val_loss': '28.01642', 'train_loss': '64.91997'}
Epoch 152: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=58]Epoch 152: {'val_loss': '27.73529', 'train_loss': '62.55812'}
Epoch 153: 100%|██████████| 14/14 [00:01<00:00, 10.19it/s, v_num=58]Epoch 153: {'val_loss': '28.06485', 'train_loss': '66.08259'}
Epoch 154: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=58]Epoch 154: {'val_loss': '28.12387', 'train_loss': '67.36610'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (14) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 14/14 [00:01<00:00,  9.02it/s, v_num=59]Epoch 0: {'val_loss': '7825.32666', 'train_loss': '379.06119'}
Epoch 1: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 1: {'val_loss': '616.76782', 'train_loss': '140.88916'}
Epoch 2: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=59]Epoch 2: {'val_loss': '105.10248', 'train_loss': '132.90311'}
Epoch 3: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=59]Epoch 3: {'val_loss': '37.70323', 'train_loss': '106.58809'}
Epoch 4: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=59]Epoch 4: {'val_loss': '39.69759', 'train_loss': '114.26229'}
Epoch 5: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=59]Epoch 5: {'val_loss': '39.59571', 'train_loss': '107.60709'}
Epoch 6: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 6: {'val_loss': '46.51904', 'train_loss': '105.71626'}
Epoch 7: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=59]Epoch 7: {'val_loss': '40.59371', 'train_loss': '112.24174'}
Epoch 8: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=59]Epoch 8: {'val_loss': '76.71389', 'train_loss': '102.41862'}
Epoch 9: 100%|██████████| 14/14 [00:01<00:00,  9.12it/s, v_num=59]Epoch 9: {'val_loss': '229.61617', 'train_loss': '109.28839'}
Epoch 10: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 10: {'val_loss': '45.30780', 'train_loss': '113.99036'}
Epoch 11: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 11: {'val_loss': '35.25351', 'train_loss': '105.85346'}
Epoch 12: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=59]Epoch 12: {'val_loss': '36.14703', 'train_loss': '93.35034'}
Epoch 13: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=59]Epoch 13: {'val_loss': '35.23337', 'train_loss': '87.42047'}
Epoch 14: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=59]Epoch 14: {'val_loss': '51.91919', 'train_loss': '101.52189'}
Epoch 15: 100%|██████████| 14/14 [00:01<00:00,  9.51it/s, v_num=59]Epoch 15: {'val_loss': '42.95166', 'train_loss': '90.98610'}
Epoch 16: 100%|██████████| 14/14 [00:01<00:00,  8.84it/s, v_num=59]Epoch 16: {'val_loss': '34.08210', 'train_loss': '95.09280'}
Epoch 17: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 17: {'val_loss': '45.22912', 'train_loss': '92.37647'}
Epoch 18: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=59]Epoch 18: {'val_loss': '45.19779', 'train_loss': '88.28966'}
Epoch 19: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=59]Epoch 19: {'val_loss': '33.48673', 'train_loss': '87.65148'}
Epoch 20: 100%|██████████| 14/14 [00:01<00:00, 10.15it/s, v_num=59]Epoch 20: {'val_loss': '37.36852', 'train_loss': '90.83551'}
Epoch 21: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=59]Epoch 21: {'val_loss': '40.89656', 'train_loss': '87.55685'}
Epoch 22: 100%|██████████| 14/14 [00:01<00:00,  9.05it/s, v_num=59]Epoch 22: {'val_loss': '35.66207', 'train_loss': '96.65332'}
Epoch 23: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=59]Epoch 23: {'val_loss': '44.54692', 'train_loss': '95.54925'}
Epoch 24: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=59]Epoch 24: {'val_loss': '87.59473', 'train_loss': '97.53076'}
Epoch 25: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=59]Epoch 25: {'val_loss': '38.94485', 'train_loss': '87.55518'}
Epoch 26: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=59]Epoch 26: {'val_loss': '32.50774', 'train_loss': '84.11536'}
Epoch 27: 100%|██████████| 14/14 [00:01<00:00,  8.99it/s, v_num=59]Epoch 27: {'val_loss': '35.65953', 'train_loss': '82.31269'}
Epoch 28: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=59]Epoch 28: {'val_loss': '31.89101', 'train_loss': '85.10894'}
Epoch 29: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=59]Epoch 29: {'val_loss': '34.41915', 'train_loss': '85.32277'}
Epoch 30: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 30: {'val_loss': '32.50375', 'train_loss': '88.86300'}
Epoch 31: 100%|██████████| 14/14 [00:01<00:00,  9.03it/s, v_num=59]Epoch 31: {'val_loss': '30.90373', 'train_loss': '79.62470'}
Epoch 32: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=59]Epoch 32: {'val_loss': '34.69503', 'train_loss': '77.15789'}
Epoch 33: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 33: {'val_loss': '31.14616', 'train_loss': '91.51112'}
Epoch 34: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=59]Epoch 34: {'val_loss': '32.52491', 'train_loss': '81.17754'}
Epoch 35: 100%|██████████| 14/14 [00:01<00:00,  9.08it/s, v_num=59]Epoch 35: {'val_loss': '30.62345', 'train_loss': '85.03313'}
Epoch 36: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 36: {'val_loss': '31.43953', 'train_loss': '77.76958'}
Epoch 37: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 37: {'val_loss': '29.89040', 'train_loss': '81.04745'}
Epoch 38: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=59]Epoch 38: {'val_loss': '29.02562', 'train_loss': '76.86642'}
Epoch 39: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=59]Epoch 39: {'val_loss': '30.21891', 'train_loss': '81.92861'}
Epoch 40: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=59]Epoch 40: {'val_loss': '39.94684', 'train_loss': '84.92289'}
Epoch 41: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=59]Epoch 41: {'val_loss': '31.10607', 'train_loss': '79.91271'}
Epoch 42: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 42: {'val_loss': '31.68486', 'train_loss': '72.41050'}
Epoch 43: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 43: {'val_loss': '30.27577', 'train_loss': '72.14919'}
Epoch 44: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 44: {'val_loss': '31.24524', 'train_loss': '73.48596'}
Epoch 45: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 45: {'val_loss': '33.22556', 'train_loss': '71.35659'}
Epoch 46: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 46: {'val_loss': '28.62085', 'train_loss': '75.42015'}
Epoch 47: 100%|██████████| 14/14 [00:01<00:00,  8.89it/s, v_num=59]Epoch 47: {'val_loss': '29.98882', 'train_loss': '73.29832'}
Epoch 48: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 48: {'val_loss': '28.16753', 'train_loss': '76.48233'}
Epoch 49: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 49: {'val_loss': '28.43262', 'train_loss': '74.50542'}
Epoch 50: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=59]Epoch 50: {'val_loss': '29.74884', 'train_loss': '71.94164'}
Epoch 51: 100%|██████████| 14/14 [00:01<00:00,  9.06it/s, v_num=59]Epoch 51: {'val_loss': '30.15174', 'train_loss': '73.24580'}
Epoch 52: 100%|██████████| 14/14 [00:01<00:00, 10.16it/s, v_num=59]Epoch 52: {'val_loss': '29.05899', 'train_loss': '70.95140'}
Epoch 53: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 53: {'val_loss': '28.20758', 'train_loss': '69.43292'}
Epoch 54: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 54: {'val_loss': '27.97833', 'train_loss': '66.96078'}
Epoch 55: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 55: {'val_loss': '28.20027', 'train_loss': '70.01464'}
Epoch 56: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=59]Epoch 56: {'val_loss': '27.23862', 'train_loss': '73.80463'}
Epoch 57: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 57: {'val_loss': '35.07520', 'train_loss': '69.41657'}
Epoch 58: 100%|██████████| 14/14 [00:01<00:00,  9.03it/s, v_num=59]Epoch 58: {'val_loss': '28.09272', 'train_loss': '67.85623'}
Epoch 59: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=59]Epoch 59: {'val_loss': '27.86668', 'train_loss': '70.54963'}
Epoch 60: 100%|██████████| 14/14 [00:01<00:00, 10.11it/s, v_num=59]Epoch 60: {'val_loss': '27.24839', 'train_loss': '68.96887'}
Epoch 61: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=59]Epoch 61: {'val_loss': '32.14641', 'train_loss': '68.01151'}
Epoch 62: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 62: {'val_loss': '26.71283', 'train_loss': '65.87424'}
Epoch 63: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 63: {'val_loss': '31.12879', 'train_loss': '75.98814'}
Epoch 64: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=59]Epoch 64: {'val_loss': '28.00598', 'train_loss': '65.71610'}
Epoch 65: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 65: {'val_loss': '26.44267', 'train_loss': '71.89726'}
Epoch 66: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=59]Epoch 66: {'val_loss': '27.21776', 'train_loss': '63.11961'}
Epoch 67: 100%|██████████| 14/14 [00:01<00:00,  9.03it/s, v_num=59]Epoch 67: {'val_loss': '27.32635', 'train_loss': '75.95867'}
Epoch 68: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 68: {'val_loss': '26.62190', 'train_loss': '71.15842'}
Epoch 69: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 69: {'val_loss': '28.18799', 'train_loss': '70.75368'}
Epoch 70: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=59]Epoch 70: {'val_loss': '31.42761', 'train_loss': '65.12416'}
Epoch 71: 100%|██████████| 14/14 [00:01<00:00, 10.12it/s, v_num=59]Epoch 71: {'val_loss': '29.49804', 'train_loss': '67.53032'}
Epoch 72: 100%|██████████| 14/14 [00:01<00:00,  8.95it/s, v_num=59]Epoch 72: {'val_loss': '26.10550', 'train_loss': '68.30997'}
Epoch 73: 100%|██████████| 14/14 [00:01<00:00, 10.18it/s, v_num=59]Epoch 73: {'val_loss': '27.24015', 'train_loss': '62.11712'}
Epoch 74: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 74: {'val_loss': '26.19605', 'train_loss': '61.29354'}
Epoch 75: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=59]Epoch 75: {'val_loss': '27.80076', 'train_loss': '63.53601'}
Epoch 76: 100%|██████████| 14/14 [00:01<00:00,  8.97it/s, v_num=59]Epoch 76: {'val_loss': '28.67549', 'train_loss': '64.91599'}
Epoch 77: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 77: {'val_loss': '25.98361', 'train_loss': '62.67651'}
Epoch 78: 100%|██████████| 14/14 [00:01<00:00,  9.75it/s, v_num=59]Epoch 78: {'val_loss': '26.67444', 'train_loss': '62.07236'}
Epoch 79: 100%|██████████| 14/14 [00:01<00:00,  9.73it/s, v_num=59]Epoch 79: {'val_loss': '24.78610', 'train_loss': '67.79465'}
Epoch 80: 100%|██████████| 14/14 [00:01<00:00,  9.66it/s, v_num=59]Epoch 80: {'val_loss': '25.86136', 'train_loss': '67.61920'}
Epoch 81: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 81: {'val_loss': '25.78507', 'train_loss': '62.44962'}
Epoch 82: 100%|██████████| 14/14 [00:01<00:00,  9.04it/s, v_num=59]Epoch 82: {'val_loss': '25.69711', 'train_loss': '63.76124'}
Epoch 83: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 83: {'val_loss': '26.06348', 'train_loss': '63.94875'}
Epoch 84: 100%|██████████| 14/14 [00:01<00:00, 10.10it/s, v_num=59]Epoch 84: {'val_loss': '26.45682', 'train_loss': '65.39902'}
Epoch 85: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=59]Epoch 85: {'val_loss': '25.38155', 'train_loss': '65.27607'}
Epoch 86: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=59]Epoch 86: {'val_loss': '25.03413', 'train_loss': '60.72481'}
Epoch 87: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 87: {'val_loss': '25.57181', 'train_loss': '66.73739'}
Epoch 88: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=59]Epoch 88: {'val_loss': '25.94778', 'train_loss': '62.42419'}
Epoch 89: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 89: {'val_loss': '25.00108', 'train_loss': '71.77708'}
Epoch 90: 100%|██████████| 14/14 [00:01<00:00,  8.96it/s, v_num=59]Epoch 90: {'val_loss': '24.70666', 'train_loss': '58.51647'}
Epoch 91: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 91: {'val_loss': '27.18927', 'train_loss': '62.09874'}
Epoch 92: 100%|██████████| 14/14 [00:01<00:00, 10.17it/s, v_num=59]Epoch 92: {'val_loss': '24.67804', 'train_loss': '60.48358'}
Epoch 93: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=59]Epoch 93: {'val_loss': '25.09349', 'train_loss': '61.07214'}
Epoch 94: 100%|██████████| 14/14 [00:01<00:00,  9.86it/s, v_num=59]Epoch 94: {'val_loss': '26.28532', 'train_loss': '62.69410'}
Epoch 95: 100%|██████████| 14/14 [00:01<00:00,  8.95it/s, v_num=59]Epoch 95: {'val_loss': '24.65687', 'train_loss': '62.75053'}
Epoch 96: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 96: {'val_loss': '24.84336', 'train_loss': '58.84601'}
Epoch 97: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=59]Epoch 97: {'val_loss': '24.84191', 'train_loss': '63.80659'}
Epoch 98: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=59]Epoch 98: {'val_loss': '24.51521', 'train_loss': '57.80984'}
Epoch 99: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=59]Epoch 99: {'val_loss': '25.09203', 'train_loss': '61.55922'}
Epoch 100: 100%|██████████| 14/14 [00:01<00:00,  9.78it/s, v_num=59]Epoch 100: {'val_loss': '24.79475', 'train_loss': '62.10350'}
Epoch 101: 100%|██████████| 14/14 [00:01<00:00,  8.98it/s, v_num=59]Epoch 101: {'val_loss': '25.53626', 'train_loss': '66.21909'}
Epoch 102: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 102: {'val_loss': '25.55244', 'train_loss': '58.93379'}
Epoch 103: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 103: {'val_loss': '25.40242', 'train_loss': '63.92273'}
Epoch 104: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=59]Epoch 104: {'val_loss': '24.44235', 'train_loss': '62.12775'}
Epoch 105: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 105: {'val_loss': '24.35374', 'train_loss': '64.78801'}
Epoch 106: 100%|██████████| 14/14 [00:01<00:00,  9.86it/s, v_num=59]Epoch 106: {'val_loss': '27.74044', 'train_loss': '61.71986'}
Epoch 107: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 107: {'val_loss': '23.92636', 'train_loss': '60.96949'}
Epoch 108: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 108: {'val_loss': '24.07599', 'train_loss': '64.13586'}
Epoch 109: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 109: {'val_loss': '24.17797', 'train_loss': '61.75963'}
Epoch 110: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 110: {'val_loss': '23.84828', 'train_loss': '61.26184'}
Epoch 111: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=59]Epoch 111: {'val_loss': '24.22856', 'train_loss': '58.78784'}
Epoch 112: 100%|██████████| 14/14 [00:01<00:00,  9.84it/s, v_num=59]Epoch 112: {'val_loss': '24.77449', 'train_loss': '58.20533'}
Epoch 113: 100%|██████████| 14/14 [00:01<00:00,  8.88it/s, v_num=59]Epoch 113: {'val_loss': '23.81202', 'train_loss': '65.71875'}
Epoch 114: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=59]Epoch 114: {'val_loss': '25.76081', 'train_loss': '66.38302'}
Epoch 115: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=59]Epoch 115: {'val_loss': '24.05863', 'train_loss': '64.33990'}
Epoch 116: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 116: {'val_loss': '23.18609', 'train_loss': '59.00741'}
Epoch 117: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 117: {'val_loss': '23.96804', 'train_loss': '59.35124'}
Epoch 118: 100%|██████████| 14/14 [00:01<00:00,  9.86it/s, v_num=59]Epoch 118: {'val_loss': '23.72627', 'train_loss': '58.54608'}
Epoch 119: 100%|██████████| 14/14 [00:01<00:00, 10.14it/s, v_num=59]Epoch 119: {'val_loss': '25.49809', 'train_loss': '62.35121'}
Epoch 120: 100%|██████████| 14/14 [00:01<00:00, 10.09it/s, v_num=59]Epoch 120: {'val_loss': '23.58340', 'train_loss': '66.17382'}
Epoch 121: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=59]Epoch 121: {'val_loss': '23.24216', 'train_loss': '59.75468'}
Epoch 122: 100%|██████████| 14/14 [00:01<00:00,  8.97it/s, v_num=59]Epoch 122: {'val_loss': '23.57703', 'train_loss': '61.23315'}
Epoch 123: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 123: {'val_loss': '23.75362', 'train_loss': '53.67693'}
Epoch 124: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=59]Epoch 124: {'val_loss': '23.28861', 'train_loss': '57.46169'}
Epoch 125: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=59]Epoch 125: {'val_loss': '24.29746', 'train_loss': '58.24662'}
Epoch 126: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 126: {'val_loss': '23.64400', 'train_loss': '59.32060'}
Epoch 127: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 127: {'val_loss': '24.24843', 'train_loss': '65.03837'}
Epoch 128: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=59]Epoch 128: {'val_loss': '23.16818', 'train_loss': '58.15819'}
Epoch 129: 100%|██████████| 14/14 [00:01<00:00,  8.92it/s, v_num=59]Epoch 129: {'val_loss': '24.03494', 'train_loss': '55.84075'}
Epoch 130: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 130: {'val_loss': '25.53310', 'train_loss': '59.05225'}
Epoch 131: 100%|██████████| 14/14 [00:01<00:00,  9.45it/s, v_num=59]Epoch 131: {'val_loss': '23.44964', 'train_loss': '57.76134'}
Epoch 132: 100%|██████████| 14/14 [00:01<00:00,  9.84it/s, v_num=59]Epoch 132: {'val_loss': '23.26429', 'train_loss': '61.25484'}
Epoch 133: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=59]Epoch 133: {'val_loss': '23.19283', 'train_loss': '63.69206'}
Epoch 134: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=59]Epoch 134: {'val_loss': '23.31823', 'train_loss': '59.34246'}
Epoch 135: 100%|██████████| 14/14 [00:01<00:00,  8.87it/s, v_num=59]Epoch 135: {'val_loss': '23.43368', 'train_loss': '60.51897'}
Epoch 136: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 136: {'val_loss': '23.11481', 'train_loss': '61.11733'}
Epoch 137: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=59]Epoch 137: {'val_loss': '24.41381', 'train_loss': '56.88235'}
Epoch 138: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=59]Epoch 138: {'val_loss': '23.94502', 'train_loss': '54.28120'}
Epoch 139: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=59]Epoch 139: {'val_loss': '22.86440', 'train_loss': '58.12787'}
Epoch 140: 100%|██████████| 14/14 [00:01<00:00, 10.13it/s, v_num=59]Epoch 140: {'val_loss': '22.56487', 'train_loss': '59.39206'}
Epoch 141: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=59]Epoch 141: {'val_loss': '22.63671', 'train_loss': '53.61349'}
Epoch 142: 100%|██████████| 14/14 [00:01<00:00,  9.00it/s, v_num=59]Epoch 142: {'val_loss': '22.76632', 'train_loss': '63.68241'}
Epoch 143: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 143: {'val_loss': '22.66867', 'train_loss': '62.23005'}
Epoch 144: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=59]Epoch 144: {'val_loss': '23.12516', 'train_loss': '59.47986'}
Epoch 145: 100%|██████████| 14/14 [00:01<00:00, 10.07it/s, v_num=59]Epoch 145: {'val_loss': '23.05694', 'train_loss': '52.81163'}
Epoch 146: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=59]Epoch 146: {'val_loss': '23.61623', 'train_loss': '58.98347'}
Epoch 147: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=59]Epoch 147: {'val_loss': '22.86628', 'train_loss': '57.78399'}
Epoch 148: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=59]Epoch 148: {'val_loss': '22.62805', 'train_loss': '64.28271'}
Epoch 149: 100%|██████████| 14/14 [00:01<00:00,  9.78it/s, v_num=59]Epoch 149: {'val_loss': '22.83044', 'train_loss': '60.98257'}
Epoch 150: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 150: {'val_loss': '22.77581', 'train_loss': '62.11685'}
Epoch 151: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=59]Epoch 151: {'val_loss': '22.96091', 'train_loss': '59.36593'}
Epoch 152: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=59]Epoch 152: {'val_loss': '22.38572', 'train_loss': '55.26277'}
Epoch 153: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=59]Epoch 153: {'val_loss': '23.20320', 'train_loss': '59.22381'}
Epoch 154: 100%|██████████| 14/14 [00:01<00:00,  9.81it/s, v_num=59]Epoch 154: {'val_loss': '23.19570', 'train_loss': '59.00797'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (14) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 14/14 [00:01<00:00,  9.82it/s, v_num=60]Epoch 0: {'val_loss': '1203.05359', 'train_loss': '367.37042'}
Epoch 1: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 1: {'val_loss': '221.71436', 'train_loss': '159.71114'}
Epoch 2: 100%|██████████| 14/14 [00:01<00:00,  8.93it/s, v_num=60]Epoch 2: {'val_loss': '1173.49707', 'train_loss': '131.22998'}
Epoch 3: 100%|██████████| 14/14 [00:01<00:00, 10.02it/s, v_num=60]Epoch 3: {'val_loss': '3645.87524', 'train_loss': '133.74272'}
Epoch 4: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=60]Epoch 4: {'val_loss': '26014.67188', 'train_loss': '116.00101'}
Epoch 5: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=60]Epoch 5: {'val_loss': '174454.62500', 'train_loss': '130.81238'}
Epoch 6: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=60]Epoch 6: {'val_loss': '365952.12500', 'train_loss': '110.07358'}
Epoch 7: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=60]Epoch 7: {'val_loss': '275313.50000', 'train_loss': '111.56147'}
Epoch 8: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 8: {'val_loss': '324265.28125', 'train_loss': '109.96371'}
Epoch 9: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=60]Epoch 9: {'val_loss': '259437.73438', 'train_loss': '97.66314'}
Epoch 10: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 10: {'val_loss': '149335.90625', 'train_loss': '100.18562'}
Epoch 11: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 11: {'val_loss': '154104.56250', 'train_loss': '93.39555'}
Epoch 12: 100%|██████████| 14/14 [00:01<00:00,  8.97it/s, v_num=60]Epoch 12: {'val_loss': '141401.15625', 'train_loss': '98.78705'}
Epoch 13: 100%|██████████| 14/14 [00:01<00:00,  9.87it/s, v_num=60]Epoch 13: {'val_loss': '61687.74609', 'train_loss': '95.23290'}
Epoch 14: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 14: {'val_loss': '66207.92188', 'train_loss': '96.02013'}
Epoch 15: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=60]Epoch 15: {'val_loss': '52776.65625', 'train_loss': '93.95928'}
Epoch 16: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 16: {'val_loss': '98436.48438', 'train_loss': '94.08762'}
Epoch 17: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 17: {'val_loss': '77911.04688', 'train_loss': '91.23378'}
Epoch 18: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 18: {'val_loss': '31954.68750', 'train_loss': '92.04218'}
Epoch 19: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=60]Epoch 19: {'val_loss': '28983.00195', 'train_loss': '89.03584'}
Epoch 20: 100%|██████████| 14/14 [00:01<00:00,  9.87it/s, v_num=60]Epoch 20: {'val_loss': '17825.36719', 'train_loss': '91.42968'}
Epoch 21: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 21: {'val_loss': '19651.21094', 'train_loss': '89.32820'}
Epoch 22: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=60]Epoch 22: {'val_loss': '15972.91992', 'train_loss': '85.82177'}
Epoch 23: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 23: {'val_loss': '7386.59766', 'train_loss': '94.97967'}
Epoch 24: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 24: {'val_loss': '2751.13452', 'train_loss': '92.52676'}
Epoch 25: 100%|██████████| 14/14 [00:01<00:00,  9.81it/s, v_num=60]Epoch 25: {'val_loss': '941.22736', 'train_loss': '88.18509'}
Epoch 26: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 26: {'val_loss': '431.88660', 'train_loss': '90.79694'}
Epoch 27: 100%|██████████| 14/14 [00:01<00:00,  8.91it/s, v_num=60]Epoch 27: {'val_loss': '355.84744', 'train_loss': '90.76419'}
Epoch 28: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 28: {'val_loss': '363.54291', 'train_loss': '84.12633'}
Epoch 29: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=60]Epoch 29: {'val_loss': '358.67526', 'train_loss': '83.36889'}
Epoch 30: 100%|██████████| 14/14 [00:01<00:00, 10.08it/s, v_num=60]Epoch 30: {'val_loss': '1042.04492', 'train_loss': '91.26627'}
Epoch 31: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 31: {'val_loss': '307.73782', 'train_loss': '85.17539'}
Epoch 32: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 32: {'val_loss': '118.14893', 'train_loss': '85.40128'}
Epoch 33: 100%|██████████| 14/14 [00:01<00:00,  8.96it/s, v_num=60]Epoch 33: {'val_loss': '65.87993', 'train_loss': '85.50726'}
Epoch 34: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=60]Epoch 34: {'val_loss': '56.10933', 'train_loss': '83.84715'}
Epoch 35: 100%|██████████| 14/14 [00:01<00:00, 10.06it/s, v_num=60]Epoch 35: {'val_loss': '58.32839', 'train_loss': '82.59599'}
Epoch 36: 100%|██████████| 14/14 [00:01<00:00,  9.84it/s, v_num=60]Epoch 36: {'val_loss': '77.16345', 'train_loss': '90.63175'}
Epoch 37: 100%|██████████| 14/14 [00:01<00:00,  8.94it/s, v_num=60]Epoch 37: {'val_loss': '107.34830', 'train_loss': '88.21894'}
Epoch 38: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=60]Epoch 38: {'val_loss': '163.48219', 'train_loss': '81.05573'}
Epoch 39: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 39: {'val_loss': '218.03358', 'train_loss': '81.81465'}
Epoch 40: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 40: {'val_loss': '256.47574', 'train_loss': '81.49882'}
Epoch 41: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 41: {'val_loss': '234.93669', 'train_loss': '89.03677'}
Epoch 42: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=60]Epoch 42: {'val_loss': '246.22961', 'train_loss': '86.10035'}
Epoch 43: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 43: {'val_loss': '282.21283', 'train_loss': '84.35200'}
Epoch 44: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 44: {'val_loss': '277.58133', 'train_loss': '86.68366'}
Epoch 45: 100%|██████████| 14/14 [00:01<00:00,  8.76it/s, v_num=60]Epoch 45: {'val_loss': '211.41273', 'train_loss': '79.03831'}
Epoch 46: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 46: {'val_loss': '183.10695', 'train_loss': '85.74079'}
Epoch 47: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 47: {'val_loss': '167.13998', 'train_loss': '88.72411'}
Epoch 48: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=60]Epoch 48: {'val_loss': '130.67526', 'train_loss': '86.97393'}
Epoch 49: 100%|██████████| 14/14 [00:01<00:00,  8.97it/s, v_num=60]Epoch 49: {'val_loss': '121.59254', 'train_loss': '82.57223'}
Epoch 50: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 50: {'val_loss': '98.35229', 'train_loss': '79.46674'}
Epoch 51: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 51: {'val_loss': '91.11787', 'train_loss': '79.98121'}
Epoch 52: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 52: {'val_loss': '88.30092', 'train_loss': '86.43587'}
Epoch 53: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 53: {'val_loss': '96.57276', 'train_loss': '88.41515'}
Epoch 54: 100%|██████████| 14/14 [00:01<00:00,  9.83it/s, v_num=60]Epoch 54: {'val_loss': '107.26512', 'train_loss': '77.60369'}
Epoch 55: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=60]Epoch 55: {'val_loss': '95.11999', 'train_loss': '83.05655'}
Epoch 56: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 56: {'val_loss': '98.41589', 'train_loss': '77.94101'}
Epoch 57: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 57: {'val_loss': '100.54846', 'train_loss': '81.08387'}
Epoch 58: 100%|██████████| 14/14 [00:01<00:00,  8.87it/s, v_num=60]Epoch 58: {'val_loss': '105.92139', 'train_loss': '78.37453'}
Epoch 59: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 59: {'val_loss': '110.37356', 'train_loss': '81.75063'}
Epoch 60: 100%|██████████| 14/14 [00:01<00:00, 10.04it/s, v_num=60]Epoch 60: {'val_loss': '101.00320', 'train_loss': '83.34486'}
Epoch 61: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 61: {'val_loss': '103.20634', 'train_loss': '81.70889'}
Epoch 62: 100%|██████████| 14/14 [00:01<00:00,  8.81it/s, v_num=60]Epoch 62: {'val_loss': '107.05837', 'train_loss': '79.34332'}
Epoch 63: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=60]Epoch 63: {'val_loss': '106.94031', 'train_loss': '80.98787'}
Epoch 64: 100%|██████████| 14/14 [00:01<00:00, 10.00it/s, v_num=60]Epoch 64: {'val_loss': '108.80173', 'train_loss': '85.14661'}
Epoch 65: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=60]Epoch 65: {'val_loss': '112.83233', 'train_loss': '79.54608'}
Epoch 66: 100%|██████████| 14/14 [00:01<00:00,  9.94it/s, v_num=60]Epoch 66: {'val_loss': '115.64856', 'train_loss': '85.74858'}
Epoch 67: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=60]Epoch 67: {'val_loss': '113.29990', 'train_loss': '87.94535'}
Epoch 68: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=60]Epoch 68: {'val_loss': '101.79229', 'train_loss': '81.79773'}
Epoch 69: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 69: {'val_loss': '108.77861', 'train_loss': '90.98678'}
Epoch 70: 100%|██████████| 14/14 [00:01<00:00,  9.85it/s, v_num=60]Epoch 70: {'val_loss': '112.12984', 'train_loss': '82.63982'}
Epoch 71: 100%|██████████| 14/14 [00:01<00:00,  8.89it/s, v_num=60]Epoch 71: {'val_loss': '106.11845', 'train_loss': '82.58360'}
Epoch 72: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 72: {'val_loss': '114.75832', 'train_loss': '86.88710'}
Epoch 73: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 73: {'val_loss': '116.41349', 'train_loss': '84.42078'}
Epoch 74: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 74: {'val_loss': '105.51491', 'train_loss': '81.59911'}
Epoch 75: 100%|██████████| 14/14 [00:01<00:00,  8.93it/s, v_num=60]Epoch 75: {'val_loss': '111.10334', 'train_loss': '85.66003'}
Epoch 76: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 76: {'val_loss': '108.43973', 'train_loss': '81.89684'}
Epoch 77: 100%|██████████| 14/14 [00:01<00:00,  9.88it/s, v_num=60]Epoch 77: {'val_loss': '109.37937', 'train_loss': '84.42973'}
Epoch 78: 100%|██████████| 14/14 [00:01<00:00, 10.03it/s, v_num=60]Epoch 78: {'val_loss': '108.05858', 'train_loss': '80.12035'}
Epoch 79: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=60]Epoch 79: {'val_loss': '110.09319', 'train_loss': '77.98569'}
Epoch 80: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 80: {'val_loss': '110.58248', 'train_loss': '86.42963'}
Epoch 81: 100%|██████████| 14/14 [00:01<00:00,  9.99it/s, v_num=60]Epoch 81: {'val_loss': '111.71572', 'train_loss': '82.95335'}
Epoch 82: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 82: {'val_loss': '112.07257', 'train_loss': '83.92235'}
Epoch 83: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=60]Epoch 83: {'val_loss': '113.14061', 'train_loss': '82.38681'}
Epoch 84: 100%|██████████| 14/14 [00:01<00:00,  8.81it/s, v_num=60]Epoch 84: {'val_loss': '106.61458', 'train_loss': '81.32774'}
Epoch 85: 100%|██████████| 14/14 [00:01<00:00, 10.05it/s, v_num=60]Epoch 85: {'val_loss': '106.21593', 'train_loss': '83.41869'}
Epoch 86: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 86: {'val_loss': '111.96242', 'train_loss': '80.15542'}
Epoch 87: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 87: {'val_loss': '110.85920', 'train_loss': '82.17707'}
Epoch 88: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 88: {'val_loss': '115.46321', 'train_loss': '85.93160'}
Epoch 89: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 89: {'val_loss': '117.61672', 'train_loss': '81.96369'}
Epoch 90: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 90: {'val_loss': '108.63700', 'train_loss': '81.72635'}
Epoch 91: 100%|██████████| 14/14 [00:01<00:00,  9.82it/s, v_num=60]Epoch 91: {'val_loss': '107.40806', 'train_loss': '82.46370'}
Epoch 92: 100%|██████████| 14/14 [00:01<00:00,  8.83it/s, v_num=60]Epoch 92: {'val_loss': '109.92598', 'train_loss': '90.79343'}
Epoch 93: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 93: {'val_loss': '107.41666', 'train_loss': '81.69596'}
Epoch 94: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 94: {'val_loss': '112.54305', 'train_loss': '83.83907'}
Epoch 95: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 95: {'val_loss': '112.71477', 'train_loss': '81.06803'}
Epoch 96: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 96: {'val_loss': '109.18543', 'train_loss': '84.09775'}
Epoch 97: 100%|██████████| 14/14 [00:01<00:00,  9.86it/s, v_num=60]Epoch 97: {'val_loss': '103.10101', 'train_loss': '81.94553'}
Epoch 98: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=60]Epoch 98: {'val_loss': '103.08746', 'train_loss': '80.21364'}
Epoch 99: 100%|██████████| 14/14 [00:01<00:00,  8.93it/s, v_num=60]Epoch 99: {'val_loss': '107.45116', 'train_loss': '81.62091'}
Epoch 100: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 100: {'val_loss': '104.13397', 'train_loss': '87.80302'}
Epoch 101: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 101: {'val_loss': '109.20744', 'train_loss': '82.41846'}
Epoch 102: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=60]Epoch 102: {'val_loss': '106.10004', 'train_loss': '84.18398'}
Epoch 103: 100%|██████████| 14/14 [00:01<00:00,  9.84it/s, v_num=60]Epoch 103: {'val_loss': '108.16406', 'train_loss': '87.25818'}
Epoch 104: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 104: {'val_loss': '112.68755', 'train_loss': '82.60817'}
Epoch 105: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 105: {'val_loss': '108.72201', 'train_loss': '89.00867'}
Epoch 106: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=60]Epoch 106: {'val_loss': '108.00047', 'train_loss': '83.86524'}
Epoch 107: 100%|██████████| 14/14 [00:01<00:00,  8.91it/s, v_num=60]Epoch 107: {'val_loss': '114.09165', 'train_loss': '83.45339'}
Epoch 108: 100%|██████████| 14/14 [00:01<00:00,  9.90it/s, v_num=60]Epoch 108: {'val_loss': '108.16075', 'train_loss': '85.75060'}
Epoch 109: 100%|██████████| 14/14 [00:01<00:00, 10.01it/s, v_num=60]Epoch 109: {'val_loss': '108.63670', 'train_loss': '88.42781'}
Epoch 110: 100%|██████████| 14/14 [00:01<00:00,  9.83it/s, v_num=60]Epoch 110: {'val_loss': '110.92674', 'train_loss': '82.98678'}
Epoch 111: 100%|██████████| 14/14 [00:01<00:00,  9.89it/s, v_num=60]Epoch 111: {'val_loss': '107.67092', 'train_loss': '86.54214'}
Epoch 112: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 112: {'val_loss': '111.62955', 'train_loss': '87.60558'}
Epoch 113: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 113: {'val_loss': '108.72724', 'train_loss': '81.56964'}
Epoch 114: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 114: {'val_loss': '114.17269', 'train_loss': '83.26444'}
Epoch 115: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 115: {'val_loss': '110.95000', 'train_loss': '81.37612'}
Epoch 116: 100%|██████████| 14/14 [00:01<00:00,  8.79it/s, v_num=60]Epoch 116: {'val_loss': '115.28591', 'train_loss': '84.16552'}
Epoch 117: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 117: {'val_loss': '106.46040', 'train_loss': '84.47160'}
Epoch 118: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 118: {'val_loss': '105.26510', 'train_loss': '83.98787'}
Epoch 119: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 119: {'val_loss': '107.51060', 'train_loss': '81.25630'}
Epoch 120: 100%|██████████| 14/14 [00:01<00:00,  9.91it/s, v_num=60]Epoch 120: {'val_loss': '106.45043', 'train_loss': '84.06964'}
Epoch 121: 100%|██████████| 14/14 [00:01<00:00,  9.69it/s, v_num=60]Epoch 121: {'val_loss': '112.76302', 'train_loss': '83.91727'}
Epoch 122: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 122: {'val_loss': '110.58067', 'train_loss': '81.13805'}
Epoch 123: 100%|██████████| 14/14 [00:01<00:00,  9.93it/s, v_num=60]Epoch 123: {'val_loss': '120.19244', 'train_loss': '82.24638'}
Epoch 124: 100%|██████████| 14/14 [00:01<00:00,  8.86it/s, v_num=60]Epoch 124: {'val_loss': '113.41695', 'train_loss': '83.70398'}
Epoch 125: 100%|██████████| 14/14 [00:01<00:00,  9.98it/s, v_num=60]Epoch 125: {'val_loss': '112.23082', 'train_loss': '82.19489'}
Epoch 126: 100%|██████████| 14/14 [00:01<00:00,  9.88it/s, v_num=60]Epoch 126: {'val_loss': '111.80941', 'train_loss': '82.26138'}
Epoch 127: 100%|██████████| 14/14 [00:01<00:00,  9.83it/s, v_num=60]Epoch 127: {'val_loss': '115.68526', 'train_loss': '83.92636'}
Epoch 128: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=60]Epoch 128: {'val_loss': '110.53565', 'train_loss': '84.76036'}
Epoch 129: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]Epoch 129: {'val_loss': '113.21795', 'train_loss': '86.99496'}
Epoch 130: 100%|██████████| 14/14 [00:01<00:00,  9.92it/s, v_num=60]Epoch 130: {'val_loss': '110.15670', 'train_loss': '87.39889'}
Epoch 131: 100%|██████████| 14/14 [00:01<00:00,  8.90it/s, v_num=60]Epoch 131: {'val_loss': '111.08971', 'train_loss': '81.75688'}
Epoch 132: 100%|██████████| 14/14 [00:01<00:00,  9.69it/s, v_num=60]Epoch 132: {'val_loss': '111.69617', 'train_loss': '81.46450'}
Epoch 133: 100%|██████████| 14/14 [00:01<00:00,  9.97it/s, v_num=60]Epoch 133: {'val_loss': '111.77151', 'train_loss': '89.51808'}
Epoch 134: 100%|██████████| 14/14 [00:01<00:00,  9.96it/s, v_num=60]Epoch 134: {'val_loss': '116.90198', 'train_loss': '76.01766'}
Epoch 134: 100%|██████████| 14/14 [00:01<00:00,  9.95it/s, v_num=60]
Fold-3 Training completed in 193.41s

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 0: {'val_loss': '8323.10254', 'train_loss': '360.18726'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  9.23it/s, v_num=61]Epoch 1: {'val_loss': '506.45181', 'train_loss': '137.76874'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 2: {'val_loss': '167.93602', 'train_loss': '120.99171'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=61]Epoch 3: {'val_loss': '105.84987', 'train_loss': '123.76221'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 4: {'val_loss': '47.47913', 'train_loss': '116.63570'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=61]Epoch 5: {'val_loss': '139.10954', 'train_loss': '108.28685'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.38it/s, v_num=61]Epoch 6: {'val_loss': '40.49265', 'train_loss': '110.04942'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 7: {'val_loss': '54.97153', 'train_loss': '109.90249'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 8: {'val_loss': '47.42642', 'train_loss': '101.72719'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  9.32it/s, v_num=61]Epoch 9: {'val_loss': '46.93041', 'train_loss': '98.09232'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 10: {'val_loss': '36.99288', 'train_loss': '100.28133'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.44it/s, v_num=61]Epoch 11: {'val_loss': '41.79525', 'train_loss': '93.83501'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.47it/s, v_num=61]Epoch 12: {'val_loss': '52.10234', 'train_loss': '101.62392'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00,  9.34it/s, v_num=61]Epoch 13: {'val_loss': '36.45565', 'train_loss': '93.38820'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.45it/s, v_num=61]Epoch 14: {'val_loss': '35.16825', 'train_loss': '98.21710'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 15: {'val_loss': '99.78517', 'train_loss': '98.60686'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 16: {'val_loss': '57.07342', 'train_loss': '102.98797'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.40it/s, v_num=61]Epoch 17: {'val_loss': '64.91537', 'train_loss': '92.49654'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.27it/s, v_num=61]Epoch 18: {'val_loss': '34.40204', 'train_loss': '95.57173'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=61]Epoch 19: {'val_loss': '32.41181', 'train_loss': '95.99865'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 20: {'val_loss': '31.72647', 'train_loss': '91.99811'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 21: {'val_loss': '36.16022', 'train_loss': '92.01915'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00,  9.34it/s, v_num=61]Epoch 22: {'val_loss': '33.68067', 'train_loss': '101.34418'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=61]Epoch 23: {'val_loss': '35.21457', 'train_loss': '96.58862'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=61]Epoch 24: {'val_loss': '34.21919', 'train_loss': '83.94433'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=61]Epoch 25: {'val_loss': '64.41600', 'train_loss': '90.57662'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.32it/s, v_num=61]Epoch 26: {'val_loss': '34.68243', 'train_loss': '86.33050'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 27: {'val_loss': '33.96850', 'train_loss': '88.14862'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=61]Epoch 28: {'val_loss': '36.46936', 'train_loss': '84.75923'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 29: {'val_loss': '42.67020', 'train_loss': '78.09709'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00,  9.29it/s, v_num=61]Epoch 30: {'val_loss': '33.20641', 'train_loss': '83.24602'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00, 10.38it/s, v_num=61]Epoch 31: {'val_loss': '37.46487', 'train_loss': '86.43024'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 32: {'val_loss': '45.99331', 'train_loss': '81.26180'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 33: {'val_loss': '37.56837', 'train_loss': '80.40042'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.31it/s, v_num=61]Epoch 34: {'val_loss': '32.93050', 'train_loss': '80.46551'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 35: {'val_loss': '31.46896', 'train_loss': '79.51762'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 36: {'val_loss': '31.08916', 'train_loss': '84.43465'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=61]Epoch 37: {'val_loss': '29.91399', 'train_loss': '79.01453'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 38: {'val_loss': '31.76030', 'train_loss': '71.51389'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=61]Epoch 39: {'val_loss': '30.87588', 'train_loss': '73.23091'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00, 10.42it/s, v_num=61]Epoch 40: {'val_loss': '30.97638', 'train_loss': '71.78486'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=61]Epoch 41: {'val_loss': '30.72264', 'train_loss': '80.16064'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 42: {'val_loss': '30.81306', 'train_loss': '82.03701'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=61]Epoch 43: {'val_loss': '38.43043', 'train_loss': '81.65986'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=61]Epoch 44: {'val_loss': '28.91091', 'train_loss': '80.00015'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 45: {'val_loss': '28.35764', 'train_loss': '72.64641'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 46: {'val_loss': '29.07346', 'train_loss': '70.28037'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=61]Epoch 47: {'val_loss': '29.50877', 'train_loss': '75.27555'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 48: {'val_loss': '28.55617', 'train_loss': '75.88965'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=61]Epoch 49: {'val_loss': '28.79833', 'train_loss': '74.87655'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=61]Epoch 50: {'val_loss': '29.00093', 'train_loss': '70.87223'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=61]Epoch 51: {'val_loss': '31.13023', 'train_loss': '72.46246'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 52: {'val_loss': '28.66861', 'train_loss': '69.05986'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 53: {'val_loss': '28.13067', 'train_loss': '72.23899'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 54: {'val_loss': '28.25771', 'train_loss': '74.12442'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=61]Epoch 55: {'val_loss': '28.83132', 'train_loss': '73.98188'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 56: {'val_loss': '27.93352', 'train_loss': '75.06020'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 57: {'val_loss': '27.51819', 'train_loss': '72.47801'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.32it/s, v_num=61]Epoch 58: {'val_loss': '27.28317', 'train_loss': '71.55553'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 59: {'val_loss': '27.38358', 'train_loss': '68.73444'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=61]Epoch 60: {'val_loss': '26.26081', 'train_loss': '72.33990'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 61: {'val_loss': '28.38366', 'train_loss': '69.89719'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00,  9.21it/s, v_num=61]Epoch 62: {'val_loss': '27.19310', 'train_loss': '69.32024'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=61]Epoch 63: {'val_loss': '26.82870', 'train_loss': '68.86079'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=61]Epoch 64: {'val_loss': '26.95308', 'train_loss': '72.94475'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=61]Epoch 65: {'val_loss': '28.14437', 'train_loss': '72.64630'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 66: {'val_loss': '29.05762', 'train_loss': '68.10794'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 67: {'val_loss': '28.39005', 'train_loss': '65.16558'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 68: {'val_loss': '27.18376', 'train_loss': '70.15172'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 69: {'val_loss': '27.88405', 'train_loss': '72.40326'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=61]Epoch 70: {'val_loss': '26.62564', 'train_loss': '69.54134'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 71: {'val_loss': '27.35509', 'train_loss': '67.68438'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 72: {'val_loss': '26.79945', 'train_loss': '67.64315'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00, 10.38it/s, v_num=61]Epoch 73: {'val_loss': '27.28280', 'train_loss': '67.02675'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 74: {'val_loss': '27.69081', 'train_loss': '65.72311'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=61]Epoch 75: {'val_loss': '28.62249', 'train_loss': '73.23419'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 76: {'val_loss': '27.55927', 'train_loss': '76.20607'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=61]Epoch 77: {'val_loss': '26.71779', 'train_loss': '67.55624'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.28it/s, v_num=61]Epoch 78: {'val_loss': '26.82101', 'train_loss': '70.36475'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00, 10.38it/s, v_num=61]Epoch 79: {'val_loss': '26.89731', 'train_loss': '68.93343'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 80: {'val_loss': '27.07262', 'train_loss': '67.16299'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00, 10.39it/s, v_num=61]Epoch 81: {'val_loss': '26.27263', 'train_loss': '70.88818'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=61]Epoch 82: {'val_loss': '26.17529', 'train_loss': '69.67487'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=61]Epoch 83: {'val_loss': '26.43062', 'train_loss': '65.55773'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 84: {'val_loss': '26.15052', 'train_loss': '71.83669'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 85: {'val_loss': '26.62099', 'train_loss': '70.62675'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=61]Epoch 86: {'val_loss': '26.73717', 'train_loss': '65.56476'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.26it/s, v_num=61]Epoch 87: {'val_loss': '26.80529', 'train_loss': '68.89135'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 88: {'val_loss': '26.97920', 'train_loss': '73.98548'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 89: {'val_loss': '26.78838', 'train_loss': '71.81822'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=61]Epoch 90: {'val_loss': '27.71197', 'train_loss': '69.81792'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 91: {'val_loss': '26.85084', 'train_loss': '66.00446'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.30it/s, v_num=61]Epoch 92: {'val_loss': '27.30792', 'train_loss': '69.88792'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 93: {'val_loss': '27.10785', 'train_loss': '68.34686'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.42it/s, v_num=61]Epoch 94: {'val_loss': '26.61571', 'train_loss': '66.95475'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=61]Epoch 95: {'val_loss': '26.82450', 'train_loss': '67.54957'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=61]Epoch 96: {'val_loss': '26.55611', 'train_loss': '72.55401'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 97: {'val_loss': '26.48342', 'train_loss': '67.48478'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=61]Epoch 98: {'val_loss': '27.58706', 'train_loss': '72.95747'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.22it/s, v_num=61]Epoch 99: {'val_loss': '26.58859', 'train_loss': '70.77566'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 100: {'val_loss': '26.61163', 'train_loss': '72.71062'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 101: {'val_loss': '26.69682', 'train_loss': '69.85831'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=61]Epoch 102: {'val_loss': '26.54093', 'train_loss': '67.01517'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=61]Epoch 103: {'val_loss': '27.03650', 'train_loss': '66.70436'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 104: {'val_loss': '26.60918', 'train_loss': '66.91576'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 105: {'val_loss': '26.84294', 'train_loss': '64.25376'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.27it/s, v_num=61]Epoch 106: {'val_loss': '26.75984', 'train_loss': '69.63867'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 107: {'val_loss': '28.37638', 'train_loss': '67.26345'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=61]Epoch 108: {'val_loss': '27.48075', 'train_loss': '65.51740'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00, 10.40it/s, v_num=61]Epoch 109: {'val_loss': '26.84832', 'train_loss': '70.07539'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.28it/s, v_num=61]Epoch 110: {'val_loss': '27.56620', 'train_loss': '67.91154'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 111: {'val_loss': '27.09045', 'train_loss': '67.00349'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00, 10.37it/s, v_num=61]Epoch 112: {'val_loss': '27.57340', 'train_loss': '65.71402'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=61]Epoch 113: {'val_loss': '26.65413', 'train_loss': '71.35439'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=61]Epoch 114: {'val_loss': '26.45084', 'train_loss': '66.01704'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=61]Epoch 115: {'val_loss': '26.66061', 'train_loss': '70.71735'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=61]Epoch 116: {'val_loss': '26.58972', 'train_loss': '71.43890'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=61]Epoch 117: {'val_loss': '26.97030', 'train_loss': '69.18792'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00, 10.35it/s, v_num=61]Epoch 118: {'val_loss': '26.91146', 'train_loss': '63.70632'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=61]Epoch 119: {'val_loss': '26.60131', 'train_loss': '65.46740'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=61]Epoch 120: {'val_loss': '26.57471', 'train_loss': '67.58053'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 121: {'val_loss': '27.38013', 'train_loss': '68.20647'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 122: {'val_loss': '27.03480', 'train_loss': '64.82775'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.24it/s, v_num=61]Epoch 123: {'val_loss': '27.34446', 'train_loss': '65.98652'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=61]Epoch 124: {'val_loss': '26.60796', 'train_loss': '65.96735'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=61]Epoch 125: {'val_loss': '26.70977', 'train_loss': '66.98936'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.40it/s, v_num=61]Epoch 126: {'val_loss': '26.82268', 'train_loss': '65.81926'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=61]Epoch 127: {'val_loss': '27.04614', 'train_loss': '70.44332'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 128: {'val_loss': '27.24017', 'train_loss': '71.22865'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=61]Epoch 129: {'val_loss': '27.94342', 'train_loss': '66.71064'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=61]Epoch 130: {'val_loss': '27.79774', 'train_loss': '65.90806'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=61]Epoch 131: {'val_loss': '26.84645', 'train_loss': '67.44824'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=61]Epoch 132: {'val_loss': '27.40788', 'train_loss': '67.78716'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=61]Epoch 133: {'val_loss': '27.69265', 'train_loss': '68.08001'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=61]Epoch 134: {'val_loss': '27.25867', 'train_loss': '70.65723'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=61]Epoch 135: {'val_loss': '28.73069', 'train_loss': '74.79136'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.23it/s, v_num=61]Epoch 136: {'val_loss': '27.68978', 'train_loss': '67.56913'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 137: {'val_loss': '27.49409', 'train_loss': '65.00634'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=61]Epoch 138: {'val_loss': '26.54909', 'train_loss': '70.13821'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=61]Epoch 139: {'val_loss': '27.13817', 'train_loss': '65.85006'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=61]Epoch 140: {'val_loss': '26.97022', 'train_loss': '67.84302'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=61]Epoch 141: {'val_loss': '26.79376', 'train_loss': '69.47481'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 142: {'val_loss': '26.63598', 'train_loss': '67.29276'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=61]Epoch 143: {'val_loss': '27.64218', 'train_loss': '68.13802'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=61]Epoch 144: {'val_loss': '27.65230', 'train_loss': '68.31903'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=61]Epoch 145: {'val_loss': '27.31367', 'train_loss': '70.48087'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=61]Epoch 146: {'val_loss': '27.18937', 'train_loss': '67.41206'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=61]Epoch 147: {'val_loss': '26.83710', 'train_loss': '65.85961'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=61]Epoch 148: {'val_loss': '26.52775', 'train_loss': '66.99519'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=61]Epoch 149: {'val_loss': '26.75845', 'train_loss': '63.51574'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=61]Epoch 150: {'val_loss': '27.02534', 'train_loss': '65.38742'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=61]Epoch 151: {'val_loss': '26.96274', 'train_loss': '69.00836'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=61]Epoch 152: {'val_loss': '26.96806', 'train_loss': '66.89143'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=61]Epoch 153: {'val_loss': '26.66528', 'train_loss': '72.71774'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=61]Epoch 154: {'val_loss': '26.63656', 'train_loss': '68.45522'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 0: {'val_loss': '2256.05225', 'train_loss': '425.71286'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 1: {'val_loss': '169.32019', 'train_loss': '145.72902'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=62]Epoch 2: {'val_loss': '152.48978', 'train_loss': '123.10954'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 3: {'val_loss': '44.51304', 'train_loss': '108.02679'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 4: {'val_loss': '47.34650', 'train_loss': '102.34669'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=62]Epoch 5: {'val_loss': '78.82775', 'train_loss': '98.99134'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=62]Epoch 6: {'val_loss': '46.92938', 'train_loss': '111.41210'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  9.20it/s, v_num=62]Epoch 7: {'val_loss': '70.89121', 'train_loss': '99.37662'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 8: {'val_loss': '67.79511', 'train_loss': '98.87501'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=62]Epoch 9: {'val_loss': '39.90343', 'train_loss': '105.79963'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.17it/s, v_num=62]Epoch 10: {'val_loss': '41.80598', 'train_loss': '93.58823'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=62]Epoch 11: {'val_loss': '43.09182', 'train_loss': '96.67373'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 12: {'val_loss': '54.67662', 'train_loss': '88.06628'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=62]Epoch 13: {'val_loss': '58.49892', 'train_loss': '91.15888'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=62]Epoch 14: {'val_loss': '39.36580', 'train_loss': '98.74913'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  9.22it/s, v_num=62]Epoch 15: {'val_loss': '38.22966', 'train_loss': '111.23953'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 16: {'val_loss': '35.53390', 'train_loss': '91.09778'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=62]Epoch 17: {'val_loss': '38.49648', 'train_loss': '87.63562'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.24it/s, v_num=62]Epoch 18: {'val_loss': '34.65013', 'train_loss': '85.47380'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=62]Epoch 19: {'val_loss': '37.86049', 'train_loss': '80.51530'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 20: {'val_loss': '52.88398', 'train_loss': '92.10143'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=62]Epoch 21: {'val_loss': '47.79502', 'train_loss': '91.83556'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 22: {'val_loss': '32.53191', 'train_loss': '88.09485'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=62]Epoch 23: {'val_loss': '37.00045', 'train_loss': '87.81401'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 24: {'val_loss': '40.14492', 'train_loss': '92.17979'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=62]Epoch 25: {'val_loss': '47.02760', 'train_loss': '104.85680'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=62]Epoch 26: {'val_loss': '39.61710', 'train_loss': '87.58887'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  9.23it/s, v_num=62]Epoch 27: {'val_loss': '70.80312', 'train_loss': '80.70144'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=62]Epoch 28: {'val_loss': '47.22034', 'train_loss': '81.55961'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=62]Epoch 29: {'val_loss': '34.20601', 'train_loss': '77.28874'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 30: {'val_loss': '43.13904', 'train_loss': '84.29789'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=62]Epoch 31: {'val_loss': '47.82936', 'train_loss': '87.00758'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 32: {'val_loss': '45.56382', 'train_loss': '82.59823'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 33: {'val_loss': '35.00087', 'train_loss': '84.31860'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=62]Epoch 34: {'val_loss': '35.23095', 'train_loss': '72.09969'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00,  9.22it/s, v_num=62]Epoch 35: {'val_loss': '32.89359', 'train_loss': '78.17768'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 36: {'val_loss': '34.93152', 'train_loss': '75.69061'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00, 10.33it/s, v_num=62]Epoch 37: {'val_loss': '34.33044', 'train_loss': '74.07907'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.17it/s, v_num=62]Epoch 38: {'val_loss': '33.19604', 'train_loss': '78.37473'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=62]Epoch 39: {'val_loss': '48.04962', 'train_loss': '81.32890'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=62]Epoch 40: {'val_loss': '38.89858', 'train_loss': '79.38022'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00, 10.32it/s, v_num=62]Epoch 41: {'val_loss': '35.53447', 'train_loss': '70.16438'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=62]Epoch 42: {'val_loss': '32.44608', 'train_loss': '71.26007'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 43: {'val_loss': '32.65058', 'train_loss': '70.38449'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=62]Epoch 44: {'val_loss': '32.62638', 'train_loss': '71.38165'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00, 10.34it/s, v_num=62]Epoch 45: {'val_loss': '32.35031', 'train_loss': '67.90453'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00,  9.29it/s, v_num=62]Epoch 46: {'val_loss': '32.20081', 'train_loss': '72.71204'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 47: {'val_loss': '33.42582', 'train_loss': '73.64632'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 48: {'val_loss': '32.23180', 'train_loss': '70.27101'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=62]Epoch 49: {'val_loss': '31.41703', 'train_loss': '72.88412'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 50: {'val_loss': '31.84365', 'train_loss': '80.76787'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=62]Epoch 51: {'val_loss': '31.93789', 'train_loss': '70.88995'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 52: {'val_loss': '31.30625', 'train_loss': '72.69603'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 53: {'val_loss': '32.46481', 'train_loss': '76.60929'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=62]Epoch 54: {'val_loss': '30.83047', 'train_loss': '72.29532'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 55: {'val_loss': '30.50030', 'train_loss': '79.72002'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=62]Epoch 56: {'val_loss': '30.63731', 'train_loss': '68.21497'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=62]Epoch 57: {'val_loss': '31.03888', 'train_loss': '74.74612'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 58: {'val_loss': '31.20367', 'train_loss': '66.90491'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=62]Epoch 59: {'val_loss': '30.62795', 'train_loss': '70.37741'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 60: {'val_loss': '31.09347', 'train_loss': '65.96651'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  9.20it/s, v_num=62]Epoch 61: {'val_loss': '33.89115', 'train_loss': '65.56071'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 62: {'val_loss': '30.41583', 'train_loss': '67.17197'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=62]Epoch 63: {'val_loss': '30.43505', 'train_loss': '68.86820'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 64: {'val_loss': '30.85942', 'train_loss': '69.40033'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=62]Epoch 65: {'val_loss': '30.37941', 'train_loss': '65.74931'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=62]Epoch 66: {'val_loss': '30.73397', 'train_loss': '68.70069'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00, 10.26it/s, v_num=62]Epoch 67: {'val_loss': '30.36560', 'train_loss': '71.44627'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 68: {'val_loss': '29.30325', 'train_loss': '69.76394'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  9.22it/s, v_num=62]Epoch 69: {'val_loss': '30.68257', 'train_loss': '69.41246'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 70: {'val_loss': '29.98065', 'train_loss': '67.65358'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 71: {'val_loss': '30.07264', 'train_loss': '63.40506'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=62]Epoch 72: {'val_loss': '30.61941', 'train_loss': '69.20877'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=62]Epoch 73: {'val_loss': '32.59651', 'train_loss': '72.65459'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=62]Epoch 74: {'val_loss': '31.61140', 'train_loss': '69.63321'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.21it/s, v_num=62]Epoch 75: {'val_loss': '29.09985', 'train_loss': '71.10289'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 76: {'val_loss': '28.99217', 'train_loss': '68.16108'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 77: {'val_loss': '29.97439', 'train_loss': '66.10419'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 78: {'val_loss': '28.84132', 'train_loss': '70.37671'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=62]Epoch 79: {'val_loss': '28.94553', 'train_loss': '66.74998'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=62]Epoch 80: {'val_loss': '29.09929', 'train_loss': '69.92663'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 81: {'val_loss': '28.97262', 'train_loss': '67.81449'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 82: {'val_loss': '29.89807', 'train_loss': '73.65244'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 83: {'val_loss': '29.05282', 'train_loss': '64.31101'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=62]Epoch 84: {'val_loss': '28.93495', 'train_loss': '64.51656'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=62]Epoch 85: {'val_loss': '29.52757', 'train_loss': '67.00994'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=62]Epoch 86: {'val_loss': '28.91714', 'train_loss': '63.76086'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=62]Epoch 87: {'val_loss': '29.04736', 'train_loss': '63.01773'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=62]Epoch 88: {'val_loss': '28.98389', 'train_loss': '62.99620'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.17it/s, v_num=62]Epoch 89: {'val_loss': '29.82961', 'train_loss': '67.20368'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 90: {'val_loss': '30.01008', 'train_loss': '61.38408'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 91: {'val_loss': '29.88706', 'train_loss': '65.00698'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=62]Epoch 92: {'val_loss': '29.88333', 'train_loss': '67.71082'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=62]Epoch 93: {'val_loss': '29.46834', 'train_loss': '62.86261'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.30it/s, v_num=62]Epoch 94: {'val_loss': '28.50569', 'train_loss': '67.58500'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.31it/s, v_num=62]Epoch 95: {'val_loss': '28.78727', 'train_loss': '62.35788'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=62]Epoch 96: {'val_loss': '28.47612', 'train_loss': '74.43280'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=62]Epoch 97: {'val_loss': '28.64773', 'train_loss': '63.47171'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 98: {'val_loss': '28.52482', 'train_loss': '65.28062'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 99: {'val_loss': '28.91008', 'train_loss': '61.71088'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=62]Epoch 100: {'val_loss': '29.31814', 'train_loss': '61.70947'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=62]Epoch 101: {'val_loss': '29.34566', 'train_loss': '68.52193'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=62]Epoch 102: {'val_loss': '28.95569', 'train_loss': '70.55901'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=62]Epoch 103: {'val_loss': '28.95612', 'train_loss': '60.51707'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 104: {'val_loss': '28.83474', 'train_loss': '61.89560'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 105: {'val_loss': '28.79997', 'train_loss': '66.41949'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=62]Epoch 106: {'val_loss': '28.48719', 'train_loss': '63.37275'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=62]Epoch 107: {'val_loss': '29.51492', 'train_loss': '68.90905'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 108: {'val_loss': '29.46639', 'train_loss': '63.65916'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 109: {'val_loss': '29.40200', 'train_loss': '63.63212'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=62]Epoch 110: {'val_loss': '28.64777', 'train_loss': '65.18867'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=62]Epoch 111: {'val_loss': '28.50050', 'train_loss': '63.26240'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00, 10.29it/s, v_num=62]Epoch 112: {'val_loss': '28.67230', 'train_loss': '64.26554'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00, 10.36it/s, v_num=62]Epoch 113: {'val_loss': '28.85734', 'train_loss': '65.62727'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=62]Epoch 114: {'val_loss': '28.87387', 'train_loss': '68.77671'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 115: {'val_loss': '29.88174', 'train_loss': '61.40125'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=62]Epoch 116: {'val_loss': '31.53679', 'train_loss': '66.13774'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=62]Epoch 117: {'val_loss': '28.82954', 'train_loss': '69.38569'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=62]Epoch 118: {'val_loss': '28.63632', 'train_loss': '64.28027'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 119: {'val_loss': '29.03400', 'train_loss': '59.69028'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=62]Epoch 120: {'val_loss': '28.67362', 'train_loss': '62.91198'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=62]Epoch 121: {'val_loss': '29.90709', 'train_loss': '65.55439'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 122: {'val_loss': '29.34026', 'train_loss': '63.27972'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=62]Epoch 123: {'val_loss': '29.67987', 'train_loss': '63.56997'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 124: {'val_loss': '28.97586', 'train_loss': '61.04406'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 125: {'val_loss': '29.09345', 'train_loss': '60.79712'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=62]Epoch 126: {'val_loss': '28.85663', 'train_loss': '67.51322'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=62]Epoch 127: {'val_loss': '29.40578', 'train_loss': '65.68462'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=62]Epoch 128: {'val_loss': '28.84626', 'train_loss': '66.81617'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=62]Epoch 129: {'val_loss': '28.51884', 'train_loss': '63.20785'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=62]Epoch 130: {'val_loss': '28.66098', 'train_loss': '67.05098'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=62]Epoch 131: {'val_loss': '29.30169', 'train_loss': '61.73111'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.06it/s, v_num=62]Epoch 132: {'val_loss': '29.22422', 'train_loss': '62.63735'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=62]Epoch 133: {'val_loss': '28.54845', 'train_loss': '65.56537'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=62]Epoch 134: {'val_loss': '28.59962', 'train_loss': '66.06203'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=62]Epoch 135: {'val_loss': '28.71376', 'train_loss': '64.69534'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=62]Epoch 136: {'val_loss': '28.77303', 'train_loss': '63.22812'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=62]Epoch 137: {'val_loss': '28.78554', 'train_loss': '65.89676'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=62]Epoch 138: {'val_loss': '29.40576', 'train_loss': '64.46857'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 139: {'val_loss': '28.80019', 'train_loss': '67.74654'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=62]Epoch 140: {'val_loss': '28.66294', 'train_loss': '68.52334'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=62]Epoch 141: {'val_loss': '28.54235', 'train_loss': '66.60534'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=62]Epoch 142: {'val_loss': '28.49992', 'train_loss': '58.93282'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=62]Epoch 143: {'val_loss': '28.81791', 'train_loss': '65.19623'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=62]Epoch 144: {'val_loss': '29.75558', 'train_loss': '64.43654'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=62]Epoch 145: {'val_loss': '29.59446', 'train_loss': '68.24711'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=62]Epoch 146: {'val_loss': '28.84295', 'train_loss': '59.24982'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=62]Epoch 147: {'val_loss': '28.62015', 'train_loss': '67.17596'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=62]Epoch 148: {'val_loss': '28.69363', 'train_loss': '63.20819'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=62]Epoch 149: {'val_loss': '29.09047', 'train_loss': '63.50043'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=62]Epoch 150: {'val_loss': '29.39647', 'train_loss': '60.64656'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=62]Epoch 151: {'val_loss': '28.80130', 'train_loss': '66.49832'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=62]Epoch 152: {'val_loss': '28.44528', 'train_loss': '59.26053'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=62]Epoch 153: {'val_loss': '28.92630', 'train_loss': '65.68083'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=62]Epoch 154: {'val_loss': '28.85369', 'train_loss': '63.69726'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=63]Epoch 0: {'val_loss': '4136.31006', 'train_loss': '368.71713'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  8.82it/s, v_num=63]Epoch 1: {'val_loss': '173.23369', 'train_loss': '138.33992'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=63]Epoch 2: {'val_loss': '42.71150', 'train_loss': '137.48430'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 3: {'val_loss': '95.49483', 'train_loss': '129.62881'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 4: {'val_loss': '88.45942', 'train_loss': '118.26128'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 5: {'val_loss': '53.66148', 'train_loss': '108.86086'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=63]Epoch 6: {'val_loss': '41.38525', 'train_loss': '101.03043'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=63]Epoch 7: {'val_loss': '48.77527', 'train_loss': '101.63710'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=63]Epoch 8: {'val_loss': '39.86829', 'train_loss': '103.12569'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=63]Epoch 9: {'val_loss': '38.21452', 'train_loss': '104.22485'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=63]Epoch 10: {'val_loss': '39.71111', 'train_loss': '106.11113'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 11: {'val_loss': '38.66499', 'train_loss': '101.33966'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=63]Epoch 12: {'val_loss': '35.75272', 'train_loss': '100.75687'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=63]Epoch 13: {'val_loss': '58.10831', 'train_loss': '109.16611'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=63]Epoch 14: {'val_loss': '39.43126', 'train_loss': '122.56536'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=63]Epoch 15: {'val_loss': '60.34980', 'train_loss': '108.50454'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 16: {'val_loss': '54.89776', 'train_loss': '93.55064'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 17: {'val_loss': '58.38332', 'train_loss': '99.71334'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=63]Epoch 18: {'val_loss': '43.72456', 'train_loss': '88.99901'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=63]Epoch 19: {'val_loss': '93.06393', 'train_loss': '96.54069'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 20: {'val_loss': '37.22830', 'train_loss': '88.55000'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.25it/s, v_num=63]Epoch 21: {'val_loss': '43.82330', 'train_loss': '96.69058'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=63]Epoch 22: {'val_loss': '36.90149', 'train_loss': '93.04255'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.09it/s, v_num=63]Epoch 23: {'val_loss': '40.48015', 'train_loss': '87.01854'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=63]Epoch 24: {'val_loss': '35.06212', 'train_loss': '85.00183'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 25: {'val_loss': '39.87472', 'train_loss': '87.94072'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=63]Epoch 26: {'val_loss': '65.91972', 'train_loss': '99.00999'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 27: {'val_loss': '35.33788', 'train_loss': '87.52287'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=63]Epoch 28: {'val_loss': '36.24004', 'train_loss': '88.63560'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=63]Epoch 29: {'val_loss': '33.75330', 'train_loss': '97.49711'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 30: {'val_loss': '52.71223', 'train_loss': '87.42831'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=63]Epoch 31: {'val_loss': '37.13921', 'train_loss': '84.15176'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=63]Epoch 32: {'val_loss': '106.17164', 'train_loss': '91.47250'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=63]Epoch 33: {'val_loss': '35.11535', 'train_loss': '87.47446'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 34: {'val_loss': '41.87323', 'train_loss': '89.51873'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 35: {'val_loss': '41.93112', 'train_loss': '90.84587'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=63]Epoch 36: {'val_loss': '34.77124', 'train_loss': '80.59520'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=63]Epoch 37: {'val_loss': '33.94023', 'train_loss': '86.30504'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 38: {'val_loss': '35.32059', 'train_loss': '83.92271'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 39: {'val_loss': '33.68292', 'train_loss': '84.47562'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=63]Epoch 40: {'val_loss': '33.13098', 'train_loss': '81.15280'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=63]Epoch 41: {'val_loss': '36.75440', 'train_loss': '84.40293'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 42: {'val_loss': '35.08867', 'train_loss': '80.07803'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 43: {'val_loss': '31.88788', 'train_loss': '81.57205'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=63]Epoch 44: {'val_loss': '31.83919', 'train_loss': '82.26295'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00, 10.28it/s, v_num=63]Epoch 45: {'val_loss': '32.88437', 'train_loss': '79.64996'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 46: {'val_loss': '34.77394', 'train_loss': '75.46482'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 47: {'val_loss': '33.45346', 'train_loss': '76.45456'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 48: {'val_loss': '44.77501', 'train_loss': '80.37320'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.18it/s, v_num=63]Epoch 49: {'val_loss': '30.98562', 'train_loss': '77.45013'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 50: {'val_loss': '36.70005', 'train_loss': '78.61891'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 51: {'val_loss': '51.51825', 'train_loss': '78.92359'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 52: {'val_loss': '32.72355', 'train_loss': '83.11922'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=63]Epoch 53: {'val_loss': '44.56078', 'train_loss': '78.03151'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 54: {'val_loss': '33.25021', 'train_loss': '79.63837'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  9.15it/s, v_num=63]Epoch 55: {'val_loss': '32.09691', 'train_loss': '75.88968'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 56: {'val_loss': '31.25082', 'train_loss': '76.30125'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 57: {'val_loss': '31.11146', 'train_loss': '83.58257'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=63]Epoch 58: {'val_loss': '31.32579', 'train_loss': '74.63422'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 59: {'val_loss': '31.74639', 'train_loss': '77.18342'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=63]Epoch 60: {'val_loss': '31.46035', 'train_loss': '75.10332'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=63]Epoch 61: {'val_loss': '31.20063', 'train_loss': '65.21806'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=63]Epoch 62: {'val_loss': '31.41236', 'train_loss': '72.85178'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 63: {'val_loss': '30.19690', 'train_loss': '69.44584'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=63]Epoch 64: {'val_loss': '30.84291', 'train_loss': '69.14600'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=63]Epoch 65: {'val_loss': '31.01003', 'train_loss': '74.65645'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=63]Epoch 66: {'val_loss': '29.52543', 'train_loss': '71.49831'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 67: {'val_loss': '29.65807', 'train_loss': '71.07563'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=63]Epoch 68: {'val_loss': '28.85744', 'train_loss': '68.34198'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=63]Epoch 69: {'val_loss': '29.35607', 'train_loss': '73.79720'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 70: {'val_loss': '29.69700', 'train_loss': '68.97427'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 71: {'val_loss': '31.27109', 'train_loss': '75.78496'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 72: {'val_loss': '31.11523', 'train_loss': '76.55359'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=63]Epoch 73: {'val_loss': '31.63197', 'train_loss': '71.64864'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 74: {'val_loss': '28.91971', 'train_loss': '72.97803'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=63]Epoch 75: {'val_loss': '28.54608', 'train_loss': '67.25808'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=63]Epoch 76: {'val_loss': '28.84050', 'train_loss': '76.03690'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=63]Epoch 77: {'val_loss': '28.63000', 'train_loss': '72.24015'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 78: {'val_loss': '30.99156', 'train_loss': '67.46825'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00, 10.27it/s, v_num=63]Epoch 79: {'val_loss': '29.04724', 'train_loss': '69.23975'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=63]Epoch 80: {'val_loss': '29.72400', 'train_loss': '68.46314'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=63]Epoch 81: {'val_loss': '29.87342', 'train_loss': '69.24864'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 82: {'val_loss': '29.62626', 'train_loss': '65.87307'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 83: {'val_loss': '29.15470', 'train_loss': '70.93050'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=63]Epoch 84: {'val_loss': '29.33621', 'train_loss': '64.04350'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=63]Epoch 85: {'val_loss': '30.37864', 'train_loss': '72.78233'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 86: {'val_loss': '28.88091', 'train_loss': '66.27386'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 87: {'val_loss': '29.98807', 'train_loss': '68.98294'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=63]Epoch 88: {'val_loss': '29.28058', 'train_loss': '72.05661'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 89: {'val_loss': '29.44500', 'train_loss': '70.76371'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 90: {'val_loss': '29.45620', 'train_loss': '73.29642'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 91: {'val_loss': '30.33616', 'train_loss': '69.08278'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.09it/s, v_num=63]Epoch 92: {'val_loss': '29.43802', 'train_loss': '66.57706'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=63]Epoch 93: {'val_loss': '29.07182', 'train_loss': '70.14314'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=63]Epoch 94: {'val_loss': '29.47153', 'train_loss': '65.97894'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 95: {'val_loss': '29.06122', 'train_loss': '66.60726'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=63]Epoch 96: {'val_loss': '28.92020', 'train_loss': '72.23095'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=63]Epoch 97: {'val_loss': '29.32223', 'train_loss': '69.81324'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 98: {'val_loss': '28.91127', 'train_loss': '69.62802'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=63]Epoch 99: {'val_loss': '28.97838', 'train_loss': '74.17919'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=63]Epoch 100: {'val_loss': '28.98536', 'train_loss': '70.69820'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=63]Epoch 101: {'val_loss': '28.94724', 'train_loss': '68.15475'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 102: {'val_loss': '32.30730', 'train_loss': '75.18101'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 103: {'val_loss': '29.84992', 'train_loss': '67.79510'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=63]Epoch 104: {'val_loss': '29.26844', 'train_loss': '69.18910'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=63]Epoch 105: {'val_loss': '29.22674', 'train_loss': '72.29098'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=63]Epoch 106: {'val_loss': '29.17715', 'train_loss': '68.39885'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 107: {'val_loss': '29.59220', 'train_loss': '65.53493'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=63]Epoch 108: {'val_loss': '29.22632', 'train_loss': '70.39674'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=63]Epoch 109: {'val_loss': '29.40397', 'train_loss': '67.25372'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=63]Epoch 110: {'val_loss': '29.03811', 'train_loss': '67.37067'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=63]Epoch 111: {'val_loss': '29.28878', 'train_loss': '69.42544'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 112: {'val_loss': '29.18381', 'train_loss': '66.78192'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.09it/s, v_num=63]Epoch 113: {'val_loss': '29.13716', 'train_loss': '64.07532'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=63]Epoch 114: {'val_loss': '29.21285', 'train_loss': '72.05292'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 115: {'val_loss': '29.40856', 'train_loss': '66.26930'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=63]Epoch 116: {'val_loss': '29.24118', 'train_loss': '70.92282'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=63]Epoch 117: {'val_loss': '29.31696', 'train_loss': '68.25306'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  8.82it/s, v_num=63]Epoch 118: {'val_loss': '29.25670', 'train_loss': '64.19921'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=63]Epoch 119: {'val_loss': '29.15413', 'train_loss': '66.43023'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=63]Epoch 120: {'val_loss': '29.55364', 'train_loss': '69.05221'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=63]Epoch 121: {'val_loss': '29.50886', 'train_loss': '67.54025'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.09it/s, v_num=63]Epoch 122: {'val_loss': '29.55262', 'train_loss': '67.02004'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=63]Epoch 123: {'val_loss': '28.96476', 'train_loss': '71.96947'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=63]Epoch 124: {'val_loss': '29.81697', 'train_loss': '64.53347'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=63]Epoch 125: {'val_loss': '29.10696', 'train_loss': '63.50985'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=63]Epoch 126: {'val_loss': '28.94000', 'train_loss': '65.12718'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=63]Epoch 127: {'val_loss': '29.42955', 'train_loss': '72.42024'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=63]Epoch 128: {'val_loss': '29.55355', 'train_loss': '66.34578'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 129: {'val_loss': '29.03172', 'train_loss': '67.44785'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 130: {'val_loss': '28.90128', 'train_loss': '67.83390'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=63]Epoch 131: {'val_loss': '29.61658', 'train_loss': '69.82831'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=63]Epoch 132: {'val_loss': '29.44080', 'train_loss': '64.92685'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=63]Epoch 133: {'val_loss': '29.86772', 'train_loss': '66.07718'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 134: {'val_loss': '29.15061', 'train_loss': '64.12113'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=63]Epoch 135: {'val_loss': '28.93033', 'train_loss': '76.63995'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=63]Epoch 136: {'val_loss': '28.89805', 'train_loss': '74.16793'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=63]Epoch 137: {'val_loss': '28.85736', 'train_loss': '64.13583'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=63]Epoch 138: {'val_loss': '28.87358', 'train_loss': '68.67570'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=63]Epoch 139: {'val_loss': '28.82263', 'train_loss': '69.31845'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=63]Epoch 140: {'val_loss': '29.26909', 'train_loss': '63.71907'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 141: {'val_loss': '29.62508', 'train_loss': '72.35113'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=63]Epoch 142: {'val_loss': '29.66931', 'train_loss': '67.06982'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=63]Epoch 143: {'val_loss': '30.19240', 'train_loss': '67.83947'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 144: {'val_loss': '29.19190', 'train_loss': '66.21926'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=63]Epoch 145: {'val_loss': '29.61933', 'train_loss': '69.81928'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=63]Epoch 146: {'val_loss': '29.10148', 'train_loss': '67.18003'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=63]Epoch 147: {'val_loss': '30.84855', 'train_loss': '65.53054'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=63]Epoch 148: {'val_loss': '29.71257', 'train_loss': '70.81026'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=63]Epoch 149: {'val_loss': '29.15810', 'train_loss': '65.31540'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 150: {'val_loss': '29.12875', 'train_loss': '69.17574'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=63]Epoch 151: {'val_loss': '29.25637', 'train_loss': '68.83183'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=63]Epoch 152: {'val_loss': '29.07481', 'train_loss': '66.97046'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=63]Epoch 153: {'val_loss': '29.27737', 'train_loss': '63.65834'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=63]Epoch 154: {'val_loss': '29.27939', 'train_loss': '66.31901'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00, 10.23it/s, v_num=64]Epoch 0: {'val_loss': '7883.35400', 'train_loss': '324.61374'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=64]Epoch 1: {'val_loss': '406.03116', 'train_loss': '128.01413'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=64]Epoch 2: {'val_loss': '52.87502', 'train_loss': '111.25172'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=64]Epoch 3: {'val_loss': '67.27842', 'train_loss': '108.39975'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 4: {'val_loss': '69.38286', 'train_loss': '98.87345'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 5: {'val_loss': '57.57101', 'train_loss': '99.60628'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 6: {'val_loss': '39.65199', 'train_loss': '97.00467'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=64]Epoch 7: {'val_loss': '56.47433', 'train_loss': '101.13854'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=64]Epoch 8: {'val_loss': '41.85340', 'train_loss': '101.45554'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 9: {'val_loss': '54.87981', 'train_loss': '102.66061'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=64]Epoch 10: {'val_loss': '36.86613', 'train_loss': '103.92538'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.24it/s, v_num=64]Epoch 11: {'val_loss': '44.22576', 'train_loss': '97.15439'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=64]Epoch 12: {'val_loss': '61.53222', 'train_loss': '101.34419'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 13: {'val_loss': '39.60716', 'train_loss': '92.99061'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=64]Epoch 14: {'val_loss': '47.49885', 'train_loss': '96.41632'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=64]Epoch 15: {'val_loss': '38.39859', 'train_loss': '102.44095'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=64]Epoch 16: {'val_loss': '67.21462', 'train_loss': '107.08626'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=64]Epoch 17: {'val_loss': '73.35814', 'train_loss': '100.23685'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 18: {'val_loss': '38.59472', 'train_loss': '89.68978'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.17it/s, v_num=64]Epoch 19: {'val_loss': '36.52374', 'train_loss': '82.17647'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=64]Epoch 20: {'val_loss': '35.26735', 'train_loss': '86.65314'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=64]Epoch 21: {'val_loss': '40.13697', 'train_loss': '86.07761'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 22: {'val_loss': '55.09336', 'train_loss': '87.70335'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=64]Epoch 23: {'val_loss': '63.03105', 'train_loss': '91.27087'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 24: {'val_loss': '35.34181', 'train_loss': '86.23651'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=64]Epoch 25: {'val_loss': '48.44472', 'train_loss': '86.46869'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 26: {'val_loss': '46.66166', 'train_loss': '80.31171'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 27: {'val_loss': '33.79591', 'train_loss': '76.85064'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.16it/s, v_num=64]Epoch 28: {'val_loss': '33.80073', 'train_loss': '85.70832'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=64]Epoch 29: {'val_loss': '33.37863', 'train_loss': '85.31306'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00,  9.58it/s, v_num=64]Epoch 30: {'val_loss': '32.55949', 'train_loss': '79.50584'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=64]Epoch 31: {'val_loss': '35.62486', 'train_loss': '77.59911'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 32: {'val_loss': '35.74858', 'train_loss': '78.03586'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 33: {'val_loss': '33.08894', 'train_loss': '83.49082'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=64]Epoch 34: {'val_loss': '30.82659', 'train_loss': '76.10696'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00,  9.06it/s, v_num=64]Epoch 35: {'val_loss': '33.21244', 'train_loss': '74.69724'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=64]Epoch 36: {'val_loss': '46.96498', 'train_loss': '76.82803'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=64]Epoch 37: {'val_loss': '30.90254', 'train_loss': '79.41350'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=64]Epoch 38: {'val_loss': '30.41190', 'train_loss': '78.43771'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.22it/s, v_num=64]Epoch 39: {'val_loss': '33.17497', 'train_loss': '82.80145'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=64]Epoch 40: {'val_loss': '35.18562', 'train_loss': '78.03730'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 41: {'val_loss': '35.60734', 'train_loss': '80.39153'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 42: {'val_loss': '30.06028', 'train_loss': '77.01328'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=64]Epoch 43: {'val_loss': '34.83193', 'train_loss': '75.95979'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=64]Epoch 44: {'val_loss': '33.76471', 'train_loss': '69.44791'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 45: {'val_loss': '28.45524', 'train_loss': '71.50163'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=64]Epoch 46: {'val_loss': '27.26324', 'train_loss': '78.97128'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 47: {'val_loss': '28.79936', 'train_loss': '72.95551'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 48: {'val_loss': '28.32819', 'train_loss': '70.59093'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=64]Epoch 49: {'val_loss': '28.26870', 'train_loss': '73.35361'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 50: {'val_loss': '27.41012', 'train_loss': '83.82063'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.56it/s, v_num=64]Epoch 51: {'val_loss': '31.37646', 'train_loss': '74.18478'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=64]Epoch 52: {'val_loss': '58.02505', 'train_loss': '70.91887'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 53: {'val_loss': '33.45585', 'train_loss': '70.91489'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=64]Epoch 54: {'val_loss': '35.84258', 'train_loss': '69.90255'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=64]Epoch 55: {'val_loss': '32.76124', 'train_loss': '70.90237'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=64]Epoch 56: {'val_loss': '26.61658', 'train_loss': '70.23036'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 57: {'val_loss': '27.39588', 'train_loss': '73.21936'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=64]Epoch 58: {'val_loss': '28.50121', 'train_loss': '70.13819'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 59: {'val_loss': '31.51851', 'train_loss': '71.41308'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 60: {'val_loss': '28.06509', 'train_loss': '69.32383'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=64]Epoch 61: {'val_loss': '29.17029', 'train_loss': '62.11716'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=64]Epoch 62: {'val_loss': '28.17396', 'train_loss': '68.33758'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=64]Epoch 63: {'val_loss': '28.06363', 'train_loss': '65.96914'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=64]Epoch 64: {'val_loss': '28.66333', 'train_loss': '67.54453'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 65: {'val_loss': '26.81094', 'train_loss': '63.97873'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=64]Epoch 66: {'val_loss': '33.76765', 'train_loss': '67.74131'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 67: {'val_loss': '27.47878', 'train_loss': '64.76604'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=64]Epoch 68: {'val_loss': '27.18423', 'train_loss': '64.99644'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=64]Epoch 69: {'val_loss': '26.74526', 'train_loss': '67.74458'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=64]Epoch 70: {'val_loss': '27.66928', 'train_loss': '65.45428'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 71: {'val_loss': '27.49867', 'train_loss': '66.73045'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 72: {'val_loss': '29.59529', 'train_loss': '59.91013'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 73: {'val_loss': '26.89972', 'train_loss': '67.29578'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=64]Epoch 74: {'val_loss': '27.37871', 'train_loss': '71.08257'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 75: {'val_loss': '26.96598', 'train_loss': '66.73535'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=64]Epoch 76: {'val_loss': '27.40158', 'train_loss': '66.72426'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=64]Epoch 77: {'val_loss': '27.32162', 'train_loss': '63.57818'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 78: {'val_loss': '26.94000', 'train_loss': '62.48814'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=64]Epoch 79: {'val_loss': '27.08233', 'train_loss': '62.79231'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=64]Epoch 80: {'val_loss': '26.82862', 'train_loss': '60.92080'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=64]Epoch 81: {'val_loss': '26.59810', 'train_loss': '61.74334'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 82: {'val_loss': '26.81699', 'train_loss': '62.59954'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=64]Epoch 83: {'val_loss': '26.79896', 'train_loss': '62.36365'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=64]Epoch 84: {'val_loss': '26.62886', 'train_loss': '62.66829'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=64]Epoch 85: {'val_loss': '27.12549', 'train_loss': '64.16723'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=64]Epoch 86: {'val_loss': '26.38389', 'train_loss': '70.10026'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 87: {'val_loss': '26.17734', 'train_loss': '71.69897'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=64]Epoch 88: {'val_loss': '26.38926', 'train_loss': '59.55814'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=64]Epoch 89: {'val_loss': '26.20924', 'train_loss': '66.02090'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.51it/s, v_num=64]Epoch 90: {'val_loss': '26.56526', 'train_loss': '67.36751'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=64]Epoch 91: {'val_loss': '28.09708', 'train_loss': '63.88995'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=64]Epoch 92: {'val_loss': '28.51237', 'train_loss': '64.17335'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=64]Epoch 93: {'val_loss': '26.54381', 'train_loss': '64.52998'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 94: {'val_loss': '26.50717', 'train_loss': '62.99843'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=64]Epoch 95: {'val_loss': '26.51019', 'train_loss': '67.03204'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=64]Epoch 96: {'val_loss': '27.16832', 'train_loss': '66.71256'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 97: {'val_loss': '26.79694', 'train_loss': '64.59972'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=64]Epoch 98: {'val_loss': '26.77174', 'train_loss': '62.63743'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=64]Epoch 99: {'val_loss': '27.50006', 'train_loss': '63.07502'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=64]Epoch 100: {'val_loss': '26.53668', 'train_loss': '61.27670'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 101: {'val_loss': '27.08503', 'train_loss': '66.31130'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=64]Epoch 102: {'val_loss': '26.95282', 'train_loss': '62.54748'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.17it/s, v_num=64]Epoch 103: {'val_loss': '27.16296', 'train_loss': '64.09780'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 104: {'val_loss': '28.01937', 'train_loss': '68.37143'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=64]Epoch 105: {'val_loss': '27.68617', 'train_loss': '63.67834'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 106: {'val_loss': '26.95748', 'train_loss': '61.09872'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 107: {'val_loss': '27.88664', 'train_loss': '61.29823'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=64]Epoch 108: {'val_loss': '27.37590', 'train_loss': '59.90443'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 109: {'val_loss': '26.95362', 'train_loss': '66.60432'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=64]Epoch 110: {'val_loss': '27.16495', 'train_loss': '68.76728'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 111: {'val_loss': '27.02693', 'train_loss': '64.47581'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=64]Epoch 112: {'val_loss': '27.17511', 'train_loss': '64.30519'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=64]Epoch 113: {'val_loss': '27.29348', 'train_loss': '64.69659'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=64]Epoch 114: {'val_loss': '27.68513', 'train_loss': '65.29383'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=64]Epoch 115: {'val_loss': '27.18196', 'train_loss': '64.31496'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 116: {'val_loss': '27.09046', 'train_loss': '60.75409'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=64]Epoch 117: {'val_loss': '27.46455', 'train_loss': '60.91857'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.12it/s, v_num=64]Epoch 118: {'val_loss': '27.01339', 'train_loss': '61.19622'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=64]Epoch 119: {'val_loss': '26.92592', 'train_loss': '64.54640'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=64]Epoch 120: {'val_loss': '27.21214', 'train_loss': '60.54340'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 121: {'val_loss': '27.36207', 'train_loss': '62.74406'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=64]Epoch 122: {'val_loss': '27.03108', 'train_loss': '62.30253'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.13it/s, v_num=64]Epoch 123: {'val_loss': '27.16638', 'train_loss': '64.93599'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00, 10.20it/s, v_num=64]Epoch 124: {'val_loss': '26.94363', 'train_loss': '69.85178'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=64]Epoch 125: {'val_loss': '26.84645', 'train_loss': '64.48973'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 126: {'val_loss': '26.97240', 'train_loss': '64.37716'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 127: {'val_loss': '27.04025', 'train_loss': '61.26973'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00,  9.14it/s, v_num=64]Epoch 128: {'val_loss': '26.96573', 'train_loss': '69.55843'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=64]Epoch 129: {'val_loss': '26.97885', 'train_loss': '61.71399'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=64]Epoch 130: {'val_loss': '27.52415', 'train_loss': '63.41725'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=64]Epoch 131: {'val_loss': '26.91648', 'train_loss': '63.89686'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 132: {'val_loss': '27.37646', 'train_loss': '63.82070'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=64]Epoch 133: {'val_loss': '27.09645', 'train_loss': '64.43143'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=64]Epoch 134: {'val_loss': '26.81359', 'train_loss': '62.61544'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 135: {'val_loss': '26.79445', 'train_loss': '63.93653'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=64]Epoch 136: {'val_loss': '26.82841', 'train_loss': '68.27517'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 137: {'val_loss': '27.00078', 'train_loss': '58.54749'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=64]Epoch 138: {'val_loss': '26.94010', 'train_loss': '69.58389'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=64]Epoch 139: {'val_loss': '26.75014', 'train_loss': '65.09531'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=64]Epoch 140: {'val_loss': '26.61248', 'train_loss': '70.76938'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=64]Epoch 141: {'val_loss': '27.13639', 'train_loss': '61.98101'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=64]Epoch 142: {'val_loss': '27.00440', 'train_loss': '63.01514'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=64]Epoch 143: {'val_loss': '26.98532', 'train_loss': '66.81676'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 144: {'val_loss': '26.79279', 'train_loss': '62.63329'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=64]Epoch 145: {'val_loss': '27.12292', 'train_loss': '66.80128'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 146: {'val_loss': '26.84083', 'train_loss': '64.33237'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=64]Epoch 147: {'val_loss': '26.80743', 'train_loss': '62.06494'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=64]Epoch 148: {'val_loss': '27.31420', 'train_loss': '59.21877'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00, 10.17it/s, v_num=64]Epoch 149: {'val_loss': '27.03069', 'train_loss': '61.40870'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=64]Epoch 150: {'val_loss': '26.81225', 'train_loss': '65.22080'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=64]Epoch 151: {'val_loss': '27.13208', 'train_loss': '69.47987'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=64]Epoch 152: {'val_loss': '27.01870', 'train_loss': '69.00232'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=64]Epoch 153: {'val_loss': '26.79624', 'train_loss': '66.51870'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=64]Epoch 154: {'val_loss': '27.14929', 'train_loss': '59.91072'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=65]Epoch 0: {'val_loss': '4626.93750', 'train_loss': '366.42105'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 1: {'val_loss': '138.80464', 'train_loss': '133.86641'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 2: {'val_loss': '46.87202', 'train_loss': '114.82355'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 3: {'val_loss': '39.54099', 'train_loss': '110.04006'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=65]Epoch 4: {'val_loss': '43.94934', 'train_loss': '113.70194'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=65]Epoch 5: {'val_loss': '45.31500', 'train_loss': '112.93752'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=65]Epoch 6: {'val_loss': '106.10071', 'train_loss': '109.53793'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=65]Epoch 7: {'val_loss': '53.73258', 'train_loss': '111.25768'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=65]Epoch 8: {'val_loss': '78.63786', 'train_loss': '107.06559'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=65]Epoch 9: {'val_loss': '37.96530', 'train_loss': '107.00096'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.01it/s, v_num=65]Epoch 10: {'val_loss': '37.57255', 'train_loss': '101.99052'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 11: {'val_loss': '38.49362', 'train_loss': '106.93252'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 12: {'val_loss': '89.08154', 'train_loss': '118.53733'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=65]Epoch 13: {'val_loss': '44.46185', 'train_loss': '99.05270'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 14: {'val_loss': '41.45871', 'train_loss': '100.40231'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00, 10.18it/s, v_num=65]Epoch 15: {'val_loss': '39.58133', 'train_loss': '97.96662'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 16: {'val_loss': '50.50562', 'train_loss': '103.71983'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.19it/s, v_num=65]Epoch 17: {'val_loss': '92.00413', 'train_loss': '100.17542'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=65]Epoch 18: {'val_loss': '36.74435', 'train_loss': '98.70379'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.65it/s, v_num=65]Epoch 19: {'val_loss': '39.55297', 'train_loss': '98.38126'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=65]Epoch 20: {'val_loss': '40.83365', 'train_loss': '93.62260'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=65]Epoch 21: {'val_loss': '66.93391', 'train_loss': '88.82325'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=65]Epoch 22: {'val_loss': '39.40308', 'train_loss': '101.05455'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  8.93it/s, v_num=65]Epoch 23: {'val_loss': '62.65263', 'train_loss': '86.10453'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=65]Epoch 24: {'val_loss': '44.17355', 'train_loss': '87.48484'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=65]Epoch 25: {'val_loss': '35.96638', 'train_loss': '95.45527'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 26: {'val_loss': '37.09177', 'train_loss': '87.75236'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 27: {'val_loss': '35.78004', 'train_loss': '89.48563'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=65]Epoch 28: {'val_loss': '40.83392', 'train_loss': '86.03895'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 29: {'val_loss': '36.60042', 'train_loss': '84.19037'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 30: {'val_loss': '34.11958', 'train_loss': '84.43909'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 31: {'val_loss': '34.05860', 'train_loss': '83.12868'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=65]Epoch 32: {'val_loss': '35.03546', 'train_loss': '78.81744'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 33: {'val_loss': '35.71677', 'train_loss': '82.53027'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=65]Epoch 34: {'val_loss': '35.48586', 'train_loss': '87.39531'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=65]Epoch 35: {'val_loss': '34.40557', 'train_loss': '80.75014'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 36: {'val_loss': '41.43135', 'train_loss': '87.15790'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 37: {'val_loss': '34.47660', 'train_loss': '80.60583'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=65]Epoch 38: {'val_loss': '34.71630', 'train_loss': '85.38710'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 39: {'val_loss': '33.39451', 'train_loss': '87.13395'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=65]Epoch 40: {'val_loss': '36.76894', 'train_loss': '84.83619'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 41: {'val_loss': '32.92446', 'train_loss': '79.39246'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=65]Epoch 42: {'val_loss': '36.45926', 'train_loss': '80.51472'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=65]Epoch 43: {'val_loss': '34.23262', 'train_loss': '78.38285'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=65]Epoch 44: {'val_loss': '32.15102', 'train_loss': '75.81218'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  8.82it/s, v_num=65]Epoch 45: {'val_loss': '33.54876', 'train_loss': '81.29214'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 46: {'val_loss': '33.17496', 'train_loss': '76.95528'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 47: {'val_loss': '32.89013', 'train_loss': '78.15004'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 48: {'val_loss': '32.49205', 'train_loss': '72.18619'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=65]Epoch 49: {'val_loss': '32.29744', 'train_loss': '78.82735'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=65]Epoch 50: {'val_loss': '36.89383', 'train_loss': '75.64664'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=65]Epoch 51: {'val_loss': '31.82395', 'train_loss': '76.67803'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=65]Epoch 52: {'val_loss': '33.86287', 'train_loss': '77.50214'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=65]Epoch 53: {'val_loss': '33.23394', 'train_loss': '75.55250'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 54: {'val_loss': '34.52091', 'train_loss': '83.42390'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 55: {'val_loss': '33.33747', 'train_loss': '71.15668'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=65]Epoch 56: {'val_loss': '34.68642', 'train_loss': '73.73257'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 57: {'val_loss': '32.00056', 'train_loss': '79.77012'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=65]Epoch 58: {'val_loss': '33.16032', 'train_loss': '71.82570'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=65]Epoch 59: {'val_loss': '32.40041', 'train_loss': '77.02923'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=65]Epoch 60: {'val_loss': '32.23457', 'train_loss': '75.84820'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 61: {'val_loss': '34.75224', 'train_loss': '75.38554'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.21it/s, v_num=65]Epoch 62: {'val_loss': '32.52353', 'train_loss': '78.09841'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 63: {'val_loss': '32.05165', 'train_loss': '70.16588'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=65]Epoch 64: {'val_loss': '32.36797', 'train_loss': '79.99828'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 65: {'val_loss': '33.05626', 'train_loss': '69.56379'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 66: {'val_loss': '34.10805', 'train_loss': '73.65788'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=65]Epoch 67: {'val_loss': '32.67373', 'train_loss': '75.75111'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 68: {'val_loss': '33.02243', 'train_loss': '72.08773'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=65]Epoch 69: {'val_loss': '31.91123', 'train_loss': '75.72897'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 70: {'val_loss': '32.94295', 'train_loss': '73.66071'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=65]Epoch 71: {'val_loss': '32.01789', 'train_loss': '74.68515'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=65]Epoch 72: {'val_loss': '32.32830', 'train_loss': '69.69827'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=65]Epoch 73: {'val_loss': '32.09527', 'train_loss': '70.77057'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=65]Epoch 74: {'val_loss': '33.22669', 'train_loss': '78.56710'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=65]Epoch 75: {'val_loss': '33.94800', 'train_loss': '78.21513'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 76: {'val_loss': '32.39187', 'train_loss': '70.80909'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.14it/s, v_num=65]Epoch 77: {'val_loss': '32.01667', 'train_loss': '75.00571'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 78: {'val_loss': '32.55091', 'train_loss': '75.77679'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.11it/s, v_num=65]Epoch 79: {'val_loss': '32.14217', 'train_loss': '75.33363'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=65]Epoch 80: {'val_loss': '32.14840', 'train_loss': '73.49540'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 81: {'val_loss': '32.86908', 'train_loss': '72.10424'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 82: {'val_loss': '32.41552', 'train_loss': '71.63033'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 83: {'val_loss': '32.09789', 'train_loss': '73.58102'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=65]Epoch 84: {'val_loss': '32.50934', 'train_loss': '72.50263'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 85: {'val_loss': '32.19973', 'train_loss': '71.07708'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=65]Epoch 86: {'val_loss': '31.85349', 'train_loss': '76.70112'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=65]Epoch 87: {'val_loss': '31.75324', 'train_loss': '72.15893'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=65]Epoch 88: {'val_loss': '32.53015', 'train_loss': '65.62067'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=65]Epoch 89: {'val_loss': '32.35024', 'train_loss': '75.18176'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 90: {'val_loss': '31.58699', 'train_loss': '72.47974'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=65]Epoch 91: {'val_loss': '32.47997', 'train_loss': '72.50430'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 92: {'val_loss': '31.99665', 'train_loss': '76.15476'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=65]Epoch 93: {'val_loss': '31.64762', 'train_loss': '74.98698'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 94: {'val_loss': '31.85461', 'train_loss': '73.32384'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 95: {'val_loss': '32.61750', 'train_loss': '74.92746'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.03it/s, v_num=65]Epoch 96: {'val_loss': '32.16895', 'train_loss': '74.72089'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 97: {'val_loss': '31.65714', 'train_loss': '71.87688'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 98: {'val_loss': '33.26203', 'train_loss': '75.63248'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=65]Epoch 99: {'val_loss': '31.94299', 'train_loss': '74.63562'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 100: {'val_loss': '32.27378', 'train_loss': '75.61195'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 101: {'val_loss': '32.91107', 'train_loss': '83.25629'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=65]Epoch 102: {'val_loss': '31.89559', 'train_loss': '76.41494'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=65]Epoch 103: {'val_loss': '31.85375', 'train_loss': '73.29445'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=65]Epoch 104: {'val_loss': '32.57668', 'train_loss': '71.68862'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 105: {'val_loss': '31.73920', 'train_loss': '72.92473'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 106: {'val_loss': '32.03585', 'train_loss': '70.96152'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=65]Epoch 107: {'val_loss': '32.09374', 'train_loss': '73.65540'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 108: {'val_loss': '31.83043', 'train_loss': '75.39260'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 109: {'val_loss': '31.73883', 'train_loss': '72.90849'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=65]Epoch 110: {'val_loss': '31.61903', 'train_loss': '75.43634'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 111: {'val_loss': '32.14191', 'train_loss': '69.88437'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=65]Epoch 112: {'val_loss': '32.34791', 'train_loss': '74.59711'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=65]Epoch 113: {'val_loss': '32.79627', 'train_loss': '74.14017'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 114: {'val_loss': '32.03382', 'train_loss': '69.95715'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 115: {'val_loss': '33.07660', 'train_loss': '68.94186'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=65]Epoch 116: {'val_loss': '31.99679', 'train_loss': '72.89478'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.06it/s, v_num=65]Epoch 117: {'val_loss': '31.39437', 'train_loss': '73.45670'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=65]Epoch 118: {'val_loss': '32.35678', 'train_loss': '78.70022'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 119: {'val_loss': '32.40566', 'train_loss': '74.68378'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=65]Epoch 120: {'val_loss': '33.54939', 'train_loss': '78.07382'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=65]Epoch 121: {'val_loss': '32.22069', 'train_loss': '69.48338'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 122: {'val_loss': '31.90718', 'train_loss': '71.90900'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=65]Epoch 123: {'val_loss': '31.84330', 'train_loss': '75.26022'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=65]Epoch 124: {'val_loss': '32.02155', 'train_loss': '71.97504'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 125: {'val_loss': '32.04052', 'train_loss': '72.33177'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.16it/s, v_num=65]Epoch 126: {'val_loss': '31.82897', 'train_loss': '76.02622'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=65]Epoch 127: {'val_loss': '32.33973', 'train_loss': '67.03737'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 128: {'val_loss': '31.94846', 'train_loss': '75.06275'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 129: {'val_loss': '31.49965', 'train_loss': '69.92027'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=65]Epoch 130: {'val_loss': '32.19256', 'train_loss': '71.08664'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 131: {'val_loss': '32.33757', 'train_loss': '73.43351'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=65]Epoch 132: {'val_loss': '32.26575', 'train_loss': '70.30607'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 133: {'val_loss': '32.45772', 'train_loss': '75.78797'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=65]Epoch 134: {'val_loss': '32.04882', 'train_loss': '71.73634'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00,  8.97it/s, v_num=65]Epoch 135: {'val_loss': '31.67271', 'train_loss': '80.06750'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=65]Epoch 136: {'val_loss': '31.75017', 'train_loss': '70.76379'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 137: {'val_loss': '31.93080', 'train_loss': '75.69904'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 138: {'val_loss': '32.21254', 'train_loss': '73.86646'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 139: {'val_loss': '31.66761', 'train_loss': '77.95542'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=65]Epoch 140: {'val_loss': '32.25248', 'train_loss': '69.98090'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=65]Epoch 141: {'val_loss': '32.47476', 'train_loss': '73.06730'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=65]Epoch 142: {'val_loss': '31.77232', 'train_loss': '74.76919'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=65]Epoch 143: {'val_loss': '33.55845', 'train_loss': '71.61487'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=65]Epoch 144: {'val_loss': '32.52388', 'train_loss': '71.81156'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=65]Epoch 145: {'val_loss': '32.20258', 'train_loss': '73.48907'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.07it/s, v_num=65]Epoch 146: {'val_loss': '32.82203', 'train_loss': '70.61200'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=65]Epoch 147: {'val_loss': '32.02251', 'train_loss': '71.57949'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=65]Epoch 148: {'val_loss': '32.75790', 'train_loss': '72.26885'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=65]Epoch 149: {'val_loss': '32.30239', 'train_loss': '69.21915'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=65]Epoch 150: {'val_loss': '32.28941', 'train_loss': '68.30059'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=65]Epoch 151: {'val_loss': '31.85190', 'train_loss': '69.13567'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=65]Epoch 152: {'val_loss': '32.43586', 'train_loss': '77.80119'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=65]Epoch 153: {'val_loss': '31.93098', 'train_loss': '69.72506'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=65]Epoch 154: {'val_loss': '31.88230', 'train_loss': '72.02579'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 0: {'val_loss': '2446.60229', 'train_loss': '379.31335'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 1: {'val_loss': '122.57745', 'train_loss': '139.73805'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.03it/s, v_num=66]Epoch 2: {'val_loss': '42.18090', 'train_loss': '119.34142'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 3: {'val_loss': '43.43066', 'train_loss': '117.57998'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 4: {'val_loss': '41.27747', 'train_loss': '126.43384'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 5: {'val_loss': '42.18755', 'train_loss': '107.40227'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 6: {'val_loss': '43.95890', 'train_loss': '113.34606'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=66]Epoch 7: {'val_loss': '39.49787', 'train_loss': '109.96854'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=66]Epoch 8: {'val_loss': '41.39336', 'train_loss': '98.95400'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 9: {'val_loss': '91.88884', 'train_loss': '109.78229'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=66]Epoch 10: {'val_loss': '43.27408', 'train_loss': '100.52753'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=66]Epoch 11: {'val_loss': '37.20537', 'train_loss': '102.54742'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=66]Epoch 12: {'val_loss': '46.29475', 'train_loss': '104.20590'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 13: {'val_loss': '37.77282', 'train_loss': '117.20410'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=66]Epoch 14: {'val_loss': '53.97369', 'train_loss': '102.89050'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 15: {'val_loss': '53.55304', 'train_loss': '100.45013'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=66]Epoch 16: {'val_loss': '39.53909', 'train_loss': '100.03555'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=66]Epoch 17: {'val_loss': '48.58957', 'train_loss': '102.85909'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=66]Epoch 18: {'val_loss': '75.97220', 'train_loss': '99.92228'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=66]Epoch 19: {'val_loss': '35.32779', 'train_loss': '100.04987'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 20: {'val_loss': '51.94872', 'train_loss': '92.23385'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 21: {'val_loss': '44.33288', 'train_loss': '86.61149'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 22: {'val_loss': '34.35122', 'train_loss': '89.62566'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 23: {'val_loss': '38.66196', 'train_loss': '102.18938'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=66]Epoch 24: {'val_loss': '49.67241', 'train_loss': '89.93526'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 25: {'val_loss': '35.54882', 'train_loss': '96.42017'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=66]Epoch 26: {'val_loss': '41.32368', 'train_loss': '92.99999'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=66]Epoch 27: {'val_loss': '33.84360', 'train_loss': '95.83073'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 28: {'val_loss': '44.70267', 'train_loss': '83.48817'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 29: {'val_loss': '35.16761', 'train_loss': '90.18558'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=66]Epoch 30: {'val_loss': '39.16623', 'train_loss': '91.67265'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.03it/s, v_num=66]Epoch 31: {'val_loss': '38.06559', 'train_loss': '89.51989'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 32: {'val_loss': '41.47366', 'train_loss': '88.68384'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.15it/s, v_num=66]Epoch 33: {'val_loss': '56.42608', 'train_loss': '88.40255'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 34: {'val_loss': '35.47141', 'train_loss': '86.27325'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=66]Epoch 35: {'val_loss': '35.45393', 'train_loss': '80.02887'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  9.52it/s, v_num=66]Epoch 36: {'val_loss': '32.56137', 'train_loss': '83.74062'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  8.76it/s, v_num=66]Epoch 37: {'val_loss': '33.34547', 'train_loss': '77.70429'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=66]Epoch 38: {'val_loss': '45.98626', 'train_loss': '79.66909'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=66]Epoch 39: {'val_loss': '32.93505', 'train_loss': '85.47047'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 40: {'val_loss': '43.65399', 'train_loss': '79.88232'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=66]Epoch 41: {'val_loss': '36.25125', 'train_loss': '84.69267'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00,  9.10it/s, v_num=66]Epoch 42: {'val_loss': '32.76050', 'train_loss': '74.63725'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 43: {'val_loss': '36.81850', 'train_loss': '74.96577'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 44: {'val_loss': '31.87134', 'train_loss': '75.81194'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=66]Epoch 45: {'val_loss': '29.74664', 'train_loss': '76.72479'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 46: {'val_loss': '32.97752', 'train_loss': '81.20094'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.03it/s, v_num=66]Epoch 47: {'val_loss': '34.00251', 'train_loss': '88.23765'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 48: {'val_loss': '30.08926', 'train_loss': '75.83318'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 49: {'val_loss': '32.00940', 'train_loss': '72.05082'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=66]Epoch 50: {'val_loss': '29.92662', 'train_loss': '72.79307'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00, 10.10it/s, v_num=66]Epoch 51: {'val_loss': '32.75530', 'train_loss': '74.89642'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=66]Epoch 52: {'val_loss': '31.44695', 'train_loss': '81.94014'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=66]Epoch 53: {'val_loss': '29.60970', 'train_loss': '74.13078'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=66]Epoch 54: {'val_loss': '30.24057', 'train_loss': '81.46935'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00, 10.13it/s, v_num=66]Epoch 55: {'val_loss': '29.58823', 'train_loss': '73.61612'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=66]Epoch 56: {'val_loss': '29.48769', 'train_loss': '76.24805'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 57: {'val_loss': '29.84775', 'train_loss': '76.42745'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 58: {'val_loss': '32.16108', 'train_loss': '78.79870'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=66]Epoch 59: {'val_loss': '29.67015', 'train_loss': '76.28996'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 60: {'val_loss': '30.53145', 'train_loss': '76.47003'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 61: {'val_loss': '28.39831', 'train_loss': '69.34049'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 62: {'val_loss': '29.89628', 'train_loss': '69.07521'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 63: {'val_loss': '28.74931', 'train_loss': '67.19714'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=66]Epoch 64: {'val_loss': '28.65266', 'train_loss': '73.40444'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=66]Epoch 65: {'val_loss': '29.66832', 'train_loss': '70.40212'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 66: {'val_loss': '28.47169', 'train_loss': '72.74796'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 67: {'val_loss': '27.86336', 'train_loss': '76.32642'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=66]Epoch 68: {'val_loss': '28.72544', 'train_loss': '69.05589'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 69: {'val_loss': '29.41828', 'train_loss': '73.06085'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=66]Epoch 70: {'val_loss': '29.22728', 'train_loss': '70.50858'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=66]Epoch 71: {'val_loss': '29.56941', 'train_loss': '76.36241'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 72: {'val_loss': '28.27268', 'train_loss': '78.45383'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 73: {'val_loss': '28.50708', 'train_loss': '70.79920'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 74: {'val_loss': '28.83911', 'train_loss': '71.49297'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 75: {'val_loss': '31.38139', 'train_loss': '63.58860'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=66]Epoch 76: {'val_loss': '28.28190', 'train_loss': '75.20087'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=66]Epoch 77: {'val_loss': '28.23970', 'train_loss': '71.17721'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=66]Epoch 78: {'val_loss': '28.85989', 'train_loss': '77.40589'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=66]Epoch 79: {'val_loss': '28.15612', 'train_loss': '71.28436'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 80: {'val_loss': '27.80801', 'train_loss': '69.46796'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 81: {'val_loss': '28.29893', 'train_loss': '69.74090'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=66]Epoch 82: {'val_loss': '27.68955', 'train_loss': '69.93085'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 83: {'val_loss': '28.32746', 'train_loss': '70.19040'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=66]Epoch 84: {'val_loss': '30.85409', 'train_loss': '71.21794'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 85: {'val_loss': '28.83045', 'train_loss': '76.47713'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 86: {'val_loss': '28.41155', 'train_loss': '67.90754'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 87: {'val_loss': '29.51221', 'train_loss': '67.81858'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 88: {'val_loss': '27.97993', 'train_loss': '72.71137'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=66]Epoch 89: {'val_loss': '28.05816', 'train_loss': '71.91650'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=66]Epoch 90: {'val_loss': '28.25411', 'train_loss': '67.59456'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=66]Epoch 91: {'val_loss': '28.82247', 'train_loss': '70.66494'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=66]Epoch 92: {'val_loss': '27.71091', 'train_loss': '73.04723'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 93: {'val_loss': '28.06577', 'train_loss': '69.18172'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 94: {'val_loss': '27.60987', 'train_loss': '70.10134'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 95: {'val_loss': '28.51845', 'train_loss': '67.22444'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=66]Epoch 96: {'val_loss': '28.76251', 'train_loss': '68.83148'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  9.04it/s, v_num=66]Epoch 97: {'val_loss': '28.47702', 'train_loss': '73.98700'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=66]Epoch 98: {'val_loss': '27.93340', 'train_loss': '64.74986'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=66]Epoch 99: {'val_loss': '27.90106', 'train_loss': '77.72807'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=66]Epoch 100: {'val_loss': '27.59369', 'train_loss': '72.67657'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=66]Epoch 101: {'val_loss': '27.47518', 'train_loss': '73.78349'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=66]Epoch 102: {'val_loss': '27.66491', 'train_loss': '70.26266'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=66]Epoch 103: {'val_loss': '27.68698', 'train_loss': '67.00099'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=66]Epoch 104: {'val_loss': '27.91674', 'train_loss': '74.15990'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 105: {'val_loss': '27.41998', 'train_loss': '67.03827'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 106: {'val_loss': '27.76275', 'train_loss': '67.60851'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=66]Epoch 107: {'val_loss': '27.66521', 'train_loss': '72.01415'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=66]Epoch 108: {'val_loss': '27.93427', 'train_loss': '68.70563'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=66]Epoch 109: {'val_loss': '28.35958', 'train_loss': '69.97553'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 110: {'val_loss': '27.75349', 'train_loss': '70.17762'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 111: {'val_loss': '28.00803', 'train_loss': '71.56648'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=66]Epoch 112: {'val_loss': '28.84028', 'train_loss': '64.27506'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=66]Epoch 113: {'val_loss': '28.05535', 'train_loss': '69.47428'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=66]Epoch 114: {'val_loss': '27.91806', 'train_loss': '69.97820'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=66]Epoch 115: {'val_loss': '28.11534', 'train_loss': '70.52629'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 116: {'val_loss': '28.20214', 'train_loss': '63.14993'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=66]Epoch 117: {'val_loss': '28.20313', 'train_loss': '65.82705'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 118: {'val_loss': '28.13959', 'train_loss': '67.00930'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=66]Epoch 119: {'val_loss': '27.37648', 'train_loss': '69.55875'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  8.94it/s, v_num=66]Epoch 120: {'val_loss': '27.44959', 'train_loss': '71.63510'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.29it/s, v_num=66]Epoch 121: {'val_loss': '27.72831', 'train_loss': '67.38280'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=66]Epoch 122: {'val_loss': '27.80906', 'train_loss': '68.61530'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=66]Epoch 123: {'val_loss': '27.44442', 'train_loss': '71.86369'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=66]Epoch 124: {'val_loss': '27.96097', 'train_loss': '67.31371'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  9.08it/s, v_num=66]Epoch 125: {'val_loss': '27.54234', 'train_loss': '71.46136'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 126: {'val_loss': '27.78351', 'train_loss': '69.26933'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 127: {'val_loss': '27.70719', 'train_loss': '69.79771'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=66]Epoch 128: {'val_loss': '27.82168', 'train_loss': '65.97940'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=66]Epoch 129: {'val_loss': '28.03687', 'train_loss': '68.44276'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=66]Epoch 130: {'val_loss': '28.04119', 'train_loss': '75.74805'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 131: {'val_loss': '27.70631', 'train_loss': '68.85855'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=66]Epoch 132: {'val_loss': '27.57751', 'train_loss': '68.51820'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  8.82it/s, v_num=66]Epoch 133: {'val_loss': '27.65317', 'train_loss': '65.77308'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=66]Epoch 134: {'val_loss': '27.79928', 'train_loss': '66.82126'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 135: {'val_loss': '27.88255', 'train_loss': '72.43460'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=66]Epoch 136: {'val_loss': '27.95714', 'train_loss': '67.88528'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=66]Epoch 137: {'val_loss': '27.75565', 'train_loss': '68.60442'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=66]Epoch 138: {'val_loss': '27.97424', 'train_loss': '68.56003'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.05it/s, v_num=66]Epoch 139: {'val_loss': '27.91060', 'train_loss': '73.89728'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=66]Epoch 140: {'val_loss': '28.08942', 'train_loss': '65.99252'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=66]Epoch 141: {'val_loss': '27.68089', 'train_loss': '66.32870'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 142: {'val_loss': '27.40077', 'train_loss': '71.50293'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=66]Epoch 143: {'val_loss': '27.74687', 'train_loss': '68.77008'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=66]Epoch 144: {'val_loss': '27.47099', 'train_loss': '64.66309'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=66]Epoch 145: {'val_loss': '27.97731', 'train_loss': '69.35668'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 146: {'val_loss': '28.25124', 'train_loss': '69.18597'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=66]Epoch 147: {'val_loss': '28.59076', 'train_loss': '71.84528'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=66]Epoch 148: {'val_loss': '28.36206', 'train_loss': '77.54627'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00, 10.11it/s, v_num=66]Epoch 149: {'val_loss': '27.43407', 'train_loss': '71.33924'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=66]Epoch 150: {'val_loss': '27.48556', 'train_loss': '69.37352'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=66]Epoch 151: {'val_loss': '27.86612', 'train_loss': '68.01825'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=66]Epoch 152: {'val_loss': '27.70514', 'train_loss': '68.96914'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=66]Epoch 153: {'val_loss': '27.66299', 'train_loss': '73.46317'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=66]Epoch 154: {'val_loss': '27.73322', 'train_loss': '69.66718'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 0: {'val_loss': '3401.54956', 'train_loss': '356.27646'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 1: {'val_loss': '228.33232', 'train_loss': '142.57239'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=67]Epoch 2: {'val_loss': '58.93584', 'train_loss': '129.81441'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=67]Epoch 3: {'val_loss': '38.34374', 'train_loss': '128.24133'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=67]Epoch 4: {'val_loss': '42.21762', 'train_loss': '130.85858'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 5: {'val_loss': '42.30820', 'train_loss': '126.70859'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=67]Epoch 6: {'val_loss': '39.98774', 'train_loss': '120.00099'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 7: {'val_loss': '57.76466', 'train_loss': '104.58002'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 8: {'val_loss': '47.73675', 'train_loss': '103.54926'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=67]Epoch 9: {'val_loss': '52.65165', 'train_loss': '107.31531'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 10: {'val_loss': '50.51002', 'train_loss': '110.03925'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=67]Epoch 11: {'val_loss': '47.42905', 'train_loss': '106.92697'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.12it/s, v_num=67]Epoch 12: {'val_loss': '48.02516', 'train_loss': '102.71849'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=67]Epoch 13: {'val_loss': '68.37350', 'train_loss': '101.43776'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 14: {'val_loss': '39.47830', 'train_loss': '101.12286'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=67]Epoch 15: {'val_loss': '59.90927', 'train_loss': '111.97200'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 16: {'val_loss': '39.00529', 'train_loss': '91.27483'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00,  9.67it/s, v_num=67]Epoch 17: {'val_loss': '35.92097', 'train_loss': '90.81892'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=67]Epoch 18: {'val_loss': '41.29824', 'train_loss': '88.54461'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=67]Epoch 19: {'val_loss': '45.65686', 'train_loss': '93.52173'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 20: {'val_loss': '39.04621', 'train_loss': '91.50450'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 21: {'val_loss': '34.59517', 'train_loss': '94.51332'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 22: {'val_loss': '35.49680', 'train_loss': '87.50628'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.02it/s, v_num=67]Epoch 23: {'val_loss': '35.11006', 'train_loss': '86.72509'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=67]Epoch 24: {'val_loss': '38.16492', 'train_loss': '86.86649'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=67]Epoch 25: {'val_loss': '36.37818', 'train_loss': '90.81359'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=67]Epoch 26: {'val_loss': '36.45263', 'train_loss': '86.25323'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=67]Epoch 27: {'val_loss': '42.02823', 'train_loss': '85.09927'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=67]Epoch 28: {'val_loss': '33.85100', 'train_loss': '82.76636'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 29: {'val_loss': '34.05264', 'train_loss': '85.70353'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 30: {'val_loss': '34.29080', 'train_loss': '87.73923'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 31: {'val_loss': '33.66124', 'train_loss': '82.81075'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 32: {'val_loss': '33.65788', 'train_loss': '85.89182'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=67]Epoch 33: {'val_loss': '32.83271', 'train_loss': '80.48672'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=67]Epoch 34: {'val_loss': '35.32069', 'train_loss': '83.38476'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=67]Epoch 35: {'val_loss': '33.27901', 'train_loss': '81.91548'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 36: {'val_loss': '34.07561', 'train_loss': '78.68407'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=67]Epoch 37: {'val_loss': '32.79774', 'train_loss': '82.67081'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 38: {'val_loss': '32.17278', 'train_loss': '83.22720'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 39: {'val_loss': '43.67218', 'train_loss': '88.20023'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=67]Epoch 40: {'val_loss': '32.10298', 'train_loss': '82.56282'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=67]Epoch 41: {'val_loss': '36.98154', 'train_loss': '82.63889'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=67]Epoch 42: {'val_loss': '32.08336', 'train_loss': '75.79484'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=67]Epoch 43: {'val_loss': '38.82167', 'train_loss': '80.41520'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 44: {'val_loss': '35.64990', 'train_loss': '81.63245'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 45: {'val_loss': '33.05713', 'train_loss': '79.55875'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 46: {'val_loss': '31.22136', 'train_loss': '89.50556'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 47: {'val_loss': '32.96972', 'train_loss': '79.42468'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 48: {'val_loss': '30.78008', 'train_loss': '79.83867'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=67]Epoch 49: {'val_loss': '31.23058', 'train_loss': '84.83208'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=67]Epoch 50: {'val_loss': '30.09896', 'train_loss': '81.42896'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 51: {'val_loss': '31.94296', 'train_loss': '74.78249'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=67]Epoch 52: {'val_loss': '29.59954', 'train_loss': '75.87623'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 53: {'val_loss': '30.22835', 'train_loss': '88.15260'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  8.94it/s, v_num=67]Epoch 54: {'val_loss': '31.04748', 'train_loss': '80.22127'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=67]Epoch 55: {'val_loss': '28.73095', 'train_loss': '78.29553'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=67]Epoch 56: {'val_loss': '31.48279', 'train_loss': '76.83549'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 57: {'val_loss': '30.29219', 'train_loss': '77.86280'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00, 10.07it/s, v_num=67]Epoch 58: {'val_loss': '30.77109', 'train_loss': '72.77402'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=67]Epoch 59: {'val_loss': '35.23086', 'train_loss': '78.56707'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00,  9.00it/s, v_num=67]Epoch 60: {'val_loss': '31.14881', 'train_loss': '76.22962'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 61: {'val_loss': '30.09874', 'train_loss': '82.46909'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 62: {'val_loss': '30.55603', 'train_loss': '74.23485'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 63: {'val_loss': '32.13232', 'train_loss': '77.84653'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 64: {'val_loss': '29.81826', 'train_loss': '72.10310'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 65: {'val_loss': '29.85275', 'train_loss': '71.97204'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 66: {'val_loss': '28.42767', 'train_loss': '73.50668'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=67]Epoch 67: {'val_loss': '28.35285', 'train_loss': '69.25241'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 68: {'val_loss': '28.51551', 'train_loss': '71.78255'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 69: {'val_loss': '28.65858', 'train_loss': '69.19421'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=67]Epoch 70: {'val_loss': '28.24233', 'train_loss': '71.24763'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 71: {'val_loss': '31.18937', 'train_loss': '75.37537'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 72: {'val_loss': '28.55120', 'train_loss': '70.56265'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00, 10.08it/s, v_num=67]Epoch 73: {'val_loss': '33.30120', 'train_loss': '74.60942'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=67]Epoch 74: {'val_loss': '29.32495', 'train_loss': '75.90788'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 75: {'val_loss': '28.71805', 'train_loss': '81.41898'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=67]Epoch 76: {'val_loss': '31.41645', 'train_loss': '75.37428'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=67]Epoch 77: {'val_loss': '30.67389', 'train_loss': '69.47844'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 78: {'val_loss': '32.47106', 'train_loss': '68.00071'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 79: {'val_loss': '28.99175', 'train_loss': '66.52225'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 80: {'val_loss': '32.62054', 'train_loss': '69.48987'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=67]Epoch 81: {'val_loss': '30.14901', 'train_loss': '78.37675'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 82: {'val_loss': '34.07068', 'train_loss': '72.10704'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  8.93it/s, v_num=67]Epoch 83: {'val_loss': '30.48136', 'train_loss': '73.52237'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 84: {'val_loss': '31.56343', 'train_loss': '70.85663'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=67]Epoch 85: {'val_loss': '30.11660', 'train_loss': '67.32202'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 86: {'val_loss': '30.98727', 'train_loss': '68.86095'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=67]Epoch 87: {'val_loss': '29.32994', 'train_loss': '69.88197'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 88: {'val_loss': '32.59091', 'train_loss': '68.03248'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=67]Epoch 89: {'val_loss': '30.66288', 'train_loss': '70.92417'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=67]Epoch 90: {'val_loss': '29.33062', 'train_loss': '68.00024'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 91: {'val_loss': '29.20131', 'train_loss': '69.59373'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=67]Epoch 92: {'val_loss': '28.69197', 'train_loss': '69.13451'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 93: {'val_loss': '30.33375', 'train_loss': '70.25995'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 94: {'val_loss': '31.24185', 'train_loss': '71.04698'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 95: {'val_loss': '32.10282', 'train_loss': '73.58407'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 96: {'val_loss': '30.13702', 'train_loss': '71.36086'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  8.94it/s, v_num=67]Epoch 97: {'val_loss': '31.70282', 'train_loss': '76.61309'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=67]Epoch 98: {'val_loss': '30.08030', 'train_loss': '68.11694'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=67]Epoch 99: {'val_loss': '29.41818', 'train_loss': '74.84956'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 100: {'val_loss': '29.07193', 'train_loss': '78.53156'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 101: {'val_loss': '29.91013', 'train_loss': '68.11514'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 102: {'val_loss': '28.84678', 'train_loss': '66.76779'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=67]Epoch 103: {'val_loss': '29.28501', 'train_loss': '65.41801'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=67]Epoch 104: {'val_loss': '29.61505', 'train_loss': '66.73331'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=67]Epoch 105: {'val_loss': '30.73576', 'train_loss': '73.50696'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 106: {'val_loss': '29.91666', 'train_loss': '72.10912'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 107: {'val_loss': '31.36466', 'train_loss': '71.92760'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 108: {'val_loss': '30.68917', 'train_loss': '67.80865'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 109: {'val_loss': '30.45786', 'train_loss': '65.25636'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 110: {'val_loss': '29.53836', 'train_loss': '69.47589'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=67]Epoch 111: {'val_loss': '29.15701', 'train_loss': '73.06892'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 112: {'val_loss': '29.67042', 'train_loss': '69.90461'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 113: {'val_loss': '30.67074', 'train_loss': '67.22509'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 114: {'val_loss': '30.81691', 'train_loss': '71.49754'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 115: {'val_loss': '29.83834', 'train_loss': '73.46880'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 116: {'val_loss': '29.16506', 'train_loss': '73.23683'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=67]Epoch 117: {'val_loss': '29.19977', 'train_loss': '70.04925'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=67]Epoch 118: {'val_loss': '29.90798', 'train_loss': '65.72519'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=67]Epoch 119: {'val_loss': '28.87920', 'train_loss': '71.99023'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=67]Epoch 120: {'val_loss': '29.37820', 'train_loss': '74.40182'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 121: {'val_loss': '29.72217', 'train_loss': '70.91008'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=67]Epoch 122: {'val_loss': '29.45801', 'train_loss': '68.85905'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 123: {'val_loss': '31.42239', 'train_loss': '72.00091'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 124: {'val_loss': '29.58862', 'train_loss': '67.66634'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=67]Epoch 125: {'val_loss': '29.63532', 'train_loss': '65.70486'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 126: {'val_loss': '30.32291', 'train_loss': '69.46652'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=67]Epoch 127: {'val_loss': '29.28246', 'train_loss': '71.93880'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=67]Epoch 128: {'val_loss': '28.85897', 'train_loss': '69.78791'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=67]Epoch 129: {'val_loss': '28.99897', 'train_loss': '74.92033'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 130: {'val_loss': '28.89073', 'train_loss': '68.57684'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  8.93it/s, v_num=67]Epoch 131: {'val_loss': '31.07552', 'train_loss': '68.93063'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=67]Epoch 132: {'val_loss': '29.83593', 'train_loss': '69.21559'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=67]Epoch 133: {'val_loss': '28.82977', 'train_loss': '70.58607'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 134: {'val_loss': '29.16201', 'train_loss': '69.47581'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=67]Epoch 135: {'val_loss': '30.29253', 'train_loss': '69.74526'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=67]Epoch 136: {'val_loss': '30.23237', 'train_loss': '68.93153'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=67]Epoch 137: {'val_loss': '29.65655', 'train_loss': '69.26660'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=67]Epoch 138: {'val_loss': '29.67596', 'train_loss': '73.94327'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=67]Epoch 139: {'val_loss': '30.21575', 'train_loss': '69.77473'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=67]Epoch 140: {'val_loss': '29.26681', 'train_loss': '70.29453'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=67]Epoch 141: {'val_loss': '29.95585', 'train_loss': '76.88016'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=67]Epoch 142: {'val_loss': '29.82302', 'train_loss': '74.40541'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 143: {'val_loss': '28.99171', 'train_loss': '66.74467'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=67]Epoch 144: {'val_loss': '29.16787', 'train_loss': '71.41678'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=67]Epoch 145: {'val_loss': '29.46063', 'train_loss': '67.48082'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=67]Epoch 146: {'val_loss': '30.71263', 'train_loss': '70.35340'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=67]Epoch 147: {'val_loss': '29.21059', 'train_loss': '74.03729'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=67]Epoch 148: {'val_loss': '29.19646', 'train_loss': '69.24995'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=67]Epoch 149: {'val_loss': '29.11422', 'train_loss': '69.35925'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=67]Epoch 150: {'val_loss': '29.27049', 'train_loss': '65.69963'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 151: {'val_loss': '29.28116', 'train_loss': '66.17819'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=67]Epoch 152: {'val_loss': '28.92435', 'train_loss': '71.64785'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=67]Epoch 153: {'val_loss': '29.83270', 'train_loss': '67.72428'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=67]Epoch 154: {'val_loss': '30.04675', 'train_loss': '67.62650'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 0: {'val_loss': '2888.32886', 'train_loss': '356.55798'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=68]Epoch 1: {'val_loss': '264.63208', 'train_loss': '132.39584'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 2: {'val_loss': '51.04105', 'train_loss': '121.63168'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=68]Epoch 3: {'val_loss': '43.45342', 'train_loss': '121.48994'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=68]Epoch 4: {'val_loss': '42.63788', 'train_loss': '106.60989'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 5: {'val_loss': '41.94062', 'train_loss': '103.75137'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=68]Epoch 6: {'val_loss': '40.70277', 'train_loss': '107.18787'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=68]Epoch 7: {'val_loss': '40.62104', 'train_loss': '115.85053'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=68]Epoch 8: {'val_loss': '54.48944', 'train_loss': '114.53042'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 9: {'val_loss': '41.16079', 'train_loss': '113.87286'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=68]Epoch 10: {'val_loss': '53.56040', 'train_loss': '108.84680'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 11: {'val_loss': '42.75755', 'train_loss': '102.44849'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00, 10.05it/s, v_num=68]Epoch 12: {'val_loss': '38.98577', 'train_loss': '102.83533'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=68]Epoch 13: {'val_loss': '36.05656', 'train_loss': '106.25498'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=68]Epoch 14: {'val_loss': '36.64304', 'train_loss': '102.24821'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 15: {'val_loss': '53.46702', 'train_loss': '108.89299'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=68]Epoch 16: {'val_loss': '55.23811', 'train_loss': '111.31109'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=68]Epoch 17: {'val_loss': '37.45406', 'train_loss': '98.03904'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 18: {'val_loss': '36.63036', 'train_loss': '103.57185'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=68]Epoch 19: {'val_loss': '35.10767', 'train_loss': '97.89903'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=68]Epoch 20: {'val_loss': '44.86997', 'train_loss': '95.13413'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 21: {'val_loss': '33.57786', 'train_loss': '92.55038'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=68]Epoch 22: {'val_loss': '37.83902', 'train_loss': '97.47964'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 23: {'val_loss': '40.31603', 'train_loss': '92.88604'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  8.93it/s, v_num=68]Epoch 24: {'val_loss': '37.05062', 'train_loss': '99.31155'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 25: {'val_loss': '41.30749', 'train_loss': '106.87816'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 26: {'val_loss': '40.29963', 'train_loss': '92.27252'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=68]Epoch 27: {'val_loss': '60.63022', 'train_loss': '97.29281'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 28: {'val_loss': '36.69869', 'train_loss': '93.43402'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 29: {'val_loss': '44.84072', 'train_loss': '87.03027'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00, 10.09it/s, v_num=68]Epoch 30: {'val_loss': '32.90490', 'train_loss': '82.88658'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  8.97it/s, v_num=68]Epoch 31: {'val_loss': '30.86776', 'train_loss': '85.80643'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 32: {'val_loss': '36.25260', 'train_loss': '82.47465'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 33: {'val_loss': '30.75949', 'train_loss': '84.36909'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.66it/s, v_num=68]Epoch 34: {'val_loss': '31.26168', 'train_loss': '84.33659'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00,  9.61it/s, v_num=68]Epoch 35: {'val_loss': '33.26514', 'train_loss': '84.06863'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  8.67it/s, v_num=68]Epoch 36: {'val_loss': '34.98177', 'train_loss': '85.10506'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 37: {'val_loss': '28.09135', 'train_loss': '82.67823'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 38: {'val_loss': '36.23266', 'train_loss': '80.76438'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=68]Epoch 39: {'val_loss': '32.77881', 'train_loss': '84.12286'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 40: {'val_loss': '40.30780', 'train_loss': '74.92396'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=68]Epoch 41: {'val_loss': '31.33033', 'train_loss': '83.69913'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=68]Epoch 42: {'val_loss': '35.49269', 'train_loss': '87.12917'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=68]Epoch 43: {'val_loss': '43.60474', 'train_loss': '80.12552'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 44: {'val_loss': '28.72692', 'train_loss': '81.56113'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 45: {'val_loss': '28.77125', 'train_loss': '80.43382'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 46: {'val_loss': '27.50373', 'train_loss': '79.60603'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 47: {'val_loss': '30.50768', 'train_loss': '75.98233'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=68]Epoch 48: {'val_loss': '35.63424', 'train_loss': '78.29422'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 49: {'val_loss': '30.15386', 'train_loss': '76.37729'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=68]Epoch 50: {'val_loss': '28.39566', 'train_loss': '80.09656'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 51: {'val_loss': '26.35629', 'train_loss': '76.78712'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 52: {'val_loss': '24.38452', 'train_loss': '73.15124'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 53: {'val_loss': '28.54913', 'train_loss': '73.90098'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  8.80it/s, v_num=68]Epoch 54: {'val_loss': '30.06257', 'train_loss': '77.61869'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 55: {'val_loss': '33.73306', 'train_loss': '71.51860'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 56: {'val_loss': '41.12545', 'train_loss': '82.75747'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 57: {'val_loss': '26.90694', 'train_loss': '71.24414'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 58: {'val_loss': '26.25433', 'train_loss': '72.39709'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=68]Epoch 59: {'val_loss': '30.38808', 'train_loss': '72.87321'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 60: {'val_loss': '25.96067', 'train_loss': '79.81450'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 61: {'val_loss': '26.23275', 'train_loss': '67.81925'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 62: {'val_loss': '25.18121', 'train_loss': '66.91263'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00, 10.03it/s, v_num=68]Epoch 63: {'val_loss': '29.25811', 'train_loss': '75.95428'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 64: {'val_loss': '25.17432', 'train_loss': '67.77139'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=68]Epoch 65: {'val_loss': '24.99475', 'train_loss': '67.22921'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 66: {'val_loss': '24.93980', 'train_loss': '65.89316'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=68]Epoch 67: {'val_loss': '25.52196', 'train_loss': '66.82014'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 68: {'val_loss': '30.96093', 'train_loss': '71.81564'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=68]Epoch 69: {'val_loss': '24.76062', 'train_loss': '71.87437'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 70: {'val_loss': '27.90164', 'train_loss': '65.46873'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=68]Epoch 71: {'val_loss': '24.94434', 'train_loss': '64.95247'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=68]Epoch 72: {'val_loss': '25.07800', 'train_loss': '67.10480'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 73: {'val_loss': '24.81711', 'train_loss': '69.58265'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 74: {'val_loss': '25.97056', 'train_loss': '64.51053'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=68]Epoch 75: {'val_loss': '28.04397', 'train_loss': '73.38537'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=68]Epoch 76: {'val_loss': '24.65651', 'train_loss': '70.82085'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=68]Epoch 77: {'val_loss': '25.23297', 'train_loss': '67.56339'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=68]Epoch 78: {'val_loss': '24.70592', 'train_loss': '70.04327'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 79: {'val_loss': '27.83685', 'train_loss': '71.77113'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=68]Epoch 80: {'val_loss': '26.92751', 'train_loss': '72.81547'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 81: {'val_loss': '26.65131', 'train_loss': '63.16496'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.40it/s, v_num=68]Epoch 82: {'val_loss': '24.89690', 'train_loss': '67.73634'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  9.69it/s, v_num=68]Epoch 83: {'val_loss': '25.60557', 'train_loss': '68.50668'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=68]Epoch 84: {'val_loss': '24.81160', 'train_loss': '72.01768'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 85: {'val_loss': '25.40133', 'train_loss': '62.71743'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 86: {'val_loss': '25.39783', 'train_loss': '63.97211'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 87: {'val_loss': '25.50125', 'train_loss': '68.22157'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 88: {'val_loss': '25.11973', 'train_loss': '64.00344'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  8.70it/s, v_num=68]Epoch 89: {'val_loss': '25.50302', 'train_loss': '66.77223'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 90: {'val_loss': '25.26180', 'train_loss': '70.97211'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 91: {'val_loss': '24.89985', 'train_loss': '66.61239'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 92: {'val_loss': '24.80714', 'train_loss': '68.04621'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 93: {'val_loss': '24.84663', 'train_loss': '69.65857'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=68]Epoch 94: {'val_loss': '24.97630', 'train_loss': '65.35854'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00,  8.79it/s, v_num=68]Epoch 95: {'val_loss': '26.77400', 'train_loss': '65.65085'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 96: {'val_loss': '25.44308', 'train_loss': '72.07214'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=68]Epoch 97: {'val_loss': '24.64195', 'train_loss': '67.25549'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 98: {'val_loss': '24.69880', 'train_loss': '61.97512'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 99: {'val_loss': '24.80282', 'train_loss': '64.98225'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 100: {'val_loss': '25.24920', 'train_loss': '67.66764'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 101: {'val_loss': '24.72636', 'train_loss': '65.86702'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  8.81it/s, v_num=68]Epoch 102: {'val_loss': '24.75941', 'train_loss': '65.45132'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 103: {'val_loss': '25.80919', 'train_loss': '68.93668'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 104: {'val_loss': '25.38820', 'train_loss': '65.83822'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=68]Epoch 105: {'val_loss': '25.86423', 'train_loss': '64.11261'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 106: {'val_loss': '25.79936', 'train_loss': '66.90862'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  8.79it/s, v_num=68]Epoch 107: {'val_loss': '25.07568', 'train_loss': '71.79167'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=68]Epoch 108: {'val_loss': '25.34561', 'train_loss': '67.53046'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=68]Epoch 109: {'val_loss': '25.92773', 'train_loss': '64.10619'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 110: {'val_loss': '25.41198', 'train_loss': '62.75826'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=68]Epoch 111: {'val_loss': '24.67717', 'train_loss': '64.32246'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 112: {'val_loss': '25.07433', 'train_loss': '65.13431'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=68]Epoch 113: {'val_loss': '25.98623', 'train_loss': '69.93572'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  8.80it/s, v_num=68]Epoch 114: {'val_loss': '25.11760', 'train_loss': '64.17798'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 115: {'val_loss': '26.06402', 'train_loss': '66.96808'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=68]Epoch 116: {'val_loss': '25.00737', 'train_loss': '62.83804'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=68]Epoch 117: {'val_loss': '25.20493', 'train_loss': '65.42682'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 118: {'val_loss': '24.56645', 'train_loss': '63.90833'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  8.75it/s, v_num=68]Epoch 119: {'val_loss': '24.62983', 'train_loss': '65.99667'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 120: {'val_loss': '25.89996', 'train_loss': '63.85277'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]Epoch 121: {'val_loss': '24.61757', 'train_loss': '66.49557'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.27it/s, v_num=68]Epoch 122: {'val_loss': '25.24323', 'train_loss': '64.20409'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=68]Epoch 123: {'val_loss': '25.57938', 'train_loss': '64.95992'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=68]Epoch 124: {'val_loss': '24.76518', 'train_loss': '63.61459'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=68]Epoch 125: {'val_loss': '25.47634', 'train_loss': '66.49237'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=68]Epoch 126: {'val_loss': '24.95934', 'train_loss': '66.86613'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=68]Epoch 127: {'val_loss': '25.76998', 'train_loss': '60.65214'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=68]Epoch 128: {'val_loss': '26.03535', 'train_loss': '63.79214'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=68]Epoch 129: {'val_loss': '26.42981', 'train_loss': '66.37104'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=68]Epoch 130: {'val_loss': '24.86148', 'train_loss': '67.27964'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=68]Epoch 131: {'val_loss': '25.65283', 'train_loss': '71.14538'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=68]Epoch 132: {'val_loss': '25.94079', 'train_loss': '64.31011'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 133: {'val_loss': '26.20691', 'train_loss': '66.70164'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=68]Epoch 134: {'val_loss': '25.28974', 'train_loss': '65.96994'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=68]Epoch 135: {'val_loss': '26.75438', 'train_loss': '67.04890'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 136: {'val_loss': '25.71922', 'train_loss': '63.15443'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  8.82it/s, v_num=68]Epoch 137: {'val_loss': '25.48808', 'train_loss': '63.14209'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=68]Epoch 138: {'val_loss': '25.03490', 'train_loss': '67.01113'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=68]Epoch 139: {'val_loss': '26.95682', 'train_loss': '61.53943'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 140: {'val_loss': '24.87836', 'train_loss': '64.03728'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=68]Epoch 141: {'val_loss': '26.57710', 'train_loss': '69.27430'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=68]Epoch 142: {'val_loss': '27.22285', 'train_loss': '62.54697'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 143: {'val_loss': '26.26595', 'train_loss': '64.90108'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  8.73it/s, v_num=68]Epoch 144: {'val_loss': '25.29836', 'train_loss': '64.35590'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=68]Epoch 145: {'val_loss': '25.16574', 'train_loss': '67.60403'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=68]Epoch 146: {'val_loss': '24.93495', 'train_loss': '64.54237'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=68]Epoch 147: {'val_loss': '25.74181', 'train_loss': '62.18861'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=68]Epoch 148: {'val_loss': '24.64399', 'train_loss': '63.96741'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  8.76it/s, v_num=68]Epoch 149: {'val_loss': '25.82972', 'train_loss': '63.73465'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=68]Epoch 150: {'val_loss': '24.86349', 'train_loss': '65.47275'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=68]Epoch 151: {'val_loss': '26.65488', 'train_loss': '67.73968'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=68]Epoch 152: {'val_loss': '26.39828', 'train_loss': '64.98745'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=68]
Fold-11 Training completed in 237.00s

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=69]Epoch 0: {'val_loss': '1907.05945', 'train_loss': '384.87244'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  8.78it/s, v_num=69]Epoch 1: {'val_loss': '276.68378', 'train_loss': '140.53703'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=69]Epoch 2: {'val_loss': '92.07362', 'train_loss': '122.78175'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 3: {'val_loss': '42.47399', 'train_loss': '111.25026'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 4: {'val_loss': '89.61723', 'train_loss': '107.96703'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=69]Epoch 5: {'val_loss': '38.85385', 'train_loss': '115.47083'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 6: {'val_loss': '46.40636', 'train_loss': '114.20586'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  8.99it/s, v_num=69]Epoch 7: {'val_loss': '39.61465', 'train_loss': '102.72586'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=69]Epoch 8: {'val_loss': '38.64894', 'train_loss': '106.41389'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 9: {'val_loss': '107.02352', 'train_loss': '103.27532'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 10: {'val_loss': '45.39895', 'train_loss': '112.69635'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=69]Epoch 11: {'val_loss': '47.60426', 'train_loss': '113.09488'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=69]Epoch 12: {'val_loss': '37.95744', 'train_loss': '100.92639'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=69]Epoch 13: {'val_loss': '45.06289', 'train_loss': '98.23618'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=69]Epoch 14: {'val_loss': '35.81521', 'train_loss': '101.58833'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  8.96it/s, v_num=69]Epoch 15: {'val_loss': '41.25099', 'train_loss': '102.12772'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 16: {'val_loss': '37.48395', 'train_loss': '99.97922'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 17: {'val_loss': '35.14370', 'train_loss': '100.24863'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=69]Epoch 18: {'val_loss': '54.14904', 'train_loss': '105.05997'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=69]Epoch 19: {'val_loss': '49.99092', 'train_loss': '97.50649'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=69]Epoch 20: {'val_loss': '43.00058', 'train_loss': '100.02756'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 21: {'val_loss': '74.32980', 'train_loss': '90.83391'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00,  8.94it/s, v_num=69]Epoch 22: {'val_loss': '96.23982', 'train_loss': '110.69060'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 23: {'val_loss': '138.77997', 'train_loss': '90.82465'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=69]Epoch 24: {'val_loss': '39.75475', 'train_loss': '97.77033'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 25: {'val_loss': '34.67299', 'train_loss': '91.97250'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 26: {'val_loss': '33.62907', 'train_loss': '90.34767'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 27: {'val_loss': '34.30958', 'train_loss': '91.52437'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=69]Epoch 28: {'val_loss': '52.11510', 'train_loss': '92.39818'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00,  8.88it/s, v_num=69]Epoch 29: {'val_loss': '47.17876', 'train_loss': '90.23965'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 30: {'val_loss': '31.60993', 'train_loss': '83.59969'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=69]Epoch 31: {'val_loss': '39.65741', 'train_loss': '85.56927'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=69]Epoch 32: {'val_loss': '45.58292', 'train_loss': '88.71358'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=69]Epoch 33: {'val_loss': '37.32837', 'train_loss': '85.95397'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=69]Epoch 34: {'val_loss': '31.70978', 'train_loss': '80.59091'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=69]Epoch 35: {'val_loss': '38.18960', 'train_loss': '89.22762'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=69]Epoch 36: {'val_loss': '36.11190', 'train_loss': '77.81560'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 37: {'val_loss': '29.51060', 'train_loss': '82.88621'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 38: {'val_loss': '32.83378', 'train_loss': '78.13751'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=69]Epoch 39: {'val_loss': '30.58176', 'train_loss': '79.08939'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 40: {'val_loss': '30.62828', 'train_loss': '84.69937'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=69]Epoch 41: {'val_loss': '33.46055', 'train_loss': '78.66615'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00,  8.75it/s, v_num=69]Epoch 42: {'val_loss': '29.98912', 'train_loss': '79.99228'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 43: {'val_loss': '29.19796', 'train_loss': '81.33139'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=69]Epoch 44: {'val_loss': '39.30826', 'train_loss': '81.60094'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 45: {'val_loss': '30.37050', 'train_loss': '75.04517'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 46: {'val_loss': '29.48532', 'train_loss': '79.18930'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 47: {'val_loss': '30.82764', 'train_loss': '81.18279'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00,  8.83it/s, v_num=69]Epoch 48: {'val_loss': '29.34439', 'train_loss': '76.50130'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 49: {'val_loss': '28.12085', 'train_loss': '78.77984'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=69]Epoch 50: {'val_loss': '27.59045', 'train_loss': '73.46561'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 51: {'val_loss': '28.19219', 'train_loss': '77.43731'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.19it/s, v_num=69]Epoch 52: {'val_loss': '36.27294', 'train_loss': '78.51446'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=69]Epoch 53: {'val_loss': '37.55909', 'train_loss': '77.82110'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 54: {'val_loss': '32.48434', 'train_loss': '80.97684'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  8.84it/s, v_num=69]Epoch 55: {'val_loss': '29.05009', 'train_loss': '77.37083'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=69]Epoch 56: {'val_loss': '28.44060', 'train_loss': '71.76648'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=69]Epoch 57: {'val_loss': '27.99932', 'train_loss': '75.86860'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 58: {'val_loss': '27.92145', 'train_loss': '80.41167'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 59: {'val_loss': '28.30399', 'train_loss': '72.22940'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00, 10.00it/s, v_num=69]Epoch 60: {'val_loss': '29.98806', 'train_loss': '76.73159'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=69]Epoch 61: {'val_loss': '29.70157', 'train_loss': '73.90163'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 62: {'val_loss': '27.77377', 'train_loss': '71.69777'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=69]Epoch 63: {'val_loss': '27.74309', 'train_loss': '64.74240'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 64: {'val_loss': '28.07129', 'train_loss': '73.23909'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00, 10.06it/s, v_num=69]Epoch 65: {'val_loss': '27.23314', 'train_loss': '71.40836'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00,  8.76it/s, v_num=69]Epoch 66: {'val_loss': '27.76173', 'train_loss': '70.93240'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 67: {'val_loss': '28.78264', 'train_loss': '70.67060'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=69]Epoch 68: {'val_loss': '27.80912', 'train_loss': '63.69710'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=69]Epoch 69: {'val_loss': '28.35245', 'train_loss': '68.43404'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 70: {'val_loss': '30.50225', 'train_loss': '68.76725'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 71: {'val_loss': '29.97318', 'train_loss': '71.22808'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=69]Epoch 72: {'val_loss': '28.83791', 'train_loss': '70.71576'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 73: {'val_loss': '31.36988', 'train_loss': '72.33580'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  8.83it/s, v_num=69]Epoch 74: {'val_loss': '27.86448', 'train_loss': '71.72935'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 75: {'val_loss': '27.45507', 'train_loss': '66.06626'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 76: {'val_loss': '27.86603', 'train_loss': '64.06008'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00, 10.04it/s, v_num=69]Epoch 77: {'val_loss': '28.81001', 'train_loss': '63.74778'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 78: {'val_loss': '28.60540', 'train_loss': '64.80730'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 79: {'val_loss': '27.80922', 'train_loss': '68.15932'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=69]Epoch 80: {'val_loss': '27.31698', 'train_loss': '74.12864'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.72it/s, v_num=69]Epoch 81: {'val_loss': '26.83046', 'train_loss': '68.78323'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 82: {'val_loss': '26.74036', 'train_loss': '66.37581'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 83: {'val_loss': '30.10784', 'train_loss': '66.69646'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=69]Epoch 84: {'val_loss': '29.02637', 'train_loss': '71.10493'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 85: {'val_loss': '27.95888', 'train_loss': '70.43018'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 86: {'val_loss': '27.91988', 'train_loss': '73.18496'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  8.93it/s, v_num=69]Epoch 87: {'val_loss': '30.55506', 'train_loss': '69.61405'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=69]Epoch 88: {'val_loss': '26.90974', 'train_loss': '70.41898'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 89: {'val_loss': '27.03590', 'train_loss': '65.60834'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=69]Epoch 90: {'val_loss': '26.81706', 'train_loss': '72.67532'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00, 10.01it/s, v_num=69]Epoch 91: {'val_loss': '29.19004', 'train_loss': '66.00607'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 92: {'val_loss': '27.88575', 'train_loss': '68.42405'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00, 10.02it/s, v_num=69]Epoch 93: {'val_loss': '27.48897', 'train_loss': '66.79058'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00,  8.75it/s, v_num=69]Epoch 94: {'val_loss': '28.12403', 'train_loss': '67.01147'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 95: {'val_loss': '27.69154', 'train_loss': '74.52249'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 96: {'val_loss': '27.46664', 'train_loss': '70.84270'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 97: {'val_loss': '27.65516', 'train_loss': '71.06987'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 98: {'val_loss': '27.93186', 'train_loss': '71.11505'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 99: {'val_loss': '27.61888', 'train_loss': '68.19249'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=69]Epoch 100: {'val_loss': '27.97344', 'train_loss': '75.87533'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 101: {'val_loss': '27.50189', 'train_loss': '69.39970'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=69]Epoch 102: {'val_loss': '28.70522', 'train_loss': '64.20034'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=69]Epoch 103: {'val_loss': '28.71789', 'train_loss': '67.44724'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 104: {'val_loss': '28.86917', 'train_loss': '66.65417'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=69]Epoch 105: {'val_loss': '30.17656', 'train_loss': '69.13287'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=69]Epoch 106: {'val_loss': '29.83123', 'train_loss': '70.50657'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 107: {'val_loss': '28.65878', 'train_loss': '64.72836'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=69]Epoch 108: {'val_loss': '27.90117', 'train_loss': '63.97999'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=69]Epoch 109: {'val_loss': '27.53687', 'train_loss': '65.35965'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 110: {'val_loss': '27.77541', 'train_loss': '66.93577'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=69]Epoch 111: {'val_loss': '28.77857', 'train_loss': '66.59118'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.71it/s, v_num=69]Epoch 112: {'val_loss': '28.08948', 'train_loss': '62.39369'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 113: {'val_loss': '27.64132', 'train_loss': '69.84650'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=69]Epoch 114: {'val_loss': '27.38058', 'train_loss': '67.84012'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 115: {'val_loss': '27.84147', 'train_loss': '68.36643'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 116: {'val_loss': '26.77115', 'train_loss': '73.72270'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=69]Epoch 117: {'val_loss': '27.19063', 'train_loss': '64.38779'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 118: {'val_loss': '28.63463', 'train_loss': '67.46536'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  8.98it/s, v_num=69]Epoch 119: {'val_loss': '27.74345', 'train_loss': '69.05913'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 120: {'val_loss': '29.37328', 'train_loss': '65.50192'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=69]Epoch 121: {'val_loss': '27.51660', 'train_loss': '68.01599'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 122: {'val_loss': '27.19842', 'train_loss': '65.44981'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=69]Epoch 123: {'val_loss': '27.88461', 'train_loss': '63.64581'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  8.92it/s, v_num=69]Epoch 124: {'val_loss': '27.16843', 'train_loss': '67.94227'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=69]Epoch 125: {'val_loss': '27.76820', 'train_loss': '68.31535'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 126: {'val_loss': '27.43723', 'train_loss': '67.86861'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=69]Epoch 127: {'val_loss': '27.63665', 'train_loss': '68.47871'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=69]Epoch 128: {'val_loss': '27.95766', 'train_loss': '64.18497'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 129: {'val_loss': '29.10728', 'train_loss': '69.64545'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=69]Epoch 130: {'val_loss': '28.54330', 'train_loss': '68.36284'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=69]Epoch 131: {'val_loss': '27.79515', 'train_loss': '63.24756'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=69]Epoch 132: {'val_loss': '27.10534', 'train_loss': '68.36222'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=69]Epoch 133: {'val_loss': '27.15742', 'train_loss': '70.98574'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=69]Epoch 134: {'val_loss': '27.95850', 'train_loss': '63.62178'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=69]Epoch 135: {'val_loss': '27.57714', 'train_loss': '68.32351'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 136: {'val_loss': '28.08718', 'train_loss': '73.60369'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=69]Epoch 137: {'val_loss': '27.63275', 'train_loss': '64.87293'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 138: {'val_loss': '27.58727', 'train_loss': '68.93771'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=69]Epoch 139: {'val_loss': '27.80002', 'train_loss': '67.15976'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=69]Epoch 140: {'val_loss': '27.84155', 'train_loss': '67.53925'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=69]Epoch 141: {'val_loss': '27.99763', 'train_loss': '69.55008'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  8.81it/s, v_num=69]Epoch 142: {'val_loss': '27.29326', 'train_loss': '69.31831'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=69]Epoch 143: {'val_loss': '27.16600', 'train_loss': '66.27539'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 144: {'val_loss': '29.18520', 'train_loss': '67.35949'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 145: {'val_loss': '30.11579', 'train_loss': '69.06428'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=69]Epoch 146: {'val_loss': '27.88464', 'train_loss': '65.37148'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=69]Epoch 147: {'val_loss': '27.99220', 'train_loss': '64.02763'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=69]Epoch 148: {'val_loss': '26.93091', 'train_loss': '69.55019'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=69]Epoch 149: {'val_loss': '28.62054', 'train_loss': '73.01781'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 150: {'val_loss': '29.90706', 'train_loss': '65.92366'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  8.78it/s, v_num=69]Epoch 151: {'val_loss': '27.11725', 'train_loss': '65.52562'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=69]Epoch 152: {'val_loss': '27.38283', 'train_loss': '69.62464'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=69]Epoch 153: {'val_loss': '27.80217', 'train_loss': '68.57081'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=69]Epoch 154: {'val_loss': '26.99691', 'train_loss': '64.77409'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  8.88it/s, v_num=70]Epoch 0: {'val_loss': '8239.04297', 'train_loss': '358.17929'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=70]Epoch 1: {'val_loss': '289.88004', 'train_loss': '140.41661'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 2: {'val_loss': '56.47031', 'train_loss': '119.45947'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 3: {'val_loss': '40.69589', 'train_loss': '122.32586'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 4: {'val_loss': '56.51545', 'train_loss': '119.60515'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 5: {'val_loss': '45.10681', 'train_loss': '104.88905'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 6: {'val_loss': '40.51318', 'train_loss': '117.25062'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=70]Epoch 7: {'val_loss': '51.10750', 'train_loss': '106.84082'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=70]Epoch 8: {'val_loss': '95.14676', 'train_loss': '120.19601'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 9: {'val_loss': '46.34827', 'train_loss': '130.01141'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.99it/s, v_num=70]Epoch 10: {'val_loss': '45.91394', 'train_loss': '137.54837'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 11: {'val_loss': '39.61164', 'train_loss': '106.84214'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 12: {'val_loss': '37.72018', 'train_loss': '99.74914'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 13: {'val_loss': '44.07420', 'train_loss': '103.21829'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00,  8.95it/s, v_num=70]Epoch 14: {'val_loss': '73.85374', 'train_loss': '106.42246'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 15: {'val_loss': '69.77548', 'train_loss': '105.67112'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 16: {'val_loss': '49.71106', 'train_loss': '98.39196'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 17: {'val_loss': '55.41832', 'train_loss': '95.57362'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=70]Epoch 18: {'val_loss': '43.94741', 'train_loss': '93.98325'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=70]Epoch 19: {'val_loss': '38.82470', 'train_loss': '96.14692'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=70]Epoch 20: {'val_loss': '36.90782', 'train_loss': '90.85736'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=70]Epoch 21: {'val_loss': '35.58590', 'train_loss': '88.92332'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 22: {'val_loss': '41.13589', 'train_loss': '91.17307'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 23: {'val_loss': '37.77925', 'train_loss': '97.12630'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 24: {'val_loss': '40.84563', 'train_loss': '82.28486'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 25: {'val_loss': '37.02298', 'train_loss': '87.22516'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 26: {'val_loss': '37.53982', 'train_loss': '93.95025'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  8.88it/s, v_num=70]Epoch 27: {'val_loss': '38.72956', 'train_loss': '98.17145'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 28: {'val_loss': '34.05584', 'train_loss': '90.07030'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=70]Epoch 29: {'val_loss': '34.07523', 'train_loss': '87.09496'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=70]Epoch 30: {'val_loss': '36.15395', 'train_loss': '84.99151'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 31: {'val_loss': '32.89498', 'train_loss': '82.40028'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 32: {'val_loss': '35.36940', 'train_loss': '89.67717'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 33: {'val_loss': '42.41639', 'train_loss': '87.03864'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 34: {'val_loss': '39.15391', 'train_loss': '84.45351'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 35: {'val_loss': '33.54766', 'train_loss': '86.43929'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 36: {'val_loss': '32.15061', 'train_loss': '90.40430'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  8.73it/s, v_num=70]Epoch 37: {'val_loss': '36.43374', 'train_loss': '80.18201'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 38: {'val_loss': '34.51867', 'train_loss': '78.70391'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00,  9.68it/s, v_num=70]Epoch 39: {'val_loss': '36.55383', 'train_loss': '77.92931'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 40: {'val_loss': '35.10061', 'train_loss': '86.73874'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=70]Epoch 41: {'val_loss': '48.61228', 'train_loss': '79.80312'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 42: {'val_loss': '42.21663', 'train_loss': '81.86643'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=70]Epoch 43: {'val_loss': '33.73858', 'train_loss': '78.61125'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=70]Epoch 44: {'val_loss': '31.29932', 'train_loss': '80.53054'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=70]Epoch 45: {'val_loss': '33.21609', 'train_loss': '76.76716'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=70]Epoch 46: {'val_loss': '32.35418', 'train_loss': '76.51721'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 47: {'val_loss': '32.68285', 'train_loss': '81.20908'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=70]Epoch 48: {'val_loss': '31.13708', 'train_loss': '77.90275'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 49: {'val_loss': '31.14737', 'train_loss': '78.30487'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=70]Epoch 50: {'val_loss': '33.16903', 'train_loss': '72.86935'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=70]Epoch 51: {'val_loss': '33.81741', 'train_loss': '77.26656'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 52: {'val_loss': '32.74156', 'train_loss': '73.07781'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 53: {'val_loss': '29.49812', 'train_loss': '74.46356'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 54: {'val_loss': '31.43241', 'train_loss': '81.86621'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=70]Epoch 55: {'val_loss': '33.34074', 'train_loss': '76.76458'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00,  9.68it/s, v_num=70]Epoch 56: {'val_loss': '36.91659', 'train_loss': '77.56740'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=70]Epoch 57: {'val_loss': '30.32268', 'train_loss': '73.01142'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 58: {'val_loss': '30.71964', 'train_loss': '74.22907'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=70]Epoch 59: {'val_loss': '33.42320', 'train_loss': '73.16669'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 60: {'val_loss': '27.99717', 'train_loss': '72.25036'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 61: {'val_loss': '29.19399', 'train_loss': '76.20434'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00,  9.62it/s, v_num=70]Epoch 62: {'val_loss': '34.34197', 'train_loss': '70.04987'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00,  9.57it/s, v_num=70]Epoch 63: {'val_loss': '30.83767', 'train_loss': '71.34727'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 64: {'val_loss': '32.61308', 'train_loss': '72.92287'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 65: {'val_loss': '29.07897', 'train_loss': '67.72561'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 66: {'val_loss': '29.67762', 'train_loss': '76.66457'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 67: {'val_loss': '29.84719', 'train_loss': '70.42165'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  8.91it/s, v_num=70]Epoch 68: {'val_loss': '28.17975', 'train_loss': '75.18069'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=70]Epoch 69: {'val_loss': '27.80648', 'train_loss': '68.68903'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=70]Epoch 70: {'val_loss': '28.64345', 'train_loss': '69.97087'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=70]Epoch 71: {'val_loss': '28.24284', 'train_loss': '80.40824'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 72: {'val_loss': '29.73200', 'train_loss': '73.04661'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=70]Epoch 73: {'val_loss': '32.63775', 'train_loss': '79.08398'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 74: {'val_loss': '31.33381', 'train_loss': '73.02293'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 75: {'val_loss': '30.39209', 'train_loss': '73.38200'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 76: {'val_loss': '28.58346', 'train_loss': '70.36687'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00,  8.89it/s, v_num=70]Epoch 77: {'val_loss': '28.93130', 'train_loss': '68.75672'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=70]Epoch 78: {'val_loss': '28.72964', 'train_loss': '71.89873'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=70]Epoch 79: {'val_loss': '28.95812', 'train_loss': '74.20658'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 80: {'val_loss': '29.86934', 'train_loss': '71.07727'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=70]Epoch 81: {'val_loss': '30.33402', 'train_loss': '71.04492'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 82: {'val_loss': '28.10958', 'train_loss': '67.87174'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=70]Epoch 83: {'val_loss': '27.94673', 'train_loss': '73.73144'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 84: {'val_loss': '27.92198', 'train_loss': '66.88274'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=70]Epoch 85: {'val_loss': '28.43447', 'train_loss': '64.71055'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=70]Epoch 86: {'val_loss': '29.23327', 'train_loss': '69.17060'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 87: {'val_loss': '28.10572', 'train_loss': '71.66933'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 88: {'val_loss': '28.69315', 'train_loss': '67.56414'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=70]Epoch 89: {'val_loss': '28.51073', 'train_loss': '70.12904'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 90: {'val_loss': '27.48773', 'train_loss': '73.36938'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=70]Epoch 91: {'val_loss': '27.96773', 'train_loss': '69.19581'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 92: {'val_loss': '28.45035', 'train_loss': '71.60604'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  8.81it/s, v_num=70]Epoch 93: {'val_loss': '27.88138', 'train_loss': '67.80669'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=70]Epoch 94: {'val_loss': '28.25066', 'train_loss': '68.86584'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00,  9.42it/s, v_num=70]Epoch 95: {'val_loss': '28.39133', 'train_loss': '68.05144'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.63it/s, v_num=70]Epoch 96: {'val_loss': '28.31284', 'train_loss': '67.12791'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=70]Epoch 97: {'val_loss': '28.56281', 'train_loss': '71.05846'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=70]Epoch 98: {'val_loss': '28.16259', 'train_loss': '76.11747'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 99: {'val_loss': '28.14461', 'train_loss': '69.36382'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=70]Epoch 100: {'val_loss': '28.31042', 'train_loss': '64.24038'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 101: {'val_loss': '29.58147', 'train_loss': '67.71217'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=70]Epoch 102: {'val_loss': '28.53756', 'train_loss': '71.97720'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=70]Epoch 103: {'val_loss': '28.53016', 'train_loss': '76.94380'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.72it/s, v_num=70]Epoch 104: {'val_loss': '28.64967', 'train_loss': '68.63049'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 105: {'val_loss': '28.96699', 'train_loss': '66.72139'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 106: {'val_loss': '28.32313', 'train_loss': '70.62217'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 107: {'val_loss': '28.36535', 'train_loss': '64.35435'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=70]Epoch 108: {'val_loss': '30.55859', 'train_loss': '67.74963'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=70]Epoch 109: {'val_loss': '32.55444', 'train_loss': '75.96702'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.69it/s, v_num=70]Epoch 110: {'val_loss': '28.78883', 'train_loss': '71.20084'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=70]Epoch 111: {'val_loss': '28.52059', 'train_loss': '67.76451'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 112: {'val_loss': '28.21549', 'train_loss': '70.36306'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 113: {'val_loss': '28.08915', 'train_loss': '67.81375'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 114: {'val_loss': '28.88454', 'train_loss': '75.14258'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.73it/s, v_num=70]Epoch 115: {'val_loss': '28.74521', 'train_loss': '73.00574'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=70]Epoch 116: {'val_loss': '28.27782', 'train_loss': '73.63916'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=70]Epoch 117: {'val_loss': '29.76197', 'train_loss': '69.32436'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 118: {'val_loss': '29.22628', 'train_loss': '66.50356'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 119: {'val_loss': '28.76894', 'train_loss': '68.36946'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  8.72it/s, v_num=70]Epoch 120: {'val_loss': '28.34611', 'train_loss': '71.52885'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=70]Epoch 121: {'val_loss': '29.99202', 'train_loss': '69.08196'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 122: {'val_loss': '30.72430', 'train_loss': '67.95083'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=70]Epoch 123: {'val_loss': '29.66191', 'train_loss': '65.92267'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 124: {'val_loss': '28.89585', 'train_loss': '72.95195'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=70]Epoch 125: {'val_loss': '28.03458', 'train_loss': '70.92844'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 126: {'val_loss': '30.22432', 'train_loss': '73.10055'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 127: {'val_loss': '30.27910', 'train_loss': '69.06996'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 128: {'val_loss': '29.25022', 'train_loss': '69.69489'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=70]Epoch 129: {'val_loss': '29.80424', 'train_loss': '69.36549'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=70]Epoch 130: {'val_loss': '30.10861', 'train_loss': '72.97670'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=70]Epoch 131: {'val_loss': '29.62820', 'train_loss': '70.19083'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 132: {'val_loss': '28.60263', 'train_loss': '74.46317'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=70]Epoch 133: {'val_loss': '28.52243', 'train_loss': '68.24175'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00,  9.25it/s, v_num=70]Epoch 134: {'val_loss': '28.50747', 'train_loss': '68.22775'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00,  9.60it/s, v_num=70]Epoch 135: {'val_loss': '31.40675', 'train_loss': '69.91949'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.73it/s, v_num=70]Epoch 136: {'val_loss': '27.84053', 'train_loss': '66.39844'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  9.60it/s, v_num=70]Epoch 137: {'val_loss': '28.83560', 'train_loss': '78.39873'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  8.80it/s, v_num=70]Epoch 138: {'val_loss': '28.30425', 'train_loss': '70.67003'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=70]Epoch 139: {'val_loss': '28.63105', 'train_loss': '70.49280'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=70]Epoch 140: {'val_loss': '31.57994', 'train_loss': '72.21504'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=70]Epoch 141: {'val_loss': '30.42484', 'train_loss': '72.50969'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=70]Epoch 142: {'val_loss': '29.04185', 'train_loss': '70.11088'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 143: {'val_loss': '28.97910', 'train_loss': '68.38741'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=70]Epoch 144: {'val_loss': '28.54742', 'train_loss': '66.84764'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=70]Epoch 145: {'val_loss': '29.24502', 'train_loss': '77.61213'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=70]Epoch 146: {'val_loss': '28.73141', 'train_loss': '68.16514'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00,  8.78it/s, v_num=70]Epoch 147: {'val_loss': '28.58230', 'train_loss': '65.90734'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=70]Epoch 148: {'val_loss': '28.57373', 'train_loss': '73.05457'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=70]Epoch 149: {'val_loss': '28.36813', 'train_loss': '68.74033'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=70]Epoch 150: {'val_loss': '28.93761', 'train_loss': '66.37679'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=70]Epoch 151: {'val_loss': '29.57864', 'train_loss': '67.62260'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 152: {'val_loss': '30.06192', 'train_loss': '71.59779'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=70]Epoch 153: {'val_loss': '28.89687', 'train_loss': '68.19398'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=70]Epoch 154: {'val_loss': '28.62733', 'train_loss': '68.32488'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /home/fede/programacion/labo3/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 732 K  | train
---------------------------------------------
732 K     Trainable params
0         Non-trainable params
732 K     Total params
2.930     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/fede/programacion/labo3/.venv/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py:310: The number of training batches (15) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Epoch 0: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 0: {'val_loss': '6064.51758', 'train_loss': '392.71814'}
Epoch 1: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 1: {'val_loss': '440.13202', 'train_loss': '134.20297'}
Epoch 2: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=71]Epoch 2: {'val_loss': '58.98793', 'train_loss': '135.18257'}
Epoch 3: 100%|██████████| 15/15 [00:01<00:00,  9.97it/s, v_num=71]Epoch 3: {'val_loss': '61.26217', 'train_loss': '125.59796'}
Epoch 4: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=71]Epoch 4: {'val_loss': '42.73008', 'train_loss': '126.61940'}
Epoch 5: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 5: {'val_loss': '40.87932', 'train_loss': '108.75598'}
Epoch 6: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 6: {'val_loss': '106.25343', 'train_loss': '109.17389'}
Epoch 7: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 7: {'val_loss': '190.39375', 'train_loss': '116.60842'}
Epoch 8: 100%|██████████| 15/15 [00:01<00:00,  8.87it/s, v_num=71]Epoch 8: {'val_loss': '131.00916', 'train_loss': '114.54578'}
Epoch 9: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 9: {'val_loss': '68.31409', 'train_loss': '105.18114'}
Epoch 10: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 10: {'val_loss': '50.00031', 'train_loss': '115.32631'}
Epoch 11: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 11: {'val_loss': '47.51447', 'train_loss': '107.17203'}
Epoch 12: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=71]Epoch 12: {'val_loss': '37.82633', 'train_loss': '99.24222'}
Epoch 13: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 13: {'val_loss': '40.47978', 'train_loss': '101.64725'}
Epoch 14: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 14: {'val_loss': '36.77530', 'train_loss': '95.55402'}
Epoch 15: 100%|██████████| 15/15 [00:01<00:00,  8.86it/s, v_num=71]Epoch 15: {'val_loss': '45.17552', 'train_loss': '94.19694'}
Epoch 16: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 16: {'val_loss': '37.25647', 'train_loss': '94.73320'}
Epoch 17: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 17: {'val_loss': '36.18283', 'train_loss': '92.09434'}
Epoch 18: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=71]Epoch 18: {'val_loss': '38.04629', 'train_loss': '92.24795'}
Epoch 19: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 19: {'val_loss': '42.82737', 'train_loss': '89.72045'}
Epoch 20: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 20: {'val_loss': '53.95221', 'train_loss': '90.80032'}
Epoch 21: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 21: {'val_loss': '37.48186', 'train_loss': '96.15359'}
Epoch 22: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 22: {'val_loss': '35.82268', 'train_loss': '100.35218'}
Epoch 23: 100%|██████████| 15/15 [00:01<00:00,  8.83it/s, v_num=71]Epoch 23: {'val_loss': '45.22111', 'train_loss': '94.70131'}
Epoch 24: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 24: {'val_loss': '39.53108', 'train_loss': '95.71755'}
Epoch 25: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 25: {'val_loss': '52.14426', 'train_loss': '90.44875'}
Epoch 26: 100%|██████████| 15/15 [00:01<00:00,  9.34it/s, v_num=71]Epoch 26: {'val_loss': '52.31267', 'train_loss': '100.93597'}
Epoch 27: 100%|██████████| 15/15 [00:01<00:00,  9.51it/s, v_num=71]Epoch 27: {'val_loss': '43.40327', 'train_loss': '84.76919'}
Epoch 28: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 28: {'val_loss': '34.78249', 'train_loss': '89.97164'}
Epoch 29: 100%|██████████| 15/15 [00:01<00:00,  8.84it/s, v_num=71]Epoch 29: {'val_loss': '39.46205', 'train_loss': '100.62502'}
Epoch 30: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 30: {'val_loss': '44.45174', 'train_loss': '92.92991'}
Epoch 31: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 31: {'val_loss': '36.14257', 'train_loss': '95.16180'}
Epoch 32: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 32: {'val_loss': '36.41272', 'train_loss': '86.13915'}
Epoch 33: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=71]Epoch 33: {'val_loss': '40.74445', 'train_loss': '82.58926'}
Epoch 34: 100%|██████████| 15/15 [00:01<00:00,  9.94it/s, v_num=71]Epoch 34: {'val_loss': '40.79245', 'train_loss': '77.83987'}
Epoch 35: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 35: {'val_loss': '36.21500', 'train_loss': '85.45226'}
Epoch 36: 100%|██████████| 15/15 [00:01<00:00,  8.73it/s, v_num=71]Epoch 36: {'val_loss': '32.73112', 'train_loss': '85.51307'}
Epoch 37: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 37: {'val_loss': '33.05409', 'train_loss': '90.89537'}
Epoch 38: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=71]Epoch 38: {'val_loss': '39.17236', 'train_loss': '83.94427'}
Epoch 39: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 39: {'val_loss': '38.23167', 'train_loss': '80.18810'}
Epoch 40: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 40: {'val_loss': '35.16513', 'train_loss': '84.78271'}
Epoch 41: 100%|██████████| 15/15 [00:01<00:00,  9.96it/s, v_num=71]Epoch 41: {'val_loss': '32.47152', 'train_loss': '87.17455'}
Epoch 42: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 42: {'val_loss': '33.82211', 'train_loss': '80.34829'}
Epoch 43: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 43: {'val_loss': '33.40756', 'train_loss': '79.88235'}
Epoch 44: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=71]Epoch 44: {'val_loss': '39.60797', 'train_loss': '80.66180'}
Epoch 45: 100%|██████████| 15/15 [00:01<00:00,  9.72it/s, v_num=71]Epoch 45: {'val_loss': '32.35320', 'train_loss': '82.26421'}
Epoch 46: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 46: {'val_loss': '34.19305', 'train_loss': '81.98061'}
Epoch 47: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=71]Epoch 47: {'val_loss': '32.83900', 'train_loss': '81.39788'}
Epoch 48: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 48: {'val_loss': '31.39027', 'train_loss': '83.10429'}
Epoch 49: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 49: {'val_loss': '30.75572', 'train_loss': '78.88350'}
Epoch 50: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 50: {'val_loss': '29.43310', 'train_loss': '84.54292'}
Epoch 51: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 51: {'val_loss': '35.89753', 'train_loss': '81.73292'}
Epoch 52: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=71]Epoch 52: {'val_loss': '29.14378', 'train_loss': '79.69800'}
Epoch 53: 100%|██████████| 15/15 [00:01<00:00,  9.98it/s, v_num=71]Epoch 53: {'val_loss': '28.93656', 'train_loss': '78.26249'}
Epoch 54: 100%|██████████| 15/15 [00:01<00:00,  8.77it/s, v_num=71]Epoch 54: {'val_loss': '33.15902', 'train_loss': '77.55109'}
Epoch 55: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 55: {'val_loss': '35.22070', 'train_loss': '83.86928'}
Epoch 56: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 56: {'val_loss': '51.43425', 'train_loss': '84.10408'}
Epoch 57: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 57: {'val_loss': '55.10112', 'train_loss': '78.61897'}
Epoch 58: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 58: {'val_loss': '37.71875', 'train_loss': '78.06557'}
Epoch 59: 100%|██████████| 15/15 [00:01<00:00,  9.91it/s, v_num=71]Epoch 59: {'val_loss': '31.25937', 'train_loss': '83.65949'}
Epoch 60: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 60: {'val_loss': '33.83761', 'train_loss': '74.39169'}
Epoch 61: 100%|██████████| 15/15 [00:01<00:00,  8.90it/s, v_num=71]Epoch 61: {'val_loss': '29.31318', 'train_loss': '71.36710'}
Epoch 62: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=71]Epoch 62: {'val_loss': '29.11958', 'train_loss': '77.35636'}
Epoch 63: 100%|██████████| 15/15 [00:01<00:00,  9.95it/s, v_num=71]Epoch 63: {'val_loss': '33.73866', 'train_loss': '71.30911'}
Epoch 64: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 64: {'val_loss': '28.96915', 'train_loss': '71.17353'}
Epoch 65: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 65: {'val_loss': '38.75423', 'train_loss': '70.07664'}
Epoch 66: 100%|██████████| 15/15 [00:01<00:00,  9.92it/s, v_num=71]Epoch 66: {'val_loss': '30.77934', 'train_loss': '69.45107'}
Epoch 67: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 67: {'val_loss': '32.13564', 'train_loss': '75.10066'}
Epoch 68: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 68: {'val_loss': '29.78505', 'train_loss': '73.54689'}
Epoch 69: 100%|██████████| 15/15 [00:01<00:00,  8.77it/s, v_num=71]Epoch 69: {'val_loss': '30.10088', 'train_loss': '71.39773'}
Epoch 70: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 70: {'val_loss': '28.71823', 'train_loss': '67.27053'}
Epoch 71: 100%|██████████| 15/15 [00:01<00:00,  9.93it/s, v_num=71]Epoch 71: {'val_loss': '27.71735', 'train_loss': '72.29537'}
Epoch 72: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 72: {'val_loss': '28.50097', 'train_loss': '71.79634'}
Epoch 73: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 73: {'val_loss': '30.19330', 'train_loss': '69.50455'}
Epoch 74: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 74: {'val_loss': '27.86142', 'train_loss': '66.81384'}
Epoch 75: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 75: {'val_loss': '27.43435', 'train_loss': '73.37922'}
Epoch 76: 100%|██████████| 15/15 [00:01<00:00,  9.73it/s, v_num=71]Epoch 76: {'val_loss': '32.17223', 'train_loss': '71.27923'}
Epoch 77: 100%|██████████| 15/15 [00:01<00:00,  8.85it/s, v_num=71]Epoch 77: {'val_loss': '28.84144', 'train_loss': '73.85011'}
Epoch 78: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 78: {'val_loss': '28.37599', 'train_loss': '70.27120'}
Epoch 79: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 79: {'val_loss': '28.99816', 'train_loss': '70.55695'}
Epoch 80: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 80: {'val_loss': '26.05540', 'train_loss': '70.49758'}
Epoch 81: 100%|██████████| 15/15 [00:01<00:00,  9.89it/s, v_num=71]Epoch 81: {'val_loss': '26.33716', 'train_loss': '68.67563'}
Epoch 82: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 82: {'val_loss': '26.13626', 'train_loss': '65.27027'}
Epoch 83: 100%|██████████| 15/15 [00:01<00:00,  9.70it/s, v_num=71]Epoch 83: {'val_loss': '24.53452', 'train_loss': '70.79299'}
Epoch 84: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 84: {'val_loss': '27.16264', 'train_loss': '67.02076'}
Epoch 85: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 85: {'val_loss': '26.38848', 'train_loss': '75.82520'}
Epoch 86: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 86: {'val_loss': '26.91813', 'train_loss': '67.57106'}
Epoch 87: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 87: {'val_loss': '25.41298', 'train_loss': '69.68345'}
Epoch 88: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=71]Epoch 88: {'val_loss': '28.08204', 'train_loss': '71.30859'}
Epoch 89: 100%|██████████| 15/15 [00:01<00:00,  9.72it/s, v_num=71]Epoch 89: {'val_loss': '25.79349', 'train_loss': '67.47512'}
Epoch 90: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 90: {'val_loss': '26.04579', 'train_loss': '66.13733'}
Epoch 91: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 91: {'val_loss': '28.03071', 'train_loss': '67.63251'}
Epoch 92: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 92: {'val_loss': '26.10766', 'train_loss': '63.78451'}
Epoch 93: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 93: {'val_loss': '25.83490', 'train_loss': '62.98597'}
Epoch 94: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 94: {'val_loss': '27.09516', 'train_loss': '66.56832'}
Epoch 95: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 95: {'val_loss': '26.72398', 'train_loss': '68.15244'}
Epoch 96: 100%|██████████| 15/15 [00:01<00:00,  9.63it/s, v_num=71]Epoch 96: {'val_loss': '28.86304', 'train_loss': '64.90786'}
Epoch 97: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 97: {'val_loss': '25.72887', 'train_loss': '65.97006'}
Epoch 98: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 98: {'val_loss': '25.62800', 'train_loss': '70.01305'}
Epoch 99: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 99: {'val_loss': '24.78352', 'train_loss': '60.63048'}
Epoch 100: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=71]Epoch 100: {'val_loss': '26.57018', 'train_loss': '66.68469'}
Epoch 101: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 101: {'val_loss': '26.14752', 'train_loss': '70.50032'}
Epoch 102: 100%|██████████| 15/15 [00:01<00:00,  9.66it/s, v_num=71]Epoch 102: {'val_loss': '26.62946', 'train_loss': '59.95672'}
Epoch 103: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=71]Epoch 103: {'val_loss': '25.99705', 'train_loss': '62.04454'}
Epoch 104: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 104: {'val_loss': '25.45721', 'train_loss': '75.03482'}
Epoch 105: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 105: {'val_loss': '26.73759', 'train_loss': '66.88476'}
Epoch 106: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 106: {'val_loss': '25.44993', 'train_loss': '63.62806'}
Epoch 107: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 107: {'val_loss': '26.65718', 'train_loss': '65.93661'}
Epoch 108: 100%|██████████| 15/15 [00:01<00:00,  9.68it/s, v_num=71]Epoch 108: {'val_loss': '26.76940', 'train_loss': '65.43758'}
Epoch 109: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 109: {'val_loss': '27.49321', 'train_loss': '64.77052'}
Epoch 110: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 110: {'val_loss': '25.84826', 'train_loss': '65.73725'}
Epoch 111: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 111: {'val_loss': '26.35636', 'train_loss': '64.39963'}
Epoch 112: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=71]Epoch 112: {'val_loss': '27.79676', 'train_loss': '66.91125'}
Epoch 113: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 113: {'val_loss': '26.71840', 'train_loss': '65.03974'}
Epoch 114: 100%|██████████| 15/15 [00:01<00:00,  9.68it/s, v_num=71]Epoch 114: {'val_loss': '26.59147', 'train_loss': '69.85761'}
Epoch 115: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 115: {'val_loss': '26.11951', 'train_loss': '71.25758'}
Epoch 116: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 116: {'val_loss': '25.89074', 'train_loss': '68.05302'}
Epoch 117: 100%|██████████| 15/15 [00:01<00:00,  9.80it/s, v_num=71]Epoch 117: {'val_loss': '29.39079', 'train_loss': '67.90422'}
Epoch 118: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 118: {'val_loss': '26.43844', 'train_loss': '69.00321'}
Epoch 119: 100%|██████████| 15/15 [00:01<00:00,  9.69it/s, v_num=71]Epoch 119: {'val_loss': '26.16264', 'train_loss': '66.06396'}
Epoch 120: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 120: {'val_loss': '24.99255', 'train_loss': '69.23183'}
Epoch 121: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 121: {'val_loss': '25.14444', 'train_loss': '70.52719'}
Epoch 122: 100%|██████████| 15/15 [00:01<00:00,  9.88it/s, v_num=71]Epoch 122: {'val_loss': '25.81869', 'train_loss': '68.20628'}
Epoch 123: 100%|██████████| 15/15 [00:01<00:00,  9.90it/s, v_num=71]Epoch 123: {'val_loss': '25.62739', 'train_loss': '63.38161'}
Epoch 124: 100%|██████████| 15/15 [00:01<00:00,  9.76it/s, v_num=71]Epoch 124: {'val_loss': '25.89418', 'train_loss': '59.79067'}
Epoch 125: 100%|██████████| 15/15 [00:01<00:00,  9.66it/s, v_num=71]Epoch 125: {'val_loss': '27.49006', 'train_loss': '70.28960'}
Epoch 126: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 126: {'val_loss': '26.99766', 'train_loss': '62.90408'}
Epoch 127: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 127: {'val_loss': '26.00807', 'train_loss': '64.67171'}
Epoch 128: 100%|██████████| 15/15 [00:01<00:00,  9.87it/s, v_num=71]Epoch 128: {'val_loss': '25.41958', 'train_loss': '67.75266'}
Epoch 129: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 129: {'val_loss': '26.04709', 'train_loss': '65.65166'}
Epoch 130: 100%|██████████| 15/15 [00:01<00:00,  9.73it/s, v_num=71]Epoch 130: {'val_loss': '28.13098', 'train_loss': '65.42259'}
Epoch 131: 100%|██████████| 15/15 [00:01<00:00,  9.78it/s, v_num=71]Epoch 131: {'val_loss': '26.47613', 'train_loss': '69.69318'}
Epoch 132: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 132: {'val_loss': '31.65804', 'train_loss': '67.28979'}
Epoch 133: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 133: {'val_loss': '27.18584', 'train_loss': '64.23993'}
Epoch 134: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 134: {'val_loss': '26.07018', 'train_loss': '64.63727'}
Epoch 135: 100%|██████████| 15/15 [00:01<00:00,  9.62it/s, v_num=71]Epoch 135: {'val_loss': '25.36110', 'train_loss': '68.33495'}
Epoch 136: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 136: {'val_loss': '25.53138', 'train_loss': '67.31953'}
Epoch 137: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 137: {'val_loss': '26.66033', 'train_loss': '67.43492'}
Epoch 138: 100%|██████████| 15/15 [00:01<00:00,  9.86it/s, v_num=71]Epoch 138: {'val_loss': '25.21636', 'train_loss': '63.54063'}
Epoch 139: 100%|██████████| 15/15 [00:01<00:00,  9.85it/s, v_num=71]Epoch 139: {'val_loss': '25.31964', 'train_loss': '64.19565'}
Epoch 140: 100%|██████████| 15/15 [00:01<00:00,  9.63it/s, v_num=71]Epoch 140: {'val_loss': '25.13985', 'train_loss': '65.59385'}
Epoch 141: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 141: {'val_loss': '25.12341', 'train_loss': '64.28168'}
Epoch 142: 100%|██████████| 15/15 [00:01<00:00,  9.84it/s, v_num=71]Epoch 142: {'val_loss': '26.16763', 'train_loss': '72.60657'}
Epoch 143: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 143: {'val_loss': '25.08226', 'train_loss': '63.59133'}
Epoch 144: 100%|██████████| 15/15 [00:01<00:00,  9.83it/s, v_num=71]Epoch 144: {'val_loss': '25.62644', 'train_loss': '62.80054'}
Epoch 145: 100%|██████████| 15/15 [00:01<00:00,  9.66it/s, v_num=71]Epoch 145: {'val_loss': '25.23632', 'train_loss': '61.81661'}
Epoch 146: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=71]Epoch 146: {'val_loss': '25.04908', 'train_loss': '64.64697'}
Epoch 147: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 147: {'val_loss': '25.41478', 'train_loss': '66.17661'}
Epoch 148: 100%|██████████| 15/15 [00:01<00:00,  9.77it/s, v_num=71]Epoch 148: {'val_loss': '26.66497', 'train_loss': '70.21407'}
Epoch 149: 100%|██████████| 15/15 [00:01<00:00,  9.74it/s, v_num=71]Epoch 149: {'val_loss': '26.52068', 'train_loss': '66.48396'}
Epoch 150: 100%|██████████| 15/15 [00:01<00:00,  9.75it/s, v_num=71]Epoch 150: {'val_loss': '25.88375', 'train_loss': '65.28722'}
Epoch 151: 100%|██████████| 15/15 [00:01<00:00,  9.81it/s, v_num=71]Epoch 151: {'val_loss': '25.91254', 'train_loss': '66.84687'}
Epoch 152: 100%|██████████| 15/15 [00:01<00:00,  9.82it/s, v_num=71]Epoch 152: {'val_loss': '25.59195', 'train_loss': '64.01939'}
Epoch 153: 100%|██████████| 15/15 [00:01<00:00,  9.79it/s, v_num=71]Epoch 153: {'val_loss': '25.40741', 'train_loss': '62.79634'}
Epoch 154: 100%|██████████| 15/15 [00:01<00:00,  9.56it/s, v_num=71]Epoch 154: {'val_loss': '25.39979', 'train_loss': '65.11549'}

# inference

In [7]:
models = []
for fold in range(args.N_fold):
    model_path = f"./models/nn_{fold}.model.ckpt"
    if os.path.exists(model_path):
        model = NN.load_from_checkpoint(model_path)
        models.append(model.to("cuda:0"))
    else:
        print(f"Model for fold {fold} not found at {model_path}")
models

[NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 ),
 NN(
   (model): Sequential(
     (0): BatchNorm1d(653, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (1): Dropout(p=0.1, inplace=False)
     (2): Linear(in_features=653, out_features=512, bias=True)
     (3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (4): SiLU()
     (5): Dropout(p=0.1, inplace=False)
     (6): Linear(in_features=512, out_features=512, bias=True)
     (7): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
     (8): SiLU()
     (9): Linear(in_features=512, out_features=256, bias=True)
     (10): Linear(in_features=256, out_features=1, bias=True)
     (11): ReLU()
   )
 )]

In [8]:
X_val = val[numeric_cols]
y_val = val[target_col]


y_pred_valid = np.zeros(y_val.shape)
with torch.no_grad():
    for model in models:
        model.eval()
        y_pred_valid += model(torch.FloatTensor(X_val.values).to("cuda:0")).cpu().numpy() / len(models)

y_pred_valid

array([0.04663732, 0.        , 0.        , ..., 0.        , 0.06433796,
       3.63920894])

In [9]:
print(list(y_pred_valid))

[np.float64(0.04663731902837753), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.8077956605702639), np.float64(0.0), np.float64(0.15172338299453259), np.float64(0.001462658285163343), np.float64(0.036024060100317), np.float64(15.276416003704071), np.float64(0.5616184351965785), np.float64(0.009599019773304462), np.float64(0.5854467707686126), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(9.350014328956604), np.float64(0.08625137805938721), np.float64(3.3428944647312164), np.float64(3.7762775868177414), np.float64(2.5969161838293076), np.float64(27.933611631393433), np.float64(4.625479444861412), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(22.834051251411438), np.float64(1.8861752897500992), np.float64(0.0), np.float64(0.0), np.float64(0.8323964029550552), np.float64(1.7381983324885368), np.float64(0.0), np.float64(0.03380203898996115), np.float64(0.0), np.float64(0.04343809559941292), np.float64(0.1321134609170258), np.float64(0.0), np.float64(0.3893311850260943), np.float64(0.6585672106593847), np.float64(1.6326965428888798), np.float64(0.0), np.float64(0.0), np.float64(0.20128102938178927), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.0212973281741142), np.float64(0.0), np.float64(1.3098027184605598), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.4949823924944212), np.float64(0.0), np.float64(0.3271016082726419), np.float64(0.0), np.float64(0.2452139897586676), np.float64(2.2174542918801308), np.float64(0.0), np.float64(2.715698778629303), np.float64(0.006362819578498602), np.float64(0.7742202840745449), np.float64(0.22753070580074564), np.float64(0.0), np.float64(0.0028878876473754644), np.float64(0.0), np.float64(2.2234108224511147), np.float64(0.40825722413137555), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.3389345072209835), np.float64(0.0), np.float64(2.9269952923059464), np.float64(23.933979988098145), np.float64(0.638241358101368), np.float64(15.348513662815094), np.float64(0.02922183834016323), np.float64(0.0), np.float64(15.421573400497437), np.float64(0.016391675919294357), np.float64(0.0), np.float64(2.1785903722047806), np.float64(0.0), np.float64(0.02756333164870739), np.float64(0.03920665034092963), np.float64(2.5030015781521797), np.float64(0.7721521118655801), np.float64(0.025144871324300766), np.float64(0.0), np.float64(0.0), np.float64(0.860147362574935), np.float64(0.19635018962435424), np.float64(0.0), np.float64(25.335138201713562), np.float64(0.886686772108078), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(12.884982526302338), np.float64(0.0), np.float64(0.0), np.float64(2.222999185323715), np.float64(2.188744768500328), np.float64(0.0), np.float64(0.019541863352060318), np.float64(0.0), np.float64(1.4824529737234116), np.float64(0.0), np.float64(0.0), np.float64(0.3632669970393181), np.float64(0.0), np.float64(0.06575730931945145), np.float64(0.07955466955900192), np.float64(0.7856784723699093), np.float64(0.23610304156318307), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.12326688040047884), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0032860299106687307), np.float64(4.433640897274017), np.float64(0.0), np.float64(0.5415746029466391), np.float64(0.0), np.float64(0.0), np.float64(0.8774153161793947), np.float64(0.48207064904272556), np.float64(2.8088503032922745), np.float64(0.36358800530433655), np.float64(0.06989627424627542), np.float64(0.0), np.float64(0.018707560375332832), np.float64(0.0), np.float64(0.0), np.float64(0.9710803311318159), np.float64(0.9884979650378227), np.float64(0.0), np.float64(2.487366706132889), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.3445256650447845), np.float64(0.0), np.float64(0.0), np.float64(0.21203865460120142), np.float64(0.0), np.float64(0.0), np.float64(1.0070525743067265), np.float64(0.7110486188903451), np.float64(3.3350645303726196), np.float64(239.1862678527832), np.float64(1.4096352010965347), np.float64(14.216629266738892), np.float64(0.0), np.float64(22.49963402748108), np.float64(0.0), np.float64(0.0), np.float64(1.499236710369587), np.float64(0.44053068198263645), np.float64(1.6035507172346115), np.float64(0.0), np.float64(0.0), np.float64(14.91763037443161), np.float64(0.01769115962088108), np.float64(0.0), np.float64(3.391903877258301), np.float64(1.4227370917797089), np.float64(21.860214591026306), np.float64(0.0), np.float64(3.9304345697164536), np.float64(0.0), np.float64(0.3287254289461998), np.float64(0.0), np.float64(2.1387700214982033), np.float64(0.0), np.float64(0.0), np.float64(0.7651788080111146), np.float64(0.44936350209172815), np.float64(0.0), np.float64(0.0), np.float64(14.542701363563538), np.float64(0.03000432625412941), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(15.020986795425415), np.float64(11.594868302345276), np.float64(3.489182248711586), np.float64(0.00037854613037779927), np.float64(0.0), np.float64(0.13151165808085352), np.float64(0.0), np.float64(2.105360209941864), np.float64(5.922304540872574), np.float64(0.0), np.float64(0.0), np.float64(0.15282561862841249), np.float64(0.0), np.float64(1.762771114706993), np.float64(0.9217206910252571), np.float64(0.4289723221445456), np.float64(1.8182187601923943), np.float64(0.21710010548122227), np.float64(0.0), np.float64(0.0), np.float64(0.005287736654281616), np.float64(0.016619326546788216), np.float64(0.0), np.float64(2.094255045056343), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.728690356016159), np.float64(0.012833064422011375), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(86.42888307571411), np.float64(0.3023932682117447), np.float64(0.0), np.float64(0.1389356714207679), np.float64(0.03551268205046654), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.8469793200492859), np.float64(0.0), np.float64(0.0), np.float64(0.04184472281485796), np.float64(1.1982176061719656), np.float64(1.621946007013321), np.float64(0.17554163426393643), np.float64(0.0), np.float64(0.020197054371237755), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(18.564650058746338), np.float64(4.364130198955536), np.float64(0.04872748127672821), np.float64(0.5063749495893717), np.float64(2.1376504078507423), np.float64(0.0), np.float64(0.0), np.float64(1.9730338230729103), np.float64(0.5568234557285905), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.1563276574015617), np.float64(0.8420910388231277), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.7644978407770395), np.float64(0.0), np.float64(14.39958381652832), np.float64(1.3725978545844555), np.float64(0.0), np.float64(0.0), np.float64(2.8126483410596848), np.float64(1.1623513959348202), np.float64(0.7701773336157203), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.39159239642322063), np.float64(0.0), np.float64(0.07104264944791794), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.6269853101111948), np.float64(0.0), np.float64(0.3856453816406429), np.float64(0.0), np.float64(0.016201065853238106), np.float64(0.038801439106464386), np.float64(1.3911344185471535), np.float64(0.0), np.float64(0.24378176243044436), np.float64(0.0), np.float64(1.2705459669232368), np.float64(0.371703177690506), np.float64(0.0), np.float64(3.0989729911088943), np.float64(0.0), np.float64(0.8265154957771301), np.float64(2.0392645746469498), np.float64(7.939657479524612), np.float64(0.0), np.float64(15.030598044395447), np.float64(0.9112431108951569), np.float64(6.552490681409836), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(3.8021753132343292), np.float64(0.0), np.float64(0.5346812158823013), np.float64(0.0), np.float64(0.8419403955340385), np.float64(3.17425899207592), np.float64(0.0), np.float64(3.024837300181389), np.float64(17.84733784198761), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(18.051084399223328), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.427850879728794), np.float64(0.0), np.float64(1.3688669577240944), np.float64(0.0), np.float64(0.0), np.float64(0.7608199845999479), np.float64(0.05721046030521393), np.float64(0.37312580924481153), np.float64(0.0), np.float64(0.019864114001393318), np.float64(0.0), np.float64(49.039509296417236), np.float64(0.0), np.float64(0.0), np.float64(0.057826969772577286), np.float64(0.0), np.float64(0.1148957000405062), np.float64(0.047301603481173515), np.float64(0.0), np.float64(2.8488074094057083), np.float64(0.0), np.float64(1.2020707465708256), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.04112355085089803), np.float64(1.439713854342699), np.float64(0.0), np.float64(13.699052333831787), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(16.25083500146866), np.float64(11.745714128017426), np.float64(0.596490727737546), np.float64(3.2076848298311234), np.float64(0.0), np.float64(0.024422980844974518), np.float64(0.004520414397120476), np.float64(0.0), np.float64(3.5159030109643936), np.float64(0.0), np.float64(0.04486571252346039), np.float64(0.0), np.float64(0.0), np.float64(0.011464484967291355), np.float64(0.0), np.float64(0.0), np.float64(1.6290387995541096), np.float64(1.0599487209692597), np.float64(2.0041842088103294), np.float64(0.0), np.float64(0.0), np.float64(1.3459720835089684), np.float64(0.004258336499333382), np.float64(0.0), np.float64(0.0), np.float64(0.01809566840529442), np.float64(0.05869606602936983), np.float64(2.629630744457245), np.float64(14.420917630195618), np.float64(0.027871685102581978), np.float64(0.0), np.float64(0.1234670840203762), np.float64(0.0), np.float64(0.0), np.float64(0.8546570464968681), np.float64(0.2156726544490084), np.float64(2.6345529705286026), np.float64(0.055354847136186436), np.float64(0.0), np.float64(0.0), np.float64(0.5105485497042537), np.float64(17.338761687278748), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.03400201036129147), np.float64(18.024112939834595), np.float64(0.22750001575332135), np.float64(0.1470265625976026), np.float64(0.0), np.float64(2.4367388039827347), np.float64(0.2567771861795336), np.float64(0.02376091480255127), np.float64(0.0), np.float64(0.0), np.float64(1.179628147991025), np.float64(0.02268681302666664), np.float64(1.1883866786956787), np.float64(0.0), np.float64(0.0), np.float64(3.5229418575763702), np.float64(1.1113274917006493), np.float64(0.4653383959084749), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.2616642713546753), np.float64(0.0), np.float64(0.23443815379869193), np.float64(0.04422130063176155), np.float64(0.0), np.float64(0.0), np.float64(2.1268597543239594), np.float64(0.0), np.float64(0.0), np.float64(65.30800747871399), np.float64(0.0), np.float64(0.0), np.float64(42.816439628601074), np.float64(0.0), np.float64(1.4387892726808786), np.float64(0.02372230775654316), np.float64(0.0), np.float64(0.39929855917580426), np.float64(0.9401053935289383), np.float64(1.777790628373623), np.float64(0.0), np.float64(0.0), np.float64(15.896809697151184), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.0223819091916084), np.float64(0.0), np.float64(0.010327760130167007), np.float64(0.0), np.float64(0.011094403453171253), np.float64(1.1065026968717575), np.float64(0.23828658886486664), np.float64(0.023113707080483437), np.float64(0.0), np.float64(0.0), np.float64(0.18795776506885886), np.float64(8.363431721925735), np.float64(0.0), np.float64(0.18253344986442244), np.float64(2.0937882363796234), np.float64(0.0), np.float64(1.7765453644096851), np.float64(0.0), np.float64(0.0), np.float64(0.023431723937392235), np.float64(0.0), np.float64(0.03446797002106905), np.float64(0.0), np.float64(0.0), np.float64(23.449069499969482), np.float64(10.739376664161682), np.float64(0.0), np.float64(0.0), np.float64(7.632498055696487), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.34148692106828094), np.float64(3.727379083633423), np.float64(2.010281503200531), np.float64(0.04088507918640971), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.0483328253030777), np.float64(0.0), np.float64(1.3233146667480469), np.float64(2.9512167870998383), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.9813302904367447), np.float64(0.0), np.float64(0.0), np.float64(0.0065709264017641544), np.float64(5.493481785058975), np.float64(0.6001650243997574), np.float64(0.0), np.float64(2.225268006324768), np.float64(3.005452513694763), np.float64(11.66720986366272), np.float64(0.0), np.float64(0.0), np.float64(2.472898080945015), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.05130894389003515), np.float64(1.7532244324684143), np.float64(3.2866843193769455), np.float64(2.194571539759636), np.float64(1.483771950006485), np.float64(0.0), np.float64(12.043512523174286), np.float64(0.7225010916590691), np.float64(3.8658969700336456), np.float64(2.1358217522501945), np.float64(0.0), np.float64(0.4156092880293727), np.float64(1.3370190262794495), np.float64(0.0), np.float64(0.8134417608380318), np.float64(0.0), np.float64(4.949997313320637), np.float64(0.0), np.float64(0.0), np.float64(0.022975368425250053), np.float64(0.0), np.float64(0.9322752356529236), np.float64(0.45160235185176134), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(12.370268881320953), np.float64(0.0), np.float64(0.0), np.float64(0.06631381064653397), np.float64(2.211500585079193), np.float64(0.9671879969537258), np.float64(7.410519436001778), np.float64(3.2372349202632904), np.float64(1.9130193591117859), np.float64(0.0), np.float64(0.7840874344110489), np.float64(0.0), np.float64(0.0), np.float64(21.35556697845459), np.float64(3.569336950778961), np.float64(0.0), np.float64(11.6032435297966), np.float64(0.004943629261106253), np.float64(0.014341805130243301), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.022546013817191124), np.float64(0.7079870952293277), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(9.81302285194397), np.float64(1.662573680281639), np.float64(0.0), np.float64(0.0), np.float64(3.449192374944687), np.float64(2.3847968503832817), np.float64(0.013122268952429295), np.float64(0.339303539134562), np.float64(0.0), np.float64(4.495398223400116), np.float64(0.0), np.float64(11.505975365638733), np.float64(0.0), np.float64(0.6719702817499638), np.float64(0.3336157950689085), np.float64(0.0), np.float64(0.0022968053817749023), np.float64(0.7547801192849874), np.float64(2.1939962208271027), np.float64(0.0), np.float64(0.0), np.float64(4.268042698502541), np.float64(20.830341696739197), np.float64(0.0), np.float64(0.26316495807259344), np.float64(0.01564704068005085), np.float64(2.8589624762535095), np.float64(8.545195460319519), np.float64(0.0), np.float64(1.4656537771224976), np.float64(0.0), np.float64(0.038822827860713005), np.float64(0.0), np.float64(4.654106721282005), np.float64(2.116110123693943), np.float64(0.0), np.float64(0.0), np.float64(0.13725084974430501), np.float64(0.0), np.float64(0.0), np.float64(0.3514603024814278), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.771521732211113), np.float64(0.1955240920651704), np.float64(3.7595977932214737), np.float64(2.2334174886345863), np.float64(0.3638433935120702), np.float64(0.0), np.float64(0.0), np.float64(0.390394163550809), np.float64(0.46997067192569375), np.float64(0.0), np.float64(0.11771146487444639), np.float64(0.0), np.float64(0.0), np.float64(38.97705912590027), np.float64(0.0), np.float64(1.8469580486416817), np.float64(1.178053755313158), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.21295917371753603), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(2.1765133887529373), np.float64(0.0), np.float64(1.0156218567863107), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.02641741745173931), np.float64(0.0), np.float64(0.0), np.float64(12.502925217151642), np.float64(1.1819552518427372), np.float64(0.4409153163433075), np.float64(0.0), np.float64(43.35818386077881), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.6219426235184073), np.float64(2.0417627096176147), np.float64(0.7579236980527639), np.float64(0.0), np.float64(0.13603377109393477), np.float64(0.0), np.float64(0.0), np.float64(9.9075226187706), np.float64(0.0), np.float64(2.16001708060503), np.float64(0.08450271189212799), np.float64(0.0), np.float64(0.0), np.float64(8.855170458555222), np.float64(0.0), np.float64(16.012864112854004), np.float64(0.0), np.float64(20.32616114616394), np.float64(0.0), np.float64(0.8380313012748957), np.float64(0.0), np.float64(0.506971139810048), np.float64(1.6111795753240585), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.05343374749645591), np.float64(0.0), np.float64(0.9024241603910923), np.float64(0.0), np.float64(0.2130799206206575), np.float64(0.13920479931402951), np.float64(19.474365651607513), np.float64(0.0), np.float64(0.28919866983778775), np.float64(2.1319207847118378), np.float64(0.017753180116415024), np.float64(0.0), np.float64(3.6902874410152435), np.float64(3.1649110019207), np.float64(0.02329058013856411), np.float64(0.37965049321064726), np.float64(0.31575757125392556), np.float64(0.22289641345560085), np.float64(0.017546923831105232), np.float64(0.0), np.float64(3.553962543606758), np.float64(0.0), np.float64(0.0), np.float64(0.16824914375320077), np.float64(0.0), np.float64(0.0), np.float64(2.076500602066517), np.float64(0.0), np.float64(0.05726967006921768), np.float64(0.8218862619251013), np.float64(0.0), np.float64(0.0), np.float64(11.205315887928009), np.float64(17.24609661102295), np.float64(0.08245643030386418), np.float64(0.0667286217212677), np.float64(1.4662607200443745), np.float64(1.140985630452633), np.float64(0.0), np.float64(0.2954373313114047), np.float64(0.6433283127844334), np.float64(0.1297174389474094), np.float64(0.0), np.float64(0.0), np.float64(0.21392446557729272), np.float64(0.0), np.float64(317.4344425201416), np.float64(0.8375623449683189), np.float64(0.6725918315351009), np.float64(0.026604870334267616), np.float64(0.0), np.float64(2.367766708135605), np.float64(0.0), np.float64(0.1501330421306193), np.float64(0.0), np.float64(1.7087594047188759), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.32978399051353335), np.float64(2.660171702504158), np.float64(0.0), np.float64(0.0), np.float64(3.900305151939392), np.float64(0.0), np.float64(0.0), np.float64(9.00102186203003), np.float64(0.0), np.float64(0.15667514584492892), np.float64(0.5229535242542624), np.float64(0.0), np.float64(0.16431994584854692), np.float64(0.0021885812748223543), np.float64(2.327940359711647), np.float64(0.0), np.float64(6.599885910749435), np.float64(0.0), np.float64(2.221591204404831), np.float64(0.0), np.float64(0.0), np.float64(19.558233618736267), np.float64(0.0), np.float64(0.0), np.float64(3.052597612142563), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.70686149969697), np.float64(1.0638103764504194), np.float64(0.0), np.float64(0.0), np.float64(0.07219271385110915), np.float64(0.0), np.float64(0.021552082151174545), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(16.195176899433136), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.3684150972403586), np.float64(2.72718159109354), np.float64(0.38274214300327003), np.float64(1.2326009087264538), np.float64(0.0), np.float64(0.0), np.f

In [10]:
target_scaler.inverse_transform(y_pred_valid.reshape(-1, 1)).flatten()

array([ 0.13469465,  0.        ,  0.        , ...,  0.        ,
        0.1858164 , 10.51050892])

In [11]:
test_df = val.copy()
test_df[numeric_cols] = scaler.inverse_transform(test_df[numeric_cols])
test_df["target"] = target_scaler.inverse_transform(test_df["target"].values.reshape(-1, 1)).flatten()
y_pred_valid = target_scaler.inverse_transform(y_pred_valid.reshape(-1, 1)).flatten()
test_df["predictions"] = y_pred_valid
test_df = test_df[["product_id", "customer_id", "date_id", "predictions", "target"]]
test_df =test_df.groupby(["product_id"]).agg({
    "predictions": "sum",
    "target": "sum"
    }
).reset_index()
test_df["abs_error"] = np.abs(test_df["predictions"] - test_df["target"])
test_df

/tmp/ipykernel_725501/3051987149.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_df["predictions"] = y_pred_valid

     product_id  predictions       target  abs_error
0       20001.0  1430.882606  1504.688599  73.805993
1       20002.0  1137.594661  1087.308594  50.286067
2       20003.0   884.176061   892.501282   8.325221
3       20004.0   623.427941   637.900024  14.472083
4       20005.0   594.198222   593.244446   0.953776
..          ...          ...          ...        ...
775     21263.0     0.000000     0.012700   0.012700
776     21265.0     0.000000     0.050070   0.050070
777     21266.0     0.000000     0.051210   0.051210
778     21267.0     0.000000     0.015690   0.015690
779     21276.0     0.000000     0.008920   0.008920

[780 rows x 4 columns]

In [12]:
total_error = test_df["abs_error"].sum() / test_df["target"].sum()
total_error

np.float64(0.2245616809949001)

In [13]:

y_pred_valid = np.zeros(X_kaggle.shape[0])
with torch.no_grad():
    for model in models:
        model.eval()
        y_pred_valid += model(torch.FloatTensor(X_kaggle.values).to("cuda:0")).cpu().numpy() / len(models)


submission_df = X_kaggle[["product_id", "customer_id", "date_id"]].copy()
submission_df["predictions"] = y_pred_valid
submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
submission_df["predictions"] = target_scaler.inverse_transform(submission_df["predictions"].values.reshape(-1, 1)).flatten()

/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])
/tmp/ipykernel_725501/2996960838.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  submission_df[numeric_cols] = scaler.inverse_transform(X_kaggle[numeric_cols])

In [14]:
submission_df

,product_id,customer_id,date_id,predictions,plan_precios_cuidados,cust_request_qty,cust_request_tn,tn,stock_final,sku_size,...,prod_tn_rolling_mean_6_lag_6_x_tn_rolling_mean_24_lag_2,prod_tn_rolling_mean_6_lag_6_x_tn_rolling_mean_24_lag_3,prod_tn_rolling_mean_6_lag_6_x_tn_rolling_mean_6,prod_tn_rolling_mean_6_lag_6_x_tn_rolling_mean_6_lag_8,prod_tn_rolling_mean_24_lag_2_x_tn_rolling_mean_24_lag_3,prod_tn_rolling_mean_24_lag_2_x_tn_rolling_mean_6,prod_tn_rolling_mean_24_lag_2_x_tn_rolling_mean_6_lag_8,prod_tn_rolling_mean_24_lag_3_x_tn_rolling_mean_6,prod_tn_rolling_mean_24_lag_3_x_tn_rolling_mean_6_lag_8,prod_tn_rolling_mean_6_x_tn_rolling_mean_6_lag_8
131775,20743.0,10001.0,35.0,1176.176789,0.0,3.0,0.04512,0.04512,6.71624,200.0,...,0.010383,0.011278,0.002597,0.005265,0.029703,0.006839,0.013865,0.007429,0.015060,0.003468
130835,20737.0,0.0,35.0,1127.950961,0.0,32.0,0.75220,0.75220,13.68429,1000.0,...,1.899130,1.839392,2.575368,0.989984,2.999002,4.198960,1.614100,4.066880,1.563328,2.188846
82859,20424.0,10004.0,35.0,1169.771814,0.0,1.0,0.13135,0.13135,0.13176,100.0,...,0.027197,0.026550,0.022410,0.026916,0.024274,0.020489,0.024608,0.020002,0.024023,0.020277
132380,20746.0,10004.0,35.0,1178.006169,0.0,0.0,0.00000,0.00000,7.72588,350.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
89201,20463.0,10003.0,35.0,1173.517061,0.0,17.0,1.57058,1.57058,4.70588,530.0,...,0.242049,0.252541,0.288872,0.223912,0.290369,0.332141,0.257451,0.346539,0.268611,0.307254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57053,20291.0,10001.0,35.0,1155.859251,0.0,2.0,0.25462,0.25462,15.74343,650.0,...,11.695195,12.132673,6.159146,14.457420,9.768928,4.959192,11.640757,5.144699,12.076199,6.130476
57017,20291.0,0.0,35.0,1683.362073,0.0,67.0,6.03982,6.03982,15.74343,650.0,...,77.211250,77.749779,65.294151,65.346382,91.025429,76.443024,76.504173,76.976196,77.037773,64.696205
146075,20840.0,10005.0,35.0,1167.398699,0.0,0.0,0.00000,0.00000,0.10957,60.0,...,0.007262,0.007830,0.000052,0.011383,0.005938,0.000039,0.008633,0.000042,0.009308,0.000061
57197,20291.0,10005.0,35.0,1179.582311,0.0,0.0,0.00000,0.00000,15.74343,650.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
188897,21276.0,10005.0,35.0,1171.442384,0.0,0.0,0.00000,0.00000,1.05592,140.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [15]:

submission_df = submission_df[["product_id", "customer_id", "date_id", "predictions"]]
submission_df = submission_df.groupby(["product_id"]).agg({
    "predictions": "sum",
    }
).reset_index()
submission_df

     product_id   predictions
0       20001.0  91211.132247
1       20002.0  72485.276069
2       20003.0  63474.882516
3       20004.0  45919.372663
4       20005.0  41475.987183
..          ...           ...
775     21263.0   7032.024705
776     21265.0   7039.413882
777     21266.0   7039.239264
778     21267.0   7039.098794
779     21276.0   7036.012543

[780 rows x 2 columns]

In [16]:
submission_df.columns = ["product_id", "tn"]
submission_df.to_csv("submission_nn.csv", index=False)